### ISSUE TITLE
Contribute upstream?

### ISSUE THREAD

**Issue by balloob** [kalkih/mini-graph-card#1]
Really love this card. It's awesome.

Would you want to contribute it back to official repo at https://github.com/home-assistant/home-assistant-polymer ?

**Comment by kalkih** [comment]
@balIoob
I would love to!
However it's a LitElement atm, and the overall quality of the code is not really on par with the official repo, but I guess that could be worked on.

Do you want me to create a PR when I've refactored the code into the official repo?

**Comment by balloob** [comment]
I have been following the Lit Element work closely and have been planning to adopt it. They recently changed their API and are assuming is going to be stable, so I am fine with adding Lit Element to our repo. I hope that eventually most of our repo can be converted to Lit 😎.

Code can be cleaned up while it's in the repo too. I think that there are some functions that can be replaced with existing helpers but generally I think this code is good to go.

**Comment by balloob** [comment]
Hit me up on Discord if you get stuck and I'll help.

**Comment by kalkih** [comment]
Closing this as the base of the card was contributed to [Home Assistant](https://github.com/home-assistant/home-assistant-polymer) as the [sensor card](https://www.home-assistant.io/lovelace/sensor/).
