### ISSUE TITLE
X and Y labels

### ISSUE THREAD

**Issue by mitchando96** [kalkih/mini-graph-card#10]
Would love to see an option of X and Y labels so this beautiful graph could be more useful.

**Comment by kalkih** [comment]
This card has been merged into the official frontend of HA https://github.com/home-assistant/home-assistant-polymer/pull/1744 please open an issue there as this repo will no longer be maintained.

You can find the docs for the official sensor card [here](https://www.home-assistant.io/lovelace/sensor/).

**Comment by kalkih** [comment]
@mitchando96 I've continued with some minor development of this custom card and Y-axis min/max labels are now available through the `labels` option.
