### ISSUE TITLE
show_hours: how to define this parameter as a non hard-coded value?

### ISSUE THREAD

**Issue by Krzysztonek** [kalkih/mini-graph-card#1003]
Here is a one-line excerpt of my card code:

``` show_hours: 720```

I would need to be able to change it from the hard-coded value (here: 720) to any numerical external value being kept in the numerical helper (e.g. `input_number.show_hours`) or any other numerical entity. 

This is basically what I want to achieve (don't look at the syntax, the semantic counts here):

 ```show_hours: Number(states['input_number.show_hours'].state)```

Is it possible to have it coded somehow?

**Comment by ildar170975** [comment]
1. Templates are NOT supported for options. You may start monitoring this FR related to using templates in the mini-graph-card: https://github.com/kalkih/mini-graph-card/issues/697 (and possibly propose some ideas).

2. Meanwhile you may use custom template-supporting cards like `config-template-card` (search in the mentioned thread). [Also, this might be helpful](https://community.home-assistant.io/t/mini-graph-card-history-graph-using-a-decluttering-template/300247).

3. Suggest to ask similar questions in a [dedicated Community mini-graph thread](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385) and leave GitHub for reporting bugs & proposing FRs.
