### ISSUE TITLE
Mini-graph-card displays an empty chart when viewed on an android tablet

### ISSUE THREAD

**Issue by ncd7** [kalkih/mini-graph-card#1005]
I’m viewing my dashboard on an android tablet and the mini-graph-card is not showing any date, just blank.
The same dashboard shows fine on my Pixel (android) phone and on an iPhone as well.

**Comment by ildar170975** [comment]
Provide some details. 
HA version. 
Code for mini-graph-card. 
Test with ONE graph card an a dashboard.

**Comment by ildar170975** [comment]
Try reseting browser cache

**Comment by ildar170975** [comment]
iOS companion app has a “reset fronted cache» button, may be Android has it as well.

**Comment by ildar170975** [comment]
But I do not see in your post about results often clearing cache. 
Did resetting a cache in Android companion app help?

**Comment by Alfons-Hetler** [comment]
I try it too and it did not worked.
It says: Custom element doesn´t exist: plothy-graph.
I deleted the app and begin from new but the error stay there.

**Comment by ildar170975** [comment]
> plothy-graph.

Not related to this Repo.
