### ISSUE TITLE
How to automatically show the area of the sensor as a title ?

### ISSUE THREAD

**Issue by Diplo95** [kalkih/mini-graph-card#1019]
Hi,

firstly, I would like to thank you for the great work ! 

Here is my question : I try to put a title to a horizontal stack. Maybe a picture would be clearer :
 
![Capture d’écran du 2023-10-22 20-32-39](https://github.com/kalkih/mini-graph-card/assets/10744682/f7a95f01-bdaa-44ce-b4ef-ce04e47e0170)

So I tried this code (But, as you can see, the result is not what I expected. Could you tell me what I'm missing ?) :
````type: horizontal-stack
title: " {{ area_name('sensor.temp_hum_1_temperature') }} "
cards:
  - type: custom:mini-graph-card
    entities:
      - sensor.temp_hum_1_temperature
    line_color: '#e16366'
    icon: mdi:tree
    line_width: 8
    font_size: 75
    unit: °C
    name: Température
  - type: custom:mini-graph-card
    entities:
      - sensor.temp_hum_1_humidity
    line_color: '#4e93dd'
    icon: mdi:wave
    line_width: 8
    font_size: 75
    unit: °C
    name: Humiditée```````

**Comment by ildar170975** [comment]
This is not related to mini-graph-card since you are looking for a way of using a templated title of a conventional horizontal stack.

**Comment by Diplo95** [comment]
Ok,
sorry for my lack of competence in HA !

**Comment by ildar170975** [comment]
This is not a problem at all. 
Please create an issue here:
https://community.home-assistant.io/c/configuration/frontend/33
ie in Configuration - Frontend section
People (incl. me) will see it and come to help!
