### ISSUE TITLE
How to display the value of a bar

### ISSUE THREAD

**Issue by my5123** [kalkih/mini-graph-card#1022]
![微信截图_20231027100349](https://github.com/kalkih/mini-graph-card/assets/48872642/60c9b1ba-c07c-44c5-a740-574ab9ba45d3)
How to show the date when hover over a bar.
It can only shows the entity name now .

**Comment by ildar170975** [comment]
Please:
1. Post a CODE, not it's picture.
2. Post a SIMPLIFIED MINIMUM code which shows your issue. No need to post unrelated things.
3. Post screenshots with English language.
4. Use a question mark when asking a question.
5. A date & a state for a particular point are shown when "show_state: true".

**Comment by ildar170975** [comment]
No feedback so far. Will be closed soon.

**Comment by ildar170975** [comment]
No feedback for 3 months from OP.
Closed.
