### ISSUE TITLE
graph is not "linear"

### ISSUE THREAD

**Issue by Tontze** [kalkih/mini-graph-card#1023]
When 50w bar is 5mm high, next bar to it, 60w is 3cm high its not very intuitive. Can this be fixed ? 

This looks like there is something massive happened : 

![kuva](https://github.com/kalkih/mini-graph-card/assets/28216916/d765ab35-6b30-43cb-b2f3-8f8c6b504853)

**Comment by ildar170975** [comment]
What you wrote is rather cryptic.
Provide more explanations, some code & a standard `history-graph` with same `hours_to_show` for comparison.

**Comment by Tontze** [comment]
I mean its not very intuitive when 60w bar is three times higher than 50w. Ofcourse it is because 50W bar is not fully shown(just top of it). Maybe this could be option to show from zero to up ?

**Comment by ildar170975** [comment]
check docs for such an option

**Comment by Tontze** [comment]
> check docs for such an option

Oh, yeah. Thanks..
