### ISSUE TITLE
[request] Would it be possible to align labels to values in or multiple entities?

### ISSUE THREAD

**Issue by Telmo** [kalkih/mini-graph-card#1029]
When displaying multiple entities is there is no way to correlate label to value.
![Screenshot-092946](https://github.com/kalkih/mini-graph-card/assets/109544/c7c4b8aa-1a47-49e8-a380-e6b8f7c45a3f)

Would it be possible to align the labels to values, or even changing the value colors to match the graph line color?

![Screenshot-092947](https://github.com/kalkih/mini-graph-card/assets/109544/b643532f-72f7-450b-a331-29360f2bd9a9)

I really appreciate all the work that you put into this card.

**Comment by ildar170975** [comment]
https://github.com/kalkih/mini-graph-card/issues/679
