### ISSUE TITLE
no card type found

### ISSUE THREAD

**Issue by georgelza** [kalkih/mini-graph-card#103]
so I've downloaded the mini-graph-card-bundle.js and place into /home/pi/homeassistant/addons/local/mini-graph-card-bundle.js

I've created the ui_lovelace.yaml and copied the resources line into there.

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.4.3
    type: module

I then go create new card, manual card and place the below in there: 
- type: custom:mini-graph-card
  entities:
   - sensor.alex_humidity
  align_icon: left
  align_state: center
  show:
    fill: false

this leads to a card type not found. what am I missing.

**Comment by cdrom1028** [comment]
You need to put the card in www. My path is as follows:
   /config/www/custom-lovelace/mini-graph-card/mini-graph-card-bundle.js

and my resources line is:
    resources:
  - type: module
    url:
/local/custom-lovelace/mini-graph-card/mini-graph-card-bundle.js?v=0.4.2


in the context of the UI, local = www



Regards,
________________________________________

ÇÐ-®ÔM

**Comment by georgelza** [comment]
hmmm, take note, i have hass.io deployed as a docker image on docker running on Raspbian on RPI... and not as a hass.io img file burned.
I don't have a config directory in my homeassistant root folder which is located at /home/pi/
G

**Comment by kalkih** [comment]
Yeah so basically, the config directory doesn't have to be named `config`, this can and will vary depending on system and setup as seen [here](https://www.home-assistant.io/docs/configuration/), but you'll know you are in the right directory if you see the `configuration.yaml` file.
When you've located the config folder proceed by creating a directory named `www` (if it doesn't exist already) inside the config folder and then restart HA.
Put the card bundle anywhere inside the `/www` directory, add the resource reference starting with `/local/`, the `/www` directory will be served at `/local/` by HA.

**Comment by georgelza** [comment]
Perfect, placing .js there, assume i have to restart...

**Comment by kalkih** [comment]
If you just created the `www` directory you'll have to restart yep!

**Comment by georgelza** [comment]
pi@hassio:~/homeassistant/homeassistant/www $ pwd
/home/pi/homeassistant/homeassistant/www
pi@hassio:~/homeassistant/homeassistant/www $ ls -la
total 84
drwxr-xr-x  2 root root  4096 Jun  4 20:42 .
drwxr-xr-x 10 root root  4096 Jun  4 20:46 ..
-rw-r--r--  1 root root 76325 May 30 16:43 mini-graph-card-bundle.js
pi@hassio:~/homeassistant/homeassistant/www $ ls -al ../
total 216024
drwxr-xr-x 10 root root      4096 Jun  4 20:46 .
drwxr-xr-x 13 pi   pi        4096 Jun  4 19:49 ..
-rw-r--r--  1 root root         2 May  9 19:14 automations.yaml
drwxr-xr-x  2 root root      4096 May  9 19:14 .cloud
-rw-r--r--  1 root root      7640 Jun  4 19:27 configuration.yaml
drwxr-xr-x  3 root root      4096 May 29 17:45 custom_components
-rw-r--r--  1 root root         0 May  9 19:14 customize.yaml
drwxr-xr-x  2 root root      4096 May  9 19:14 deps
drwxr-xr-x  2 root root      4096 May 19 17:09 glances
-rw-r--r--  1 root root         0 May  9 19:14 groups.yaml
-rw-r--r--  1 root root         6 May 29 20:00 .HA_VERSION
-rw-r--r--  1 root root       497 Jun  4 20:45 home-assistant.log
-rw-r--r--  1 root root 221130752 Jun  4 20:46 home-assistant_v2.db
-rw-r--r--  1 root root         0 May 23 13:14 known_devices.yaml
drwxr-xr-x  5 root root      4096 Jun  1 16:47 node-red
-rw-r--r--  1 root root       105 Jun  4 20:45 plex.conf
-rw-r--r--  1 root root         0 May  9 19:14 scripts.yaml
-rw-r--r--  1 root root       240 May 23 14:44 secrets.yaml
drwxr-xr-x  2 root root      4096 Jun  4 20:46 .storage
drwxr-xr-x  2 root root      4096 May  9 19:14 tts
-rw-r--r--  1 root root        77 Jun  4 19:46 ui-lovelace.yaml
drwxr-xr-x  2 root root      4096 Jun  4 20:42 www
pi@hassio:~/homeassistant/homeassistant/www $

I've created the ui_lovelace.yaml and copied the resources line into there.
the ui_lovelace is in same dir as configuration.yaml

resources:
url: /local/mini-graph-card-bundle.js?v=0.4.3
type: module

still getting : no card type configured

**Comment by kalkih** [comment]
If you're not using [yaml mode](https://www.home-assistant.io/lovelace/yaml-mode/) for lovelace, you might have to add the resource reference through the raw UI editor in the HA interface.

> still getting : no card type configured

Try removing the initial dash before type (`- type`)

**Comment by kalkih** [comment]
Here's a great guide covering the basics of installing custom lovelace cards
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by georgelza** [comment]
I got ... top right, then configure UI, then bottom right on + and then go Manual card. 
I then past:
- type: custom:mini-graph-card
  entities:
   - sensor.alex_humidity
  align_icon: left
  align_state: center
  show:
    fill: false

and get error...

**Comment by kalkih** [comment]
> > still getting : no card type configured
> 
> Try removing the initial dash before type (`- type`)

**Comment by georgelza** [comment]
.Working... did the RAW add to add the resources... that fixed things.
thanks.

**Comment by georgelza** [comment]
thanks thanks. looking lovely.
G

**Comment by sealsteady** [comment]
If you are going to use the example code i lovelaces UI "Card Configuration" then you need to remove the - from type to make it work.

If you dont remove the - you will get the no card type found error

This only works if you enter it in the RAW config editor:

- type: custom:mini-graph-card
  entities:
   - sensor.illumination

Here is what it needs to look like in the configure ui "Card confuguration"
type: 'custom:mini-graph-card'
entities:
  - sensor.illumination

Sorry if this is obvious, but i struggled with this for more than an hour. And i even read this whole topic :P

**Comment by hitesh-singh** [comment]
@georgelza  Could you please tell me what was the final path where you have put your mini-graph-card-bundle.js file and what is your final resources: config looks like in the ui-lovelace.yaml file

FYI my hassio is on docker in the following path
/usr/share/hassio/homeassistant

**Comment by georgelza** [comment]
My final location was:
/home/pi/homeassistant/homeassistant/www
Also have Hass.io deployed inside docker on top of Raspbian.
Then in my configuration.yaml.

#I first pull in the values coming from the sensors: Note, these values come from node red, I read the sensor value from there, change the message/subject, then push the new son message here and also to Influxdb.

sensor:
  - platform: mqtt
    name: "CJ Temperature"
    state_topic: "home/plug/cj_bedside_light/dht22"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "CJ Humidity"
    state_topic: "home/plug/cj_bedside_light/dht22"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"

# and then use the custom component to get the extra values
  - platform: thermal_comfort
    sensors:
      cjroom:
        friendly_name: CJ Room
        temperature_sensor: sensor.cj_temperature
        humidity_sensor: sensor.cj_humidity

**Comment by tmcquaig** [comment]
I had this issue and had two things I had to check to fix it.

```
- type: 'custom:mini-graph-card'
entities:
  - sensor.Pool_Temp
align_icon: left
align_state: center
show:
  fill: false
```

Case sensitive on my sensor and remove the dash and fix the indention on the type.


```
type: 'custom:mini-graph-card'
entities:
  - sensor.pool_temp
align_icon: left
align_state: center
show:
  fill: false
```
