### ISSUE TITLE
Is it possible to show the full date of min/max value

### ISSUE THREAD

**Issue by maijo366** [kalkih/mini-graph-card#1033]
Hello, 
Is it possible to show the full date of min/max value.

![grafik](https://github.com/kalkih/mini-graph-card/assets/96180786/f90f9233-c44b-483e-9cfc-32fb7f13fb77)

```
type: custom:mini-graph-card
card_mod:
  style: |
    .header.flex .name.flex {
      color: #ff4500;
    }
name: Energieverbrauch / Täglich
entities:
  - entity: sensor.energieverbrauch_taglich
show:
  extrema: true
  average: true
  graph: false
hour24: true
hours_to_show: 8760
decimals: null
```

**Comment by ildar170975** [comment]
No it is not.
Consider converting this question-issue to FR.

**Comment by ildar170975** [comment]
No feedback for 4 months .
Closing in favour of https://github.com/kalkih/mini-graph-card/issues/1102
