### ISSUE TITLE
Sporadic data showed wrong from origin

### ISSUE THREAD

**Issue by emandtf** [kalkih/mini-graph-card#1034]
Let me prepare an example:

1. latest 12h on X-axis
2. first data available from "_now - 9h_" (it means at about 1/3 of X axis)
3. all previous 3h are showed at the same value of the first available record value

![20231124_wrong_graph](https://github.com/kalkih/mini-graph-card/assets/13537385/7f2b58be-2fe8-44d1-abdc-bea6520b51af)

As you can see the whole rounded-in-red part is displayed by the Chart but there aren't any data there.
The very first and existent record is the first on the right-side of the red-border.

This happens in both "bars" and "lines" mode.

**Comment by ildar170975** [comment]
Unclear.
Please provide more detailed description & a short minimal code.

**Comment by emandtf** [comment]
> minimal code.

Minimal code of what?
I have a sensor that stored a temperature every X hours, so if the x-axis represents 24h I'm expecting only 4 "peaks"/bars but instead I get N bars starting from the origin (0,0) until first data is reached and all these bars have the "first data" value.
Screenshot previously attached (and its description) is very clear.
I'm expecting NO BARS until first data is met (in the middle of X-axis), and not N fake bars starting from origin which have the same value of the first available data that occurs in the middle of X-axis 😅

**Comment by ildar170975** [comment]
> t's Homeassistant YAML, not a programming language/software with its code 

yaml code

**Comment by emandtf** [comment]
> 1 picture is worth 100 words.

I've already attached a screenshot at the first post 😅

This is the "code" :
> - type: custom:mini-graph-card
    entities:
      - entity: sensor.openwrt_cpu_temperature
    hours_to_show: 58
    show:
      graph: bar
  - type: history-graph
    entities:
      - entity: sensor.openwrt_cpu_temperature
    hours_to_show: 58

and this is the picture
![SmartSelect_20240118_233317_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/13537385/87d98c89-c305-4715-ae21-25cc75127ba8)
that is "the same" of before 🤷‍♂️

Mini-chart starts to show some values starting from origin even if the data are not present in the DB. And these values (before the first valid one) has the same value of that first valid.

**Comment by ildar170975** [comment]
> This is the "code" :

Yet the posted code is clear - it is still unformatted and cannot be used to copy/paste. If you need to be helped - try to cooperate, otherwise you will not get a support, issue will be closed.
"Formatted" - check other issues how people format a code.

Edit your code as follows:
1. Replace `bar` with `line`.
2. Define `points_per_hour` close to the actual frequency of your readings.

The post the FORMATTED code & screenshot.
