### ISSUE TITLE
[FR] Make "smoothing" per-entity

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#1039]
Currently the `smoothing` option is defined on a card's level - globally for all entities.
Proposal: make this option available per-entity as well (if defined per-entity - it has priority).

**Comment by JulienDeveaux** [comment]
I was looking into this when I noticed that it's already working like this in the current version.
When creating the Graphs, smoothing is set from the entity if defined, from the card if defined and finally disabled for binary sensors in this order.
Does this still need to be open ?

**Comment by ildar170975** [comment]
You are right.
It is even mentioned in Docs.
No idea why I believed that `smoothing` is per-card only.
Mea culpa.
