### ISSUE TITLE
Add install/usage instructions for non yaml users

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-graph-card#104]
Add install/usage instructions for non yaml mode users.

**Comment by rosscullen** [comment]
Does this mean that the examples listed on the mini-graph Github homepage would be reformatted for easier use in Home Assistant - Lovelace Card Configuration Editor? Thanks!

**Comment by kalkih** [comment]
Yes, possibly, but also where the resource reference goes etc.

**Comment by jcgoette** [comment]
Does PR #492 resolve this?

**Comment by jlsjonas** [comment]
Closed by a462c8486a68557a2902a501b02a5074df29381c (along with other past effort, and #689 as _follow-up_)
