### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by Vartkat** [kalkih/mini-graph-card#1045]
Hi,

since a few versions of Home Assistant user can ask to show hours either by server time or local time which was long awaited feature for people monitoring systems abroad.

On mini grah card hours do not comply with this setting, whenyou hover a point the hour given is the reader local tile never the server TZ even if the preferences setting is set to server time.

V.

**Comment by ildar170975** [comment]
Consider renaming the issue to reflect it's purpose.
Now the issue's title is absolutely unclear & "blaming".

**Comment by ildar170975** [comment]
Duplicates https://github.com/kalkih/mini-graph-card/issues/983
