### ISSUE TITLE
Feature Request: Align graphs with and without legends

### ISSUE THREAD

**Issue by michaelblight** [kalkih/mini-graph-card#105]
I would like two graphs side-by-side with the same height. I have one that plots one series, and therefore cannot have a legend, and other plots multiple series, and needs its legend. They cannot be aligned because the legend is not included in `height`. One option would be to allow `legend` to be set to "always" to display even if there's only one series. Or is there another way I'm not aware of. At the moment I'm just plotting the same data twice to get a dummy legend, which is a bit of a hack.

**Comment by kalkih** [comment]
The card does already adjust to fill the whole container height by default, so if you place the two graphs in a horizontal-stack it will look something like this.

![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/59691905-23297000-91e4-11e9-8a54-fc427f9a5693.png)

**Comment by michaelblight** [comment]
Ah, my bad. I have them at the bottom of two vertical stacks that are side-by-side. I can fix that. Thanks.

**Comment by kalkih** [comment]
Awesome, yup, adding a horizontal-stack should do the trick!
I had almost forgot I added that "feature" 🙂

**Comment by michaelblight** [comment]
Looks much better now, thanks again.

<img width="1427" alt="Screen Shot 2019-06-20 at 5 06 20 pm" src="https://user-images.githubusercontent.com/373079/59828307-0b85ef00-937e-11e9-9c95-8265fa1f24ba.png">
