### ISSUE TITLE
Sporadic data showed wrong from origin

### ISSUE THREAD

**Issue by emandtf** [kalkih/mini-graph-card#1057]
I'm rewriting the same things of other post that "_ildar170975_" choosed to close and mark as "completed" 🤷‍♂️

I tried but it's not possible to paste my YAML code using a CODE tag in this GitHub form due to carriage_returns or other characters which interrupts that Tag in the middle leaving half code out of it.

The user/moderator "_ildar170975_" neither accepted a QUOTE tag (which seems to not ruins my YAML but lost few indentations) so I have to post the screenshot of my YAML 🤷‍♂️

![SmartSelect_20240119_000550_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/13537385/c623ab5d-821a-4bec-988b-0b32f2c3a1da)

This is the result:
![297899281-87d98c89-c305-4715-ae21-25cc75127ba8](https://github.com/kalkih/mini-graph-card/assets/13537385/6eed8c8b-c5f6-4f1e-b8bd-6ae442621f2a)

I have no any data in my DB starting from origin, but mini-graph has still created its graph by using first available data which is in the future compared to the origin.

**Comment by ildar170975** [comment]
Your issue was closed since you reacted in a negative way to my request to provide data in a usable way.
Disrespect is not tolerated.

**Comment by ildar170975** [comment]
Code should not be posted neither as a screenshot nor as a quote.
Check other posts containing a code & compare with yours.

**Comment by emandtf** [comment]
> Your issue was closed since you reacted in a negative way to my request to provide data in a usable way. Disrespect is not tolerated.

- You started to call "code" the YAML....which is not a CODE. So I didn't understand what "code" you asked for.
- the issue is present beside the YAML. No any YAML attribute/row can let min-graph to create data where there aren't any one.
- the "code" is made by literally 6 rows of YAML...so it's not a big deal to "decipher" even if 2 indents are lost during copy/paste procedure

> Code should not be posted neither as a screenshot nor as a quote.
Are you kidding me?
I said that copying/pasting ruins the format of the final YAML.
What's the problem to read a damned 6-rows-YAML even if 2 intent are lost? Don't you have that ability? Are you a bot which with a wrong indentation cannot understand what is written?
The point is NOT the YAML but the mini-graph which shows data where there isn't.
I wasted, yesterday, hours to answer you just because you didn't understood initial post where I was even providing a valid and perfectly understandable screenshot.

> The "`" char is located right below "ESC" button on a keyboard.
Are you thinking am I stupid?
I'm a developer from 30 years of work and I know where characters are. Maybe you didn't considerate that the BACKTICK is present only in YOUR keyboard layout. In my keyboard it isn't. So maybe you lack of knowledge of something technical but you act as a moderator here....it's incredible.

However THIS is the result by pasting my YAML in the CODE tag:
`- type: custom:mini-graph-card
    hours_to_show: 58
    entities:
      - entity: sensor.openwrt_cpu_temperature
    show:
      graph: bar
  - type: history-graph
    entities:
      - entity: sensor.openwrt_cpu_temperature
    hours_to_show: 58`

Are you happy now? I hope yes.
