### ISSUE TITLE
Extrema option doesn't account for unit changes

### ISSUE THREAD

**Issue by theanorak-keith** [kalkih/mini-graph-card#1060]
A question:
I'm using mini-graph-card for a weather dashboard but decided to switch the unit of measurement for windspeed after setup. The graph and value update correctly (i.e. use the new unit and the converted value) but the extrema display just updates the units without converting the values.

Is this a (minor) issue with the mini-graph-card or a product of underlying functionality?

**Comment by ildar170975** [comment]
All graphs in HA work same way.
Even a standard history-graph.
Changing UoM does not cause changing a history.

**Comment by ildar170975** [comment]
Close the issue if resolved.

**Comment by theanorak-keith** [comment]
Ah, ok. Thanks.

**Comment by ildar170975** [comment]
Actually, this is a duplicate of https://github.com/kalkih/mini-graph-card/issues/945
That is not closed yet since I opened an issue against a standard `history-graph`.
If the standard card is updated - then we'' probably consider that issue for mini-graph-card.
