### ISSUE TITLE
Possibility to map string values to binary values

### ISSUE THREAD

**Issue by orzechszek** [kalkih/mini-graph-card#1062]
Hi,

Is it possible to add mapping functionality to change string values to binary values? 
For example to have possibility to present device_trackers graph stability.

**Comment by ildar170975** [comment]
1. This is a question, not a feature request. 
2. Device tracker coukd be home, not_home or a name if a zone. If you need to show this as on/off - create a corresponding template binary sensor.

**Comment by ildar170975** [comment]
Answer was provided, closing.
