### ISSUE TITLE
Feature request - Option to show vertical markers for specific time periods

### ISSUE THREAD

**Issue by psfshr** [kalkih/mini-graph-card#1074]
An option to show vertical markers for specific time periods on the graphs, e.g. show markers/lines/etc weekly, daily (at midnight), hourly (on the hour), etc depending on the graph. This would help make it clearer as to the horizontal scale of the graph, and when glancing at the graph help give an indication of when something takes place (e.g. did something happen before/after midnight on graph showing the previous 12h)

**Comment by ildar170975** [comment]
gridlines - https://github.com/kalkih/mini-graph-card/issues/837
scale - https://github.com/kalkih/mini-graph-card/issues/739
