### ISSUE TITLE
align_icon to right is not applied

### ISSUE THREAD

**Issue by SAOPP** [kalkih/mini-graph-card#1078]
Hey!

I tried to show my icons to the right corner, but this is not working for me. Any suggestion? Thanks!

![image](https://github.com/kalkih/mini-graph-card/assets/5647009/f86d83b5-91d0-4ea9-95ba-8e0763dd5205)

```
        - type: custom:mini-graph-card
          entities:
            - entity: sensor.toilet_monitor_temperature
              name: Температура
              color: '#03A9F4'
          hours_to_show: 24
          line_width: 4
          decimals: 1
          align_icon: right
          animate: true
          height: 90
          font_size: 65
          show:
            name: false
            icon: true
            state: false
            legend: false
            fill: fade
          card_mod:
            style: |
              ha-card {
                border-radius: 8px;
                background: none;
                box-shadow: none;
                --ha-card-border-width: 0;
              }
        - type: custom:mini-graph-card
          entities:
            - entity: sensor.toilet_monitor_humidity
              name: Влажность
              color: '#B694E7'
          hours_to_show: 24
          line_width: 4
          decimals: 1
          align_icon: right
          animate: true
          height: 90
          font_size: 65
          show:
            name: false
            icon: true
            state: false
            legend: false
            fill: fade
          card_mod:
            style: |
              ha-card {
                border-radius: 8px;
                background: none;
                box-shadow: none;
                --ha-card-border-width: 0;
              }
```

**Comment by ildar170975** [comment]
1. Why the code & screenshot contain lots of unrelated things like card-mod, other UI elements? This should not be posted. Just a distraction & waste of space.
2. The `align_icon: right` option works only if `name` is shown. If you do not want to show `name` - just set it to `name: ' '`. In your code you have `name: Температура` and `name: false` which has no sense.

**Comment by SAOPP** [comment]
> 1. Why the code & screenshot contain lots of unrelated things like card-mod, other UI elements? This should not be posted. Just a distraction & waste of space.

Hey homie, I didn't ask u how I should post here. I asked a completely correct question, something I had never encountered before when using a card. In the end, I showed the general picture of how I organize this, I see no reason why u should be indignant when looking at the information that I presented above. :smile: 

> 2\. The `align_icon: right` option works only if `name` is shown (this is a "flex" row). If you do not want to show `name` - just set it to `name: ' '`. In your code you have `name: Температура` and `name: false` which has no sense.

Yes, I actually posted the code with the name field because of my experiments. But even without him, I was convinced that the icon was not moving to the right, which is why I asked this question.

**Comment by Nickduino** [comment]
> 2\. The `align_icon: right` option works only if `name` is shown (this is a "flex" row). If you do not want to show `name` - just set it to `name: ' '`.

I don't get the reasoning but ok. Could you update the doc, then?

![image](https://github.com/user-attachments/assets/bb105ff1-f7a0-4602-a65e-e72f56778ef1)
to something like "Set the alignment of the icon, `left`, `right` or `center`, only if the name is displayed."
(I imagine it's `center` and not `state` but I may have gotten that wrong.
