### ISSUE TITLE
add offset to the right

### ISSUE THREAD

**Issue by hoedha12** [kalkih/mini-graph-card#108]
Hi,

First of all this is my first opening an issue, so apologize if I made this incorrectly. I'd like to thank the developers first for this wonderful add on for HA, it is really beautiful, increasing WAF by tenfold I may say.. ;)

One problem for me is that when I view the card in full portrait mode in my phone, I cannot see the rightmost line/data (the most current data). This is due to my phone (and several other phones) has curved screen edge, in my case it is Samsung Note 8. I propose, if it's not too much from you, to be able to add offset of certain 'n' data to the right, so that the most current data is a bit padded to the center. I hope I can convey my message well, since English is not my main lainguage.

Thank you very much!

**Comment by kalkih** [comment]
Hey, thanks, glad you're enjoying the card!

I get your point and there are a few ways you can solve this.

* Hiding the graph fill will add a `16px` padding to the graph.

```yaml
show:
  fill: false
```

* If you want to keep the fill but add a margin to the graph I would suggest wrapping the card inside an entities card and use the group option on the card, like this.
```yaml
- type: entities
  entities: 
    - type: custom:mini-graph-card
      group: true
      # ... rest of config
```

* You could also use [card-modder](https://github.com/thomasloven/lovelace-card-modder) to add a custom right padding/margin to the card.
