### ISSUE TITLE
Show state next to a legend's label

### ISSUE THREAD

**Issue by ljmerza** [kalkih/mini-graph-card#1081]
Is there a way to have the `show_state` next to the label instead of off to the side? With a few entities added, its not easily seem which state belongs to which entity

<img width="774" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/4085765/de84ab9c-ce07-4d19-ae9c-70a1e3ccf61f">

**Comment by ildar170975** [comment]
Similar proposal were here: https://github.com/kalkih/mini-graph-card/issues/679
Will keep both issues open:
1. this current issue is associated with a corresponding PR;
2. [another issue](https://github.com/kalkih/mini-graph-card/issues/679) contains card-mod-based solutions.

Probably both issues could be closed in case of the PR is reviewed & merged.

**Comment by ildar170975** [comment]
Implemented in https://github.com/kalkih/mini-graph-card/pull/1173
