### ISSUE TITLE
12am or 12pm in a 24 hour format shown as 0am or 0pm when using extrema

### ISSUE THREAD

**Issue by hendy-ghub** [kalkih/mini-graph-card#1086]
When extrema is enabled, if min or max values are shown using the 24 hour format, if values are detected at 12am or 12pm, they are shown as 0:xx am or 0:xx pm

here are two examples:

![image](https://github.com/kalkih/mini-graph-card/assets/82519013/493d7678-8567-4473-9849-9c141897f540)

![image](https://github.com/kalkih/mini-graph-card/assets/82519013/e518ae20-a044-4fb4-bbe2-03ce4729ee90)

**Comment by ildar170975** [comment]
same as https://github.com/kalkih/mini-graph-card/issues/887
