### ISSUE TITLE
Yaml code does not work on HAOS but works on docker container version

### ISSUE THREAD

**Issue by badkernel** [kalkih/mini-graph-card#1087]
Hello
I have been testing Home assistant in docker for some time now and been using mini graph card.
I am very happy with the way graphs look and installed full version of Home assistant on spare PC and wanted to copy my code to it. Unfortunately code does not work and it does not provide needed information. 

Code looks like this: (removed pasted code and added screenshot)

<img width="1036" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/51629615/73905d7f-8db9-4c44-b8fa-3c7d125e2f1d">

<img width="497" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/51629615/49259d15-0496-482b-be30-2a025326181a">

When I add the same code to HAOS full installation on it does not show information.

<img width="504" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/51629615/aa47b00b-4874-486e-9f96-23e2720ac471">

HA version in docker 
Core 2024.2.5
Frontend 20240207.1

HAOS installed on PC
Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0

Config

<img width="981" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/51629615/c8c151e0-80d0-460f-8db5-93e371e28eea">

**Comment by ildar170975** [comment]
Try to check with a standard history-graph.

**Comment by badkernel** [comment]
Pasted inn screenshot since code was a mess in GitHub.

Thanks for the tip, I see the same with standard history-graph :(
Very odd
