### ISSUE TITLE
Question: Average between two entities?

### ISSUE THREAD

**Issue by Dumonster** [kalkih/mini-graph-card#1094]
Hi,

I have a graph with two entities (temperature sensors). Is there any way to have the value displayed be the average of these two?

I've read through the whole documentation and couldn't find it but there are so many options that I might have just missed it.

Thanks!

**Comment by ildar170975** [comment]
Not possible. Create a template sensor to get an average value.

**Comment by Dumonster** [comment]
Thanks for your reply.

Follow up question: Can I then have that value displayed without a corresponding graph? As in, I'd like to have the grafic showing only the two original sensors and then just the current value from the template sensor.

**Comment by ildar170975** [comment]
There is an example in docs

**Comment by Dumonster** [comment]
I've looked through the docs and examples once more and didn't find it.

Thanks anyway.

**Comment by ildar170975** [comment]
Since you need

> have that value displayed without a corresponding graph

you should check a chapter about “show additional data”.
It is about showing a state without showing a graph. 
If you need a different look - consider using other custom solutions.

**Comment by ildar170975** [comment]
@Dumonster 
Please respond, is the issue still unsolved?

**Comment by ildar170975** [comment]
No feedback within a month.
Closing.
