### ISSUE TITLE
[FR] Format numbers according to "Number format" of user profile

### ISSUE THREAD

**Issue by dr3amr** [kalkih/mini-graph-card#1103]
Hi @kalkih ,

Was looking at #495 but now HA has a Number Format in the user profile, would be great if you could change how numbers are displayed based on this rather than Language. I use English everywhere (apps, phone etc) but use numbering format from my country (which uses , for decimals instead of . ). All other cards are aligning to this preference in the user profile rather than Language. If this would be rather hard perhaps some custom attribute can be created to switch from one format to the other. Thanks.

**Comment by ildar170975** [comment]
duplicate https://github.com/kalkih/mini-graph-card/issues/1010

**Comment by dr3amr** [comment]
@ildar170975  sorry did not see #1010 ...
