### ISSUE TITLE
Title letter spacing

### ISSUE THREAD

**Issue by aegjoyce** [kalkih/mini-graph-card#111]
Please please please could I request that line 85 of style.js is changed to 'letter-spacing: normal'? Or even just deleted entirely? On every system and browser I run, and from what I've seen, other people's HA instances too, having it set to .05em (as it is currently) causes weird letter spacing that just is not consistent with any other elements on a Lovelace page.

I was until recently using a modified version of the card where I had made this change but with the new HACS system for updates it makes it harder to keep the card up-to-date AND keep somewhat-normal-looking and consistent text formatting.

**Comment by aegjoyce** [comment]
For example, here: https://community.home-assistant.io/t/system-monitoring-how-does-your-look/109713/212

My Lovelace looks very similar to this - titles of other cards have normal letter spacing, whilst the mini-graph ones stand out because of the unusual spacing.

It's an otherwise PERECT card and I can't express how much I appreciate your time spent in developing it! I'm just a total anorak when it comes to UI and consistency :) Forgive me!

**Comment by kalkih** [comment]
Sure, could remove for consistency’s sake, and possibly add an optional theme variable later.
HA could really use some more letter-spacing throughout though...
