### ISSUE TITLE
Graph not respecting change of unit of meassure from W to kW

### ISSUE THREAD

**Issue by bqzero** [kalkih/mini-graph-card#1110]
Hi

I noticed today that changing the unit of meassure has a strange effect on the graph display. Although min max and average as well as current value work perfectly. The graph has issues displaying the data correctly.

![2024-06-25 14_05_43-Solar – Home Assistant and 5 more pages - Work - Microsoft​ Edge](https://github.com/kalkih/mini-graph-card/assets/40733259/efedf1f2-5600-4b33-9883-29be14befb57)

old data just seams to be handled as same unit of meassure as the new ones that come in.

![2024-06-25 14_06_01-Solar – Home Assistant and 5 more pages - Work - Microsoft​ Edge](https://github.com/kalkih/mini-graph-card/assets/40733259/298cc9df-7880-43ed-a3ae-ba15622abfb1)

Result is that the older data from before the change is display with basically a scale times 1000, resulting in current values not being really registered at all in the graph. I suspect that there is some scaling not taken care of when data is read from the db. Would be nice to have the data presented properly. I normally display multiple months in my card and with this the current data just displays a bottom line.

BR,
Christian

**Comment by ildar170975** [comment]
Same as https://github.com/kalkih/mini-graph-card/issues/945
