### ISSUE TITLE
line_width is interpreted differently depending on screen size: looks a lot larger on larger resolution screens

### ISSUE THREAD

**Issue by ncd7** [kalkih/mini-graph-card#1113]
I'm not sure if this is intended but if I set line width to 5 for instance, the thickness looks different on my large-screen tablet (MUCH larger), than on my phone (relatively thing but readable and minimalistic). 
Is this a bug or is there some way to specify units that show the line at the same thickness regardless of the screen's resolution? 
Thanks.

**Comment by ildar170975** [comment]
> the thickness looks different on my large-screen tablet 

Line width is used for a `stroke-width` CSS property measured in `px`.
A pixel has a different size on different viewports.

>  than on my phone

Companion app uses its own scaling. Better check on a mobile browser.

> show the line at the same thickness regardless of the screen's resolution?

It cannot be since - read above - pixels have diff sizes.

**Comment by ildar170975** [comment]
You may try defining `line_width` dynamically dependingly on viewport's sizes, but this may not worth it:
1. Place the whole `mini-graph-card` inside `config-template-card` (google it's repo for docs).
2. Define a value for `line-width` in a JS template.

**Comment by ildar170975** [comment]
> perhaps it is better to use e.g. an `em` unit

According to my quick check, the `stroke-width` property accepts a unitless value; it also accepts a value with "%" and I have no idea how this percentage it used. So, may be internally in depths of CSS this value is somehow converted to `px` and it seems to be a fixed value on different viewports.
