### ISSUE TITLE
Cannot hide state (show_state=false) for the first entity

### ISSUE THREAD

**Issue by fbsdmon** [kalkih/mini-graph-card#1123]
When I try to graph two entities, I cannot hide the state of the first entity. It is always shown. I can show or hide the state of all other entities the list of entities I am trying to graph, but not the first one.

I don't want to change the order because I want to use the icon from the first entity. So, I guess another solution for my problem is to introduce a functionality to choose which icon is used by the mini-graph-card, from which entity.
I know that I can just set an icon manually, but the icon in question is dynamic (changes depending on value), and there is no way to template the icon inside the mini-graph-card.

**Comment by ildar170975** [comment]
Please do not several questions in one issue. 

1. You cannot currently hide a state fir the 1st entity. If you need to change it - register a feature request for it. Also, I think there is an existing issue for this, try finding it. 
2. Since the card may show graphs for several entities, only an icon for the 1st entity is shown. But you can define your own icon by a corresponding “icon” option.

**Comment by ildar170975** [comment]
Is the issue resolved?

**Comment by fbsdmon** [comment]
Well, no. But this limitation is by design, and there is a feature request for it, so we can close it.

**Comment by fbsdmon** [comment]
Well, no. But this limitation is by design, and there is a feature request for it, so we can close it.

**Comment by ildar170975** [comment]
> But this limitation is by design

Correct.


> and there is a feature request for it, so we can close it.

Actually, I do not recall an OPEN issue for "allow not showing a state for the 1st entity".
[Here ](https://github.com/kalkih/mini-graph-card/issues/889#issuecomment-1901778402)- similar issue & it was advised to use card-mod to hide a state as a workaround.
[Here](https://github.com/kalkih/mini-graph-card/issues/1018) - a similar issue with no feedback from OP.
Means - you may keep your issue open - but rename it to something like "[FR] Allow hiding a state (show_state=false) for the first entity".
