### ISSUE TITLE
Feature Request - Option for secondary y-axis

### ISSUE THREAD

**Issue by michaelblight** [kalkih/mini-graph-card#113]
I have multiple graphs that span a few days. I find it useful to have a light-gray banding showing where nighttime is. I'm doing this by plotting another series that has data points of 0 during the day and 'n' at night. This works okay, but I have to have separate data for different values of 'n'. Ideally I would plot this day/night series on a separate y-axis that appears on the right, as you can do in Excel and Google Sheets. This way I would only need points at 0 and 1 (ie. n=1) - then 0 would plot at the bottom of the graph, and 1 at the top, independent of the vertical scale of other data series.

I've had a look at the existing code, and a solution presents itself. Is it worthwhile if I have a go at making the changes myself and then submitting a PR? And if so, how can I communicate my thoughts beforehand so I don't waste everybody's time? Alternatively, given the popularity of the card and the number of current feature requests, I can understand you may want to manage the change process yourself.

**Comment by kalkih** [comment]
Hey,

I can see the use case, could also be useful to see the state switches or status of the AC.
If you feel like it, please have a go at it, all contributions are highly appreciated!

We can discuss the feature/code/changes in the PR you open, you can submit the PR even if the implementation isn't complete/working and we can discuss it further there.

**Comment by michaelblight** [comment]
You're probably going to think I'm mad, but...

I had noticed a problem where a graph didn't always match the expected data - I would know something was on and it was showing off, or vice versa, but I never did anything about it. Now that I'm making changes, it's becoming obvious. For example the following two pics are of the same graph, just with a page refresh between. Notice that the gray shading starts is one the left on the top one, but not on the bottom. This is my modified version of the code (it includes a right y-axis and no lines or points), but I get the same result with the original code (see 3rd pic). The 2nd pic is correct - that data is there, just not being graphed. When I refresh it might change from one to the other, or change once and then not again. It only seems to occur when all the values are the same at the start of the graph. Have you seen anything like this?

<img width="478" alt="Screen Shot 2019-07-05 at 5 16 37 pm" src="https://user-images.githubusercontent.com/373079/60704925-22fdd400-9f49-11e9-9d2e-89bbfe7f936e.png">

<img width="479" alt="Screen Shot 2019-07-05 at 5 16 20 pm" src="https://user-images.githubusercontent.com/373079/60704907-19746c00-9f49-11e9-8b0c-91df8d46b9c9.png">

<img width="479" alt="Screen Shot 2019-07-05 at 5 24 35 pm" src="https://user-images.githubusercontent.com/373079/60705189-d2d34180-9f49-11e9-9eac-a44a379796f3.png">

**Comment by michaelblight** [comment]
Here's the 0.4.3 code beside a history-graph showing the mini-graph-card is missing data. Both are showing 36 hours.

<img width="950" alt="Screen Shot 2019-07-05 at 5 52 43 pm" src="https://user-images.githubusercontent.com/373079/60706919-df599900-9f4d-11e9-8885-ba04c42ab48d.png">

**Comment by kalkih** [comment]
Haven't noticed the issue myself.

Keep in mind that this graph card calculates the graph by the moving average and also applies a smoothing effect to the line, so the data might not always match what you see in the history-graph for example.

Also, when requesting history data from the API, we get one "extra" history entry (unless we explicitly tell the API not to give us it) at the beginning of the time range, this entry has the reported timestamp of the start time set in the api request, even though in reality, the entry can be older than that.
In mini-graph-card we skip this entry, not sure how the default history-graph handles it.

Not sure if this explains the differences you are seeing, but if the graph differ randomly between fast page refreshes there might be something wrong somewhere. 🤔

**Comment by kalkih** [comment]
Okay, I'll close this now, thanks for the PR @michaelblight, great addition! 
The data/graphing issue described is similar to #117, so let's continue the discussion there.
