### ISSUE TITLE
Choosing the layer of a line

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1147]
![image](https://github.com/user-attachments/assets/c72462ef-67ae-4861-98a3-2ad79c3b311b) vs  ![image](https://github.com/user-attachments/assets/f05e8f2b-c240-456d-bf75-a17bd720b626)

I mean it's not the end of the world but I'd like the CO₂ state to be the first (ligned left) **and** the CO₂ line to always be on top. Is there a way to do it? I tried with `align_state: center` but it aligns the whole section, not individual states.

**Comment by ildar170975** [comment]
Z -index depends on an order of entities. 
You may re-define z-index for a particular graph by card-mod. 
Ask in the main mini-graph-card thread in Community. 
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385
