### ISSUE TITLE
Height control dosent work as it should

### ISSUE THREAD

**Issue by heyimdownhere** [kalkih/mini-graph-card#1162]
When you change the height it only changes the height of the graph and no the height of the card. It would be VERY VERY helpful (and its asked for a lot from what I see) to have the ability to move the graph behind the text. 
![image](https://github.com/user-attachments/assets/c195e3a7-9868-424b-8194-18ed842fec70)
Basically the above image shows it. You can shrink the bottom of the card (the graph) but you cannot shrink the cards so the graph moves up. 

Card mod also applies to everything except these seemingly. Changed it to 10px and no size changes were noted.

**Comment by ildar170975** [comment]
> only changes the height of the graph and no the height of the card

Wrong. Suggest to retest without using grids, stacks etc.

**Comment by heyimdownhere** [comment]
Okay here is the new test. I will also attach code for the entire dashboard so you can maybe be less rude...
![wrong](https://github.com/user-attachments/assets/39e91e53-d543-46b0-89c2-a53bad644943)
Above images both use the same code but only change the "height" setting that you said works...
It does not work as intended. 

`      - type: custom:mini-graph-card
        entities:
          - sensor.sam_pc_sam_pc_gputemperature
        font_size: 80
        height: 60
        line_width: 3
        hours_to_show: 0.5
        points_per_hour: 150
        align_icon: left
        align_state: right
        line_color: red
        name: GPU Temp
        smoothing: true
        show:
          icon: true
          name: true
          state: true
          average: false
          labels: false
          extrema: false
        card_mod:
          style: |
            ha-card {
              height: 20px !important;
            }
      - type: custom:mini-graph-card
        entities:
          - sensor.sam_pc_sam_pc_gputemperature
        font_size: 80
        height: 10
        line_width: 3
        hours_to_show: 0.5
        points_per_hour: 150
        align_icon: left
        align_state: right
        line_color: red
        name: GPU Temp
        smoothing: true
        show:
          icon: true
          name: true
          state: true
          average: false
          labels: false
          extrema: false
        card_mod:
          style: |
            ha-card {
              height: 20px !important;
            }`

**Comment by ildar170975** [comment]
Correct a formatting of your post.

**Comment by heyimdownhere** [comment]
Watch my language? I said you were rude because you offhand dismissed what someone else said.

> Correct a formatting of your post.

Wrong. Suggest to retest formatting without using grids, stacks etc.

**Comment by ildar170975** [comment]
Too heated. Calm down and come back.
