### ISSUE TITLE
include a setting to switch to display 12(am/pm)/24 hours

### ISSUE THREAD

**Issue by flammoracle** [kalkih/mini-graph-card#1177]
please add a switch or config to easily remove am/pm from the display or just make use of system settings to display the time correctly in the native way. basically include a setting to switch between 12 or 24 hours display

**Comment by ildar170975** [comment]
> include a setting to switch between 12 or 24 hours display

![image](https://github.com/user-attachments/assets/a3c7590e-660a-4aea-b3a5-4af293696b62)
