### ISSUE TITLE
Feature Request - Dynamic Bound

### ISSUE THREAD

**Issue by ge33ek** [kalkih/mini-graph-card#1187]
Any way for us to enable the upper and lower bound to be dynamic based on either the state of other entities, or similar so that on-draw it adjusts to reflect the latest lower and upper bound?

I’d like the upper and middle bound to be n-1 based on certain criteria 

Thanks

**Comment by ildar170975** [comment]
> upper and lower bound to be dynamic based on either the state of other entities

Just do not specify these options - then bounds will be set dynamically.
