### ISSUE TITLE
0.50 seems to break ios app

### ISSUE THREAD

**Issue by mikalmo1** [kalkih/mini-graph-card#120]
After installing 0.50 the ios app started misbehaving. Downgraded to 0.43 and everything was back to normal again.

**Comment by kalkih** [comment]
Hey, what do you mean by misbehaving? Just tried on a few iPhones and couldn't notice anything strange.

**Comment by kalkih** [comment]
@mikalmo1 Do you still have these issues?

**Comment by maestropastelero** [comment]
I have ios v10.2 and don't work for me, I don't think it is related to this code, as my other custom card have the same error. Looks more like a lovelace issue for mobile.

On the app (v0.96.5), Safari and Chrome on iPhone I got the error on red :Custom element doesn`t exists: mini-graph-card.

On desktop works perfect, really beautiful graph, thanks.

**Comment by kalkih** [comment]
Thanks for the info @maestropastelero!

You could try the following if you experience the `Custom element doesn`t exists` error.
> If you have issues displaying the card in older browsers, try changing type: module to type: js in the card resource reference.

Changing type to js can solve compatibility issues in some cases.

**Comment by mikalmo1** [comment]
> @mikalmo1 Do you still have these issues?

Sorry for the late reply. Yes, I am still having issues with my iOS-app and this version (0.50) It shows up as intended on my desktop computers, but in the iOS-app it just says: "Custom element doesn't exist: mini-graph-card."
![IMG_1003](https://user-images.githubusercontent.com/46075715/62934349-9e626900-bdc4-11e9-856f-5f73ec017e8f.png)

**Comment by kalkih** [comment]
Okay.
Please try the following:

> If you have issues displaying the card in older browsers, try changing `type: module` to `type: js` in the card resource reference.

**Comment by mikalmo1** [comment]
Ok, I tried that. Nothing different, i am afraid..

**Comment by kalkih** [comment]
Very strange, I can't manage to reproduce the issue on my iOS devices 🤔 
What version of iOS are you running?

**Comment by mikalmo1** [comment]
iOS 12.4 on an iPhone 7. Very strange. I'll have to say, this was not the strange behavior I was mentioning in the initial post. Then it caused the app to be very slow and unresponsive for a while, before it ultimately crashed.. So I guess there might be something going on with my app. I'll try and reinstall the companion app on my phone and see how that goes.

**Comment by mikalmo1** [comment]
Nope - same error occurs after reinstalling the app..

**Comment by kalkih** [comment]
You didn't possibly install the card from HACS?

If so, please double check the resource reference as it seems to have changed recently.
It could be that the card is still cached on your desktop and that's why it's working there still.

For me it's now
```yaml
 - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
   type: module
```

And before:
```yaml
 - url: /community_plugin/mini-graph-card/mini-graph-card.js
   type: module
```

You can see the correct one by navigating to the card in the HACS store

**Comment by mikalmo1** [comment]
Yes! I figured this out a couple of days ago.. Works perfectly now!
