### ISSUE TITLE
Graphs aren't displaying in panel mode...

### ISSUE THREAD

**Issue by arretx** [kalkih/mini-graph-card#121]
So, I have 4 graphs with vertical and horizontal stacking and multiple entities per graph, but when the view is set to panel mode, they disappear.  Is this a bug?

**Comment by kalkih** [comment]
Hey,
Could you send your config? I've tried in views with `panel: true` and a vertical-stack with multiple horizontal-stacks in but seemed to work as expected.

Note, [panel-mode](https://www.home-assistant.io/lovelace/views/#panel-mode) will only render the first card in the view.
