### ISSUE TITLE
Not working on Samsung Hub Fridge browser

### ISSUE THREAD

**Issue by rodhall** [kalkih/mini-graph-card#122]
Panels say custom card not found on Samsung Tizen browser on Family Hub fridge. No idea why as mini-graph-panel working fine in Safari

**Comment by kalkih** [comment]
Hey, please try this:
> If you have issues displaying the card in older browsers, try changing `type: module` to `type: js` in the card resource reference.

**Comment by kalkih** [comment]
Closing this for now, the suggestion above should do the trick I believe, feel free to reopen the issue if it doesn't.
