### ISSUE TITLE
Feature Request: Option to disable interpolation

### ISSUE THREAD

**Issue by snarky-snark** [kalkih/mini-graph-card#126]
It would be nice to have an option to disable interpolation. There are use cases where it makes sense to have sharp transitions between values. In particular, I would like to have a graph that displays state transitions of a variable or the results of step functions.

**Comment by kalkih** [comment]
Hey, there's the option `color_thresholds_transition` which you can set to `hard` to get a hard transition between threshold colors. This option might change to a scale later https://github.com/kalkih/mini-graph-card/issues/118

> In particular, I would like to have a graph that displays state transitions of a variable or the results of step functions.

This functionality will most likely not get added to the card, but what you could do is to try [config-template-card](https://github.com/custom-cards/config-template-card), with which you could possibly achieve that.

**Comment by snarky-snark** [comment]
I realized that what I wanted could be achieved by increasing points_per_hour to sufficiently large value.
