### ISSUE TITLE
line_value_below: 0 Does not work

### ISSUE THREAD

**Issue by deviant-studio** [kalkih/mini-graph-card#13]
I'm trying to change line color on negative temperatures, so i set
`line_value_below: 0`
and it does not work for me. Color doesn't change when the value < 0. Looks like the card ignores this setting. 
The temporary workaround is:
`line_value_below: 0.1`

**Comment by kalkih** [comment]
Fixed in [v0.0.9](https://github.com/kalkih/mini-graph-card/releases/tag/v0.0.9), thanks!
