### ISSUE TITLE
How to show 1 bar per day

### ISSUE THREAD

**Issue by Thomasdmm** [kalkih/mini-graph-card#134]
Hello I have a sensor who show the power used of yesterday, i want to show it in a mini graph type bar but i don't create the good one
I try with point-per-hour but i don't get what i want
Can you help me ?
thanks

**Comment by kalkih** [comment]
Hey, sorry, not currently possible.
There's a feature request for it here already https://github.com/kalkih/mini-graph-card/issues/78.
