### ISSUE TITLE
24 to 48 hours graph

### ISSUE THREAD

**Issue by IkkeLogisk** [kalkih/mini-graph-card#138]
Hi, would it be possible to have a graph showing for example 24 to 48 hours as 2 curves?
Where the first 24 hours represent yesterday and the second graph represent the current day?
See example picture where the blue line is yesterday and the red line is today until current time.
![2days](https://user-images.githubusercontent.com/32767577/63514854-da46ae00-c4e9-11e9-854f-04eba4c90758.png)

**Comment by kalkih** [comment]
Hey, there's a feature request open for this already, see https://github.com/kalkih/mini-graph-card/issues/110.
Thanks!
