### ISSUE TITLE
Configuration affects wrong entity

### ISSUE THREAD

**Issue by roybosch** [kalkih/mini-graph-card#140]
Hi,

First of all: great card you made. I'm having fun using it and it looks great!

Today I tried making it some more advanced. I want to show the mean temperature of the house as a state but hide the graph line. 

In your description you're mentioning this functionality, so I used it. I encountered something what seems to be a bug though. By adding entity-specific configuration, it's hiding the wrong entity. The image below illustrates this:

![image](https://user-images.githubusercontent.com/45666392/63573138-de73d980-c584-11e9-8435-81ea54f3ce65.png)

As you can see the straight mean ("Gemiddelde" in Dutch) line still exists, and the "Badkamer" entity disappeared from the legend. I wanted to hide the "Woning gemiddelde" entity from the legend.

I hope you can help me.

Kind regards,

Roy

**Comment by kalkih** [comment]
Hello, thank you very much!
This should be fixed in latest release #137.

Also if you installed the card from HACS and already updated the card but still having this issue, please check this:
> You didn't possibly install the card from HACS?
> 
> If so, please double check the resource reference as it seems to have changed recently.
> 
> For me it's now
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
>    type: module
> ```
> 
> And before:
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card.js
>    type: module
> ```
> 
> You can see the correct one by navigating to the card in the HACS store

**Comment by roybosch** [comment]
It works like a charm now. Thank you very much!
