### ISSUE TITLE
Feature request: Dynamic line color thresholds for secondary axis

### ISSUE THREAD

**Issue by s-hutter** [kalkih/mini-graph-card#141]
Dynamic line colors using color thresholds look very nice. However, it seems like they are always applied to both axes, with no option to set different thresholds and colors for the second axis.
Would it be possible to add `color_thresholds_secondary` in a future release?

**Comment by kalkih** [comment]
Possibly.
Right now you can override the dynamic color threshold on specific entities by setting the `color` option on the entity/entities.

**Comment by jlsjonas** [comment]
Closing in favor of #589

**Comment by jlsjonas** [comment]
Closing in favor of #589
