### ISSUE TITLE
Feature request: The ability to add line_color for the entire chart

### ISSUE THREAD

**Issue by darkkatarsis** [kalkih/mini-graph-card#144]
The ability to add color for the entire chart below a specific value. Thanks to this, it will be possible to obtain e.g. red when the graph is below the expected value or green when it is ok

<img width="391" alt="Screenshot 2019-08-27 at 20 16 06" src="https://user-images.githubusercontent.com/24244919/63797050-897aef00-c907-11e9-8f03-7757aeae4bfd.png">

**Comment by kalkih** [comment]
Hello, this is already possible https://github.com/kalkih/mini-graph-card#dynamic-line-color

**Comment by darkkatarsis** [comment]
@kalkih I was afraid you would write it. Functionality you are talking about mixes 3 colors, sometimes it is one three-colored line. However, In this case color does not depend on the level/position of the line but the value. Thanks to this, the chart will change color to one selected color when it reaches a specific value. Sorry for my english

**Comment by darkkatarsis** [comment]
From the left "dynamic-line-color", on the right the one I'm talking about

![Screenshot 2019-08-28 at 07 49 16](https://user-images.githubusercontent.com/24244919/63828948-5caaf400-c968-11e9-9af9-a92f21378912.png)

**Comment by kalkih** [comment]
Okay, I see what you mean now.

You can use [config-template-card](https://github.com/custom-cards/config-template-card) to achieve this easily.
