### ISSUE TITLE
What about this display filling?

### ISSUE THREAD

**Issue by 399310471** [kalkih/mini-graph-card#146]
I am not good at English, so this is translation.
I want to use icons to show CPU usage of 0-100，
Use blue, green, yellow and red to represent different intervals from 0-100, 0-25-50-75-100 (blue/green/yellow/red). When CPU usage is [less](url) than 25%, the filling area is always red. Why?

Here is my configuration

color_thresholds:
  - color: '#0000FF'
    value: 25
  - color: '#008000'
    value: 50
  - color: '#FFA500'
    value: 75
  - color: '#FF0000'
    value: 100
entities:
  - sensor.synology_dsm_cpu_load_total
hours_to_show: 24
points_per_hour: 1
show:
  labels: true
type: 'custom:mini-graph-card'
![QQ截图20190831094030](https://user-images.githubusercontent.com/47575637/64057751-8451c480-cbd3-11e9-875b-a050e6d39eb7.png)

I think it should be blue.

**Comment by kalkih** [comment]
Hello, thanks for the report, this is definitely a bug, should be blue indeed.
I will look into it.

**Comment by 399310471** [comment]
Hi, hello, I am not very good at English. I try to make my words friendly. If my words are not friendly, please forgive me.
I really like the card you developed, which makes my home assistant front page very beautiful and vibrant. I have previously reported a question about threshold filling. I saw your reply description fixes this problem, I hope to get a new version, I believe it is a very amazing plugin. But I can't use the new version, just see that you have an update in your github. There are a lot of js suffix files inside, how do I get a new version of the mini-graph-card-bundle.js file, do I need to build it myself? I am not a programmer, so I don't know your code very well. I hope you can teach me, thank you.

**Comment by kalkih** [comment]
Hey @399310471, thank you, I'm glad you like it!
Yes, that's correct, this fix isn't included in a release yet, if you need/want it right now you would indeed have to build it from source. Or if you are okay with waiting a few more days, a new release of the card with the fix included will be available for you to download.

To build the project yourself from source please see the [developer instructions](https://github.com/kalkih/mini-graph-card#instructions), but I guess it could be tricky if you have no prior experience in git/npm.
