### ISSUE TITLE
Feature Request: More default colors

### ISSUE THREAD

**Issue by SNoof85** [kalkih/mini-graph-card#147]
Hey,

Love this card, and using it for graphs with more that 6 entities. But there's only 6 default colors. What about using more ?
Using a palette like this one : http://colrd.com/palette/27645/ with 16 colors would be nice no ?

If you think that's nice, i'll be glad to PR this.

**Comment by kalkih** [comment]
Hello!

Sure, that would be great.
I would prefer if we could keep the colors to the ones available within this palette ([flatui v1](https://flatuicolors.com/palette/defo)) as we are already using some of those colors.

Thanks!

**Comment by SNoof85** [comment]
That's fine to me to use this one too. Just a question to be sure. The first default color is var accent-color wich is configuration (theme) dependant right ?
That means if someone changed it to a color wich is already in the palette, we could have 2 times the same color selected automatically ?
Maybe would be better to place this var in last position ?

**Comment by kalkih** [comment]
The reason for having `var(--accent-color)` at the first spot is to by default adapt better to the user's theme without any need to configure the card.
From my understand the majority of usage is just single entity graphs so I think this implementation works fairly well for the majority and eliminates extra color configuration.

Could be an issue in multi color graphs as you mentioned, not sure how we would solve that best, but I'd like to keep `var(--accent-color)` default for the initial entity.

**Comment by SNoof85** [comment]
That's a good reason to let it first.

For the multi color graph, I think it's not a big deal if a color from the palette looks like the `var(--accent-color)` because at this time it's already the case. Even more when you graph like me 10 entities and you have 6 times the same color with automatic selection !

**Comment by kalkih** [comment]
Yes, that's true.
Feel free to submit that PR with some additional default colors, would be great!

**Comment by koying** [comment]
Thanks for this great card.

I have the issue that my accent color is very close to the second color of your palette, so I was wondering why my first 2 entities had very close color :)

I understand your reasoning to use the accent color for single entity graph, but it might make sense to skip the accent for multi-entities, or all themes with a blue accent have a problem.

Thanks for considering this.
