### ISSUE TITLE
Bug: Fill true/false will change the layout

### ISSUE THREAD

**Issue by SNoof85** [kalkih/mini-graph-card#148]
Hi,

I just noticed that fill option in show object changes the layout of the card (padding on the graph) : 
```yaml
show:
  fill: false
```
![image](https://user-images.githubusercontent.com/25659602/64411408-6251b980-d08d-11e9-9308-ffecb6458ff0.png)

```yaml
show:
  fill: true
```
![image](https://user-images.githubusercontent.com/25659602/64411428-6c73b800-d08d-11e9-8d07-3c9f9d034af7.png)

As you can see the fill color is bad but this is reported in #146 but also padding on the graph is different. Is that a bug or works as designed ?

Comes from https://github.com/kalkih/mini-graph-card/blob/0933d44a5d067cac8ec4aaf99d87090496b8ccfa/src/style.js#L40-L42 ?

Fill has padding 0px but no fill doesn't.

**Comment by kalkih** [comment]
Correct, that is by design.
Looks weird/bad with no padding around the card when there's no fill imo 🙂
