### ISSUE TITLE
axis upper and lower bound numbers are black on black in secondary mode

### ISSUE THREAD

**Issue by magiva** [kalkih/mini-graph-card#156]
I have the following, the upper and lowel bound labels are black on black

animate: true
entities:
  - color: '#00bed8'
    entity: sensor.freezer_temperature
    name: Temperature
  - color: '#f39d12'
    entity: sensor.freezer_humidity
    name: Humidity
    y_axis: secondary
hours_to_show: 4
name: Freezer
points_per_hour: 20
show:
  labels: true
  labels_secondary: true
type: 'custom:mini-graph-card'

![image](https://user-images.githubusercontent.com/7522405/65141872-ce2f0d00-da11-11e9-9190-c03fd51981fe.png)

**Comment by kalkih** [comment]
What browser are you running?
The label background should be based on the theme variable `primary-background-color`.

**Comment by magiva** [comment]
in chrome (latest), the theme is default.  Ive tried cycling my other themes and i do see it faintly in other themes, switched back to default and its as per the screen shot

**Comment by kalkih** [comment]
Okay, maybe something has changes with the default theme, I'll double check, WHat HA version are you on?

**Comment by magiva** [comment]
0.98.5

should i also log the issue that color thresholds dont take effect if i
show a secondary line as per example, if i add color thresholds, nothing
changes

**Comment by magiva** [comment]
This is an error on my part
even though the theme was set to default, the view theme was set as
backend-selected
