### ISSUE TITLE
Custom element doesn't exist: mini-graph-card.

### ISSUE THREAD

**Issue by misthios** [kalkih/mini-graph-card#158]
I have added the "Resources" line in the Raw UI still getting this error :(

![image](https://user-images.githubusercontent.com/48213966/65167701-adda6f00-da60-11e9-925e-fd5a57f967b9.png)

**Comment by kalkih** [comment]
Hey, did you download the bundle and place it inside your home assistant `www/` folder?
If so navigate to `http://[HA-IP]:[PORT]/local/mini-graph-card-bundle.js` to see if it's served properly.

I really recommend checking out [HACS](https://github.com/custom-components/hacs) which really simplifies the install/update process of custom cards.

**Comment by Gogmaghog** [comment]
I have installed the plugin from HACS and it also fails.

![15688811186692608402601982399645](https://user-images.githubusercontent.com/55345809/65226280-e1e87b00-dac6-11e9-8cca-87fc1d879979.jpg)

**Comment by kalkih** [comment]
What happens when you navigate to `http://[HA-IP]:[PORT]/local/community/mini-graph-card/mini-graph-card-bundle.js`?
And what browser are you using?

**Comment by Gogmaghog** [comment]
![Screenshot_20190919-181612](https://user-images.githubusercontent.com/55345809/65262061-cd79a200-db09-11e9-8d86-fb2952b41dc8.jpg)
All is ok when I navigate to url http://[HA-IP]:[PORT]/local/community/mini-graph-card/mini-graph-card-bundle.js

**Comment by misthios** [comment]
@kalkih I tried via HACS still getting the error! 

All is ok when I navigate to url http://[HA-IP]:[PORT]/local/community/mini-graph-card/mini-graph-card-bundle.js

![image](https://user-images.githubusercontent.com/48213966/65301664-0e1efd00-db96-11e9-91af-f211b3fab151.png)

**Comment by kalkih** [comment]
Double check your resource reference, if installed through hacs it should be 
```yaml
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
```

**Comment by misthios** [comment]
It's working fine @kalkih 

My mistake! Forgot to add "resources:"

**Comment by un1te** [comment]
thanks a lot "reload resources" hepled )

**Comment by ralong777** [comment]
I'm having the same problem. But there is no reload resources option in home assistant

**Comment by zhangela** [comment]
I made it work by going into Settings > Dashboards > "three dot menu" > Resources  then manually adding the JS bundle as a Javascript module. 

<img width="940" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/1552837/aa1dd130-3916-4a90-825f-0186cd572ae7">
