### ISSUE TITLE
NaN Invalid Date

### ISSUE THREAD

**Issue by BrettWa** [kalkih/mini-graph-card#161]
Today all the graphs are displaying the same error message with no data , "NaN Invalid Date" - it has otherwise been working perfectly - any advice on debugging?

See screenshot: https://ibb.co/xMwPMmd

**Comment by kalkih** [comment]
Are you connected to the HA [recorder database](https://www.home-assistant.io/components/recorder/)? If not, try restarting HA or check the logs for related errors.

Does the default graphs work?

Only time this should happen is when there's no history available afaik.

You could try opening the browser developer console -> refresh the page and look for potential errors there.

**Comment by BrettWa** [comment]
Yes, connected to recorder database, if I click on the measures it pops up with the HA stats, and yes, the default HA graphs work.

Everything is working fine again this morning though - I'm not sure if it potentially had anything to do with it being month end, and maybe the time offset?

**Comment by kalkih** [comment]
Alright, hard to tell, could be a corrupt value in the DB, if that's the case you might be able to reproduce it if you set `hours_to_show` to a higher number.

Feel free to reopen this if you experience it again, and check the browser dev console log if it ever happens again, that information could be very useful.
