### ISSUE TITLE
error loading graph   attribute d: Expected number

### ISSUE THREAD

**Issue by gnkarn** [kalkih/mini-graph-card#17]
mini-graph-card-bundle.js?v=0.0.8:1 Error: <path> attribute d: Expected number, "M 4,NaN 4,NaN Q4,NaN…".

just a super simple example with this config 
      - type: "custom:mini-graph-card"
        entity: sensor.home_energy_sensor_current
        height: 100
        line_width: 4
        font_size: 75
        color: '#3498db'
        hours_to_show: 168

it shows the number but not the graph .

**Comment by kalkih** [comment]
Hey,
It's very hard to pinpoint the issue when I don't have access to the sensors history data, unfortunately.

Does the graph work with other sensors? or if you change `hours_to_show`?
What browser are you using?
Are there any other error messages in the browsers developer console log?

**Comment by kalkih** [comment]
@gnkarn

**Comment by kalkih** [comment]
Can't reproduce, closing this.
