### ISSUE TITLE
Multiple graphs with different time ranges causes missing data

### ISSUE THREAD

**Issue by maxwroc** [kalkih/mini-graph-card#171]
I didn't try to repro it yet but looking at the code issue can happen. Please close it if I'm not right. I don't have time now to test it.

Let say we have one mini-graph-card on one page showing only 24h. But on the other hassio tab/page we have graph showing data from entire week. 

The problem is with the cache. We use the same entry with the same key in DB. So the 24h graph removes data which is still required by 7d graph on the second page.

Possible solutions:
* compute DB key based on card id (if such thing exists)
* backfill data - though I think it's not good idea

**Comment by kalkih** [comment]
This is indeed an issue, good catch.

> * compute DB key based on card id (if such thing exists)

There's no such thing I don't think, at least not that's persistent.

Another solution would be to append hours_to_show or similar to the key.

Issue with that solution; we potentially cache some duplicate data & can't reuse already cached entity data in other card if hours_to_show doesn't match.
