### ISSUE TITLE
feature request: add fill_secondary

### ISSUE THREAD

**Issue by gw1gw1** [kalkih/mini-graph-card#175]
Would it be possible to choose to fill either secondary or primary information.
Currently we can only have both or none.

An example would be to have temperatures lines as primary information and a day/night sensor as secondary information. We would be able to easily know when it is night or day.

**Comment by kalkih** [comment]
Hey, are you talking about the line fill, the fill below the graph line?

If so, you can override it on an entity level already, check the [entities-object](https://github.com/kalkih/mini-graph-card#entities-object) and `show_fill` in particular.

**Comment by gw1gw1** [comment]
Indeed. I must have missed this option.

Thanks

**Comment by kalkih** [comment]
Thank you,
Easy to miss, there's quite a few options... 😆
