### ISSUE TITLE
How to scale the height of the  bar height value=0.00 ??

### ISSUE THREAD

**Issue by zibous** [kalkih/mini-graph-card#178]
How can I scale the height of the bar. The value of 0 is too high.

![min-graph-barchart](https://user-images.githubusercontent.com/30198737/67187985-bc170480-f3eb-11e9-96ff-64bc25e1a56e.png)

**Mini Graph Card: v0.8.0**

```
type: "custom:vertical-stack-in-card"
title: "Ertrag vs. Verbrauch"

cards:
  - type: "custom:mini-graph-card"
    entities:
      - sensor.kostal_current_watt
    hours_to_show: 54
    icon: "mdi:theme-light-dark"
    name: "Photovoltaik Ertrag"
    font_size: 80
    unit: kWh
    upper_bound: 2000
    aggregate_func: max
    group_by: hour
    show:
      icon_adaptive_color: true
      name_adaptive_color: true
      name: true
      icon: true
      state: true
      fill: fade
      points: true
      legend: bottom
      extrema: false
      labels: hover
      graph: bar
    style: |
      ha-card {
          transform: scale(0.95);
          background-size: 100% 100%;
          height: 240px;
      }
      .graph__legend {
         flex-wrap: nowrap;
      }
    color_thresholds:
      - color: "#CFD8DC"
        value: 5000
      - color: "#4CAF50"
        value: 800
      - color: "#FDD835"
        value: 600
      - color: "#64DD17"
        value: 400
      - color: "#FFF176"
        value: 300
      - color: "#FFEB3B"
        value: 200
      - color: "#FF5722"
        value: 100
      - color: "#f44336"
        value: 50
      - color: "#f44336"
        value: 0

  - type: "custom:mini-graph-card"
    entities:
      - sensor.verbrauch_gesamt
    hours_to_show: 54
    icon: "mdi:home"
    name: "Haus Verbrauch"
    font_size: 80
    unit: kWh
    upper_bound: 2000
    aggregate_func: max
    group_by: hour
    show:
      icon_adaptive_color: true
      name_adaptive_color: true
      name: true
      icon: true
      state: true
      fill: fade
      points: true
      legend: bottom
      extrema: false
      labels: hover
      graph: bar
    style: |
      ha-card {
        transform: scale(0.95);
        background-size: 100% 100%;
        height: 240px;
      }
      .graph__legend {
             flex-wrap: nowrap;
      }
    color_thresholds:
      - color: "#CFD8DC"
        value: 0
      - color: "#4CAF50"
        value: 50
      - color: "#FDD835"
        value: 100
      - color: "#64DD17"
        value: 200
      - color: "#FFF176"
        value: 300
      - color: "#FFEB3B"
        value: 400
      - color: "#FF5722"
        value: 600
      - color: "#f44336"
        value: 800
      - color: "#f44336"
        value: 5000

  - type: markdown
    style: |
      ha-card {
         color: #B5B5B5;
         font-weight: 300 !important;
         font-size: 1.5em !important;
      }
    content: >
      <div>Zusammenfassung</div>

  - type: glance
    style: |
      ha-card {
          background-color: transparent;
          box-shadow: none;
      }
    entities:
      - sensor.kostal_current_kw
      - sensor.psm_totalkw
      - sensor.psm_nettokw

```

**Comment by kalkih** [comment]
Hey,
Thanks for letting me know.
The min bar height got a little taller in the latest release (unwanted side effect), I'll revert the change and push up a new update later today.

**Comment by zibous** [comment]
@kalkih 

Sorry, new version installed, browser cache cleaned, but nothing has changed:

![Bildschirmfoto 2019-10-22 um 08 44 54](https://user-images.githubusercontent.com/30198737/67263426-66ecf880-f4a8-11e9-970c-4fa2fccda121.png)

**Comment by kalkih** [comment]
I'm pretty sure you're still loading the old code from cache.
Anyway, yesterday while I reverted the changes It got me thinking, and you could actually adjust the minimum bar height by setting the `line_height` option, the lower you set it the smaller the minimum bar height. If you set it to `0` it should be completely hidden.

**Comment by zibous** [comment]
@kalkih 

Yes, I'm sure I'm not loading the file from the cache. But can not find a version number, therefore the code part "getBars" was changed:

```
            getBars(a, b) {
                const c = this._calcY(this.coords)
                  , d = 4
                  , e = (this.width - d) / za(this.hours * this.points) / b;
                return c.map((c,f)=>({
                    x: e * f * b + e * a + d,
                    y: c[X] - 2 * this.margin[X],
                    height: this.height - c[X] + 6 * this.margin[X],
                    width: e - d,
                    value: c[Y]
                }))
            }
```
Where is the "setting the line_height option" ? 
If I set the lower_bound: 0 then nothing changes

**Comment by zibous** [comment]
@kalkih 

solved, setting **line_width: 1** and now all is o.k
Thanks 👍

**Comment by kalkih** [comment]
> Yes, I'm sure I'm not loading the file from the cache. But can not find a version number, therefore the code part "getBars" was changed:

That's version 0.8.0, 0.8.1 looks like this (ignore variable names):
https://github.com/kalkih/mini-graph-card/blob/2b80e8d5fa6d20a1fc2ece56074a1a3087ec50e7/src/graph.js#L174-L185

> solved, setting **line_width: 1** and now all is o.k

Of course it's `line_width`, sorry for the confusion 😆
Great to hear it worked out in the end!

**Comment by zibous** [comment]
![barchart](https://user-images.githubusercontent.com/30198737/67315970-ed84f280-f507-11e9-82e0-9af2cb611831.png)

@kalkih 

I've tried to choose a different variant of the rendering, but it looks like the "bar" graphic can not be negative.
Is that correct or am I doing something wrong?
