### ISSUE TITLE
Decimals option applied to labels too??

### ISSUE THREAD

**Issue by MarsWarrior** [kalkih/mini-graph-card#19]
In v0.09 the decimals option is introduced.

Can the same decimals option also be applied to the displayed labels?

**Comment by kalkih** [comment]
You are right, should be consistent, throughout the card.
Will add this with the next release.

**Comment by kalkih** [comment]
Now the default behaviour in the latest release [v0.2.0](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.0)
