### ISSUE TITLE
See all X values on hover

### ISSUE THREAD

**Issue by Extarys** [kalkih/mini-graph-card#190]
I'm just starting to play with Lovelace. I love those graphs but I wonder if it's possible to see all values on the X axis at once. It's hard to check values when the graph accuracy is more than 1 per hour or when the lines are thinner.

![image](https://user-images.githubusercontent.com/11581433/67605070-54deb480-f74b-11e9-8fda-3f0e60f6fb62.png)

To understand what I mean, you can look at this graph: https://www.echartsjs.com/examples/en/editor.html?c=area-stack

**Comment by sparkydave1981** [comment]
Similar to this, I would like to see the x value on hover as a pop-up text item at the cursor just how the core graph card does.  I realise that if `show_state: true` is set then the value at the cursor is shown in that state text, however if `show_state: false` then we have no display of the value when hovering.  I think this is pretty much the same as this feature request?

**Comment by mihalski** [comment]
I don't know if what I would like is any different from what you both describe, but I would love it if both the left y_axis state AND the right updated for each position on the x axis without needing to hover over the particular y_axis.. so for example if I have a temp/humidity graph and I hover over ANY x position it will show both the temp and humidity states for that time on the x axis.

If this is already possible I would dearly love to know how :P

Thank you for an INCREDIBLY configurable and useful Lovelace card.

**Comment by vadipp** [comment]
I see no reason to close this. This would be a very useful feature for graphs with many entities, where it's hard to point at a particular line in the graph
