### ISSUE TITLE
Zero level Bar graph

### ISSUE THREAD

**Issue by Gio-dot** [kalkih/mini-graph-card#196]
Hi, i noticed that zero level using bar graph is very very high. I think is better to make it maximum 1-2 pixels to gain graph height. In general ghraps height is very low respect to the card height (less than half). I hope you can even arrange texts differently in the future to increase graphs heght.
Thank you.
![Annotazione 2019-11-02       185049](https://user-images.githubusercontent.com/55327160/68075198-dd410300-fda4-11e9-8dbb-f371e0af1ff8.jpg)

**Comment by kalkih** [comment]
Hello,
The card has to work with both mouse & touch input and 1-2pixels is just too small to be usable with touch input.
If you don't intend to interact with the graph through touch or don't like the default min-height you can override it by setting the option `line_width`, the lower you set it the lower the minimum bar height will be.

Your second suggestions is similar to https://github.com/kalkih/mini-graph-card/issues/176 and/or https://github.com/kalkih/mini-graph-card/issues/157.
