### ISSUE TITLE
set min and max value on scale Y

### ISSUE THREAD

**Issue by LeidenSpain** [kalkih/mini-graph-card#198]
Hi,

I think it would be interesting to be able to select the range of the scale in Y.
I want to graph the prices of light, and they are small values (0.100, 0.098, .... and I find that they always look like a small line).

Thank you

**Comment by kalkih** [comment]
Hello,
You can already set the upper (max) and lower bound (min) of the Y-axis, see the `lower_bound` & `upper_bound` options.

**Comment by LeidenSpain** [comment]
Ah, ok,
Thanks and sorry
