### ISSUE TITLE
Graph with X using list of values instead of time

### ISSUE THREAD

**Issue by LeidenSpain** [kalkih/mini-graph-card#199]
Hello

I am trying to create a graph where the evolution of the price of light of the next day is seen.
I have the hourly values in a sensor list, so they do not vary over time.
I think it would be very useful to create a graph using a list of sensors as an X base, instead of always changing that sensor's time.

I don't know if this is possible or very complicated, I just contribute my idea.

Greetings and great work

**Comment by kalkih** [comment]
Hello.
Interesting idea but it's a bit too niche of a feature / use-case imo, but I appreciate the suggestion.
Thanks!
