### ISSUE TITLE
Mini Graph Card is not loading after installation via HACS

### ISSUE THREAD

**Issue by sMauldaeschle** [kalkih/mini-graph-card#203]
Hi, I have been using the mini graph card for quite a while by installing the plugin manually. And I included the js file the following:
```
  - url: /local/mini-graph-card-bundle.js?v=0.2.2
    type: module
```
Now I installed it again via HACS (like other plugins as well). But surprisingly the graphs are not showing anymore. Not at all. I used this include code:
```
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
```
Adding the version `?v=0.8.2` doesn't change the behaviour. It only works if I go back to the local include from above. Any ideas how this can be solved? My other plugins that I installed again via HACS are working fine.

**Comment by kalkih** [comment]
Hey,
Try navigating to the file location manually to see if it's there and you can access it: `http://[HA_IP]:[PORT]/community_plugin/mini-graph-card/mini-graph-card-bundle.js`

Try
* Reinstalling the card in HACS
* Clearing browser cache
* Try another browser or incognito mode, just to see if that works

If the above doesn't help try to open developer tools in your browser and look for the developer console, refresh the HA page with the graph(s) and see if there's any errors popping up in the console.
