### ISSUE TITLE
[Feature request] expose Secondary info (last_updated/last_changed)

### ISSUE THREAD

**Issue by tomecki88** [kalkih/mini-graph-card#204]
Hi, i'm trying to show up secondary_info but this is not displaying.
Trying with:
'entities:
    - entity: sensor.xxx
       secondary_info: last-changed`

Can be 'secondary_info' displayed using custom:mini-graph-card ?

**Comment by kalkih** [comment]
Hello, `secondary_info` is not a valid option in this card.
All available options are listed in the readme.

**Comment by tomecki88** [comment]
Thanks for quick reply. Any plans to add this?

**Comment by kalkih** [comment]
Please elaborate on secondary_info, what would it do? Display the timestamp for the last state change?

**Comment by tomecki88** [comment]
For example, right. I know that there is in more info card information when the last update was:
![obraz](https://user-images.githubusercontent.com/57391115/68624472-31e82a80-04d7-11ea-916e-e6441fa22488.png)

Please consider if you can add possibility to display this for example below sensor state with small font.

**Comment by kalkih** [comment]
Thanks, I'll consider it

**Comment by Misiu** [comment]
@kalkih I'd like to ask for the same feature as @tomecki88.
Here is my use case:
I have multiple Shelly temperature sensors. They work by sending the temperature only when the temperature and/or humidity changes by a specific value, so it might take very long to get an update.

Ideally, we should be able to display some additional information.
The use case for this is simple:
Shelly is battery powered, so I want to have a graph showing those two values (temperature and humidity), but additionally, I'd like to display the battery level as an icon and a value (or just as formatted text `Battery: 45%`). This would allow us to build UI's that look really well and don't take a lot of space.

Please consider this feature.

**Comment by kalkih** [comment]
Hello, thanks for the suggestion.
I could see this being added for at least the primary entity, displayed below the state, where the timestamp is displayed when hovering over a graph point.
Similar to the default [entities card](https://www.home-assistant.io/lovelace/entities/#secondary_info).

**Comment by Misiu** [comment]
@kalkih this would be awesome.
But as I wrote in my use case, I want to display additional information:
I want to show a graph with three entities: temperature humidity and humidity (this is currently possible) and I want to show battery, but not as a graph, but instead as a single label.

Something like this (just a simple mockup):
![image](https://user-images.githubusercontent.com/1741838/73320532-e45e9c80-423f-11ea-9ae4-00015a297e00.png)

**Comment by jlsjonas** [comment]
@Misiu you could use the `show_graph` option for this; would that cover your use-case?

**Comment by Misiu** [comment]
@jlsjonas not sure if `show_graph` will help.
In the mock above I've added the bolt icon and the battery percentage value.
This is how I'd like my card to look.
I see that this project is getting back, so I'll give this another try.
Maybe will try to contribute.

**Comment by ildar170975** [comment]
These additions may be achieved by card-mod (using `:after` & `:before` pseudo classes)

**Comment by jlsjonas** [comment]
@Misiu Not _exactly_ but you could get quite close

```
type: custom:mini-graph-card
name: Temperature
icon: mdi:thermometer-lines
entities:
  - entity: weather.home
    attribute: temperature
    unit: °C
  - entity: sensor.some_other_temperature
  - entity: sensor.battery_level
    show_graph: false
    show_state: true
show:
  labels: false
  legend: false
```
gets you something like this
![image](https://user-images.githubusercontent.com/932193/150666267-c7e5b9f8-98cc-4f1c-89d2-42af8d03fc9e.png)

But I'm definitely liking your UI proposal; this could become a potential default if you don't provide an icon on card level but on the entity's level.

**Comment by ildar170975** [comment]
> you could get quite close

Good solution.
And also we can add a "Battery" label here:
```
type: custom:mini-graph-card
name: Temperature
icon: mdi:thermometer-lines
entities:
  - entity: sensor.cleargrass_1_temperature
  - entity: sensor.battery_cleargrass_1
    show_graph: false
    show_state: true
show:
  labels: false
  legend: false
card_mod:
  style: |
    .states--secondary::after {
      content: "Battery";
    }
```
![image](https://user-images.githubusercontent.com/71872483/150688191-7573b42b-c826-40d2-8553-985ffd174897.png)

**Comment by jlsjonas** [comment]
>  And also we can add a "Battery" label here:

Card-mod is not default functionality though ;)

**Comment by ildar170975** [comment]
You are right, but sometimes it is better to use an already implemented & tested functionality provided by another plugin than adding more, more & more features into the card... People will never stop complaining and asking for more features...

**Comment by tomecki88** [comment]
It is possible to have different font sizes for entities ? Actually font_size is setting size for all entities states.  I want to set smaller size for battery state.
Thanks in advance ;)
