### ISSUE TITLE
Custom element doesn't exist: mini-graph-card.

### ISSUE THREAD

**Issue by thegeek-sys** [kalkih/mini-graph-card#209]
When I try to manually add the mini graph card I get this error: Custom element doesn't exist: mini-graph-card. HASSIO mini graph card installed with HACS. How I can solve it?
![error](https://user-images.githubusercontent.com/55345633/69274134-08678700-0bda-11ea-924b-70f8e04e0f3b.png)

**Comment by kalkih** [comment]
Make sure you've setup the resource reference correctly in the raw GUI editor or lovelace-ui.yaml, as shown by HACS.

**Comment by thegeek-sys** [comment]
Yes the code is correct:

resources:
- url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  type: module

But still got the error

**Comment by kalkih** [comment]
Can you access the file at `http://[HA-IP]:[PORT]/community_plugin/mini-graph-card/mini-graph-card-bundle.js`?
What browser are you using?

**Comment by pbruen** [comment]
i see the same issue.  I was able to get by

  - url: local/community/mini-graph-card/mini-graph-card-bundle.js
    type: module

**Comment by thegeek-sys** [comment]
@kalkih Ok here you are the screenshot:
![photo_2019-11-21_14-32-33](https://user-images.githubusercontent.com/55345633/69342465-e9193a00-0c6b-11ea-9b8b-aab8f0a2d585.jpg) On the phone I use Via and on laptop Firefox.

**Comment by thegeek-sys** [comment]
> 
> 
> i see the same issue. I was able to get past this by pointing to the direct path as below:
> 
>     * url: local/community/mini-graph-card/mini-graph-card-bundle.js
>       type: module

tried to edit the code. No result.

**Comment by kalkih** [comment]
Not really sure then.
Try reinstalling the card in HACS, clearing browser cache, try installing the card manually.
Check in firefox developer-tools console and network tabs for clues.

**Comment by thegeek-sys** [comment]
Do I have to add to the configuration.yaml those lines?

`lovelace:`
`  mode: yaml`

**Comment by thegeek-sys** [comment]
Solved by adding the code in the raw GUI. Thanks you very much for the patience!
