### ISSUE TITLE
Request: Grid & Axis labels

### ISSUE THREAD

**Issue by gianky69** [kalkih/mini-graph-card#21]
1 . Could it be possible to have a limitation for max-min data displayed (example temperature from 0° to 35°)?
2 . In graph could it be possible to add axes (X-Y) and horizontal/vertical grid (with user spacing selctable)?

Thanks a lot

**Comment by slavkobrzeg** [comment]
My vote for point 2 !

**Comment by kalkih** [comment]
The first point was implemented a few releases back, see `lower_bound` & `upper_bound` options.

Second point, not sure if this will be implemented as I want to keep the card rather simple and minimalistic.

**Comment by Ralph101** [comment]
My vote for point 2 !

**Comment by Atalonica** [comment]
I don't know if it is related but I would appreciate X axis times, in any way to visualize without hovering where things happened. (i.e. + for 2).

**Comment by kalkih** [comment]
> I don't know if it is related but I would appreciate X axis times, in any way to visualize without hovering where things happened. (i.e. + for 2).

Most likely not gonna happen, there's already the `history-graph` card if you want.a more detailed graph.

**Comment by snis** [comment]
I would like 2. 
But right now I've got a template sensor showing 0 degrees C (32F) and my outside temerature.
I'm missing a feature to make individual lines thinner. So that my reference line of 0 degrees would be thinner, it would also be nice if I could override witch line is in front or back (Z axis)

**Comment by kalkih** [comment]
> it would also be nice if I could override witch line is in front or back (Z axis)

They are rendered in the order they are listed in.

**Comment by snis** [comment]
> > it would also be nice if I could override witch line is in front or back (Z axis)
> 
> They are rendered in the order they are listed in.

So if I want my (feature thinner) reference line to be rendered behind my actual temperature sensor line I put it first. But then the card displays the temperature from that bogus reference line. See my problem ;)

Still thinks this card is fantastic!

**Comment by schmurtzm** [comment]
Hi, these graph are the most beautiful but I can't understand their use without horizontal/vertical grid....
So you see a curved line and you can say "oh ! the temperature has changed today !" : you don't know how much or when. :neutral_face:
So a big vote for the point 2 to get the most beautiful and useful graphics :)  :rainbow:

**Comment by LCerebo** [comment]
I'm also looking for X-axis scale and label, it would be nice to see the time at a glance, without hover on the data point.
@kalkih if this is implemented as an option you can keep the card simple by default, but give the users the possibility to further customise and enrich it.
Thanks!

**Comment by Gio-dot** [comment]
https://github.com/kalkih/mini-graph-card/issues/21#issuecomment-466664778
Hystory graph card has 2 big limits that Mini graph card hasn't : maximum 80 hours and no possibility to show 2 different y axys, so i think that if axys would be implemented in mini graph card it would be very useful.

**Comment by georgbachmann** [comment]
I think so too, yes. Without a the labeled axis it's quite hard to make use our of this widget...
But I also think that min and max values would be super nice. For temperature f.e. I don't have that much temperature changes going on, but the graph is jumping from top to bottom. So on first glance you would think there are drastic changes, but there aren't.
Would be cool to have a not only beautiful but also functional graph for home-assistant :)

**Comment by kalkih** [comment]
> But I also think that min and max values would be super nice. For temperature f.e. I don't have that much temperature changes going on, but the graph is jumping from top to bottom. So on first glance you would think there are drastic changes, but there aren't.

min/max labels for the y-axis already exists, the only show on hover by default, see [available show options](https://github.com/kalkih/mini-graph-card#available-show-options)

To display them at all time:
```yaml
...rest of card config
show:
  labels: true
```

There's also the `extrema` show option that'll give you min/max including timestamp for each one, but I don't think that's what you're after.

> but the graph is jumping from top to bottom

If you want more control over the y-axis scale you can use the options `upper_bound` and/or `lower_bound`, they are independent and you can choose to use both, one or neither in your config.

**Comment by adamgorz** [comment]
X-axis labels - I need it also. It is possible in the future release?

**Comment by rcrisp** [comment]
Another vote for axis labels.  Without those its kind of just a squiggly line on the screen.  It's a great component, but is impossible to quickly/easily view data without hovering over each individual point (which is kind of the purpose of a graph).  Unfortunately makes what would otherwise be a perfect component unusable for a lot of purposes.

**Comment by f00dagi** [comment]
Nice looking card but I need to revert back to my old solution until there is a option to add grid and x/y-axis scales.

**Comment by finity69x2** [comment]
I just remembered why I don't use this card...

So yeah, I'd like to see the x-y axes displayed too.

**Comment by PipeDeveloper** [comment]
Ohhh i think i duplicated #308, but yes its necessary this feature.
@finity69x2 Im thinking the same use another graph but i want to give a chance to this

**Comment by VoyteckPL** [comment]
Please add this feature. Thanks.

**Comment by RolphH** [comment]
#2 would be really helpful when you have graphs with negative and positive values. Without the axes it is hard to see when you go through 0.

**Comment by NdS-Research-Facilities** [comment]
As history-graph will be deprecated, any progress on the axis-es ?

**Comment by kalkih** [comment]
It's next in the pipeline.

**Comment by PipeDeveloper** [comment]
@NdS-Research-Facilities what do you mean with deprecated? this will not be developed anymore?

**Comment by adriandelcl** [comment]
I would like to have this feature too.

**Comment by smugleafdev** [comment]
I would find this card much more useful if it had:
- x-axis label customization
- y-axis labels beyond min and max
- grids

Configurable on/off of course. I do not like that the history graph arbitrarily sets the x-axis labels, and would love it if this card both added them as an option and allowed us to set the number of them to show.

"Without those its kind of just a squiggly line on the screen." is a perfect summary of how I feel about this card.

**Comment by AlexeyHimki** [comment]
Any chance to see this future? )

**Comment by cromatox** [comment]
On the Desktop it is OK to use the hover but on an mobile touchscreen device it's completely not usable! So please add the x/y-axis-label option, Thx!

**Comment by githubnoobjk** [comment]
I support the demand for x-axis labels. The history-card doesn't have features like last,max etc.

**Comment by PipeDeveloper** [comment]
i have been holding my 10dollars from May to donate this guy for implement grid and axis labels but i think i should spend it on a beer or something to enjoy

**Comment by svenstaro** [comment]
Don't be rude. If you really want this feature implemented and don't want to do it yourself, I suggest you raise some proper bounty or pay a freelancer to implement it for you. Keep in mind that the project author doesn't owe anyone here anything and if it's not a feature they personally want, they're unlikely to have an interest in implementing it soon.

**Comment by terminet85** [comment]
+1

**Comment by mabahj** [comment]
I just wanted to share a possible workaround that I've used for my (°C) temperature graphs that may (or may not) work for others: Create an input_number in configuration.yaml, call it "always_zero" or something and set the initial to 0. Max, min and step to whatever. Then add this as a line in a graph.

This gives me a decent reference axis/line without cluttering the layout too much. An alternative that may look better is to not draw the line, but only use fill. This workaround probably works best when the temperature is around 0°C, but other tweaks based on the same concept may make it work for other scenarios. For example lines at 0, 50 and 100 for a load graph. 

Also an automation script could possibly be triggered every hour and generate spikes in the input_number to indicate some kind time ticks on the graph, but I haven't tried that.

(Love the plugin! Thank you!)

**Comment by rasssta** [comment]
It's such a shame that this awesome card doesn't have grid support. It's like running a 100m sprint and stop at 99m to go back to the start and do it all over again (for me and by reading this thread also for a lot of others :) )

I've found myself to set up the graphs and enjoy the hell out of the look and features, and then realize I never look at the graphs because they sadly tell me...nothing...in my use case.

Is there anything anyone can do to make this happen or is there a sort of philosophic agenda here that prohibits such an implementation? Could someone, with the knowledge and skill, fork it perhaps?

Thanks for a 99% awesome card though! :)

**Comment by goaen** [comment]
Totally agree with @rasssta, as I love the card but do miss the label feature.
Still, thank you for your efforts, @kalkih !!!

**Comment by embcla** [comment]
Up vote for the x axis, I definitely need it! At least a coarse one please

**Comment by RomRider** [comment]
So this has now been implemented in another card `apexcharts-card` that I built.
https://github.com/RomRider/apexcharts-card

It won't make it into this card as it would require way too much work and I think we want to keep this one `mini`(`-graph-card`). I'm closing this.

**Comment by r-jean-pierre** [comment]
Thanks for pointing apexcharts, I was also looking for permanent (but not too blinky) x-axis labels plus some over tweaks

**Comment by thelvyn777** [comment]
Up vote for the x and/or y axis

**Comment by rasssta** [comment]
> Up vote for the x and/or y axis

Use apexcharts. It's fab.

**Comment by tefracky** [comment]
Is there anything new on it?

**Comment by ildar170975** [comment]
Check all existing issues for `mini-graph-card`. Probably some of them is about the same.
If it is open - start monitoring and keep it open. If it is closed - write a comment, will be reopened (if no open duplicates).

**Comment by mbalasz** [comment]
I understand the recommendation is to use the alternative, but this feels like such a simple and yet critical feature, that `mini-graph-card` really misses out on that.

While it's possible to display data points on hover, having an at-a-glance view of all data points on X axis helps get a better grasp of the graph. Additionally the hover doesn't work well on mobile as the touch area for the points is very small and it's almost impossible to touch them.

Is the complexity of the implementation an issue here? I didn't investigate the code and I'm trying to understand why this problem can't be addressed.

**Comment by ildar170975** [comment]
> why this problem can't be addressed.

You are more than welcome to contribute.

**Comment by schmurtzm** [comment]
> You are more than welcome to contribute.

This kind of answer is the most bad we can have in the open source community. As involved in multiple important open source projects I can understand your frustration to not receive some PR but receive many features request, but here users are asking the complexity level of the implementation of this, just to understand. A correct answer can be technical or personal (lack of time to invest on this project) but it can't be "you're welcome to contribute" because many people can like your project without having the technical level to modify it.

**Comment by ildar170975** [comment]
> A correct answer can be technical or personal

Simple reasons: lack of time, potential developers need to sort out how everything works, ...
As you may notice, currently the plugin's author cannot spent his personal time for the project as it used to be (this is called "life", "family" etc).

> I'll add that this issue should not be "closed as completed"

Nobody is going to do it.
