### ISSUE TITLE
Bars with a sensor using 'h' (hours) as unit_of_measurement

### ISSUE THREAD

**Issue by septeven** [kalkih/mini-graph-card#211]
Hi,
I'm trying to use your card for showing with bars how many hours I'm heating my place daily.

I first tried to populate the card with the history_stats sensor I created for it but I wasn't happy with the fact that it was showing the quantity of hours with decimals (eg. 1,87 hours) so I created a template sensor from that specific history_stats sensor using 'h' as unit_of_measurement.

The sensor is now displaying the hours correctly (I mean, not as a float number anymore) but your graph card is now using only the integer of that number (eg. 6h34 will show a bar of y=6 - that means if one day I'm using 6h15 and another day 6h59 - the bars will be the same)...

Hopefully I'm clear :)

Any chance you can help me on this ?

**Comment by kalkih** [comment]
Hey,
So the template sensor you created, what does it do exactly? rounds it to whole hours?
If so, you could skip the template sensor and just set the card option `decimals: 0`.
The drawback being that you can't see the exact value when hovering a bar, as it will be rounded as well.

Another alternative would be to list both sensors in the card (the regular and the template), and have one render the graph and one render the state. The only thing you need to do in order to achieve this is to make sure to list the template sensor first with the `show_graph` option set to `false`.

I hope that was of help, let me know if I misunderstood you 🙂

**Comment by Gio-dot** [comment]
> Hi,
> I'm trying to use your card for showing with bars how many hours I'm heating my place daily.
> 
> I first tried to populate the card with the history_stats sensor I created for it but I wasn't happy with the fact that it was showing the quantity of hours with decimals (eg. 1,87 hours) so I created a template sensor from that specific history_stats sensor using 'h' as unit_of_measurement.
> 
> The sensor is now displaying the hours correctly (I mean, not as a float number anymore) but your graph card is now using only the integer of that number (eg. 6h34 will show a bar of y=6 - that means if one day I'm using 6h15 and another day 6h59 - the bars will be the same)...
> 
> Hopefully I'm clear :)
> 
> Any chance you can help me on this ?

Hi, i use hours with decimal and this is not perfect but acceptable for me. However you have to know that that type of graph is suffering from a severe bug: it doesn't refresh itself until you clean browser cache or change hours to show, so for now it is practically unusable.

**Comment by septeven** [comment]
Thanks for your answer, basically:

My history_stats sensor - that one displays decimal formatted time (eg. 3.97h)
```
  - platform: history_stats
    name: 'Total Heating Time Today'
    entity_id: sensor.thermostat_hvac_action
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}' 
```

My template sensor - that one displays correctly formatted time (eg. 6h47m)
```
- platform: template
    sensors:
      total_heating_time_today_formated:
        value_template: "{{ states.sensor.total_heating_time_today.attributes.value }}"
        unit_of_measurement: 'h' 
```

I want the state of my graph (including when I'm hovering a bar) to display a correctly formatted time (eg. 6h47m)

Now:
- if I use the history_stats sensor with your card, the state shows decimal time (don't pay attention to the difference between the bar height here and below)
 <img width="245" alt="Capture d’écran 2019-11-23 à 18 34 47" src="https://user-images.githubusercontent.com/3216560/69482799-1e668900-0e20-11ea-9f9c-b4cc3752a971.png">
- if I use the template sensor, the state only shows the hour without the minutes (eg. for 3h34m, the state only shows 3)
<img width="422" alt="Capture d’écran 2019-11-23 à 18 32 17" src="https://user-images.githubusercontent.com/3216560/69482754-ba43c500-0e1f-11ea-9243-104de61b5299.png">

- Finally, if I do what you suggested, the state only shows the hour without the minutes, and when hovering a bar, it shows the hour with decimals...

Hope that helps...
@Gio-dot I noticed a problem like this, yes - I can see that if I group-by: date, the last bar displayed is the yesterday and not today...

**Comment by kalkih** [comment]
Ok, I could potentially add the ability to display non numeric states in the future so you at least could show the state in "3h46m" format.

> @Gio-dot I noticed a problem like this, yes - I can see that if I group-by: date, the last bar displayed is the yesterday and not today...

Fixed with https://github.com/kalkih/mini-graph-card/commit/035ea3dfba55eea62efbc18b69a166cfa948041b

**Comment by septeven** [comment]
Hi kalkih, was wondering if you still thinking about adding this feature ? Thanks

**Comment by kalkih** [comment]
Not really sure why I closed this, sure would be a good addition.

**Comment by jlsjonas** [comment]
@septeven If you're still interested, what would you expect exactly from this feature?
Displaying time entities _correctly_, or displaying any non-numeric state? (or something else?)
