### ISSUE TITLE
error after upgrade to v 0.102.1

### ISSUE THREAD

**Issue by vpomax** [kalkih/mini-graph-card#215]
Afer upgrade to Hassio v. 0.102.1 i see this...
![temp](https://user-images.githubusercontent.com/33105151/69483564-24ad3300-0e29-11ea-898e-5644ffdf4ef8.png)

**Comment by kalkih** [comment]
Most likely cause is that HA isn't properly connected to the history (recorder) database, or that it's empty.
Make sure your recorder in HA is correctly setup and working.
Check your logs and check the history page from the HA sidebar, see if the graphs show up there

**Comment by BertrumUK** [comment]
I had this as well but I just found that my MariaDB addon had crashed - restarted it and all was good.

**Comment by korderos** [comment]
Quick question : is this plugin compatible with Hassio based on Influx database ?

**Comment by kalkih** [comment]
Yes, the database interface is generalized by HA so no matter what recorder you're using (as long as it's compatible in HA) it should work.
