### ISSUE TITLE
grouping by date should convert W to Wh and display accordingly

### ISSUE THREAD

**Issue by djgan2018** [kalkih/mini-graph-card#218]
For a power measurement and grouping by date, the result should be Wh together with another icon (as shown in the figure). Two questions on this:
1st: Why do you use 'aggregate_func: max'?
2. why doesn't it work for me under Lovelace?
What am I doing wrong? Any idea? Many thanks in advance!

![Bildschirmfoto 2019-12-10 um 09 31 51](https://user-images.githubusercontent.com/44236623/70511702-ebb2d500-1b2f-11ea-89a9-2ff9967f18cf.png)

![Bildschirmfoto 2019-12-10 um 09 27 06](https://user-images.githubusercontent.com/44236623/70509887-629b9e00-1b2f-11ea-951b-479c5a095e9b.png)

**Comment by kalkih** [comment]
Hello,

The graph will not do the energy calculations for you, you need to set up a sensor (template sensor or [utility meter](https://www.home-assistant.io/integrations/utility_meter/) for example) that does the wh calculations and then use that sensor for the card.

By default this card will present data points based on the moving average, setting the aggregate function to max will instead present each data point by the highest value from the timespan, useful for e.g. utility meters that resets daily/hourly.

You can change the icon through the icon option.

2. What isn't working?

**Comment by djgan2018** [comment]
Hello,

thank you so much for the quick response. First of all I think your mini-graph-cards are ingenious!
But, your example for Grouping by Date suggests that the calculation is done automatically. A mouseover over the bars also shows a value that could be a Wh value. Since the graph does not do this, my guess was that something is not configured correctly or something is not working properly.  But it was my mistake.
Well, I'll soon take a look at setting up template sensors or utility meters.

Many greetings!

**Comment by kalkih** [comment]
Thank you,

The example in question is a utility meter sensor I believe, storing usage in `wh` and resetting to `0` at midnight.
The example is submitted by a contributor so I'm not 100% sure but that's what I think it is.

Yes, check out template sensor and utility meter, really useful components!
Good luck!
