### ISSUE TITLE
decimals not working

### ISSUE THREAD

**Issue by vMeph** [kalkih/mini-graph-card#22]
for some reason im not getting the``` decimals:``` option to work
```
type: 'custom:mini-graph-card'
name: Exterior Temperature
accuracy: 30
decimals: 0
entity: sensor.dark_sky_temperature
line_color: '#3498db'
line_width: 8
```
the output is always same ex: ```18.3``` wont matter if decimals is ```0. 1. 2. 3. ```etc...

**Comment by kalkih** [comment]
Hi,
Make sure you've updated the card, the decimals option was added in version v0.0.9.
Also, the accuracy option has been removed and replaced by the detail option, check the readme for up to date instructions.

**Comment by kalkih** [comment]
@vMeph Did you get it to work?

**Comment by vMeph** [comment]
yes @kalkih is working perfect
awesome job you did it on this!!!
thanks
