### ISSUE TITLE
request: divide sensor values

### ISSUE THREAD

**Issue by legolas0802** [kalkih/mini-graph-card#220]
what do you think about adding the possibility to multiply or divide the value of a sensor? I think it could be useful. thank you for your wonderful work!!!!

**Comment by kalkih** [comment]
Hello!
I think a [template sensor](https://www.home-assistant.io/integrations/template/) would be the perfect fit for the job.

`value_template` example of dividing the original sensor state by 10:
`{{ (states("sensor.example")) | float / 10 }}`.

Thanks!

**Comment by legolas0802** [comment]
I know and that's what I'm using, I made the proposal because I find it unnecessary to have duplicate sensors

**Comment by kalkih** [comment]
Okay, I see.
I'm trying to stay away from doing computations on the source data, since I believe that's better done on the server side.
I appreciate the suggestion though!
