### ISSUE TITLE
Bars get really narrow when there are a lot of them

### ISSUE THREAD

**Issue by tomlevels** [kalkih/mini-graph-card#221]
If I try to show my weekly usage for gas as bar graph, the bars get really narrow. Is there a way you could optimise this by reducing spacing?
![image](https://user-images.githubusercontent.com/3691709/71252081-4e705180-2324-11ea-87a5-496046eee2b5.png)

**Comment by kalkih** [comment]
Hello,
Yes, we could add some kind of margin/spacing option I guess.

BTW, there's a maximum of 96 bars allowed in the graph. If `points_per_hour` times `hours_to_show` exceeds this number, the graph will automatically adjust `points_per_hour` to a lower value where the graph can be rendered in 96 bars or less.

**Comment by tomlevels** [comment]
Good to know about the maximum of 96 👍.  I guess you could add a spacing option or you could just reduce the space based on the amount of bars (whatever you like)
