### ISSUE TITLE
Labels for X 

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-graph-card#223]
I would like to have an option to show  X labels for time, hovering or always
If you have  a graph for, maybe, 24h, the only way to have an idea of the time of a point is by  clicking, but on a phone/tablet is almost impossible, and would be nice to have a fixed label every x hours.

Like this, with the time in the X line

![image](https://user-images.githubusercontent.com/12759632/71451254-1fb60900-2772-11ea-9258-e734fbfe6630.png)

Or with the hours passed (for example, 2,4,6,8,10,12  for a 12h graph)

**Comment by kalkih** [comment]
Hello,
Thanks for the feature request, this has been requested earlier and can be tracked here https://github.com/kalkih/mini-graph-card/issues/21.
