### ISSUE TITLE
Y label with current value, not min/max

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-graph-card#225]
From what i understand, the Y Label shows min/max values of the graph
Maybe can bel nice to optionally show the current value for each line, instead the min/max for only the first line.

**Comment by kalkih** [comment]
Hello,
I'm not sure what you mean, the current line/entity value/state is displayed at the top of the card, if you have multiple entities of which you want to display the current state, you can do so by setting the `show_state` option to true on each entity entry.

Let me know if I didn't get your request correctly.

**Comment by Kedryn** [comment]
Yes, it can be done that way, but i didn't know when i made this post. Thanks.
