### ISSUE TITLE
Entity fill not showing up if line is false and graph animated

### ISSUE THREAD

**Issue by dark3dge** [kalkih/mini-graph-card#228]
Hi,

I wanted to replicate the example in the readme and overlay the nighttime fill in gray with my animated temperature graph.
It would only show the fill when showing the line too, until I removed animate: true.

![image](https://user-images.githubusercontent.com/28789433/71996638-8a535400-320a-11ea-87df-e6b4c1e36818.png)

I don't mind to keeping it off, just wanted to give a heads up
Thanks!

**Comment by kalkih** [comment]
Hello!
Thanks for the heads up, this has been fixed in the [v0.9.0 beta](https://github.com/kalkih/mini-graph-card/releases/tag/v0.9.0-beta)
> Fill not showing when line is hidden & animate option is enabled
