### ISSUE TITLE
Aggregate_func to support "First" and "Last"

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#229]
Please add support to make aggregate_func support first and last ... if I have multiple readings on a day (and group by the day) I want to be able to show the last reading only.

This is good for eg with weight readings ... I have a smart scale that I sync with ... and before I weigh myself in a day I weigh 70... then at mid day I weigh myself and weigh 80... I don't want the average (75) or the min / max ... I want the graph to show the latest reading in each period.

**Comment by valantur** [comment]
I second this request. Useful for things like hourly counters, or other sensors that go up or down by increments and you'd like to know what was the last value of any time period.

**Comment by valantur** [comment]
Hey man thank you so much for being on top of this!
I seem to have a problem with how the stats are being displayed (I'm running the dev branch though HACS).
I have a sensor that tracks how much time my furnace was on per hour. The sensor's last value for the hour between 7 and 8 am was 18 minutes, as shown in the screenshot of the history graph attached to this message. However, the mini graph is displaying 6 minutes. The same happens for every hour on the graph.

Here's the relevant configuration of the card:
(Lovelace UI editor rearranges everything alphabetically)

  - aggregate_func: last
    align_state: center
    cache: false
    entities:
      - color: red
        entity: sensor.furnace_on_last_hour_minutes
        show_legend: false
        show_line: false
        show_points: true
        show_state: false
        unit: minutes /hr
        y_axis: secondary
    group_by: hour
    hours_to_show: 24
    points_per_hour: 1
    type: 'custom:mini-graph-card'

I tried reloading, clearing cache, loading the page in incognito mode, same results.


Any idea what the issue can be?

Thanks!

<img width="540" alt="furnace runtime" src="https://user-images.githubusercontent.com/2516392/72558210-1bec4280-3857-11ea-84d1-aa59f6c063f9.png">
<img width="284" alt="furnace runtime history" src="https://user-images.githubusercontent.com/2516392/72558213-1bec4280-3857-11ea-9c04-c7382b3debbe.png">

**Comment by kalkih** [comment]
Hello,

Selecting `dev` in HACS won't work for this card since the source has to be built before it can be used by the browser.

So setting `aggregate_func` to `last` will probably just make it fall back to `avg`.

There are instructions in the readme on how to build the project from source but I think it can be a bit overwhelming if you have no prior experience of nodejs or npm.

Otherwise you'll have to wait for the next release, got a couple if things I want to get done before I do the next release, a couple of open pull requests e.t.c.

Thanks!

**Comment by valantur** [comment]
Got it, thanks for taking the time to clarify this.

**Comment by stigvi** [comment]
![image](https://user-images.githubusercontent.com/25978315/74907961-d15d6900-53b4-11ea-9034-693991cb67d9.png)

I have a sensor which goes to zero at midnight and it seems that this zero value is registered as the last value for the day. The value for 19th February is 0 and not 67 as I would expect when I have group by date.
