### ISSUE TITLE
not an issue, but a showcase

### ISSUE THREAD

**Issue by iantrich** [kalkih/mini-graph-card#23]
![image](https://user-images.githubusercontent.com/1287159/51229138-e3064e80-1920-11e9-805e-5e95864aaac1.png)

starting to work on supplementing my [pc-card](https://github.com/custom-cards/pc-card) with your min-graph-card and it is going great! will probably submit a PR soon to remove the box shadow, but beyond that, it is absolutely awesome for this!

**Comment by kalkih** [comment]
@iantrich This is awesome, very creative and looks great! 💯

**Comment by iantrich** [comment]
just need that graph to start moving upward now ;)
