### ISSUE TITLE
Don't fade out the graph completely on mouse over

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#232]
When you are over a point the other series fade out entirely ... would be nice if the only faded out to 25% for eg so still slightly visible.

**Comment by kalkih** [comment]
Hmm... could be a good, I'll play around with it.
Thanks!

**Comment by kalkih** [comment]
Decided against this, it gets pretty messy in graphs with many entities.

**Comment by i00** [comment]
> Decided against this, it gets pretty messy in graphs with many entities.

I am not sure what you mean by messy?? ... the graph itself before any fading would look more messy in this case would it not?

I mean like this:
![image](https://user-images.githubusercontent.com/1435262/72588536-5f70aa80-3944-11ea-9f97-74197cb61dda.png)
