### ISSUE TITLE
Add option to show values when actual data is logged rather than just "points_per_hour"

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#233]
Sometimes it is critical if a reading fluctuations, but this can easily get missed with points_per_hour.

Please add an option to allow the listing of discrete points when data is actually logged.

**Comment by kalkih** [comment]
This will not be implemented in this card unfortunately, If you need this functionality I would recommend the default history card.

**Comment by i00** [comment]
Out of curiosity, why not?  Your card is great and the built in one does not have other features that I require.
Thanks K.
