### ISSUE TITLE
Dynamic Line Color Black or Grey

### ISSUE THREAD

**Issue by jstinesnc** [kalkih/mini-graph-card#236]
I hope I'm not overlooking something obvious, but my humidity graph using dynamic line color will sometimes go black or dark grey.  Is this a bug or human error in using the feature?  Thanks for a great card!
![image](https://user-images.githubusercontent.com/58440965/72219279-5cc02080-3512-11ea-8039-aa7cf507dc91.png)

**Comment by kalkih** [comment]
Hello,
As of version [v0.4.3](https://github.com/kalkih/mini-graph-card/releases/tag/v0.4.3) colors have to be specified in 6-digit hex format e.g. `#00ff00`.

> ### BREAKING CHANGES
> * Color thresholds now only support colors specified in hex format

While other color formats may work in certain setups it's not recommended.

**Comment by jstinesnc** [comment]
I missed that, Karl, So sorry. Thanks for responding!

John

**Comment by Phontana** [comment]
@kalkih I just found out that using theme variables for the `color_thresholds` option also renders black graphs, although I put hex values in the theme definitions. Is this expected behavior?

**Comment by kalkih** [comment]
Yes this is expected unfortunately, calculations on the colors has to be done in JavaScript and there we aren't aware of the css variables.

**Comment by Phontana** [comment]
@kalkih Is that because of the gradient calculations? Because for some other custom cards, the variables do work.

**Comment by kalkih** [comment]
Yes.
You can use css variables for other color options in this card, just not for color thresholds unfortunately. Not much we can do about it, we need to interpolate colors if the threshold is out of bound to ensure the gradient effect is applied correctly.

**Comment by Phontana** [comment]
Is it maybe possible to only calculate the colors if the `color_thresholds_transition` is set to `smooth`? So we can still use variables if this option is set to `hard`?

**Comment by kalkih** [comment]
Hmm yes, I think we should be able to skip those calculations when hard transition.

**Comment by Phontana** [comment]
Sounds great. Should I open a new issue for that or will this one do?

**Comment by kalkih** [comment]
New one preferably 👍
