### ISSUE TITLE
Request: add value of secondary axis to card

### ISSUE THREAD

**Issue by Beertje135** [kalkih/mini-graph-card#238]
Would it be possible to add the top value of the secondary axis to the card? Same as you show the first value of the main axis to the left, maybe the value of secondary axis to the right.

**Comment by Beertje135** [comment]
Would it be possible to add the top value of the secondary axis to the card? Same as you show the first value of the main axis to the left, maybe the value of secondary axis to the right. Eg so you can see the temperature And the operation mode in one view. Thank you for this great card!

**Comment by Beertje135** [comment]
Never mind. I found your comment in an other request and this fills my need. Thank you again for this great card! Your comment: “You can actually do this already in the entity object with help of the show_state option.”

**Comment by ETaube** [comment]
Hi, I'm looking for something similar like what is requested here. Could you please add a comment on how you solved it?

**Comment by kalkih** [comment]
Hello,
You can display states on an entity basis, see the `show_stste` entity option in the documentation.
