### ISSUE TITLE
Show average for secondary y-axis

### ISSUE THREAD

**Issue by Diondelpino** [kalkih/mini-graph-card#240]
Due to temperature° (Celsius) and humidity% not graphing very well together I’ve ended up implementing the secondary y-axis which works well enough. However there doesn’t seem to be a way to display the average of the secondary y-axis. Something like show: secondary_average? Is it possible to display this information via some other method?

**Comment by ildar170975** [comment]
Will be achieved if this is implemented:
https://github.com/kalkih/mini-graph-card/issues/466
Then the "max/min/avg" line will contain data for the selected graph (1st if none is selected).
This approach does not support "display max/min/avg line for each sensor".
