### ISSUE TITLE
What's this theme?

### ISSUE THREAD

**Issue by epiller** [kalkih/mini-graph-card#243]
Daaamn, can you share the theme shown on the right side of the first image shown in README?
It looks amazing.

**Comment by kalkih** [comment]
Hello,
Indeed, it's a good looking dark theme!
It's the "Dark – Blue" theme by @JuanMTech, you can find it here:
https://www.juanmtech.com/themes-in-home-assistant/

**Comment by JuanMTech** [comment]
Indeed. More themes available on my [GitHub](https://github.com/JuanMTech). The latest themes are also available via HACS.
