### ISSUE TITLE
NaN values on Min, Max & Avg when the show graph is false

### ISSUE THREAD

**Issue by dpjrodrigues** [kalkih/mini-graph-card#248]
Hello, 
below is my card setup. In the top 2 cards everytime I enter HA page I'm geting NaN values for Min, Max and Avg. I've read a lot about it and most issues were due to the formats which is not the case here because after some time it starts showing (but it can take a long time) and after I leave HA and comeback or just refresh the page it goes back to NaN again. 
![image](https://user-images.githubusercontent.com/45293584/73060700-588bef80-3e90-11ea-9eeb-c51335127c56.png)
Based on this behaviour I assume that calculation in this case is only triggered when sensor updates for the first time after the card is renderend (since this temperature sensor do not update that frequently it can really take several minutes) 

Still... I continued my investigation and as you can see in the image below I found out that when the show graph is true the problem doesn't exist so there is an issue only when the graph is false.
![image](https://user-images.githubusercontent.com/45293584/73060583-0fd43680-3e90-11ea-9c14-df8e5d03f6c8.png)

Thanks,
Diogo

**Comment by kalkih** [comment]
Hello Diogo,

Thanks for the detailed report, I was easily able to reproduce the issue described and have made a fix for it.
The fix will be included in the next release.

Thanks!
