### ISSUE TITLE
Lower_bound changes line and fill color

### ISSUE THREAD

**Issue by julienlarivee** [kalkih/mini-graph-card#256]
Hi,
I'm having an issue with the line and fill color when setting a lower_bound.
When the lower_bound is set to 0 everything is ok.
When setting it to 20 some black color is added the desired color.

lower_bound: 0
![1](https://user-images.githubusercontent.com/55027006/73141763-dc430900-4055-11ea-8789-24518c214605.png)

lower_bound: 20
![2](https://user-images.githubusercontent.com/55027006/73141772-e2d18080-4055-11ea-82bf-2feefd671e5f.png)

Here is my config:

>       - color_thresholds:
>           - color: var(--primary-text-color)
>             value: 0
>           - color: '#ffb033'
>             value: 75
>           - color: '#ff3333'
>             value: 85
>         color_thresholds_transition: hard
>         entities:
>           - entity: sensor.temperature_raspberry
>             name: Température
>             show_fill: true
>         font_size: 75
>         font_size_header: 12
>         height: 150
>         hour24: true
>         hours_to_show: 1
>         lower_bound: 20
>         points_per_hour: 60
>         show:
>           extrema: true
>         type: 'custom:mini-graph-card'
>         upper_bound: 100

Thank you for having a look.
Great card by the way! :)

**Comment by kalkih** [comment]
Hello,
Only color thresholds specified in 6-digit hex format is officially supported.
Other formats may work in some cases, depending if the bound is outside of the threshold or not.

So you would either have to switch to hex format for the first color entry or possibly keep the color variable and change the first threshold value to the same threshold as your lower_bound (20).

Thanks!

**Comment by julienlarivee** [comment]
Thanks alot. Changing the threshold value did the trick.
