### ISSUE TITLE
Feature request: sum aggregate function

### ISSUE THREAD

**Issue by meatheadmike** [kalkih/mini-graph-card#257]
Use case: I'd like to see total "on" time for my hvac in a given time period.

**Comment by valantur** [comment]
I've been trying to get that info on the graph too but I can't, even with the new first and last aggregate functions. For some reason they both show the average. Anyway, It would be awesome if we could group by hour and have the point of that hour be the total number of minutes a state was "on" or some other value.

**Comment by kalkih** [comment]
Hello,
Sum would probably not give you the result you'd want.
There's no standard for how often or when a sensor reports a state change in HA, (a state change will result in a history entry).
The way aggregation in this card works right now is by taking all history entries from within one data point (timeframe) and then do calculations on them (min, max, avg, last, first).
I don't really see how sum would be useful for sensor history data in HA, it would just take all history entries within a data point and add them together. A sensor could update three times one hour and 20 times the next hour and the sum would make no sense.

I could add `sum` as an aggregation option, it could possibly be useful in some cases, but I don't think it will help in your case.

I do however think you can achieve what you want by creating a [history stats](home-assistant.io/integrations/history_stats/) sensor or possibly a [utlity meter](https://www.home-assistant.io/integrations/utility_meter/) sensor and use that sensor for the graph, together with `group_by` `date` or `hour` and aggregate function `max` or `last`.

**Comment by kalkih** [comment]
> I've been trying to get that info on the graph too but I can't, even with the new first and last aggregate functions. For some reason they both show the average. Anyway, It would be awesome if we could group by hour and have the point of that hour be the total number of minutes a state was "on" or some other value.

Make sure you're actually loading the new version of the card, any non known aggregate function values will fall back to `avg`, and if you aren't loading the latest version of the card `first` & `last` isn't known.
Try clearing cache or check this issue https://github.com/kalkih/mini-graph-card/issues/169 if you're running HACS.
You can double check your version by opening the browser developer console, the latest version will output "MINI GRAPH CARD" and a version number there.

You can group by hour, the exact option is `group_by: hour`, see my answer above regarding the "total time on" .

**Comment by valantur** [comment]
Yeah there's something weird going on. I'm not sure I'm running the last version, even though I've removed the card from HACS, cleared the cache and reinstalled the card.

I searched for mini at the dev tools' console and only these show up:

<img width="601" alt="Screen Shot 2020-01-29 at 10 19 14 PM" src="https://user-images.githubusercontent.com/2516392/73425251-f1ce6200-42e5-11ea-929d-d390295f326c.png">

By the way I have a history_stats counter already working and showing the right value for each hour. Any idea how to make this work?

**Comment by kalkih** [comment]
The version should be at the very top of the log.
<img width="544" alt="Screenshot 2020-01-30 at 11 16 04" src="https://user-images.githubusercontent.com/457678/73440843-53c4b100-4352-11ea-860d-e0b517e26977.png">
I've had users complain about cache/update issues while using HACS before, reinstalling the card seem to solve it most times from what I've understood. Try updating HACS if you haven't or consider opening an issue in the HACS repository if you can't get the card to update correctly.

You could always install the card manually.

> By the way I have a history_stats counter already working and showing the right value for each hour. Any idea how to make this work?

Create a graph with the history stats sensor together with group_by date or hour and aggregate function max or last, and probably disable smoothing as well.
Something like this
```yaml
- type: custom:mini-graph-card
  entities:
    - entity: sensor.time_on
      aggregate_func: max
      smoothing: false
  group_by: hour
```

**Comment by kalkih** [comment]
Added in latest release
