### ISSUE TITLE
Where to put codes?

### ISSUE THREAD

**Issue by chintito4ever** [kalkih/mini-graph-card#258]
Sorry I'm a newbie to HA, I am actually confused, where do I put codes to customize cards or add cards?

TIA

**Comment by kalkih** [comment]
Hello,
You can add custom card configs in the UI editor by creating a black card.
If you're using [YAML mode](https://www.home-assistant.io/lovelace/yaml-mode/) the card configurations goes inside `ui-lovelace.yaml`.
