### ISSUE TITLE
Is there a way to display an array of value

### ISSUE THREAD

**Issue by afaucogney** [kalkih/mini-graph-card#261]
I have a list of value, how can i display this in a chart ?
Those values come from a sensor attributes.

For my needs (but it should not necessary be that specific), I get an array of daily energy consumption of the latest 31 days (starting from today minus 2 days).

Any idea ?

**Comment by kalkih** [comment]
Hello, no this is not supported, only history data from HA is supported.

**Comment by kalkih** [comment]
So if you somehow can get that data into a template sensor in HA, it could work.

**Comment by afaucogney** [comment]
- 

> So if you somehow can get that data into a template sensor in HA, it could work.

Could you please elaborate ?

**Comment by kalkih** [comment]
Look into [template sensor](https://www.home-assistant.io/integrations/template/), as long as you can get the data into HA you could create a template sensor that you populate with the data, you could then use that sensor in a mini-graph-card.
