### ISSUE TITLE
Data aggregation functions Max, Min, Avg does not want to work

### ISSUE THREAD

**Issue by octaviz** [kalkih/mini-graph-card#263]
I do not know why crazy reason does not indicate the 3 Max, Min and Avg values, I do it according to the parameters and only a temperature line is shown, what am I doing wrong?, this is my code in card
![temperature crazy](https://user-images.githubusercontent.com/856579/73957180-4b4a1880-4906-11ea-9213-06cd190e89d7.jpg)

```entities:
  - aggregate_func: max
    color: '#ff0042'
    entity: sensor.terraza_temperatura
    name: Max
  - aggregate_func: min
    color: '#00a2ff'
    entity: sensor.terraza_temperatura
    name: Min
  - aggregate_func: avg
    color: '#62ff96'
    entity: sensor.terraza_temperatura
    name: Media
group_by: hour
hours_to_show: 48
icon_adaptive_color: true
line_width: 2
lower_bound: -10
name: Temperatura Max & Min
name_adaptive_color: true
points: hover
points_per_hour: 20
show:
  labels: true
type: 'custom:mini-graph-card'
unit: ºC
upper_bound: 40

**Comment by kalkih** [comment]
Thanks, yes this is a bug introduced in 0.9.0, when using an entity more than once in the same configuration.

**Comment by octaviz** [comment]
Will there be any kind of solution shortly? Or can this parameter never be used? Thanks

**Comment by kalkih** [comment]
It will absolutely be addressed, I'll work on it when I have an opportunity.

**Comment by octaviz** [comment]
Good job your Mini graph card for HA, Home Assistant should buy your design, it's great and mandatory

**Comment by drew-kun** [comment]
Thank you very much! Waiting for this too!

**Comment by kalkih** [comment]
Thanks!
Hopefully this weekend if nothing else comes up 👍

**Comment by kalkih** [comment]
Should now be fixed in the latest release.

**Comment by drew-kun** [comment]
Updated the card version, restarted HA.. no changes. Did I miss anything? Can anybody confirm that it's fixed for sure?

**Comment by kalkih** [comment]
Hello, HACS is really broken lately, updates do not work as they should.
Reinstalling the card though HACS will probably solve it.
See https://github.com/kalkih/mini-graph-card/issues/259#issuecomment-583760988

**Comment by drew-kun** [comment]
Oh, sorry, thanks for the tip!

**Comment by octaviz** [comment]
I don't have HACS, I just have Home Assistant in a Synology docker, do I have to do something special?  I created a new card but it still ignores me

**Comment by kalkih** [comment]
Update the card manually, the aggregate function falls back to avg if it doesn't recognize the aggregate function, so if you're running a version of the card prior to min & max was implemented the card will use avg instead.
