### ISSUE TITLE
Feature Request: Allow for "predicting points" 

### ISSUE THREAD

**Issue by badrobit** [kalkih/mini-graph-card#264]
Allow the ability to define a set of points to be used before the last value is displayed for historical purposes. 

E.g.: 
Dark sky lets me get the hourly temperature prediction so I select knowing the current temperature up to 6 hours out. I want to be able to define a list of measurements that would precede the current. Then once I hit the actual current temperature that would be the value to be listed for historical context as well.

my awful drawing of what I mean:
![really-bad-drawing](https://user-images.githubusercontent.com/1327963/74091118-0c40d200-4a82-11ea-9b46-e37310a9f7c6.png)

**Comment by kalkih** [comment]
Hello,

Yes this would indeed be very neat.
It's however a bit out of scope for this project, I feel like it's too niché of a request, implementation time versus value added doesn't feel justified, at least not at this time.

Hope you understand, Thanks!

**Comment by badrobit** [comment]
Hey, 

I understand, hopefully, you will keep it on your radar if you ever run out of things to keep adding. I tried adding multiple entities but shows them as multiple lines. 

Thanks!
