### ISSUE TITLE
Request: Ability to change current value at top of chart to average of all sensors instead of current value of top sensor

### ISSUE THREAD

**Issue by fortepc** [kalkih/mini-graph-card#266]
Maybe I'm stupid... and this is possible already, but I have a card like this 

![image](https://user-images.githubusercontent.com/26149601/74195789-0259d300-4c2a-11ea-93d2-12f05e748d48.png)

And it shows the Living Room temperature at the top (the first entity I've specified) and what I'd prefer is to have the Avg of all the current sensors being the chart's value at the top. 

Or maybe instead, just let me hide the "current" value all together, but then I don't know where you'd show the value if you hovered over a point with the cursor.

**Comment by kalkih** [comment]
Hello,
You can create a [template sensor](https://www.home-assistant.io/integrations/template/) for the combined total and then use that as the first entity in the card config. You would probably also want to hide it from the graph (`show_graph: false`).
