### ISSUE TITLE
[Enhancement] Icon Location

### ISSUE THREAD

**Issue by PeteCondliffe** [kalkih/mini-graph-card#27]
Would you consider giving the option of displaying the icon next to the state in a future version?

The reason for this is space saving. For things like temperature & humidity an icon is enough to know what the graph is for. Unfortunately hiding the title doesn't give you the space back but having the option to display the icon next to the state would.

I've created a background with the icons on as a workaround and example of what I mean 
![capture](https://user-images.githubusercontent.com/37262524/51802552-29be4780-2243-11e9-857c-832d51250dc9.PNG)

Thanks for considering.

**Comment by kalkih** [comment]
Nice setup!
That's indeed a great idea for saving space.
i'm thinking about what we should name that option,
`icon_position` maybe? What do you think?

**Comment by PeteCondliffe** [comment]
Thank you so much.
Love the other things you guys have done with it too. Its allowed me to do this;
![capture](https://user-images.githubusercontent.com/37262524/52087003-370b6700-25a0-11e9-8e99-4979a7bee572.PNG)
