### ISSUE TITLE
Different graph type for indivitual entities

### ISSUE THREAD

**Issue by valantur** [kalkih/mini-graph-card#270]
DISCLAIMER: This is definitely in the "nice to have" category, not an actual issue.

Would it be possible to add an option to mix graph types whithin the same card?
For example, my card tracks the temperature on every room in my house, and they on the secondary axis I have plotted the time the furnace was on:

<img width="509" alt="current card" src="https://user-images.githubusercontent.com/2516392/74563750-531b4580-4f22-11ea-8d6d-ffc0163e191d.png">

What I would like to do is to set the secondary axis to "bar" instead of "line", so that the card looks like a better version of this:

<img width="510" alt="new card" src="https://user-images.githubusercontent.com/2516392/74563813-7c3bd600-4f22-11ea-8289-3147143823d5.png">

Does that make sense? I just think there are certain sensors that are better represented by bars instead of a continuous line.

Thanks for considering it!

**Comment by ildar170975** [comment]
Closed in favour of https://github.com/kalkih/mini-graph-card/issues/479
