### ISSUE TITLE
Modify more details of Title & Icon Position

### ISSUE THREAD

**Issue by jankete** [kalkih/mini-graph-card#278]
I'd like to modify the title of mini-graphcard (right) to look like the simple thermostat card (left).

![image](https://user-images.githubusercontent.com/22338766/75022893-2d98b980-5497-11ea-82c5-7c0de6681840.png)

Is there any chance to change font/icon that way? Maybe with cardmod?

**Comment by kalkih** [comment]
```yaml
align_icon: left
align_header: left
```
Add these two options to your card config and you should get the look you're after.

But yes, you can also always use card-mod to customize the card further.

**Comment by jankete** [comment]
Thanks for this. But how can I address the "opacity" of the card name with card-mod? If I use this, it doesn't work:

```
.name > span {
    opacity: 1.0;
  }
```

**Comment by kalkih** [comment]
Try with `!important`

**Comment by jankete** [comment]
Works, thank you!
