### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by bussio** [kalkih/mini-graph-card#281]
Since HA 0.106.0b0 there have been problems with the "mini-graph-card". Even the new v0.9.3 released today I still have the following problem:
![2020-02-24_13-19-53](https://user-images.githubusercontent.com/48105172/75152576-a737de00-5709-11ea-887f-f15f71670bc5.jpg)

What can I do to fix the problem?

**Comment by kalkih** [comment]
Clear cache, reinstall the card completely if using HACS.
Open the browser developer console and see what output you get there.

**Comment by bussio** [comment]
Excuse me, I'm using Safari (Mac). Can't find the developer console there. Post my yaml entries here again. In the Entities area they are displayed correctly ... only not in the graph display.

![2020-02-24_15-26-00](https://user-images.githubusercontent.com/48105172/75160393-31883e00-571a-11ea-8e86-29469dde1a76.jpg)
![2020-02-24_15-28-35](https://user-images.githubusercontent.com/48105172/75160491-5d0b2880-571a-11ea-97be-4425dc957ab1.jpg)
 and here yaml from graph display

![2020-02-24_15-31-12](https://user-images.githubusercontent.com/48105172/75160689-c1c68300-571a-11ea-993e-3f97c7b9bf2c.jpg)
![2020-02-24_15-32-58](https://user-images.githubusercontent.com/48105172/75160816-03572e00-571b-11ea-92f4-03cdb040c7ff.jpg)

**Comment by bussio** [comment]
Sorry, but I don't close this thread?!

**Comment by kalkih** [comment]
There's a developer console in Safari.
Please do the following:
* Clear cache
* Reinstall the card completely if installed through HACS.

**Comment by bussio** [comment]
Did exactly as you wrote it ... unfortunately nothing has changed.
Which menu item should I have displayed in the developer console?

**Comment by kalkih** [comment]
The console tab and let me know the output there.

**Comment by bussio** [comment]
![2020-02-25_10-04-22](https://user-images.githubusercontent.com/48105172/75231877-84afce80-57b6-11ea-992b-14b45b079744.jpg)

In the Logfile I see following:
![2020-02-25_10-08-00](https://user-images.githubusercontent.com/48105172/75232034-cb9dc400-57b6-11ea-962d-43257b568725.jpg)

but in the file list there is only this:

![2020-02-25_10-09-48](https://user-images.githubusercontent.com/48105172/75232195-17e90400-57b7-11ea-8914-3e649c970c2a.jpg)

**Comment by bussio** [comment]
Seems like it's my mistake. The name of the * .js file has changed and must be changed in the configurations.yaml.
I'm sorry I missed that.
