### ISSUE TITLE
Line drawn at 100%, although the values in history are 0%

### ISSUE THREAD

**Issue by hajo62** [kalkih/mini-graph-card#283]
See screenshots: Browser refresh does not help.
<img width="329" alt="image" src="https://user-images.githubusercontent.com/15800980/75336957-5ac8db80-588c-11ea-970c-b81b0e2995ec.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/15800980/75336982-687e6100-588c-11ea-975f-773ddf651570.png">

Some times later, the lines were displayed correct.

**Comment by kalkih** [comment]
Hello, make sure you got the latest version of the card, if using HACS, try reinstalling it and double check the resource reference.
Feel free to reopen if you experience the issue again.
