### ISSUE TITLE
Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by codylv7** [kalkih/mini-graph-card#285]
Getting an error on all graphs after upgrading to 0.106

Cannot assign to read only property '0' of object '[object Array]'

Let me know what else I can provide to assist

![Annotation 2020-02-26 172431](https://user-images.githubusercontent.com/40413816/75403543-e5c1ca00-58bc-11ea-8b3e-3ea819f41f41.png)

**Comment by sfgabe** [comment]
Same issue here

**Comment by kalkih** [comment]
Update the card, see #274, #284

**Comment by codylv7** [comment]
I did update the card already, same thing...
