### ISSUE TITLE
Show only differences

### ISSUE THREAD

**Issue by Dario82** [kalkih/mini-graph-card#288]
Hello, from my air conditioner I have this situation:

from 08.00 to 9.00 -> 8.5kwh
from 9.00 to 10.00 -> 9.9kwh (8.5 + 1.4)
from 10.00 to 11.00 -> 10.7kwh (9.9 + 0.8)
from 11.00 to 12.00 -> 11.45kwh (10.7 + 0.75)

I've created a bar graph and I have this:
![image](https://user-images.githubusercontent.com/39548149/75542889-f68b5080-5a20-11ea-8f9a-0080be060340.png)

But I want the differences between hours (0, 1.4, 0.8, 0.75)
Is it possible?

Thank you.

**Comment by Dario82** [comment]
This is my configuration:

  - type: 'custom:mini-graph-card'
    aggregate_func: max
    entities:
      - entity: sensor.daily_power
        index: 0
        name: kWh
      - entity: sensor.daily_costs
        index: 1
        name: €
    group_by: hour
    points_per_hour: 0.25
    hour24: true
    cache: false
    hours_to_show: 24
    icon: 'mdi:contrast-box'
    name: Consumo orario
    show:
      average: true
      extrema: true
      fill: false
      graph: bar
      points: true

**Comment by JohNan** [comment]
:+1:
I would also have use of this kind of graph.

**Comment by kalkih** [comment]
This should already be possible by setting up a utility sensor, see [utility sensor](https://www.home-assistant.io/integrations/utility_meter/) and https://github.com/kalkih/mini-graph-card/issues/197
