### ISSUE TITLE
Question: Any way I can display a value like 0.0004 instead of 0.00 ?

### ISSUE THREAD

**Issue by dkalinai** [kalkih/mini-graph-card#292]
Right now the value is truncated to two numbers after point. Any way to override this? I am trying to calculate some cents and cannot for the life of me live with the rounding. Alternatively, and if what i am asking is not possible is there any way to adjust the incoming value on fly via template instead of creating a new sensor just for value display in graph?

**Comment by kalkih** [comment]
The card has a `decimals` option in which you can specify the number of decimals the graph should display.
This will however not solve the issue if the sensor is reporting the state with only two decimals, so if that's the case you'd need to look at setting up another sensor and feed that sensor to the card.

**Comment by dkalinai** [comment]
Damn (facepalm) so stupid of me. I missed this option entirely. yes it works and does what it needs now. Thanks for fast turnaround.
