### ISSUE TITLE
Extra padding

### ISSUE THREAD

**Issue by sgttrs** [kalkih/mini-graph-card#294]
The 'info' element is not hidden, even if I do not use the average and extrema options. This results in extra unnecessary padding.
![mini-graph-card](https://user-images.githubusercontent.com/33804747/76069662-708d7d80-5fbd-11ea-9ce7-0434033e9382.jpg)

Card config:
```type: 'custom:mini-graph-card'
entities:
  - entity: sensor.weather_temperature
    name: На улице
hour24: true
points_per_hour: 1
animate: true
show:
  labels: true
color_thresholds:
  - color: '#000080'
    value: -30
  - color: '#0000ff'
    value: -20
  - color: '#0080ff'
    value: -10
  - color: '#00ffff'
    value: 0
  - color: '#00ff00'
    value: 10
  - color: '#ffff00'
    value: 20
  - color: '#ff8000'
    value: 30
  - color: '#ff0000'
    value: 40

**Comment by kalkih** [comment]
The info element has nothing to do with the extrema or average, the info element contains information when you hover over a point in the graph, so this behaviour is expected.

**Comment by sgttrs** [comment]
Ok, thanks for the clarification. But this padding remains even if I hide points. `points: false`

**Comment by kalkih** [comment]
True, it will always be there regardless of setup, interacting with other graph elements will also display additional data in that container, e.g. when hovering a legend entry.

Try card mod and set `display: none` on the container if you really don't want it there.
