### ISSUE TITLE
not showing graph data

### ISSUE THREAD

**Issue by clydefrog76** [kalkih/mini-graph-card#295]
On my HA 0.106.5 I am not seeing any graph data. I stopped, started, removed, reinstalled and finally uninstalled -> installed mini graph again without luck. The entity shows up fine, values are there but there is just not graph data. Any idea?

![image](https://user-images.githubusercontent.com/34819069/76073618-2fd03d00-5f9a-11ea-98d4-f1dd166f5f78.png)

**Comment by smith-scot** [comment]
I have exactly the same problem

**Comment by kalkih** [comment]
This happens when the recorder isn't setup or working correctly in HA (the history database), when this isn't working the card can't fetch the history data. Try restarting HA or look into your recordersetup and make sure it's setup working correctly.

**Comment by clydefrog76** [comment]
Thanks! My homeassistant_v2.db was malformed after a snapshot restore it seems. I deleted it in the file manager and restarted HA. It recreates the db and it works fine again.

**Comment by smith-scot** [comment]
Is it possible to pull the data from influxDB, or would it be better to configure grafana as an iframe?

**Comment by kalkih** [comment]
I don't quite understand the question, what kinda of data is it? Is the data coming from Home Assistant?Doesn't matter what database it is as long as it's setup as the recorder in HA.
If it's data coming from outside of HA, grafana would be the way to go.

**Comment by smith-scot** [comment]
All of my data from home assistant is already going to influxDB, I am not familiar with the recorder component. The nature of my question is, do I need to set up both the recorder along with influx or can I point the graph card to influx as its data source?

**Comment by nilsi** [comment]
Also wonder the same as @smith-scot. I guess its not possible right now?
