### ISSUE TITLE
Installing via HACS doesn't work

### ISSUE THREAD

**Issue by chansearrington** [kalkih/mini-graph-card#296]
Hey there,

Love this mini-card. Thank you for all your work on it.

I just tried installing this for the first time from the HACS add-on and the installation "completed" but the resources were never added to the configuration.

After manually adding the resources to the config everything was fine, but it didn't automatically do it. 

normally these add-ons generate a prompt in HACS that says "Add this to your lovelace configuration"

Setup:
Lovelace
HACS v0.22.2
HA v106.5
Mini-Card v0.9.3

**Comment by initrd** [comment]
I came here to comment that I have the same issue. But I got it to work by adding these lines to ui-lovelace.yaml:

```
resources:
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
```

It says so in the addon info page (*When you add this to your lovelace configuration use this:*), and I missed it too.

**Comment by kalkih** [comment]
Does HACS have support for automatically adding the resource reference? I didn't know that, and can't find anything in the docs about it.
