### ISSUE TITLE
Set a numerical value when using State Map

### ISSUE THREAD

**Issue by carlos-sarmiento** [kalkih/mini-graph-card#297]
I have a bunch of sensors that have discrete values but I'd like to represent as charts using the mini-graph-card. 

Right now I'm using state map to map values to labels, and it works correctly except that I don't understand how the code decides when the value is high and when it is low. I tested using the order in which mappings are declared on the `state_map` but it doesn't seem to correlate.

My question/request is "is there a way I can map a particular label to a particular numeric value so I can control how different values are rendered in relation to one another"

**Comment by maxwroc** [comment]
State map let's you use mini-graph to show sensor states which are not numbers (but strings). The order of the items in the `state_map` matters as the index of the item becomes the value on the graph. E.g.:
```yaml
state_map:
  - value: "night"
    label: "Night"
  - value: "day"
    label: "Day"
```
The above will result in the graph as the sensor would have the `0` state for `night` and `1` for `day`.  And accordingly it will show `Night` and `Day` labels for each of these states (e.g. when you hover over the point on the graph).

> I tested using the order in which mappings are declared on the state_map but it doesn't seem to correlate.

So it should correlate. Can you please provide your configuration and screenshot of the results?

**Comment by carlos-sarmiento** [comment]
You were right, the values do correlate. My issue was that since I didn't set `upper_bound` or `lower_bound`, when the same value lasted for longer than the time in the chart, it would always render as the min value, so it would seem the behavior was inconsistent. After adding the bounds, it worked great.

Since you tagged this as a feature request, I'll leave closing this issue up to you. But my problem was fixed. Thanks a lot

**Comment by ildar170975** [comment]
> Since you tagged this as a feature request, I'll leave closing this issue up to you. But my problem was fixed. Thanks a lot

Since the problem is fixed, then the issue is closed
