### ISSUE TITLE
Times on points going backwards

### ISSUE THREAD

**Issue by iantrich** [kalkih/mini-graph-card#30]
The time ranges, starting at the most recent point are increasing rather than decreasing when moving back in time

![graph](https://user-images.githubusercontent.com/1287159/52029457-e67d0680-24d8-11e9-9153-5de6fbb322f2.gif)

**Comment by kalkih** [comment]
This is what happens when you don't have proper testing 😆

**Comment by kalkih** [comment]
Fixed in [v0.2.1](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.1).
Thanks!
