### ISSUE TITLE
Wrap Unit to new line

### ISSUE THREAD

**Issue by ameennihad** [kalkih/mini-graph-card#303]
Hi, I want to show Unit of Measure under the value in a graph, I can imaging this can be done by Style but I don't know how, can anyone help with that?

I currently have few graph show values in MBit/s, the Graph shows (100.00 Mbit/s) but due to limited size unit is truncated to (100.00 M...), I want it to be:
100.00
MBit/s

**Comment by kalkih** [comment]
Hello,
Here's the code needed for this to work with card-mod:
```yaml
style: |
  .state {
    flex-wrap: wrap !important;
  }
  .state__uom {
    overflow: unset !important;
  }
```

Do you really need the decimals? you could save some space by using the `decimals` option.

**Comment by ameennihad** [comment]
Hi Kalkih,

I tried that but it didn't make any difference, here is my code and screenshot of the card:
```
entities:
  - sensor.speedtest_download
hours_to_show: 24
icon: 'mdi:download-network'
line_color: '#2980b9'
line_width: 6
name: Download
style: |
  .state {
    flex-wrap: wrap !important;
  }
  .state__uom {
    overflow: unset !important;
  }
  .state__value {
    overflow: unset !important;
  }
type: 'custom:mini-graph-card'
```

![image](https://user-images.githubusercontent.com/24837471/77054521-f0194480-69e0-11ea-9e33-3271909776b8.png)

**Comment by kalkih** [comment]
Do you have card-mod installed?

**Comment by ameennihad** [comment]
I was not aware of that, just installed it and everything looks right now. Thank you.
