### ISSUE TITLE
Show one bar per entity/attribute in bar graph

### ISSUE THREAD

**Issue by ricreis394** [kalkih/mini-graph-card#307]
Hello,

I already can have one bar per entity by grouping it by date. But I wonder if I can have the same functionality with attribute only.

Graph will compare the last values of each attribute.
Since attributes doesn't have history, maybe mini graph card cannot handle it.

Or atleast if I can have the bar graph with entities without history activated. Some entities have lots of changes and I only need the last value, so I exclude that entity in the recorder. But mini graph card can't handle it because not having history

**Comment by kalkih** [comment]
Hello,
The solution would be to create a [template sensor](https://www.home-assistant.io/integrations/template/) for each attribute you want to graph, and then use those sensors in the mini-graph-card.
