### ISSUE TITLE
Feature Exist? label X and Y Axis

### ISSUE THREAD

**Issue by PipeDeveloper** [kalkih/mini-graph-card#308]
Hello Comunity!
I just tried today this awesome graph card, i love it but i read the whole instruction and i couldn't find anything related with label the Axis X and Y.

For example if you watch this graph:
![Sin título](https://user-images.githubusercontent.com/35433329/77234384-ac633e00-6b8c-11ea-995d-8e5b9f39f8e4.png)
Personally i dont understand nothing, even i dont know what it means.

BUT... if you see this graph
![Sin título2](https://user-images.githubusercontent.com/35433329/77234387-c13fd180-6b8c-11ea-988d-3a0d93914a53.png)
Whoooaaaaa MAGIC!!! i understand it perfectly!!!

Let me know if it exist, or if not i could donate for the effort, i really think its nessesary, just for any basic graph construction. Also add a little marging for the label.

Thank you very much!

**Comment by kalkih** [comment]
Hello, this has been requested before #21 

I see the request has quite a few thumbs up, will see if I can get this done soon.

Closing in favor for #21 
Thanks!

**Comment by PipeDeveloper** [comment]
Thank you very much!

Send your paypal e-mail when this is done. I would like to donate you for this feature, I really love the theme of the graphs

**Comment by bmutari** [comment]
Hi @kalkih, I would also like to donate to you via paypal or venmo, this is a beautiful card and would really love to see the x-axis labeling as well.

**Comment by kalkih** [comment]
Thank you, I'll hopefully have some time to work on this next week.
