### ISSUE TITLE
Mini-graph-card does not work anymyore with hassio 0.107.4

### ISSUE THREAD

**Issue by Joezi79** [kalkih/mini-graph-card#309]
Hello, I have upgraded my hassio to version 0.107.4. Now, my mini-graph-card is not shown anymore, it is blank in the frontend. Does anyone know the reason for that?

Here is my config:

type: 'custom:mini-graph-card'
entities:
  - entity: sensor.temperature_158d00023f36a5
    index: 0
    hour24: true
    name: Wohnzimmer
    points_per_hour: 2
    show:
      align_state: left
      extrema: true
      fill: true
      graph: true
      icon: true

**Comment by Joezi79** [comment]
Ok, it seemed to be a problem with my cache. I have deleted all files. After that the graph was shown again. But now I am missing the extrema. Now min and max value is shown anymore. Anyone an idea?

**Comment by Quart666** [comment]
I have the same problem, tried deleting webbrowser cache, but still the same problem.
Wich cache did you delete?

**Comment by Dulcow** [comment]
It's odd because I have the same problem on all my devices (phones, PCs, laptops). I tried to uninstall/reinstall the plugin, same results. I tried different Web browsers, same results :-(

**Comment by Dulcow** [comment]
I found this error in the console:
`Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at cover.get _value [as _value] (slider-entity-row.js:1)
    at cover.get value [as value] (slider-entity-row.js:1)
    at HTMLElement.render (slider-entity-row.js:6)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)`

**Comment by Dulcow** [comment]
I found the issue. The HA state database was corrupted. If you click on one of the entities, you will see that it shows "No state history". That's why Mini Graph cannot show any points.

You just need to remove all home-assistant_v2* files and restart HA. Yes, you will loose all your history but the history is going to work again ;)

https://community.home-assistant.io/t/no-state-history-after-0-99-2/138507
