### ISSUE TITLE
Cant add card after installing with HACS

### ISSUE THREAD

**Issue by Appesteijn** [kalkih/mini-graph-card#310]
- Reboot HA (0.107.5, hassio)
- Install this plugin with HACS:
<img width="814" alt="Screenshot 2020-03-23 at 10 59 42" src="https://user-images.githubusercontent.com/353164/77304903-6f668b00-6cf5-11ea-8699-c06c3009c991.png">

- Reboot
- Add 'custom card':
<img width="425" alt="Screenshot 2020-03-23 at 10 58 37" src="https://user-images.githubusercontent.com/353164/77304811-480fbe00-6cf5-11ea-8a57-8d376772af46.png">

Expected result: Show a nice card with graphs :)

**Comment by kalkih** [comment]
Did it work as expected previously?

**Comment by Appesteijn** [comment]
No I never got it running. Did try to reinstall and remove, reboot and install.

**Comment by kalkih** [comment]
Does the sensor exist, and contain history? Does it show history in a default history-graph card?

**Comment by Appesteijn** [comment]
Yes:
<img width="421" alt="Screenshot 2020-03-24 at 08 01 36" src="https://user-images.githubusercontent.com/353164/77397364-be6bf900-6da5-11ea-9b6a-354797b2b28d.png">

vs:
<img width="403" alt="Screenshot 2020-03-24 at 08 01 46" src="https://user-images.githubusercontent.com/353164/77397381-c62b9d80-6da5-11ea-97f0-7f7dc40922c5.png">

**Comment by Appesteijn** [comment]
Progress! This works:
```
type: 'custom:mini-graph-card'
entities: ['sensor.power_consumption', 'sensor.hourly_gas_consumption']
```

but this doesnt:
```
type: 'custom:mini-graph-card'
entity: sensor.power_consumption
```

**Comment by kalkih** [comment]
Great, yeah that's right, entity is not a valid option anymore (should be entities), although I thought I would catch this and display an error about it 🤔

This should also work:
```yaml
type: "custom:mini-graph-card"
entities:
  - sensor.power_consumption
```

**Comment by Appesteijn** [comment]
Confirm that this works, thanks!
