### ISSUE TITLE
switched to Lovelace Dashboards and card is not working anymore

### ISSUE THREAD

**Issue by GitHubxtsnl** [kalkih/mini-graph-card#311]
running HA 0.107.5
I recently switches to Lovelace Dashboards. I created a copy of an existing .yaml file and associated with the newly created Dashboard. An now I get the error "Custom element doesn't exist: mini-graph-card."
![image](https://user-images.githubusercontent.com/43134674/77313399-1baf6e00-6d04-11ea-85a8-fa25e909cfd2.png)

This is my .yaml config:

`  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js`

and

`# CARD GAS EN STROOMVERBRUIK IN GRAFIEKVORM
        - type: custom:mini-graph-card
          name: Gas- en Stroomverbruik
          icon: mdi:server
          entities:
          - entity: sensor.monthly_gas
            name: Mnd Gas
          - sensor.daily_gas
          - entity: sensor.monthly_power
            name: Mnd Stroom
          - sensor.daily_power`

**Comment by kalkih** [comment]
I think you have to add resources in configuration.yaml instead of in ui-lovelace.yaml, in 0.107.0 an onwards.

Check the release notes and breaking changes in HA.

**Comment by GitHubxtsnl** [comment]
I moved the resources to the configuration.yaml file and this fixed the issue.
