### ISSUE TITLE
No visual editor available for: custom:mini-graph-card

### ISSUE THREAD

**Issue by Marozhenk** [kalkih/mini-graph-card#315]
Hey,

was searching how to solve this issue and nothing found except  [https://community.home-assistant.io/t/mini-graph-card-isnt-displaying-nothing/165171/20](url)
![minigraph1](https://user-images.githubusercontent.com/30979847/77671169-43b6ff80-6f98-11ea-82a4-39d5b9122a1b.png)
The link with solution didnt help.
So, any ideas to try?

**Comment by kalkih** [comment]
Hello,
There's no visual editor, that's correct: https://github.com/kalkih/mini-graph-card/issues/29, but I don't think that's your issue?
Do you have your recorder setup correctly? Do you get the history if you try the default `history-graph` card?

**Comment by Marozhenk** [comment]
Yeap, db was corrupted, I didnt pay attention to it as never used.
Many thanks!
