### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by TheMrg** [kalkih/mini-graph-card#319]
we get this error of all of our mini-graph-card

entity exist in hassio and we get data from it:

sensor.wohnung_helioslufter 
| 80 | 
unit_of_measurement: % 
friendly_name: Wohung Lüfter 
icon: mdi:air-conditioner

Cannot read property 'length' of undefined
type: 'custom:mini-graph-card'
entity: sensor.wohnung_helioslufter
name: Lüftung
line_color: lightblue
line_width: 4
hours_to_show: 48
detail: 2
labels: true

**Comment by Pschittt** [comment]
Same issue here. How did you solve it ?

I got the error when trying to use mini-graph-card in lovelace graphical edition. In Yaml mode, it doesn't seem to have the problem.
