### ISSUE TITLE
Min max values

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-graph-card#32]
I have 2 request regarding the min-max values.

- The time is shown with AM-PM. Is it possible to also configure a 24 hours clock?
- If you set `graph: false` under `show` then min-max (extrema) is not shown anymore. Is it possible to still show these values even when the graph is not shown?

Some more info [here](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/118?u=gerard33).

**Comment by kalkih** [comment]
> * The time is shown with AM-PM. Is it possible to also configure a 24 hours clock?

A actually added just this earlier today (8464a859ef83c5e521110aa57736539ee151e675), will be in the next release!

> * If you set `graph: false` under `show` then min-max (extrema) is not shown anymore. Is it possible to still show these values even when the graph is not shown?

Good catch, will fix!

**Comment by kalkih** [comment]
Both issues addressed with [v0.2.1](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.1).
Use new `hour24` for 24 hour clock.
Thanks!
