### ISSUE TITLE
negative numbers impossible

### ISSUE THREAD

**Issue by blubbel42** [kalkih/mini-graph-card#328]
Hello there,
I'm not sure if i got everything right. 
I tried to use the solar angle (numeric sensor derived from sun.sun_elevation) as a second axis background display data. Just to make a visual connection between time of the day and the values.
It does not show.
Tried to display it alone in an own mini-graph card. Current value is negative, shown correctly, but no graph.
I tried to find something in the documentation about this, but was not successful.
Hope i could describe this so it can be understood.

Greetings

Blubbel

**Comment by kalkih** [comment]
Hello,
The graph does support negative numbers, the issue is probably the format of the state coming from the sun.sun_elevation entity. I've never used it so I'll have to take a look at the output from it.

**Comment by blubbel42** [comment]
Hey... Thanks
I'm a real noob with programming and things like that, but please let me know if i can help in any way or if you need better descriptions of the problem
