### ISSUE TITLE
Is it possible to use an entity value as y-axis max?

### ISSUE THREAD

**Issue by Dinth** [kalkih/mini-graph-card#331]
I want to calibrate my graph using an entity value as y-axis maximum. Is it possible to do that in mini-graph-card? 
I have tried:
```
lower_bound: 0
upper_bound: sensor.value_total 
```
but it doesnt seem to work.

**Comment by kalkih** [comment]
Yes, with the help of something like [config-template-card](https://github.com/iantrich/config-template-card)
