### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by FedgarLurch** [kalkih/mini-graph-card#334]
I installed and configured (adding the js to the lovelace resources) the plugin through HACS, and I went to the examples you had posted, and tried to add a card manually to lovelace. 

I fought with it for about an hour, and I finally figured out there was an issue with the documentation (I think)

```
- type: custom:mini-graph-card
  entities:
   - sensor.illumination
```

Only works if I modify it to:

```
- type: custom:mini-graph-card
  entities:
   - entity: sensor.illumination
```

I am not actually sure if this is a bug, or an oversight on the documentation or what. I tried to move on to a 3 entity card, and I can't make that work at all. 

I will be happy to help update the documentation if that is all this is. I think this is a great plugin and much needed for data visualization.
My system is running 0.107.7

Thanks,

**Comment by kalkih** [comment]
Hello,
Sorry for the late reply, both should be supported, unless something broke with a recent HA version.

The following syntax is however only allowed when there's no additional entity options for the entity, it's basically a "shorthand" for `- entity: sensor.example` syntax
```yaml
- type: custom:mini-graph-card
  entities:
   - sensor.illumination
```

Thank you.

**Comment by kalkih** [comment]
I've tried both syntaxes on the latest HA version and both work fine.
Closing this for now, feel free to reopen if you encounter this again.
