### ISSUE TITLE
Support applicable translation strings (from HA?)

### ISSUE THREAD

**Issue by carsten-h** [kalkih/mini-graph-card#336]
Hi!

I saw that the texts inside the graph are only english:
here the AM/PM value and not 24 hour:
![Bildschirmfoto 2020-04-17 um 10 50 58](https://user-images.githubusercontent.com/44360828/79551299-c3b51e80-8099-11ea-8384-5f5585ef1e73.png)
here the word "current":
![Bildschirmfoto 2020-04-17 um 10 51 07](https://user-images.githubusercontent.com/44360828/79551413-eb0beb80-8099-11ea-8354-e47e5eb05fae.png)

Is this intended or are simply the translations missing or is this a Home Assistant problem?
How can I help to translate this (into German)?

**Comment by kalkih** [comment]
Hello,
This card doesn't use any translations from HA, There are translations available in HA and if there are translations for "Current" and other relevant card text available, I could potentially utilize those in the future. I'll look into it.

As for AM/PM, you can use the `hour24: true` option to switch to 24 hour clock.

**Comment by carsten-h** [comment]
Hello!

> I'll look into it.
Thank you!

> you can use the hour24: true option
Oh, am I stupid. My fault. Thank you!

**Comment by Misiu** [comment]
@kalkih there is:`ui::card::climate::currently` maybe it could be used?

**Comment by TheTimmaeh** [comment]
I've noticed this aswell. How about adding an option to define the 'Current' text with a custom phrase?

**Comment by Luth1ng** [comment]
Hi, any news on this ?

**Comment by jlsjonas** [comment]
This is something we'll consider later this year.
