### ISSUE TITLE
Show the X axis to see the 0 value for positive/negative value graphs

### ISSUE THREAD

**Issue by StefanoGiu** [kalkih/mini-graph-card#337]
Is it possible to show the X axis to see the 0 value for positive/negative value graphs?

**Comment by maxwroc** [comment]
It is not possible ATM but you can get the indication when the values are below 0 when you setup [color_thresholds](https://github.com/kalkih/mini-graph-card#dynamic-line-color)

**Comment by StefanoGiu** [comment]
I know this... :) But I'm trying to draw the balance power of my inverted, and I'd like to see the axis of when the power goes down zero and I'm getting the power from the network instead from my solar panels.

**Comment by kalkih** [comment]
Hello, I'll close this as it's been requested here https://github.com/kalkih/mini-graph-card/issues/80 already.
