### ISSUE TITLE
No new card appearing?

### ISSUE THREAD

**Issue by alphabeta279** [kalkih/mini-graph-card#339]
Hi installed this via HACS and followed instructions, but no new card appearing? Any tips on what I'm missing??

**Comment by Jitsert** [comment]
Sorry, not here to answer the question but also looking for the anwser :)

**Comment by maxwroc** [comment]
First of all try to look at your question as if you are the one who needs to answer it. Not knowing anything about what you have done there doesn't help at all. 

Please at least paste your yaml configuration for this card. It would be nice to know if the sensor which you want to use with it actually exist. Second thing: if you're able to see the native [history graph](https://www.home-assistant.io/lovelace/history-graph/) for that sensor (e.g. from more-info dialog/popup)

There is usually hunered of reasons why something is not working and it is really hard to guess what is the problem if you don't provide any info.
