### ISSUE TITLE
Max value displays NaN

### ISSUE THREAD

**Issue by brezuicabogdan** [kalkih/mini-graph-card#34]
This happens on the latest version - just installed the custom bundle an hour ago. It happens for all cards as you can see in the screenshot.

If more details are needed please let me know.

![mini-graph-card-nan-issue](https://user-images.githubusercontent.com/4300597/52138414-c7f04a00-2655-11e9-9c04-3ff6193850dd.PNG)

**Comment by kalkih** [comment]
Perfect, new release tonight hopefully.

**Comment by brezuicabogdan** [comment]
I acum confirm the issue has been fixed in v0.2.1. 

Thank you very much.
