### ISSUE TITLE
Data not correct when group by date 

### ISSUE THREAD

**Issue by dazzaboy74** [kalkih/mini-graph-card#341]
![energy](https://user-images.githubusercontent.com/62834453/80401137-22f60880-88bc-11ea-8e2a-775f1f9a570e.PNG)
Hi, awesome job on this card, really is good. 

I have found what appears to be a bug.  I use a card to show energy consumption using efergy energy monitor, that all works (i.e the efergy integration).

What I am finding is that if I group by date and remove hours_to_show: I get of course 1 day, and that day shows the correct kwh consumption (ie right now 25.42, i have that showing in another guage and also checked on the efergy cloud site, so it is correct.  In the line chart it shows correctly when setup like that.

If I then put hours to show as say 120 (5 days) it gives incorrect values for the the nearest 4 hours and only actually correct on the 1st day, it shows 16kwh for today, even tho it is 25.42, and it is the same for all prior days, not the same value but out by a factor of almost half.

I have this:

align_state: center
entities:
  - color: '#66bb6a'
    entity: sensor.energy_cost
  - entity: sensor.energy_consumed
group_by: date
hour24: true
hours_to_show: 144
line_width: 1
name: ENERGY CONSUMPTION
show:
  fill: true
  graph: bar
type: 'custom:mini-graph-card'

the alignment is all ok as the chart shows just fine,just wrong values on 5 of these 6 days,i have messed around with numbers of days to shows etc

I have attached a screenshot,, my daily usage is pretty consistant and about the same as the first bar in the chart.  I have teamviewer/zoom etc if you wanted to ever see it first hand.

all the best
Darren

**Comment by fedebruni84** [comment]
Same problem!

**Comment by rittyroo** [comment]
I have the same issue as well.  The data behind the card is correct, but the group_by: date is displaying it incorrectly (interval and hours both work correctly).  

I created a sensor to sum my GEM CTs, then feed that into an integration sensor to get kw, then use the Utility Meter.

<img width="178" alt="Screen Shot 2020-05-06 at 12 38 15 AM" src="https://user-images.githubusercontent.com/19392211/81139060-668ee900-8f32-11ea-871a-e13f801b4f1e.png">
<img width="355" alt="Screen Shot 2020-05-06 at 12 38 45 AM" src="https://user-images.githubusercontent.com/19392211/81139065-68f14300-8f32-11ea-9fc5-a01445811d45.png">

**Comment by kalkih** [comment]
Hello,
Please try using the `aggregate_func: max` option, the default aggregation is set to `avg` (average).

**Comment by fedebruni84** [comment]
> Hello,
> Please try using the `aggregate_func: max` option, the default aggregation is set to `avg` (average).

Already using it:

```text
- type: custom:mini-graph-card
  entities:
    - sensor.home_daily_energy
  show:
    graph: bar
  line_color: orange
  group_by: date
  aggregate_function: max
  hours_to_show: 240
  points_per_hour: 6
```

**Comment by kalkih** [comment]
The aggregate function could explain OPs issues.

> it shows 16kwh for today, even tho it is 25.42, and it is the same for all prior days, not the same value but out by a factor of almost half.

@fedebruni84 
Need more data from you if possible

**Comment by fedebruni84** [comment]
> The aggregate function could explain OPs issues.
> 
> > it shows 16kwh for today, even tho it is 25.42, and it is the same for all prior days, not the same value but out by a factor of almost half.
> 
> @fedebruni84
> Need more data from you if possible

I have the same behavior, the card shows correct value (it's 0.4 kWh) but if I click on a single bar it's not correct, same thing for previous days 

![IMG_0468](https://user-images.githubusercontent.com/37954254/81145704-12f2be80-8f77-11ea-82b0-a462996cb09c.jpeg)


![IMG_0469](https://user-images.githubusercontent.com/37954254/81145739-2c940600-8f77-11ea-8718-4ccdb8a1227d.jpeg)

**Comment by dazzaboy74** [comment]
I tried aggregate_function: max no change.  even using the same sensor gives different results on different cards.

Right now, on a guage card my sensor.energy_consumed shows 9.04kwh

on the mini-graph card it shows 8.73kwh, and loses throughout the day, by the end of most days I am around 25-30wh (according to the guage card AND the efergy cloud app but mini graph shows usually 14-16kwh for any given day, it only then seems to get it right on the last bar on the chart (last bar to the left, in my case 6 days ago, so looking at the bar for 6 days ago, it shows 29.87kwh, so the data is in there somewhere, it is just not calculating correctly.

aggregate function made no difference.  

thanks
Darren

**Comment by kalkih** [comment]
> Already using it:
> 
> ```
> - type: custom:mini-graph-card
>   entities:
>     - sensor.home_daily_energy
>   show:
>     graph: bar
>   line_color: orange
>   group_by: date
>   aggregate_function: max
>   hours_to_show: 240
>   points_per_hour: 6
> ```

You have misspelled the option name `aggregate_function` -> `aggregate_func`

**Comment by kalkih** [comment]
Please do also try `aggregate_func: last` and see if that changes things.

**Comment by dazzaboy74** [comment]
yeah, aggregate_func: (spelt func not function) and putting it last has worked :-) thanks

**Comment by rittyroo** [comment]
aggregate_func: max worked for me as well.  Thanks!

**Comment by dazzaboy74** [comment]
sorry its not fixed :-(  checking this morning, new day, i have:

yesterday shows 27,95kwh (about right), today (fresh day) shows 27.15kwh but on the guage shows 6.37kwh - so the aggregate is causing other problems :-(

thanks
