### ISSUE TITLE
Ability to adjust css elements

### ISSUE THREAD

**Issue by darkknightjs24** [kalkih/mini-graph-card#342]
Hey kalkih, 

I was wondering if it is possible to add the ability for users to add custom styling variables without the need of another card like 'card-mod' (which has not been updated and is causing a lot of problems with stability)? 

Specifically, it would be nice to adjust font-family, font-weight of title and state, card background color, and card filters, such as opacity. 

If it is something you'll look into, could you also implement those adjustments into your other plugins like mini-media-player and simple-weather-card?

**Comment by kalkih** [comment]
Hello,
Why don't you want to use card-mod?
Feels unnecessary to reinvent the wheel, would result in extra logic and complexity to all cards.
I much prefer having a dedicated universal solution like card-mod.
