### ISSUE TITLE
[Feature request] Add loading indicator

### ISSUE THREAD

**Issue by Misiu** [kalkih/mini-graph-card#344]
Recently HA added loading state to graphs: https://github.com/home-assistant/frontend/pull/5448
I think it would be a good improvement to add similar functionality here.
Now you see an empty card that will show graph after some time.
Showing the loading indicator will show user that something is happening and he must wait a bit longer.

This is my current setup. As you can see the current value is displayed, but it need some time to load the graph.
![mini_graph](https://user-images.githubusercontent.com/1741838/80952315-c59d1280-8df9-11ea-8f1c-6bfa1a4edd60.gif)

**Comment by kalkih** [comment]
Yes, great suggestion, fetching data can be slow so a loading indicator would be nice.

**Comment by Misiu** [comment]
@kalkih should this be added to renderGraph function (https://github.com/kalkih/mini-graph-card/blob/master/src/main.js#L283)?

**Comment by kalkih** [comment]
Yes that could be a good place to add it.

**Comment by ildar170975** [comment]
Could be informative.

**Comment by ildar170975** [comment]
fixed by https://github.com/kalkih/mini-graph-card/pull/1180

**Comment by emufan** [comment]
@ildar170975 Can we have this optional? I don't like it at all to have this spinners on the page. Esp. if they don't fit to my style.. Fine with having indicator as default =true, but really like to have the possibility to switch it off via yaml of the card.

**Comment by ildar170975** [comment]
@emufan 
Hi. You can disable the indicator in yaml. If you like, we can discuss it in community DM. I am not near a PC, but can talk in DM.

**Comment by emufan** [comment]
@ildar170975 : Ah. Great. Got/found it. Working. Thx,
