### ISSUE TITLE
fixed_value problem

### ISSUE THREAD

**Issue by Jalleronline** [kalkih/mini-graph-card#346]
Hello, I have a couple of sensors in Home Assistant that are not saved in the history but have static values:

![image](https://user-images.githubusercontent.com/17021666/81058160-272eb100-8ece-11ea-877b-ec9fbce0e5be.png)

These sensors are populated by an script and the value doesn't change over the year (are my electric month peak of current).
I want to compare the fixed_value (actual state) of the 12 months in a single graph, trying this:

`entities:`
`  - entity: sensor.pico_potencia_enero`
`  - entity: sensor.pico_potencia_febrero`
`  - entity: sensor.pico_potencia_marzo`
`  - entity: sensor.pico_potencia_abril`
`  - entity: sensor.pico_potencia_mayo`
`  - entity: sensor.pico_potencia_junio`
`  - entity: sensor.pico_potencia_julio`
`  - entity: sensor.pico_potencia_agosto`
`  - entity: sensor.pico_potencia_septiembre`
`  - entity: sensor.pico_potencia_octubre`
`  - entity: sensor.pico_potencia_noviembre`
`  - entity: sensor.pico_potencia_diciembre`
`fixed_value: true`
`name: Pico de Potencia`
`show:`
`  graph: bar`
`  legend: true`
`type: 'custom:mini-graph-card'`

I am able to see the state but the graph is not showing, even if I specify only to use the fixed_value:

![image](https://user-images.githubusercontent.com/17021666/81057819-788a7080-8ecd-11ea-8316-cf4316204fe1.png)

Kind regards.

**Comment by kalkih** [comment]
Hello,

The graph is completely depending on history data, if there's none, there won't be a graph rendered, it won't fallback to the current state value, (which it probably should).
It's been requested here before https://github.com/kalkih/mini-graph-card/issues/89, so closing this in favor for that issue.

Thanks!
