### ISSUE TITLE
0 is read-only

### ISSUE THREAD

**Issue by xobix** [kalkih/mini-graph-card#349]
Hi,

Your card looks great, but I have the following issue when I try it: 

```
0 is read-only

type: 'custom:mini-graph-card'
entities:
  - sensor.zigate_00158d000358e414_temperature
```

**Comment by kalkih** [comment]
Hello,
Please see #274

> This has been fixed in the latest version of the card released a few days back.
>
> If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:
> 
> Reinstall the card in HACS (if installed though HACS)
> Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169
> Clear browser cache
> If you still have issues after this, open the browser developer console (google how to do this) and look for a line which says "MINI-GRAPH-CARD" followed by the version number and let me know what version it says.

**Comment by xobix** [comment]
Thanks, it works.
I was because of the navigators cache.
