### ISSUE TITLE
Improve aesthetics when using labels

### ISSUE THREAD

**Issue by kloggy** [kalkih/mini-graph-card#35]
As per the forum:
(https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/137)

It seems a bit churlish to ask for such a small (and maybe niche) change in such a great card but would it be possible to do something about the bottom left corner being cut off when using labels in a card with rounded corners using card-modder?

Maybe have the min. value optional? Or remove the - (which would help if the min. value was only one digit).
Or, my preferred option would be to shift the whole thing including the y-axis over to be where the left side of the graph is? I think this would be more aesthetically pleasing even without rounded corners.

**Comment by an20dei** [comment]
Is it also possible to have a parameter for labels to round the value? Or do you think that it should exist?
For example, i have manually rounded the values (top top one with math.round and the low one with math.floor). Cause there are too much numbers in some circumstances and the decimal numbers are too less to be taken into consideration when looking at the card (like in your example, it will be prettier to the HIGH value - 969 and the LOW value 30)

**Comment by kalkih** [comment]
@an20dei It's actually already possible right now, see the `decimals` options. Since version 0.2.0 that option is also applied to labels (#19).

```yaml
- type: custom:mini-graph-card
  decimals: 0
  ...
```
![hyperion_8123_lovelace_4 19](https://user-images.githubusercontent.com/457678/52275686-88c14200-2950-11e9-866e-14c7d94fb146.png)

**Comment by kalkih** [comment]
Okay, I think you'll have to fork and add it yourself, sorry,
I don't want to oversaturate with options since they all add to the complexity of the card.

**Comment by an20dei** [comment]
fair enough, thanks :)

**Comment by kloggy** [comment]
This is the first issue I've raised on GitHub so I hope I am doing the right thing here...?
I see it is still open despite being resolved so I am closing it.

**Comment by kalkih** [comment]
> This is the first issue I've raised on GitHub so I hope I am doing the right thing here...?
> I see it is still open despite being resolved so I am closing it.

Yes, thank you, and thanks for the issue!
