### ISSUE TITLE
[Feature Request] show the last known state, when a sensor is offline

### ISSUE THREAD

**Issue by jankete** [kalkih/mini-graph-card#350]
Hi, I use the graph to show ink-amount of my printer. When It's online, everything is fine:

![image](https://user-images.githubusercontent.com/22338766/81394800-d5329900-9122-11ea-8a3e-cacdb7dc63df.png)

But when it's offline, the bars are still showing the last known state (which is good), but the state shows "NaN"

![image](https://user-images.githubusercontent.com/22338766/81394778-c9df6d80-9122-11ea-8baf-1db8f9489cca.png)

Could there be an option to show the last known state, when a sensor is offline instead of "NaN"?

HA-version: 0.109.6
Card version: 0.9.3

**Comment by broyuken** [comment]
could you share your code for this? I like it.

**Comment by shurickdaryin** [comment]
+1 to this feature request
