### ISSUE TITLE
Feature Request - Horizontal and Vertical bar graphs

### ISSUE THREAD

**Issue by DrewXT** [kalkih/mini-graph-card#351]
It would be awesome to be able to have horizontal bars as well as vertical bars - is this an easy enhancement?

**Comment by kalkih** [comment]
Hello!
Vertical bars are actually already supported, see this [example](https://github.com/kalkih/mini-graph-card#grouping-by-date). Vertical bars are most likely not getting added since this is primarily used to display data over time and having time on the x-axis makes a lot more sense.

**Comment by DrewXT** [comment]
hey Karl, was actually wondering if horizontal bars can be implemented - would be nice to be able to show two bars for say, energy consumption vs energy production for solar/wind generation monitoring
