### ISSUE TITLE
hour24 doesn't work

### ISSUE THREAD

**Issue by michalk-k** [kalkih/mini-graph-card#354]
I'm not sure it's somehow related to another issue: https://github.com/kalkih/mini-graph-card/issues/314

On my end, hour24 does nothing:
![obrazek](https://user-images.githubusercontent.com/7868445/82143614-70bfba00-9845-11ea-9f84-a604ad279429.png)

**Comment by kalkih** [comment]
Hello, your indentation is wrong, `hours_to_show` and `hour24` should be on the same indentation as the rest of the base card options e.g. `font_size`, `smoothing`, `icon`.

**Comment by michalk-k** [comment]
yes, you are right. 
Time is now displayed in 24h format.

But for some reason hours_to_show puts the card in error state. if I comment it out, it looks as expected. Do you have an idea why?

![obrazek](https://user-images.githubusercontent.com/7868445/82160815-35021000-9898-11ea-9921-097353120823.png)

**Comment by kalkih** [comment]
You have hours_to_show twice in your card config, could be that.

**Comment by michalk-k** [comment]
Yes, didn't expected that but it was it. 
Thank you and sorry for bothering with user mistakes

with regards
