### ISSUE TITLE
Hide name-div

### ISSUE THREAD

**Issue by yabbah** [kalkih/mini-graph-card#355]
Hi and first of all thanks for a wonderful card. I just have one issue. I don't want to display a name of the graph and want to earn some space in the GUI.

![image](https://user-images.githubusercontent.com/13518966/82416088-c8466b80-9a79-11ea-884f-a8bcf5b543a3.png)

Is it possible to add an option to hide the div for the name?

//yabbah

**Comment by yabbah** [comment]
And an option to center both state and icon, so the space between the icon and the state in the ping-result isn't that large :)

**Comment by kalkih** [comment]
Hello, thank you!

Spontaneously I feel like it would make sense to not render the top portion of the card when hiding name & icon? If we take that route we wouldn't need to add an additional option for this, which is good imo.
