### ISSUE TITLE
Hide info-div

### ISSUE THREAD

**Issue by guillaumelamirand** [kalkih/mini-graph-card#360]
Hi,

First of all thank you for your card, really great.

With default configuration, average and extrema are hidden but the div info is taken some extra space. Could we hide it when show options for average and extrema are set to false?

I could work on a PR if you'd like.
Thank you.

![image](https://user-images.githubusercontent.com/4324887/82749574-5c7e3e80-9daa-11ea-94e6-a4ae7c031684.png)
![image](https://user-images.githubusercontent.com/4324887/82749587-6b64f100-9daa-11ea-8611-a82f2720f578.png)

**Comment by kalkih** [comment]
Hello, thank you!

This has actually been fixed in the dev branch #325 and will be included in the next update.
