### ISSUE TITLE
Card not found after installing via HACS

### ISSUE THREAD

**Issue by basdejong95** [kalkih/mini-graph-card#361]
Hi,

I have installed this plugin via the HACS -> Frontend -> Mini Graph Card

It installs the plugin and adds the JS file to my Lovelace resources folder, however when i try to add the card in the front-end it gives me this error.

![image](https://user-images.githubusercontent.com/28990334/82823700-58d0e180-9ea8-11ea-83de-48f0af0ad4b6.png)

HACS version: 1.0.3 
Home Assistant: 0.110.2

Edit:

The Mini-Graph-Card does show up in the console:
![image](https://user-images.githubusercontent.com/28990334/82824292-5cb13380-9ea9-11ea-8c2b-da533a1af9a0.png)

**Comment by kalkih** [comment]
Hello,
Remove the initial dash before type, it's automatically added by the GUI editor at the root (only needed for yaml mode or raw editor).

**Comment by basdejong95** [comment]
> Hello,
> Remove the initial dash before type, it's automatically added by the GUI editor at the root (only needed for yaml mode or raw editor).

Thanks! That did the trick, i feel stupid now :)
