### ISSUE TITLE
[Feature request] Ability to show data starting from a given date/time

### ISSUE THREAD

**Issue by thermseekr** [kalkih/mini-graph-card#363]
First of all, mini-graph-card is great! Thank you for taking the time to write it.

The ability to show data starting from a specific date and time would be useful to display graphs for events like for example the evolution of the coronavirus pandemic.

The way its done today, being able to show only a determined interval given in hours makes the component unable show the complete scenario.

The tool would need to be able to evaluate if the points density is too high and adjust for that. This tends to happen when using a fixed start date/time as time passes and more information gets compressed in the graph. Maybe a adequate solution is, when selecting a fixed start date/time, also set a fixed number of points for the graph instead of points per hour.

**Comment by jlsjonas** [comment]
Might depend on #641

**Comment by ildar170975** [comment]
May be based on the same approach: https://github.com/kalkih/mini-graph-card/issues/726
