### ISSUE TITLE
Unable to load card in 0.11.03

### ISSUE THREAD

**Issue by Maltavius** [kalkih/mini-graph-card#364]
![image](https://user-images.githubusercontent.com/10133945/82949049-3bcd0900-9fa3-11ea-8e0d-f71fe3445e67.png)
Custom element does not exist

I've installed via HACS (1.0.3) and I'm on v0.9.3 of mini-graph-card

Nothing has changed in my configuration other than upgrading HA to 0.11.03 and with that HACS and mini-graph-card

I've restarted HA several times and checked that HA Lovelace Resources contains mini-graph-card
/community_plugin/mini-graph-card/mini-graph-card-bundle.js
Type: JavaScript Module

**Comment by kalkih** [comment]
Go into HACS and check the resource url, as I think it's changed in later versions, should be hacsfiles or something I believe.

**Comment by Maltavius** [comment]
![image](https://user-images.githubusercontent.com/10133945/82951658-e1827700-9fa7-11ea-829e-81254db0a58a.png)
The other repositories seem to link their documentation here.

![image](https://user-images.githubusercontent.com/10133945/82951667-e6472b00-9fa7-11ea-8774-8d3fa475a74c.png)

I've uninstalled and installed the repository again, it still installs in /config/www/community/mini-graph-card/mini-graph-card-bundle.js

Changing that path in the resources page does this to the Java Console
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Uninstalling again, and then reinstalling again and then reloading the page AGAIN with Ctrl+Shift+R
fixes the graphs.

And now the resource path seem to have changed to /hacsfiles... what the?

**Comment by kalkih** [comment]
Read the release notes, especially the breaking change section https://github.com/hacs/integration/releases/tag/1.0.0

**Comment by Maltavius** [comment]
I did, but several reinstalls HACS put them in that place and the files where there.
