### ISSUE TITLE
NaN displayed on graph even if current value is legit

### ISSUE THREAD

**Issue by tangowhisky37** [kalkih/mini-graph-card#365]
Hey folks,

Let me start by saying - thanks for the awesome HACS add-on!!!!!! I love it.

I seem to have this issue where even if there is one "NaN" value over the last 24Hrs the graph displays NaN rather than the latest value which is a proper number. 

See the second image which clearly shows that the last value is not NaN. If there's something i need to add in my configuration to ignore NaN's am happy to do that as well but this seems like a bug.

![mini-graph_nan](https://user-images.githubusercontent.com/13373159/83380926-9989a700-a422-11ea-97f4-bfe24bbd6ce2.JPG)

![non_nan_value](https://user-images.githubusercontent.com/13373159/83381042-ea999b00-a422-11ea-9e67-fbfad610883f.png)

**Comment by kalkih** [comment]
Hello, thank you!

Can you navigate to `/developer-tools/state` and see what the state is reported as for any of the entities that you see this issue with.
The state doesn't seem to be parsed correctly in the card, could be because of the number format used.

**Comment by ildar170975** [comment]
No clarifications were provided by the topic starter.
I do not confirm the issue.
Closed.
