### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MrLukson** [kalkih/mini-graph-card#367]
When i configure mini-graph-card on my docker HomeAssistant instance  and try to add to dashboard comes warning "Cannot read property 'length' of undefined". Home Assistant core version: 0.110.4. 
![mini-graph-card](https://user-images.githubusercontent.com/65340460/83754261-f75cff80-a66b-11ea-8169-7fcc89c43e04.png)

**Comment by kalkih** [comment]
You have to provide at least one entity under the `entities` option.
