### ISSUE TITLE
Time span for historic data points not correct

### ISSUE THREAD

**Issue by cicero22** [kalkih/mini-graph-card#37]
This card works perfectly fine except for the mouse-over of data points. When I move the mouse pointer to a data point, the correct value is shown, but the time span is not correct. It's always the same minutes with a random hour, no matter whether I choose 12h or 24h date format.

This screenshot I took at 12:09 and every data point in the graph shows "XX:07-XX:09" with a random hour. I use `points_per_hour: 30`.

![defect_mini_graph](https://user-images.githubusercontent.com/6802528/52337612-67bc2800-2a08-11e9-8df5-8bddf8bd0228.png)

**Comment by cicero22** [comment]
OK, I am not the only one... :-)

https://github.com/kalkih/mini-graph-card/issues/36#issuecomment-460963144

**Comment by kalkih** [comment]
Thanks for the details, will look to resolve this!

**Comment by kalkih** [comment]
Should now be resolved, available in the next release.

Example
```yaml
hours_to_show: 4
points_per_hour: 50
```
![kapture 2019-02-06 at 15 28 46](https://user-images.githubusercontent.com/457678/52348495-c099b980-2a24-11e9-8198-8c72ca34dd47.gif)

**Comment by cicero22** [comment]
Fixed with 0.2.2. Thx!
