### ISSUE TITLE
'install' is deprecated, use 'async_install' instead

### ISSUE THREAD

**Issue by Golab** [kalkih/mini-graph-card#370]
every time I'm trying to install it i get error

Logger: hacs.repository.plugin.kalkih.mini-graph-card
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 7:37:05 PM (1 occurrences)
Last logged: 7:37:05 PM

'install' is deprecated, use 'async_install' instead

trying to install version v1.3.7

im running
HassOS 4.10
Home Assistant 0.110.6
Supervisor 227

**Comment by kalkih** [comment]
This is related to HACS and should be discussed here https://github.com/hacs/integration/issues/1320
