### ISSUE TITLE
Night not showing up in Y AXIS on Home Assistant 0.111.0

### ISSUE THREAD

**Issue by nytram-md** [kalkih/mini-graph-card#371]
Hi

Upgraded to 0.111.0 and Night option on the graphs is not showing.

Checked with another user and they have said the same. Its just dissapeared.

**Comment by kalkih** [comment]
Hello,
Need more info, what night option? What does your card config look like?

Make sure the entity is working after the HA update and make sure the recorder is working and there's history for the entity.

**Comment by nytram-md** [comment]
Hi. Sorry, this is my first issue report. I copied the below from your github page and changed the temp sensors to the 2 that I required.

Hope this helps

Martyn

`entities:
  - entity: sensor.living_room_temperature
    name: Living Room
  - entity: sensor.heating_temperature
    name: Hallway
  - color: gray
    entity: input_number.nighttime
    name: Night
    show_legend: false
    show_line: false
    show_points: false
    y_axis: secondary
hours_to_show: 168
show:
  labels: true
  labels_secondary: true
  points: hover
type: 'custom:mini-graph-card'
`

![image](https://user-images.githubusercontent.com/55548608/84420342-ceabab80-ac11-11ea-8261-d5776954122a.png)

**Comment by kalkih** [comment]
I've not yet update to v.0.111.0 but I'll try to recreate this when I do.
What you can do is to navigate to `/developer-tools/state` and look for the entity `input_number.nighttime`, make sure it exists and has history available (should be able to check that by pressing the icon left of the entity name).

**Comment by nytram-md** [comment]
Hi 111.1 came out last night and looks to have fixed the issue. Below is a graph I have and its showing last night.

Thanks again and I will close the issue

![image](https://user-images.githubusercontent.com/55548608/84480389-61892c00-ac8c-11ea-8404-a1131695c571.png)
