### ISSUE TITLE
"No type card configured"

### ISSUE THREAD

**Issue by NapalmCandy** [kalkih/mini-graph-card#372]
Hi, 

I installed from HACS, it don't ask anything and don't show any button to add to Lovelace. When I try to create a new card of mini-graph-card it say "No type card configured" So, I need to do anything more to install it?

![Captura de pantalla 2020-06-11 a las 15 00 31](https://user-images.githubusercontent.com/12048931/84389898-0d803800-abf7-11ea-8413-2a8434270583.png)

**Comment by NapalmCandy** [comment]
![Captura de pantalla 2020-06-11 a las 15 02 27](https://user-images.githubusercontent.com/12048931/84389969-2d176080-abf7-11ea-877b-7a63b1053e8f.png)

**Comment by kalkih** [comment]
Remove the initial dash before `type`, it's not needed in the UI editor

**Comment by marcelohm** [comment]
I had that issue too, solved editing the UI Raw code changing the type to js:
resources:
  - type: js
    url: /local/mini-graph-card-bundle.js?v=0.9.3

**Comment by robo-kob** [comment]
`type: 'custom:mini-graph-card'
name: MINI Graph
entities:
  - sensor.motion_flur_temperature`
