### ISSUE TITLE
NOT IN HACS

### ISSUE THREAD

**Issue by rhgiter** [kalkih/mini-graph-card#374]
Why cant i found this in HACS ?
![image](https://user-images.githubusercontent.com/61065752/84797334-fd52c900-aff9-11ea-84e2-bd791eb2607f.png)

**Comment by modularTaco** [comment]
Hi,
I've installed HACS and mini-graph-card via HACS minutes ago and everything was working flawlessly.
Are you sure that HACS initialized completely before you searched for the card?
Are you sure that you're running the latest HACS version?
Are you sure that mini-graph-card isn't already installed via HACS?

**Comment by rhgiter** [comment]
![image](https://user-images.githubusercontent.com/61065752/84812853-5bd67200-b00f-11ea-8bfa-90c017296246.png)
latest?
i have not installed i before 

HACS initialized completely  YES

but no mini-graph   hmm

**Comment by kalkih** [comment]
You need to press the plus icon in the lower right corner, and then look for mini graph card in the popup.
HACS does only seem to display "NEW" and installed card directly in the frontend tab.

**Comment by rhgiter** [comment]
ahh   there it is   -  thanks.

**Comment by martinjuhasz** [comment]
oh yeah, fell for the same. thats quite unintuitive

**Comment by kalkih** [comment]
Indeed, I was confused as well, not the best from a UX perspective.
