### ISSUE TITLE
Feature request: Title font

### ISSUE THREAD

**Issue by TompaNation** [kalkih/mini-graph-card#377]
Love this card! I just have one wish and that is that I could set the font type of this cards so that it have the same look as my others.
![image](https://user-images.githubusercontent.com/61341892/85211405-23090680-b349-11ea-8de0-994e02d41b49.png)

BR
Tomas

**Comment by kalkih** [comment]
Hello,
Glad you like the card!

There are two ways you can achieve this:
1. Nest the card inside an entities card or any other card with a dedicated title, hide the name & icon e.t.c. from the mini-graph-card & use the `group` option.
2. Use [card-mod](https://github.com/thomasloven/lovelace-card-mod) to manually style the card to the way you like it.
