### ISSUE TITLE
Updated HACS and now addon is showing "Not Loaded"

### ISSUE THREAD

**Issue by Krojack** [kalkih/mini-graph-card#379]
Just did an update and this happened. None of the graphs are working. I tried to reinstall, uninstall then reinstall and no luck.

HACS:
Integration version:	**1.1.1**
Frontend version: **202006201137**

![HACS_Home_Assistant](https://user-images.githubusercontent.com/908461/85338717-ce809b00-b4b0-11ea-9d38-00e530df3dd9.png)

**Comment by kalkih** [comment]
This is HACS related, you should open an issue in the HACS repo instead.
