### ISSUE TITLE
More grouping options?

### ISSUE THREAD

**Issue by maartenterpstra** [kalkih/mini-graph-card#381]
Hi, 

First of all, thank you for this component! It looks really slick and works amazing.

I have a feature request. As far as I can tell, the only grouping options are per day or per hour. It would be nice if more grouping options were available, such as per week or per month. 

For me this would work, but ideally custom ranges in the config would be most flexible but also the most work, I think. 

Let me know what you think. I could also try my attempt and submit a pull request, if you prefer.

**Comment by kalkih** [comment]
Hello, thank you!

Yes, this would be useful indeed.
It's been requested here (https://github.com/kalkih/mini-graph-card/issues/302) before, I'll close this issue in favor for that one.

Also somewhat relevant feature requests https://github.com/kalkih/mini-graph-card/issues/181, https://github.com/kalkih/mini-graph-card/issues/363.

Pull requests are always welcome!
