### ISSUE TITLE
Floating numerics don't seem to work

### ISSUE THREAD

**Issue by Tovrin** [kalkih/mini-graph-card#382]
I'm not sure if this is the issue or not, but whenever I have numbers with lots of decimal places, the graphs don't seem to work.  If t them out, they work just fine.

Could this be investigated?

**Comment by kalkih** [comment]
Hello.
Can you give me some examples of the state reported by the entity?

**Comment by Tovrin** [comment]
Ok.  I've had a closer look and it's not what I thought it may be.  I had a look at the states today and they were 2 decimal points which should be fine.  I have seen them before and they've been up to 10 decimal places; I thought that might have been it. Perhaps you can see what's going on?

`          - entities:
              - entity: input_number.baseline_zero
                color: grey
                show_fill: false
                show_points: false
                show_legend: false
              - entity: input_number.binary_nighttime
                name: Night
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
                color: black
              - entity: sensor.power_ac_fronius_inverter_1_http_192_168_0_24
                color: deepskyblue
                show_fill: false
                name: Power Generated
#              - entity: sensor.power_grid_fronius_power_flow_0_http_192_168_0_24
#                color: red
#                show_fill: false
#                name: Grid Usage
#              - entity: power_load_fronius_power_flow_0_http_192_168_0_24
#                color: yellow
#                name: Home Usage
#                show_fill: false
            name: 3-day Solar Generation & Usage
            font_size_header: 20
            icon: mdi:solar-power
            height: 158
            hours_to_show: 72
            points_per_hour: 2
            upper_bound: 15000
            lower_bound: -15000
            line_width: 2.5
            tap_action:
              action: none
            show:
              fill: true
              points: hover
              labels: true
            type: 'custom:mini-graph-card'`

I've if I remove the comments, the graph disappears from the UI entirely.

**Comment by kalkih** [comment]
Check the browser developer console log and see if there are any errors in there and let me know if so.

What decimal seperator does the states have? Period or comma?

Make sure there's history available for the entities (the [recorder](https://www.home-assistant.io/integrations/recorder/) is recording them).

**Comment by Tovrin** [comment]
Sorry it's taken so long to get back to you.

Decimal Separator is a period.  Yes, recording is working.  I can get the sensors to display one at a time, but if I have two or more displayed, the graph fails to load.

I am getting an error in the console (it took a while to figure it out).  It's shown [here](https://imgur.com/OHxMW6l).  I hope this helps.

**Comment by kalkih** [comment]
Looks like the graph can't find the `state` of one of the entities, does it work with either of the sensors on their own?
Try each of the sensors on their own and see if you can pinpoint the issue to one of them.

**Comment by Tovrin** [comment]
They can all be used independently.  That's the odd thing.
