### ISSUE TITLE
Show entity name in title when hovering over a line

### ISSUE THREAD

**Issue by jarrah31** [kalkih/mini-graph-card#39]
When hovering the mouse over a line with multiple entities, would it be possible to reveal the entity name in place of the card title (e.g. it would show ‘Loft’ instead of ‘Indoor Temperatures 24hr’) in the same way the entity state changes to match which line the mouse hovers over please? This would be useful if I decide to not show a legend to help with the minimalist look.

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/e/2/e2ea0eb30e245e811511bdc7beb6f48bc9bb2cfc.png)

**Comment by jarrah31** [comment]
superb! I'll try this out tonight, thanks!

**Comment by kalkih** [comment]
It's available in the latest beta release [here](https://github.com/kalkih/mini-graph-card/releases/tag/0.2.2-beta).
Probably releasing the final v0.2.2 later tonight.

**Comment by jarrah31** [comment]
Ah thanks for the beta link, I was a bit too quick and have already built it from source and successfully tested it. :) Works a treat, thanks for adding yet another great feature!

**Comment by kalkih** [comment]
Closing this as it's now available in [v0.2.2](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.2)
Thanks, for the suggestion!
