### ISSUE TITLE
Feature Request: Plot graph with list values for state

### ISSUE THREAD

**Issue by kaizersoje** [kalkih/mini-graph-card#393]
Would be nice to plot a graph with state having list values.

**Comment by kalkih** [comment]
You would have to elaborate on that, I'm not sure what you mean.

**Comment by kaizersoje** [comment]
I have a sensor that gets populated with a list of values eg: [-0.001, -0.047, -0.211, -0.264]. Is it possible to plot these values as a graph? This sensor that gets set is the energy usage for my home. Hope this is clear.

**Comment by kalkih** [comment]
What are those data points representing? You could possibly create a template sensor & base the sensor state on the list data?

**Comment by kaizersoje** [comment]
Each value is the energy usage for an hour of the day.

**Comment by kalkih** [comment]
Can you only get those once a day? Otherwise you could just poll each hour and grab the latest data point and use that for the state of a template sensor.

**Comment by kaizersoje** [comment]
Yes, this is populated once a day.

**Comment by kaizersoje** [comment]
I am able to do this using [apexcharts](https://github.com/RomRider/apexcharts-card). So no need to look into this further.
