### ISSUE TITLE
Feature Request - Stacked Bar charts

### ISSUE THREAD

**Issue by slurpey** [kalkih/mini-graph-card#394]
Hi,

First, I'm grateful for this and it's awesome.

If I may: a feature request: stacked bar chart.  I use it for energy off peak / peak and it would be so nice to display this way.
![image](https://user-images.githubusercontent.com/10026060/86616333-f9d9ae80-bfb5-11ea-9bb1-2ee2a95a41f9.png)

Thank you!

**Comment by kalkih** [comment]
Hello, there's a feature request open for this here https://github.com/kalkih/mini-graph-card/issues/79
