### ISSUE TITLE
Feature request: Change icon size

### ISSUE THREAD

**Issue by B3voholic** [kalkih/mini-graph-card#396]
Would love for it to be possible to change the size and position of the icon.

**Comment by kalkih** [comment]
You should be able to accomplish this with [card-mod](https://github.com/thomasloven/lovelace-card-mod).

**Comment by agneevX** [comment]
Can you please provide an example @kalkih?

I've tried this, per this [HA Forums post](https://community.home-assistant.io/t/change-ha-icon-size-in-markdown-card/186644/7), but doesn't seem to work.
```yaml
style: |
  ha-card {
        --iron-icon-width: 45px;
        --iron-icon-height: 45px;
  }
```
