### ISSUE TITLE
Formatting of title

### ISSUE THREAD

**Issue by cicero200272** [kalkih/mini-graph-card#4]
When I add the card, entity titles and states as well as icons are not properly formatted:

![mini_graph](https://user-images.githubusercontent.com/15817602/46494163-7e603180-c812-11e8-96dc-9bf1d993657e.jpg)

**Comment by neoantox** [comment]
+1
It will be great if we have a parameter to adjust font size. Because it looks too large now, especially on mobile phones
<img src="https://user-images.githubusercontent.com/134825/46556601-c739e800-c8ef-11e8-9948-680826014422.png" width="250">

**Comment by kalkih** [comment]
Font size option now available in v0.0.3

**Comment by kalkih** [comment]
I will close this for now, you are welcome to open another issue if you have more suggestions.

**Comment by cicero200272** [comment]
@kalkih 
Thanks for the amendment, but _font_size_ only  changes the size of the value, but not the size of the sensor name which was my concern in the first place...

**Comment by kalkih** [comment]
That's a design decision and will stay that way, but you are welcome to fork this repo and modify it, or you could make the changes locally.

You can find and modify the name font size at line `208` in `mini-graph-card.js`
