### ISSUE TITLE
Support for optional Y-axis anchoring of lower and/or upper bounds (as opposed to full graph auto-scaling)

### ISSUE THREAD

**Issue by arigit** [kalkih/mini-graph-card#40]
Currently the Y-axis lower-bound and upper-bound fluctuate constantly as the graph auto-scales itself every time it is updated. This is great for certain use cases. 

Other use cases would benefit from static lower bound (e.g. leave the lower bound anchored in zero or some other value) and/or upper-bound - where it is important to visually spot the "big picture" rather than smaller variations.

For example, anchoring only lower-bound to zero would be great for a Humidifier or Temperature type use case, where minor variations of a fraction of a degree are not relevant, but one would normally like to spot bigger-picture trends - so it's important to leave the lower bound constant in zero, but the upper bound can be auto-scaled 

Other user cases may benefit from anchoring both lower and upper bound, for example router throughput, where throughput is limited to a known upper bound set by the ISP/DSL/Cablemodem subscription speed. So in this case one would use e.g. 0Mbps for the lower bound and 25Mbps for the upper bound.

Ideally, either ‘auto’ or a specific lower bound would apply on a per-entity basis (if different y-axis scales are support, which I believe is not the case now)

Usage examples 
```

lower_bound: auto  # (default) 

lower_bound: 0
```

Currently I think only a single Y-axis scale is supported for all graphed entities, so lower_bound and upper_bound would be 'global' card configuration options. If in the future independent Y-axis scales are supported, then lower_bound/upper_bound would be best configured withing each entity

**Comment by kalkih** [comment]
Great request.
This should be easy to add, the functionality is basically already there 👍

**Comment by kalkih** [comment]
Implemented and should be available in the next release.

Added the two options `lower_bound` & `upper_bound` as you suggested.
They are both optional and you can provide one, both or none. Default is auto scaling.

**Comment by arigit** [comment]
Magic :)  Thanks!!
Can't wait to test this out. Will try to compile the package. Will report back

**Comment by arigit** [comment]
Tested & using this - it's working great! 
Only one moot point - it seems the only way to set auto mode for either bound is to not define the 'option', i.e. lower_bound: 'auto' is not taken. Just a side note for the documentation.

**Comment by kalkih** [comment]
Great!
That's correct, I'll make sure to list it as an optional option, without a default value.
Thanks.

**Comment by kalkih** [comment]
Now available in the latest release, thanks!
