### ISSUE TITLE
Feature request: Grid in background

### ISSUE THREAD

**Issue by Draggon** [kalkih/mini-graph-card#400]
Hi

The only two things I'm missing in Your graph are
- grid in background 
- labels in case of multiple values at top

Something like:
![image](https://user-images.githubusercontent.com/2098284/87322175-619b7680-c52d-11ea-83d3-e471cd0bc33d.png)

**Comment by Salamandar** [comment]
Yeah. Having vertical lines to see days in a week graph would be great !

**Comment by pdeelen** [comment]
love to see this function!

**Comment by ipa64** [comment]
And please with scale label X and Y

**Comment by RomRider** [comment]
Duplicate of #21

(let's discuss it there while I'm trying to wrap my head around the codebase :))
