### ISSUE TITLE
BUG: Bar graph with all negative values displays incorrectly

### ISSUE THREAD

**Issue by devbobo** [kalkih/mini-graph-card#402]
When a bar graph of all negative values is displayed, the graph that is displayed is actually the inverse of what is expected.

As you can see in the screenshots below, the y axis is 0 to -2171.98.

In the first screenshot, the data point selected is 0, but the bar for this entry is shaded when it should be clear.

In the second screenshot, the data point selected is -2171.98.

<img width="482" alt="Overview_-_Home_Assistant" src="https://user-images.githubusercontent.com/680871/87526310-0b196e00-c6ce-11ea-90ed-2f386bbf209d.png">
<img width="471" alt="Overview_-_Home_Assistant" src="https://user-images.githubusercontent.com/680871/87526372-17053000-c6ce-11ea-874b-18315b916b78.png">

**Comment by devbobo** [comment]
@matteofranceschini yeah, my ultimate goal was to produced a stacked graph of net electricity consumption/production.

![MyEnlighten_-_Residential_System](https://user-images.githubusercontent.com/680871/91123727-e6f37880-e6e0-11ea-888a-0f43608f301d.png)

**Comment by matteofranceschini** [comment]
How did you achieve that? :)

**Comment by hk-ret** [comment]
Similarly the filling of line curves is done towards the minimum and not towards zero. In the example below for positive values the filling should only go down to the zero line and for negative values the filling should be above the curve and go up to the zero line.
![grafik](https://user-images.githubusercontent.com/55021191/105528829-c22e1c00-5ce5-11eb-9ecd-394596fb68c7.png)

**Comment by ildar170975** [comment]
To be replaced by https://github.com/kalkih/mini-graph-card/issues/630
