### ISSUE TITLE
Displayed data won't update when changing 'hour_to_show'

### ISSUE THREAD

**Issue by bemilicus** [kalkih/mini-graph-card#404]
Hello and thanks for this great card!
Maybe this is a question due to a misconfiguration my side but since i cannot  get rid after reading several times the manual, i'm asking here.

Here's the question:
i'm trying to show the energy consumption along with power for a period of 30 days in mini-graph-card.
My card setup is attached here below.
The data are present and recorded for 30 days with a sample every 30 secs (as shown in the hassio screeshot).
The data in the mini-graph-card seems to show only for the last 24 hours even if i set 744 in the 'hour_to_show' parameter.

Also i cannot see any changes in the displayed data when changing other parameters like 'points_per_hour' or 'value_factor'.
I'm pretty sure there are some misconfigured options in my card but since there's no error displayed, cannot catch them ;-)

Any hints?

Thanks!

<img width="904" alt="mgc-energy" src="https://user-images.githubusercontent.com/62201229/87874604-719ed480-c9cb-11ea-9574-41c2e631793f.png">
<img width="274" alt="hassio-energy-meter" src="https://user-images.githubusercontent.com/62201229/87874605-72376b00-c9cb-11ea-8790-568569594998.png">
[energy_mgc.txt](https://github.com/kalkih/mini-graph-card/files/4943690/energy_mgc.txt)

**Comment by kalkih** [comment]
Hello!
Those two options global options and need to be specified on the root level, can't be specified on an entity level.

**Comment by bemilicus** [comment]
Got it...
Thank you!
