### ISSUE TITLE
Feature Request - Graph times spent

### ISSUE THREAD

**Issue by hugosbnarciso** [kalkih/mini-graph-card#405]
Hello,

First of all, great work!

I have a sensor that tracks time spent (eg sleep, how long something is opened for) and the value for that state would be '05:25' (for 5 hours and 25 minutes).

Thing is, when i do a graph, it only shows the first number (hours).

see screenshot.
![Screen Shot 2020-07-24 at 20 12 15](https://user-images.githubusercontent.com/44305822/88412053-03eb1200-cdea-11ea-81a5-9a258b9a5a1b.jpg)
![Screen Shot 2020-07-24 at 20 12 06](https://user-images.githubusercontent.com/44305822/88412057-064d6c00-cdea-11ea-91d0-2c34288bb8fe.jpg)

Any way to add this functionality?

Thanks,
H

**Comment by RomRider** [comment]
What I think should be done:
* the value of the sensor should be in minutes (or seconds), this would require you to create a template sensor converting your current value into a valid number of minutes or seconds (not a string)
* we should introduce an option which would enable the the state to be displayed as a `time` object like so `2d 12h 52m 25s`

I had this feature in mind too. I'll work on this ASAP.

**Comment by hugosbnarciso** [comment]
awesome, thanks

**Comment by ildar170975** [comment]
@hugosbnarciso 
Is this issue still crucial?
Currently you may use a converted float value (i.e. `07:30` -> `7.5`).

**Comment by ildar170975** [comment]
No feedback within 3 months, closing
