### ISSUE TITLE
1k ⭐  on GitHub — Congratulations 🎉 

### ISSUE THREAD

**Issue by bessarabov** [kalkih/mini-graph-card#409]
Thank you for you work and congratulations for reaching 1k Stars on GitHub!

![Screenshot 2020-07-29 at 17 00 32](https://user-images.githubusercontent.com/47263/88809635-08824280-d1bd-11ea-8c59-78733651332f.png)

PS This is the first custom UI card that get 1k stars on GitHub.

🎉 👍 🥇 1️⃣

**Comment by kalkih** [comment]
Thank you & everyone else for the support & contributions to the card ❤️ 

We now have [21 contributors](https://github.com/kalkih/mini-graph-card/graphs/contributors) on this project, which is awesome!
Thanks everyone! 🎉
