### ISSUE TITLE
[Feature request] Have label/name overlap with graph

### ISSUE THREAD

**Issue by DrBlokmeister** [kalkih/mini-graph-card#417]
For small graphs, the labeling and current sensor values take up a lot of space. It would be nice to have an option if the text can be displayed on top of the graph, resulting in a graph like below:

![image](https://user-images.githubusercontent.com/57352628/89292805-394ef580-d65d-11ea-93f2-613edf08b6e7.png)

I think the easiest way is to include vertical scaling of the graph portion of the card.

**Comment by kalkih** [comment]
Hey, this has been requested here #176 already.

**Comment by DrBlokmeister** [comment]
Oops! Apologies! Thanks for the heads-up!
