### ISSUE TITLE
Inverting graph

### ISSUE THREAD

**Issue by magnusoverli** [kalkih/mini-graph-card#426]
Hi!

Would it be possible to add an option to invert the graphs?
I am using the card to visualize air quality from this integration (https://www.home-assistant.io/integrations/waqi/).
It returns values on the AQI scale, where `0` is best air quality and 300+ is hazardous. It would be nice to let the graph represent the quality, instead of the particulate matter measuerment it returns.

**Comment by Fusseldieb** [comment]
> Hi!
> 
> Would it be possible to add an option to invert the graphs?
> I am using the card to visualize air quality from this integration (https://www.home-assistant.io/integrations/waqi/).
> It returns values on the AQI scale, where `0` is best air quality and 300+ is hazardous. It would be nice to let the graph represent the quality, instead of the particulate matter measuerment it returns.

For this I would suggest feeding that value in a [template sensor](https://www.home-assistant.io/integrations/template/) and give an template sensor to the graph.

Alternatively, you can try with the [upper_bounds and lower_bounds properties](https://github.com/kalkih/mini-graph-card#card-options), but I don't know if they allow you to invert them.

Let me know!

**Comment by kalkih** [comment]
Great suggestions!
Give it a shot and see if that does the trick.
