### ISSUE TITLE
Feature request - dots in other color than lines

### ISSUE THREAD

**Issue by xvolte** [kalkih/mini-graph-card#428]
Hello. 
When multiple sensors (in my case temperature) are loaded on a graph with color threshold , it is impossible to know which line is what - as all the dots show in black

Would be great if we could have a « dots-color » option, for each entity, and still be able to use the line color for the values. 

Moreover it would be great if we can choose the title instead of selecting the first graph. 

See attached problems in picture

![E1900DFB-F505-409B-9F31-49096F981B77](https://user-images.githubusercontent.com/21142611/90973945-06df3c80-e527-11ea-9429-4c21790094bf.jpeg)

**Comment by agneevX** [comment]
Setting the color under the entity should solve your issue.

**Comment by xvolte** [comment]
If i put the color below the entity - all color thresholds are ignored - and i don’t want that

**Comment by agneevX** [comment]
Can you share the card config?

**Comment by kalkih** [comment]
Hello,
Please post your configuration so I can try to reproduce the issue.

**Comment by xvolte** [comment]
color_thresholds:
  - color: blue
    value: 0
  - color: mediumaquamarine
    value: 17
  - color: cyan
    value: 19
  - color: lime
    value: 22
  - color: yellow
    value: 24
  - color: orange
    value: 26
  - color: red
    value: 28
entities:
  - entity: sensor.mi_t_1
    show_legend: true
  - entity: sensor.mi_t_2
    show_legend: true
  - entity: sensor.mi_t_3
    show_legend: true
  - entity: sensor.mi_t_4
    show_legend: true
  - entity: sensor.mi_t_5
    show_legend: true
  - entity: sensor.mi_t_6
    show_legend: true
  - entity: sensor.mi_t_7
    show_legend: true
hour24: true
show:
  extrema: true
  labels: true
  points: true
type: 'custom:mini-graph-card'

**Comment by xvolte** [comment]
@agneevX @kalkih 
Does it help ?

**Comment by agneevX** [comment]
You don't need to add `show_legend` as it's already enabled by default.

Seems to be a bug with the color thresholds.

**Comment by kalkih** [comment]
Yes, you need to use hex color values.
Only colors in hex format is officially supported in 'color_thresholds'.
