### ISSUE TITLE
Custom element doesnt exist: mini-graph-card

### ISSUE THREAD

**Issue by Cyoshi** [kalkih/mini-graph-card#433]
hi
i have installed Lovelace Mini Graph Card via HACS.

A line appeared in the Settings - Lovelace - resources panel
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js (module)
but cards cannot be added (No card type found)

I tried to add the script manually but that didn't bring any result either

please tell me how to fix it 

HA 0.114.4

<img width="1174" alt="res" src="https://user-images.githubusercontent.com/57960844/91634117-8fae1a80-e9f6-11ea-9df6-ade21fd80f95.png">
<img width="977" alt="error" src="https://user-images.githubusercontent.com/57960844/91634119-90df4780-e9f6-11ea-964a-3fe85f413b03.png">

**Comment by kalkih** [comment]
Hi,
Remove the initial dash (-) before type, it's not needed in the root in the UI editor.

**Comment by Cyoshi** [comment]
ow! it works!!! Thank you!
