### ISSUE TITLE
show_state in same color as lines. 

### ISSUE THREAD

**Issue by pesor** [kalkih/mini-graph-card#438]
I made this graph for my solar panels, production, upload to grid, and download from Grid, All about energy production and  consumption. 

I would really like to have the show_state in same color as the graph. 

Can it be done (have I overlooked something), or if not, can it be an enhancement. 

I love your card. 
![1C27DD09-A343-484E-8AB2-1CCAEC887006](https://user-images.githubusercontent.com/3110308/91882666-9ac9aa80-ec83-11ea-876f-33660d53b196.jpeg)

**Comment by kalkih** [comment]
Yes, set the option `state_adaptive_color: true` on each entity in the card config.

Another alternative would be the `show_indicator: true` which will show the line color in a dot beside the state.

**Comment by xvolte** [comment]
> show_indicator: true

state_adaptive_color: true works very well, thanks
however, show_indicator: true does not work correctly on single lines

Thanks for providing a solution to this !

**Comment by kalkih** [comment]
Yes, it's by design, there's no real use for indicators when the graph only contains one entry.

**Comment by xvolte** [comment]
> Yes, it's by design, there's no real use for indicators when the graph only contains one entry.

I know, but if you just wan to see the current color status, that would be helpul, even if only one graph!
nevertheless, thanks a lot for the hard work :) and support!
