### ISSUE TITLE
Sum in mini-graph-card

### ISSUE THREAD

**Issue by pesor** [kalkih/mini-graph-card#439]
I have been looking for an example but found none. 

Again, my energy visualization graph. 
![E528E65A-270F-4084-9AF7-BBD3E27AE792](https://user-images.githubusercontent.com/3110308/91969922-2a6c6900-ed17-11ea-8e98-e00f32cd6607.jpeg)

Thanks for solving the color issue. 😃

As you can see there is three graphs, but one is missing, namely the difference between the producing graph(green) and the uploading to grid graph(Blue). This is the Power used directly from the solar panels. 

Is it possible to make that substraction between the two sensors in the card. (Maybe a +-). 

I can of cause make the sensor my self, but the data is coming from two different ESP32, so it will demand a lot of programming, and Exchange of data between the two ESP32. A simple subtraction in the mini-graph-card would therefore be nice.

**Comment by pesor** [comment]
I just found that I maybe can create the extra entity in the configuration.yaml file

See this link, if it works, problem solved. 

https://community.home-assistant.io/t/subtracting-two-values-from-two-sensors-in-a-template/140693/6

**Comment by kalkih** [comment]
Hello!
Yes, a template sensor would be the way to go here, that way we can also spare the client from doing additional computing and leave that to the server 👍

**Comment by pesor** [comment]
It worked. 

![image](https://user-images.githubusercontent.com/3110308/92301871-9218f300-ef67-11ea-8d99-c8fa0460f23d.jpeg)
