### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by nonamewastaken** [kalkih/mini-graph-card#440]
After installing the addon through hacs and setting up a basic configuration
(- type: custom:mini-graph-card
  entities:
    - sensor.humidity)
 HA gives me the error "No card type found" 
Most likely pebcac.
Help would be apreciated.

**Comment by kalkih** [comment]
Hello,
Remove the initial dash before `type`.
See https://github.com/kalkih/mini-graph-card/issues/361
