### ISSUE TITLE
Feature request - Print values in bar graphs

### ISSUE THREAD

**Issue by leafshore** [kalkih/mini-graph-card#443]
Thanks for this component! Solves a lot of issues with using aggregate_func: max and group by date. Showing solarenergy produced per day, rain per day etc.

But it would be nice to see the actual numbers/values for each bar. Like in this photoshop'ed example (solar energy per day, like your "enery consumption example"):
![BarGraph](https://user-images.githubusercontent.com/58782442/92512425-0fb25c80-f20f-11ea-812d-33d33224c4b1.png)

**Comment by mmirannalti** [comment]
I would also like to have this feature implemented.

**Comment by Toukite** [comment]
Hello, I would also like to have this feature implemented !

**Comment by RomRider** [comment]
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.
