### ISSUE TITLE
Feature request: Show graph in "more-info" popup

### ISSUE THREAD

**Issue by BoneheadFraggle** [kalkih/mini-graph-card#446]
The mini-graph-card is perfect for my dashboards. Thanks a lot for sharing and maintaining!

A feature that I think would be very useful is if it was possible to have a more detailed mini-graph-card as a tap_action where the current entity could be configured to show more info, for example a graph (see mock up below).

Example:
**My current dashboard. Just showing temperatures to make it readable from a far distance with tap_action more-info:**

![Mini-1](https://user-images.githubusercontent.com/2287810/93129332-19d1d080-f6d1-11ea-92d9-209aed453551.png)

![Mini-2](https://user-images.githubusercontent.com/2287810/93129339-1b9b9400-f6d1-11ea-9315-60e981d60670.png)

**Feature request, an overlay with more/other options then the dashboard:**

![Mini-3](https://user-images.githubusercontent.com/2287810/93129341-1cccc100-f6d1-11ea-816d-630dd07f1dbe.png)

**Comment by kalkih** [comment]
Hey,

Nice setup & great suggestion.
That type of feature is a bit outside the scope of a custom card.

There's a solution though! Check out [browser_mod](https://github.com/thomasloven/hass-browser_mod) and specifically [the popup feature](https://github.com/thomasloven/hass-browser_mod#popup), it should allow you to achieve just this.
