### ISSUE TITLE
problem view graph bar

### ISSUE THREAD

**Issue by LaurentMicrotec** [kalkih/mini-graph-card#447]
do you know why I have a curve instead of a bar graph?
![Curve not bar](https://user-images.githubusercontent.com/50947256/93131327-2c013e00-f6d4-11ea-9679-9b2392c14318.png)

**Comment by kalkih** [comment]
Yes, `graph: bar` should be indented inside `show`, see example in the documentation.

**Comment by LaurentMicrotec** [comment]
I've seen the wiki, but the graph doesn't want to be built when 
graph: bar should be indented inside show
![Curve not bar 2](https://user-images.githubusercontent.com/50947256/93181482-cc894980-f738-11ea-85c0-d7864a24e858.png)

**Comment by kalkih** [comment]
`show` should not be set to `null`.
See this example: [bar chart card](https://github.com/kalkih/mini-graph-card#bar-chart-card)

**Comment by LaurentMicrotec** [comment]
thank you, the null value came automatically during a previous test.
You solved my problem I'm super happy
