### ISSUE TITLE
Feature request: possibility to display extremas all the time

### ISSUE THREAD

**Issue by cadavre** [kalkih/mini-graph-card#450]
A graph without reference for its values is not worth much. Currently we can display extremas only on hover but simple glance is not giving much about historical values.

It would be awesome if we could display extremas all-the-time on graph, in a little bit lighter version, like this:
<img width="263" alt="Zrzut ekranu 2020-09-23 o 16 27 31" src="https://user-images.githubusercontent.com/461796/94026232-af4c1f00-fdb9-11ea-8013-979ad47c45dc.png">

Values can be really small and without containers (like current oval) it still looks good.

**Comment by cadavre** [comment]
BTW above chart is actually graphed with yours `src/graph.js`. ;)

**Comment by kalkih** [comment]
Hello!
Very nice, did you build your own custom card around the graph functions?

Please see the show option [labels](https://github.com/kalkih/mini-graph-card#available-show-options). You can set it to `true` to always display the min-max of the value axis (extremas).
