### ISSUE TITLE
Request feature - Add aggregate functions to calculate the difference between last and first value

### ISSUE THREAD

**Issue by NikoM87** [kalkih/mini-graph-card#457]
Add aggregate functions to calculate the difference between **last** and **first** value.
To visualize how much an observed value has increased (positive value)  or decreased (negative value) during the day.

Thanks!

**Comment by mvimercati** [comment]
It would be also useful to have the delta between last value of a day and last value of previous day.

**Comment by mhspelt** [comment]
I needed this too and submitted a PR to add a diff function that does exactly this
https://github.com/kalkih/mini-graph-card/pull/601/commits/39b82140117a74b306aeca565829908a8ca1d379
