### ISSUE TITLE
Temporarily offline sensor without value breaks graph?

### ISSUE THREAD

**Issue by isabellaalstrom** [kalkih/mini-graph-card#46]
History graph shows this: ![image](https://user-images.githubusercontent.com/22006797/52722855-bdff0d00-2fac-11e9-9957-6d85df211a66.png)
mini graph card shows this: ![image](https://user-images.githubusercontent.com/22006797/52722896-ce16ec80-2fac-11e9-98d7-dc9b37dd3463.png)
Console says this 
![image](https://user-images.githubusercontent.com/22006797/52722956-ee46ab80-2fac-11e9-93e8-bbf64907e734.png)
and this
![image](https://user-images.githubusercontent.com/22006797/52722977-f7d01380-2fac-11e9-9c79-67081a2d32b1.png)

**Comment by kalkih** [comment]
Did you see this issue before updating to 0.2.3 or only after?

**Comment by kalkih** [comment]
@isabellaalstrom I think I managed to recreate this. Apparently, `Number(null)` equals `0`, which made history entries with `null` as state pass straight through the isNaN check 😕

**Comment by isabellaalstrom** [comment]
I see! The issue was present before 0.2.3 as well. Not that regularly occuring perhaps, and for me it's alright since this will be gone in an hour or so by now.

**Comment by kalkih** [comment]
Okay, thanks for the issue, should be fixed in the next release!

**Comment by kalkih** [comment]
@isabellaalstrom New version available [v0.2.4](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.4), this should hopefully be resolved.

**Comment by isabellaalstrom** [comment]
Can confirm!
