### ISSUE TITLE
Feature request: History overlap

### ISSUE THREAD

**Issue by fodi666** [kalkih/mini-graph-card#461]
Hello,
Is there a chance to include a "history overlap" option? Imagine I would like to show 4 days worth of data of an entity, however I'd like to have a span of one day and have all the previous data cut into one-day-long segments and put behind the current data (maybe with a slight gradient)
Imagine this as if the top-left corner of the preview image (https://user-images.githubusercontent.com/457678/52977264-edf34980-33cc-11e9-903b-cee43b307ed8.png) would have blue as the current day, red as yesterday and yellow as the day before yesterday. 
This way it would be perfect to see if for example the weather is changing or something. Since history data is already scraped by the card it would be a different way to present it.

Ideally I'd imagine that it I add one entity and if I turn this setting on, then I could define the length of this window and if I'd like this to be a rolling window (always ending with latest data) or to be a fixed one (eg. from midnight to midnight or 6am to 6am with the current data gradually filling the view but history data being already populated according to window settings)

**Comment by kalkih** [comment]
Cool idea.

One possible implementation would be to add support for setting some form of `offset`, and also allow this on an entity-basis.
That way you could e.g. add the same entity three-four times and just adjust the `offset` of each entity, + it would allow for some other use-cases as well.
