### ISSUE TITLE
[Feature Request] Display state for each variable that is plotted

### ISSUE THREAD

**Issue by embcla** [kalkih/mini-graph-card#471]
Hi I propose to add additional variables that are plotted (or at least the second one) to the STATE

see picture
<img width="566" alt="ha graph second state" src="https://user-images.githubusercontent.com/54371771/95756146-ae662900-0ca5-11eb-9501-f62fa137400a.PNG">

**Comment by RomRider** [comment]
What do you mean by "to the STATE"?
