### ISSUE TITLE
HACS Custom element doesn't exist

### ISSUE THREAD

**Issue by barthelemyguillaume** [kalkih/mini-graph-card#474]
Hello,

I meet a problem with the mini-graph-card install via HACS in Home Assistant Supervised 0.116.2

After the installation, the resources is automatically add but there is a mistake. 
`/local/mini-graph-card/mini-graph-card-bundle.js`

I need to add ?v=0.9.4 at the end.

The complete resources is
`/local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.9.4`

Regards

**Comment by KireStreve** [comment]
Hello, I can't test it, But i have the same problem dat de custom element doesn't exist if you won't to put it in Lovelace

In the YAML file he says **Error: Custom element not found: mini-graph-card**
and in de example i get this error
```
Custom element doesn't exist: mini-graph-card.
type: 'custom:mini-graph-card'
entities:
  - sensor.adguard_dns_queries
```

**Comment by wgomeringer** [comment]
I do have this working with Home Assistant OS 0.116.3

Home Assistant config
---------------------
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.5
supervisor | 247
timezone | America/New_York
version | 0.116.3
virtualenv | false

HACS config [1]
---------------------
Integration version: | 1.6.0
Frontend version: | 202009091732

Once installed I restarted Home Assistant and HACS took some time to initialize. I then navigated to HACS -> Frontend -> Clicked the + at the bottom, then added Mini Graph Card. I once again restarted Home Assistant. I did have an issue where the card would not load the first time so I uninstalled the card, restarted HA, reinstalled the card, restarted HA, then it just worked. I did have a lot of issues getting this card to work over the past couple of months, so I did a completely fresh install of HA and everything else, not importing any of my old data from previous installs. So, in essence I had to start over, but at least it's working now...

Mini Card config[2]
---------------------
The following resource is defined:
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js (this is the default when installed through HACS)

Navigating to http://10.10.0.65:8123/hacsfiles/mini-graph-card/mini-graph-card-bundle.js shows the javascript code

Sample sensor config (very simple)
---------------------
type: 'custom:mini-graph-card'
entities:
  - sensor.attic_temperature
align_icon: left
align_state: center


[1] https://hacs.xyz/ I installed in the terminal in HA using wget, just easier to me
[2] https://github.com/kalkih/mini-graph-card using the HACS Recommended Install

**Comment by kalkih** [comment]
Hello, late reply sorry, Is this still an isse?

**Comment by frankyhun** [comment]
Hello, yes, same issue here. 

Currently Lovelace shows a reminder if i want to add the resource via the yaml, that the resources have to be added at:
`https://<HA>/config/lovelace/resources`

The HACS installer adds it automaticall as a JavaScript module, with the URL:
`/hacsfiles/mini-graph-card/mini-graph-card-bundle.js`

The js file gets installed at:
`/config/www/community/mini-graph-card/mini-graph-card-bundle.js`

So it is available via a browser at:
`https://<HA>/local/community/mini-graph-card/mini-graph-card-bundle.js`

But the UI shows the error:
No card type configured
- type: 'custom:mini-graph-card'

**Comment by kalkih** [comment]
I believe `/hacsfiles` should point to `/config/www/community`, so that shouldn't be an issue.

If you get `No card type configured` That's most likely because you have a dash (`-`) in front of `type`, when using the UI editor it will add a dash in the root config behind the scenes.

**Comment by frankyhun** [comment]
Removing the - fixed the issue. Thank you!

Maybe the examples in the readme should be changed.

**Comment by kalkih** [comment]
Yes, should maybe change the formatting.
They were made for YAML users initially (well, they were written even before the UI editor was a thing) but more and more users are now using the UI.

**Comment by KireStreve** [comment]
Still dont work for me. I uninstall and install de mini graph in HACS but even work. Even i put the follow in de YAML file form de Lovelance
`url: /www/community/mini-graph-card/mini-graph-card-bundle.js
type: module`

**Comment by vaanja** [comment]
My working setup is like this:
configuration.yaml :
lovelace:
  resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module

and Configuration / Lovelance Dashboards / Resources:
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js

**Comment by tlsJP** [comment]
vaanja's setup is how I got mine working:

**configuration.yaml**
`
lovelace:
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
`

I do also have it configured in the UI under Configuration > Lovelace Dashboards > Resources

**Comment by donparlor** [comment]
> > vaanja's setup is how I got mine working:
> > **configuration.yaml**
> > ```
> > lovelace:
> >   resources:
> >     - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
> >       type: module
> > ```
> 
> _Thank you!!!_ Amazing how many different topics don’t mention that it **needs to go into configuration.yaml** under lovelace. Banging my head for far too long.

I confirm, I couldn't set things correctly without adding it into configuration.yaml under lovelace.
The HACS integration should integrate it automatically.
