### ISSUE TITLE
[Feature Request] color_thresholds per axis (primary, secondary)

### ISSUE THREAD

**Issue by cfuerst** [kalkih/mini-graph-card#475]
Hi There 👋 many thanks for this card, simply amazing!

How about the possibility of having color_threshold values which are exclusive per axis?
Currently, I see no option to have axis exclusive colours for both the primary and secondary axis.
(Especially problematic if the values could be in a similar range e.g. temperature C and moisture %)

Cheers

may be a duplicate of: https://github.com/kalkih/mini-graph-card/issues/141

**Comment by kalkih** [comment]
Hello, thank you, glad you like it!
I'm closing this since as you mentioned it's the same request as #141 #153
