### ISSUE TITLE
Empty block instead of widget (Not always)

### ISSUE THREAD

**Issue by yadenisenko** [kalkih/mini-graph-card#476]
Hello,
Sometimes the widget is not displayed and there is an empty block in its place and there are no errors in the chrome console.
But when I open the lovelace edit, the widgets appear immediately. It seems to me that the problem arises when I open the home assistant in my smartphone. I also did testing in google chrome on a PC using imitation display as on a mobile device and then the problem also appears.
The problem also occurs with the simple widget from the example: 
- type: custom:mini-graph-card
  entities:
   - sensor.temperature

Home Assistant 0.116.2,  docker_version | 19.03.13, Debian GNU/Linux 10 (buster)

![1](https://user-images.githubusercontent.com/15608867/96502332-4e015980-125a-11eb-9620-5ce7a3b4959f.jpg)
<br>
![2](https://user-images.githubusercontent.com/15608867/96502334-4f328680-125a-11eb-8744-578abde24a2a.jpg)
<br>
![3](https://user-images.githubusercontent.com/15608867/96502335-4f328680-125a-11eb-9eb7-c9136f4984d9.jpg)
<br>
![4](https://user-images.githubusercontent.com/15608867/96502336-4fcb1d00-125a-11eb-9f5c-c890f25b14f7.jpg)

**Comment by JackTalisker** [comment]
I have quite the same issue.
I don't have empty blocks but the cards simply disappear if I start HA with my custom dashboard or I refresh it. 
If I change view with anything else (e.g. settings or default auto dashboard) and then I return to my custom dashboard, the cards appear again (then if I refresh the page the cards disappear again).
This behaviour occurs either in a PC with google chrome or with the android app.
HA 0.116.4 Core on a Raspbian Buster RPi 3/ Python 3.8.6

**Comment by mateuszlukasik-PL** [comment]
Same issue like Jack wrote (HA Core 0.116.4, Debian buster, python 3.7). Three was no problem on 0.115.

**Comment by mmalina** [comment]
It happens to me too. I need to refresh in Safari several times (full reload with Cmd+Option+R) before the card is displayed. I'm on latest full Home Assistant install on RPI 3b+.

**Comment by rchovan** [comment]
Hi, 
I have same behavior on Android device. Widgets are not loaded on app start, but when I click edit on dashboard, they are loaded. After restarting app, they are missing again. https://github.com/home-assistant/android/issues/1107

**Comment by RomRider** [comment]
Is this still happening?

**Comment by rchovan** [comment]
> Is this still happening?

Not for me.

**Comment by yadenisenko** [comment]
problem no longer happens

ср, 20 янв. 2021 г. в 02:18, Jérôme W. <notifications@github.com>:

**Comment by mmalina** [comment]
I can confirm this problem disappeared soon after - maybe early November.

**Comment by RomRider** [comment]
Alright, seems fixed. I'll close it then, thanks :)

**Comment by yadenisenko** [comment]
Yes, after updating the Home Assistant.

ср, 20 янв. 2021 г. в 11:58, Martin Malina <notifications@github.com>:
