### ISSUE TITLE
Rendering issue on Android 7.0

### ISSUE THREAD

**Issue by alexvillehart** [kalkih/mini-graph-card#477]
I'm currently running a wall mounted Galaxy Tab S2 (9.7) running Android 7.0. When viewing from the Home Assistant android application (version 2.5.0-full) and from the browser, the graphs do not want to render properly
![image](https://user-images.githubusercontent.com/9193198/96530951-3e513780-1291-11eb-919f-0afb6a3677ad.png)

After doing some testing, without a fill attribute the graphs render properly inside a browser, but not within the app.

**Comment by Hypfer** [comment]
Most likely caused by an outdated WebView component.

https://play.google.com/store/apps/details?id=com.google.android.webview

Try updating it

**Comment by RomRider** [comment]
Did you manage to fix it by updating webview? If yes, please close the issue

**Comment by RomRider** [comment]
Duplicate of #422
