### ISSUE TITLE
Grouping monthly bar chart 

### ISSUE THREAD

**Issue by linkmaks** [kalkih/mini-graph-card#485]
Hello, is that possible to group bars not only by date, hours etc. but by month or any range of time? I need it to reflect my monthly power usage using bar chart, but I can't find a solution.

**Comment by koldogut** [comment]
+1, same need here

**Comment by danielleteyski** [comment]
+1, It would be a nice option.

**Comment by linkmaks** [comment]
@kalkih Hello, give it a chance, please

**Comment by allacArneo** [comment]
+1, would be very usefull

**Comment by a0024** [comment]
+1,need monthly bar!

**Comment by denveronly** [comment]
+1 to the group

**Comment by Obergangster123** [comment]
+1

**Comment by tbhsm** [comment]
Yes please!

**Comment by ArnoutVerbeken** [comment]
I would welcome this too.  I did not find a way around this for the moment.  I can perfectly show daily usage, but not monthly usage.

**Comment by RomRider** [comment]
Grouping by `month` is complex because each month has a variable number of days and that sucks for the maths 😅

**Comment by DanielBaulig** [comment]
Came here looking for a way to do this since I couldn't for the life of me figure it out. Somewhat relieved to find it's not possible (because that means I might not be a moron after all), but also sad to see that it doesn't appear to be currently possible.

At least in SQL or when mapping over an array of data points, grouping by month shouldn't be hard (you can extract the current month as a number from a timestamp and let the date/time functions deal with figuring out how a timestamp maps to a month).

**Comment by RomRider** [comment]
Well we're waiting for your PR then since it's simple :)

**Comment by DanielBaulig** [comment]
Just spent a couple minutes digging around the code, but it appears to me the main change is to make `_reducer` look at each of the data points timestamps and output them in groups of months.

I understand that there are a couple of other things that need adjusting (e.g. the `hours * points` construct used in various locations needs to be generalized), but it absolutely seems doable. 

It *probably* makes sense to refactor the current hours + points_per_hour abstraction into a more generalized abstraction that can handle months and other non-uniform groups.

If you are willing to take a PR for this I might look into it next weekend.

**Comment by RomRider** [comment]
The grouping is not a problem, the problem is displaying uneven groups. PRs are always welcome :)

**Comment by corke2013** [comment]
+1

**Comment by cvjensen** [comment]
+1

**Comment by JayChun** [comment]
No way to create a monthly 'Group by'  conclusionally?

**Comment by ildar170975** [comment]
> No way to create a monthly 'Group by' conclusionally?

This is an open source project, developers are spending their spare time to create something.
There are many issues in the repo to fix.

**Comment by JayChun** [comment]
> > No way to create a monthly 'Group by' conclusionally?
> 
> This is an open source project, developers are spending their spare time to create something. There are many issues in the repo to fix.
> 
> Besides, this particular issue is CLOSED. That means that it is not supposed to be considered. If you need the "monthly Group by" functionality - then:
> 
> 1. Check if a non-closed issue is present for this functionality.
> 2. If present - then start monitoring it.
> 3. If not  present and this issue is the only one - then ask for reopening it.

Thanks for your comment.
I just wanted to know how it went.
Anyway I decided to go to fluxDB and Grafana, I think it is the second best way.

Thank you,
Jay
