### ISSUE TITLE
Daylight Savings Time change causes display issues for daily bar graph

### ISSUE THREAD

**Issue by brucehvn** [kalkih/mini-graph-card#488]
I'm not sure how this can be fixed, but I have a bar graph that shows the count of something on a daily basis.  The count gets reset to zero every night just after midnight.  When we just recently switched back to standard time from DST, now my graph is showing zero for many days before the time change.

In the database, states are stored in UTC, so before the time change, we were at UTC-7, so the db time for midnight was 07:00:00 and the daily totals get updated at about 12:03 AM.  Now, the db time for midnight is 08:00:00.  When the graph card is getting the entity values, the entries from before the time change were still zero at 08:00 UTC so they get displayed incorrectly.

I'm not sure this is a problem with the graph card itself and I'm going to post on the HA forums as well, but I wonder if maybe there could be a setting as to what time should signify when the day should start for the graph.

**Comment by TobiasKneidl** [comment]
Any update on this?
