### ISSUE TITLE
[Feature Request] Enable ability to configure card from card picker

### ISSUE THREAD

**Issue by TJohnson93** [kalkih/mini-graph-card#493]
Just a user-friendly feature request to enable to the ability to configure this awesome card from the lovelace card picker? Apparently a few lines of code, not sure how realistic the "easiness" is.

https://www.reddit.com/r/homeassistant/comments/jovt1l/usedevelop_custom_cards_your_card_could_be_in_the/?utm_source=share&utm_medium=web2x&context=3

**Comment by dcs8** [comment]
I've done this in [pull 492](https://github.com/kalkih/mini-graph-card/pull/492), it just needs to be accepted and merged in
