### ISSUE TITLE
Problem with average

### ISSUE THREAD

**Issue by SilverWx** [kalkih/mini-graph-card#498]
Hey !

I have problem with average function does not take 0 value into account :

![image](https://user-images.githubusercontent.com/16896194/99915101-d368a580-2d01-11eb-8c13-077c4da1e096.png)

![image](https://user-images.githubusercontent.com/16896194/99915109-ebd8c000-2d01-11eb-96d8-ce57b666334a.png)

**Comment by christoftaylor** [comment]
Just a guess, but it looks like the smoothing is averaging out the peaks to plot an hourly average. Would increasing the `points_per_hour: ` increase the resolution so it takes into account being on and off multiple times within an hour?

**Comment by kalkih** [comment]
Yes, as @christoftaylor suggested the ganularity of the graph is most likely too low, hence you can't see the "fast changes" becuase they are averaged/smoothed out.

Try increasing `points_per_hour`, also check out `smoothing` depending on what result you want.

**Comment by SilverWx** [comment]
Thank you for your answer, I don't want to increase the resolution for displayed graph, I just want hourly average of  consumption, how can I do ?

**Comment by kalkih** [comment]
It should already do that, but if your sensor doesn't record its state in regular intervals and only on changes, the average could be somewhat skewed, please see my answer in https://github.com/kalkih/mini-graph-card/issues/522#issuecomment-752772405, would be for the same reason.

Increasing the resolution will improve the accuracy in your case but I understand that's not always what you want.
