### ISSUE TITLE
Can't add card to Lovelace: "No card type found" - Installed through HACS

### ISSUE THREAD

**Issue by Beastlander** [kalkih/mini-graph-card#500]
Followed the steps in the readme and and installed through HACS. Installed other front end addons through HACS and they have worked well.

My actions:
Cleared cache/tried multiple browsers

As the card type wasn't found I have tried to add the Lovelace resource manually with many different setups:

- /hacsfiles/mini-graph-card/mini-graph-card-bundle.js

- /local/community/mini-graph-card/mini-graph-card-bundle.js

Also moved it to www-folder and added:

- /local/mini-graph-card-bundle.js

But to no avail.. Still can't seem to add it to lovelace.

I have "_default_config_:" added to my config so the latest JavaScript should be enabled.
Additional info:

**Home Assistant Core Integration**
version: 0.118.4
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
Home Assistant Cloud
relayer_connected: true

**Home Assistant Supervisor**
host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 20.8 GB
disk_used: 7.9 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok

Please help :)

**Comment by Beastlander** [comment]
Copied lovelace card code from installation but should be without dash prior to type. So tester following setup and it worked:

type: 'custom:mini-graph-card'
entities:
  - sensor.temperature_12
align_icon: left
align_state: center

**Comment by zvoniimiir** [comment]
![chrome_66baFGHtXc](https://user-images.githubusercontent.com/23482061/100997378-78814a80-355a-11eb-9d78-31181b9e5050.png)

To anyone else having issues, this is the correct formatting (pay attention to indentation).

**Comment by Beastlander** [comment]
Yeah, and this is the correct syntac for using them in a stack:
type: horizontal-stack
cards:
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.vardagsrum_temperature
    line_color: '#adce74'
    name: Nere
    line_width: 16
    font_size: 100
    font_size_header: 12
    hour24: true
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.plan_2_brandslackare_temperature
    line_color: '#839b97'
    line_width: 16
    name: Uppe
    font_size: 100
    font_size_header: 12
    hour24: true
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.temperature_22
    line_color: '#e6d5b8'
    name: Bibliotek
    line_width: 16
    font_size: 100
    font_size_header: 12
    hour24: true


![image](https://user-images.githubusercontent.com/73158958/100999012-8506a280-355c-11eb-8318-30e5f6f22965.png)
