### ISSUE TITLE
Hi, Why this message? thank

### ISSUE THREAD

**Issue by LaurentMicrotec** [kalkih/mini-graph-card#504]
Hello, where is my mistake?

![Home Assistant](https://user-images.githubusercontent.com/50947256/100655842-1ce17200-334c-11eb-801a-68ca74890278.png)

**Comment by benjgos** [comment]
This won't likely fix the issue, but entities needs to be a list: 
entities:
  - entity: sensor.test_sensor

Did you install via HACS or manually?
Did you add the needed entries into the Lovelace resources?

**Comment by LaurentMicrotec** [comment]
Hi, thanks for your reply. The problem comes with the repository. I do install a new one.
Now everything is good.

**Comment by benjgos** [comment]
excellent, happy you're all set now. :)
