### ISSUE TITLE
Ability to control card height?

### ISSUE THREAD

**Issue by Kraechtshammer** [kalkih/mini-graph-card#506]
Hi, I'm wondering about how to control the height of the cards... I have a triple horizontal stack of graphs which have a very compact height. Now I'm trying to add a single graph card below which I want to have the same compact style/height as the others (I have homeassistant on a tablet as Smart Display with very limited space, so I can't really tolerate any taller cards)
I'm thinking the margin between the current value label and the actual graph is really high... maybe add an option so we can control the margin between the max graph value on screen and that label?

**Comment by kalkih** [comment]
Hello,
You can play with the `height` option (will change the height of the graph part of the card), but if you want a symmetrical look, your best bet would be [card-mod](https://github.com/thomasloven/lovelace-card-mod) and manually style the `padding` or `margin` as you suggested.
