### ISSUE TITLE
Feature Request: State in Legend or Name in label

### ISSUE THREAD

**Issue by christoftaylor** [kalkih/mini-graph-card#507]
Turning on `show_state` per entity puts the current value above the graph.

Would it be possible / useful to save some UI real estate by combining the states above the graph and the legend below the graph? Could be either by putting the state value in place of the colored dot in the legend, or by putting the name next to the state above the graph, or both and let the user decide per card which it will be.

![image](https://user-images.githubusercontent.com/19713082/101101067-965fa700-357c-11eb-9c5e-7e47015144b3.png)

**Comment by ildar170975** [comment]
Closed in favour of https://github.com/kalkih/mini-graph-card/issues/679
