### ISSUE TITLE
Feature request: Show message or icon to indicate stale data

### ISSUE THREAD

**Issue by bob-u** [kalkih/mini-graph-card#510]
My card is displaying 5 states with 2 minute resolution, 15 sec update interval.  When I switch to the page with the graph it takes some time for it to update with current data.  

It would be nice if there was a label shown when it is updating or when it was last updated.

EDIT: delay in update happens with cache: false as well.

**Comment by ildar170975** [comment]
Seems to be the same: https://github.com/kalkih/mini-graph-card/issues/344

**Comment by jlsjonas** [comment]
Duplicate of #344 
@ildar170975 please just close duplicates with a reference, definitely if marked stale ;)

**Comment by ildar170975** [comment]
Jonas, OK!
Since YOU are the Dev here, I just proposed the final decision for you.
