### ISSUE TITLE
Variables in Card Options not working?

### ISSUE THREAD

**Issue by Fettkeewl** [kalkih/mini-graph-card#512]
Hi,
Thanks for a really nice card 👍 
Please refer to the image

I can use variables to change the color on the lines but cant use variables in Card Options?
Intended or bug? I have many graphs that should be similar and that I would like to
refer to variables in themes when it comes to appearance,.

If (issue = intended) please see this as a feature request
if (issue = bug) please fix
if (issue = I'm stupid) please advise as how to fix, I've tried using string variables aswell

![image](https://user-images.githubusercontent.com/25577040/102005827-49b66180-3d1c-11eb-84a6-29fcd419edb1.png)

**Comment by kalkih** [comment]
Hey,
I understand what you're trying to achieve but this is not possible with CSS variables.
CSS variables can't be used to set values that has to be exposed and executed on in JavaScript, (the logic of the card).

And by default there are no variables available for use in Lovelace (would be cool though).

Check out https://github.com/custom-cards/decluttering-card, could possibly be useful for this.
