### ISSUE TITLE
could not get them work

### ISSUE THREAD

**Issue by jjdave2002** [kalkih/mini-graph-card#513]
tried several time, also included the configuration.yaml following:

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.9.4
    type: module

but still get error when adding a manually card:
No card type found
- type: 'custom:mini-graph-card'
  entities:
    - sensor.mobile_akkufullstand

So, how to solve this? thank you! JJ

**Comment by Gio-dot** [comment]
Ok, you have to write type at the end of the card configuration, in this way
![Screenshot_20201213-215711_Home Assistant](https://user-images.githubusercontent.com/55327160/102023830-54a9da00-3d8e-11eb-8a19-d66e8ddf4f6e.jpg)

**Comment by jjdave2020** [comment]
thank you, but what's the difference to what I wrote? can't see any difference. Thank you for your help - JJ

**Comment by Gio-dot** [comment]
> thank you, but what's the difference to what I wrote? can't see any difference. Thank you for your help - JJ

You wrote type at the top of card configuration. You have to wrote it at the end.

**Comment by jjdave2002** [comment]
GREAT - thank you so much, it looks it works now!
