### ISSUE TITLE
Feature request: Add gridlines

### ISSUE THREAD

**Issue by stevearmitage** [kalkih/mini-graph-card#514]
I love this card for showing comparative information - thank you so much for your time creating it!

I have a graph that shows the solar provision, grid consumption and energy used.
The graph shows from -5 to +5 (kW)

<img width="463" alt="Screenshot 2020-12-14 at 11 55 05" src="https://user-images.githubusercontent.com/29444933/102038828-3a5e1380-3e03-11eb-8a79-119c2bcb12ab.png">

**1. horizontal lines**
I'd like to add a gridline at zero to see how far above and below this line the other graph lines are.

It could also be useful to have lines at other intervals - e.g. every one vertical unit - or every 1000 if I was using watts.

**2. Vertical lines**
It would also be useful to see the vertical lines on the graph for every n hours - e.g. every 6 house to show the blocks of the day - possibly starting at the nearest 6 hours point in a 24 hour cycle. This is possibly a little more tricky - choosing when to display the first check mark.

Thanks,
Steve

**Comment by stevearmitage** [comment]
now i submitted, i found this as point #2 of https://github.com/kalkih/mini-graph-card/issues/21

**Comment by ivanpavlina** [comment]
Create few dummy sensors and set them to values you want shown on graph, 0, 1000, ...
Then just display on graph's secondary axis.

**Comment by kalkih** [comment]
Thanks for the request, closing in favor for https://github.com/kalkih/mini-graph-card/issues/21
