### ISSUE TITLE
line_color and themes variables

### ISSUE THREAD

**Issue by MapoDan** [kalkih/mini-graph-card#516]
Ciao,

I'm using this card since long time. Now I was trying to use a custom theme that use custom variables (like '--orange') so to not change theme but have a set of colors for all the cards.
I noticed that your card is managing only default var (like '--primary-color') but not the custom ones..

Thanks if you can fix it
Ciao
Daniele

**Comment by marcelodavanzo** [comment]
Please add this. The add-on seems to have trouble dealing with CSS variables referencing colors from the themes file.

**Comment by kalkih** [comment]
Hello,
Great idea, we should add a few pre-defined css variables for line colors that the card will default to if specified in the user theme.
Did i understand your request correctly?
Custom theme variables can be used already by referencing the color variable e.g. `var(--accent-color)`

**Comment by marcelodavanzo** [comment]
That would be a great solution! I have had trouble using multiple data points each having its own colour variable. Or the same data point but with color thresholds using different variables for colors. In both cases I just get black and the variables seem to be ignored.

**Comment by kalkih** [comment]
The color threshold option is and would still not be compatible with CSS variables however, because of technical limitations, see https://github.com/kalkih/mini-graph-card/issues/520

**Comment by RomRider** [comment]
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.
