### ISSUE TITLE
Battery icon, like color_thresholds

### ISSUE THREAD

**Issue by tpbillund** [kalkih/mini-graph-card#518]
Hi
First great work...
I have a ZigBee device and it works :-) with this code:
`                      - type: 'custom:mini-graph-card'
                        entities:
                          - sensor.stue_temperature
                        name: Temperatur Stue
                        line_color: blue
                        line_width: 8
                        font_size: 75
                        hour24: true
                        show:
                          extrema: true
                          icon: true
                          name: true
                          state: true
                          labels: true
                          points: false
                        color_thresholds:
                          - value: 20
                            color: '#f39c12'
                          - value: 21
                            color: '#d35400'
                          - value: 22
                            color: '#c0392b'
`
I know i can add an extra entities to the card and I know the name of it, but how can I add an extra entities "sensor.stue_battery" as an "battery icon" in the corner, so it show the icon as a FULL-battery, HALF-Battery or LOW-Battery icon (As color_thresholds) depending on the "sensor.stue_battery" value >80 = FULL, <80->40 = HALF and <30 = LOW Battery icon?

**Comment by kalkih** [comment]
Hello and thank you!

This is probably nothing that will be integrated into the card.
It's a cool idea and I've seen in been done before with the help of [config-template-card](https://github.com/iantrich/config-template-card), by templating the icon with a few conditions.
