### ISSUE TITLE
Threshold colors not correctly shown on iphone when 2 graphs on a page

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-graph-card#52]
On my iPhone with the HA app, the threshold colors of the graph 1 get the colors of graph 2. Where on my desktop PC the colors are shown correctly.

This is the screenshot from my desktop:
![mini-graph-card](https://user-images.githubusercontent.com/11230573/52817654-c6d30a00-30a4-11e9-9724-6e0d8953b314.jpg)

And from my phone:
![mini-graph-card-iphone](https://user-images.githubusercontent.com/11230573/52817668-cfc3db80-30a4-11e9-9455-f20437d331fa.jpg)

As you can see the dots show the correct colors, just the line isn't.

The card is now in a horizontal-stack, but when I remove them from that stack it still shows the same colors.
Graph 1 does show the correct colors when I remove graph 2 from the view.

Any ideas if this can be fixed?

**Comment by kalkih** [comment]
Thanks, could reproduce it in Safari.
Conflicting references in the SVG elements (the gradients) most likely.

**Comment by kalkih** [comment]
Found the issue (I think), should be resolved in the next release!

**Comment by kalkih** [comment]
New release [v0.3.0](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.0) now available with a fix for this.

**Comment by nardev** [comment]
@gerard33  could you please share the code for that card, i can't figure out at once how to make that min max temps on the card? thnx

**Comment by gerard33** [comment]
@nardev you can use `extrema: true` for that -> https://github.com/kalkih/mini-graph-card#available-show-options

**Comment by nardev** [comment]
> @nardev you can use `extrema: true` for that -> https://github.com/kalkih/mini-graph-card#available-show-options

ou, thnx, i confused it with aggregation .. completely was lost at first sight. Thnx.
