### ISSUE TITLE
Color thresholds don't work

### ISSUE THREAD

**Issue by andymarden** [kalkih/mini-graph-card#520]
When I set these, I just get a black or dark red line. The threshold's don't vary the color (although they do change the color of the lines). Tried removing theme from view and only having one sensor - but still the same:

type: 'custom:mini-graph-card'
name: Temperature
show:
  labels: true
entities:
  - entity: sensor.temperature_158d000358bb29
    name: Room
  - entity: sensor.living_room_temperature
    name: Tado
color_thresholds:
  - value: 0
    color: blue
  - value: 19
    color: orange
  - value: 21
    color: red

**Comment by kalkih** [comment]
Hello, dynamic color thresholds requires colors specified in 6-digit hex format to work correctly, see https://github.com/kalkih/mini-graph-card/issues/236, this is because we need to interpolate the colors at the edges of the visible scale.
