### ISSUE TITLE
info about customisation transparent background

### ISSUE THREAD

**Issue by pilot1981** [kalkih/mini-graph-card#524]
Hi,
I'm using in my card your components in this way: 

`
- type: 'custom:mini-graph-card'
    entities:
      - sensor.watt_lavatrice
    style:
      '--paper-card-background-color': 'rgba(0, 0, 0, 0.0)'
      top: 60%
      left: 70%
      width: 50%
    hours_to_show: 4
    icon: 'mdi:flash'
    name: Potenza
    font_size: 2
    unit: W
    hour24: true
    points_per_hour: 60
    show:
      icon_adaptive_color: true
      name_adaptive_color: true
      name: true
      icon: true
      state: false
      fill: fade
      points: false
      extrema: true
      labels: hover
`
and this is the result:

<img width="326" alt="Schermata 2020-12-31 alle 08 49 09" src="https://user-images.githubusercontent.com/46350465/103400368-1dd11380-4b45-11eb-8e40-93f448051c4b.png">

but I would obtain this result:

![device_lavatrice](https://user-images.githubusercontent.com/46350465/103400394-32151080-4b45-11eb-9c76-96f8c345b04e.png)

where I would have section of "Potenza" in trasparent mode (I would use image in background) and I would section "Potenza" to be lower (now it overlapping with the bar on the bottom and label on the top).

regards

**Comment by pilot1981** [comment]
any ideas?

**Comment by pilot1981** [comment]
thanks, but it seems to be not compatibile with other config...

this is my new config:

`  - type: 'custom:mini-graph-card'
    entities:
      - sensor.watt_lavatrice
    style: |
      ha-card {
        background: transparent;
      }
      '--paper-card-background-color': 'rgba(0, 0, 0, 0.0)'
      box-shadow: 0px 0px 2px 1px
      top: 55%
      left: 70%
      width: 50%
      height: 50%
    hours_to_show: 4
    icon: 'mdi:flash'
    name: Potenza
    font_size: 2
    unit: W
    hour24: true
    points_per_hour: 60
    show:
      icon_adaptive_color: true
      name_adaptive_color: true
      name: true
      icon: true
      state: false
      fill: fade
      points: false
      extrema: true
      labels: hover
`

and this is the result:

![Schermata 2021-01-05 alle 17 51 23](https://user-images.githubusercontent.com/46350465/103674102-a5bc8080-4f7e-11eb-81ae-dc2e6f2e82dd.png)

**Comment by pilot1981** [comment]
sorry, I tried again...it could be better...:-)

**Comment by kalkih** [comment]
What about this:
```yaml
style: |
  ha-card {
    background: transparent;
  }
  :host {
    '--paper-card-background-color': 'rgba(0, 0, 0, 0.0)';
    box-shadow: 0px 0px 2px 1px;
    top: 55%;
    left: 70%;
    width: 50%;
    height: 50%;
  }
```

**Comment by pilot1981** [comment]
great! it works!!!

thanks very much for your help and your job!!!!


happy new year!!!!

**Comment by kalkih** [comment]
Great!
Thank you and happy new year to you as well 🎉
