### ISSUE TITLE
color_thresholds render incorectly with logaritmic on

### ISSUE THREAD

**Issue by richie-svk** [kalkih/mini-graph-card#531]
the color thresholds render incorrectly for logaritmic graph. The points color correctly, but the graph line not.

**Comment by RomRider** [comment]
Please share your config

**Comment by richie-svk** [comment]
Hello Jerome,

This is my current code:
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.solar
    name: Sunshine
    show_graph: false
  - entity: sensor.log_lux
aggregate_func: max
show:
  name: false
  state: true
  icon: true
  points: false
  labels: false
  icon_adaptive_color: true
hours_to_show: 48
cache: false
logarithmic: true
smoothing: true
points_per_hour: 3
font_size: 60
font_size_header: 10
align_state: right
color_thresholds:
  - value: 4.6
    color: '#040d69'
  - value: 5.3
    color: '#942500'
  - value: 6.9
    color: '#ebae3f'
  - value: 8
    color: '#e6f4fc'
  - value: 11
    color: '#59c3ff'
  - value: 60
    color: '#040d69'
  - value: 200
    color: '#942500'
  - value: 1000
    color: '#ebae3f'
  - value: 3000
    color: '#e6f4fc'
  - value: 60000
    color: '#59c3ff'


with the following output (this is desired outcome) - achieved via custom
logarithmic sensor, but not using the logarithmic function of the graph:
[image: image.png]

if I change it to using the logarithmic function:
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.solar
    name: Sunshine
    logarithmic: true
aggregate_func: max
show:
  name: false
  state: true
  icon: true
  points: true
  labels: false
  icon_adaptive_color: true
hours_to_show: 48
cache: false
logarithmic: true
smoothing: true
points_per_hour: 3
font_size: 60
font_size_header: 10
align_state: right
color_thresholds:
  - value: 60
    color: '#040d69'
  - value: 200
    color: '#942500'
  - value: 1000
    color: '#ebae3f'
  - value: 3000
    color: '#e6f4fc'
  - value: 60000
    color: '#59c3ff'

i get the following output:
[image: image.png]
also the points have correct coloring, the line not:
[image: image.png]

I hope this helps. all the best.
Richard.
