### ISSUE TITLE
Feature request: Only plot known data points

### ISSUE THREAD

**Issue by Jaxon77** [kalkih/mini-graph-card#538]
Hi,

is there any way to display binary sensors like in the picture below without having to set 60 points per hour?
There sould be only one data-point per change resulting in a completely vertical line from 0 to 1.
![image](https://user-images.githubusercontent.com/30999568/104856724-aa851b00-5914-11eb-93ec-19146a7f86bd.png)

It's working on the home assistant history graph:
![image](https://user-images.githubusercontent.com/30999568/104856815-dc967d00-5914-11eb-971d-bb2c3b94c977.png)

**Comment by kalkih** [comment]
No, that's not possible, the graph implementation is based on the moving average and static time intervals.
So the only way to achieve a similar look is to increase the granularity (points_per_hour), like you've done. Can also turn the `smoothing` setting off.

**Comment by Jaxon77** [comment]
Thank you for the info. Any chance to have a feature request for that?

**Comment by kalkih** [comment]
Yes 👍🏼

**Comment by RomRider** [comment]
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.

**Comment by ildar170975** [comment]
Closed in favour of https://github.com/kalkih/mini-graph-card/issues/366
