### ISSUE TITLE
Graph div in square sized card

### ISSUE THREAD

**Issue by ee02217** [kalkih/mini-graph-card#539]
I am opening this as a feature request/enhancement.
It would be great to have the graph area correctly dimensioned when using inside a grid with square cards.
Currently it create a considerable void between the sensor value and the top part of the graph.

**Comment by maxwroc** [comment]
Can you please paste some screenshot showing up the problem?

**Comment by ee02217** [comment]
Hi! 
Sure, please find the screenshot and a sample config:
![image](https://user-images.githubusercontent.com/60232595/105557560-7179eb80-5d04-11eb-9a93-c559743c07b2.png)


Config:
`views:
  - badges: []
    cards:
      - cards:
        - type: grid
          square: false
          columns: 4
          cards:
......

            - align_state: left
              hours_to_show: 24
              points_per_hour: 12  
              hour24: true          
              decimals: 1
              entities:
                - entity: sensor.sensor_quarto
                  name: Bedroom
                  unit: °C
              height: 200
              #font_size: 60
              lower_bound_secondary: 0
              line_width: 5
              show:
                extrema: false
                fill: fade
                icon: true
                labels: true
                labels_secondary: false
                name: true
              type: 'custom:mini-graph-card'
......
`
