### ISSUE TITLE
fill color using color_thresholds

### ISSUE THREAD

**Issue by WhistleMaster** [kalkih/mini-graph-card#54]
I'm using color_thresholds to display different colors based on values but I'm wondering if the fill color shouldn't be the same color ?

<img width="510" alt="screenshot 2019-02-15 at 23 04 31" src="https://user-images.githubusercontent.com/1544568/52886913-3238dc80-3176-11e9-98fe-d010d23b95c5.png">

**Comment by kalkih** [comment]
Need more information, please post the card config.
Which browser are you using?

**Comment by kalkih** [comment]
Think I found the issue, should be resolved in the next version.

**Comment by kalkih** [comment]
New release [v0.3.0](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.0) now available with a fix for this.
