### ISSUE TITLE
feature request: display current value under the entity name

### ISSUE THREAD

**Issue by anubisg1** [kalkih/mini-graph-card#547]
As per title, i'd like to request a feature so that the below picture would be supported

![image](https://user-images.githubusercontent.com/4518931/105367975-52466580-5c01-11eb-8650-a9a21f1b3002.png)

**Comment by anubisg1** [comment]
it would be likely using show_state, just not as invasive :)

**Comment by RomRider** [comment]
Duplicate of #507
