### ISSUE TITLE
Fill with gradient

### ISSUE THREAD

**Issue by mReXiTuS** [kalkih/mini-graph-card#549]
Hey, 

Your component is cool and works well for me. I just wanted to request new feature: 

**Fill with gradient.** Going from 100% opacity to 0% opacity at the bottom. That would be cool and it will look perfect.

I was trying to achieve it with custom CSS but with no luck.

Thanks

**Comment by RoboMagus** [comment]
Having more configuration on this type of styling would be nice to have (custom defined gradient ranges and all that), but have you looked at the fill: fade option?
Sounds similar to what you'd like and looks really good in my setup ;)

**Comment by RomRider** [comment]
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.
