### ISSUE TITLE
Total solarpower production

### ISSUE THREAD

**Issue by wolfhond** [kalkih/mini-graph-card#551]
I see now  the solarpower production on the moment.
Is there a way to have a total of the graphic?

**Comment by RomRider** [comment]
No, that is not a possibility at the moment. However, you could use a [history_stats sensor](https://www.home-assistant.io/integrations/history_stats/) to achieve what you want

**Comment by wolfhond** [comment]
Thanks
But I Can show It with my card for the solar panels. But It would be Nice to see It in the graphic too

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________
