### ISSUE TITLE
Bar chart with custom time periods

### ISSUE THREAD

**Issue by wasyl00** [kalkih/mini-graph-card#552]
I have a counter which resets everyday at noon and cannot have it to reset at midnight. Is there a way to build a bar chart which have 24 hour periods but which run from noon to noon instead from midnight to midnight? 
I noticed that values are not counted after midnight in the current form I have. Thanks

`
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.daily_wheel_turns
name: Wheel spins/day
hours_to_show: 168
aggregate_func: max
group_by: date
unit: spins/day
show:
  graph: bar
  icon: false
`

**Comment by RomRider** [comment]
That's not possible with mini-graph-card but possible with https://github.com/RomRider/apexcharts-card
