### ISSUE TITLE
Uptime sensor showing incomplete state

### ISSUE THREAD

**Issue by backslashV** [kalkih/mini-graph-card#554]
Hi,
I have a template sensor showing the uptime in the form of hours:minutes. When I put it in a mini-graph-card, it shows the first digit of the hour as the state value. For example, if uptime is 02:00, it shows 2. How can I get it to show the correct state?

![image](https://user-images.githubusercontent.com/8752221/106693343-1c06cf80-658b-11eb-8bde-150558c34285.png)

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.uptime_parsed
    show_graph: false

**Comment by RomRider** [comment]
It's not a numerical sensor, so that is expected. Convert it using a template sensor and use that one instead.

**Comment by backslashV** [comment]
> It's not a numerical sensor, so that is expected. Convert it using a template sensor and use that one instead.

How would I convert it while keeping the time format?

**Comment by RomRider** [comment]
You can't it has to be a number, you'd have to decide how you want to display it (days, hours, etc...) and convert it in the template sensor.

**Comment by backslashV** [comment]
ok, thanks.
