### ISSUE TITLE
[Request] Vertical separators

### ISSUE THREAD

**Issue by lordraiden** [kalkih/mini-graph-card#557]
Could you please add vertical separators or some kind of signal configurable every X hours?
For example in a chart showing more than 1 day of data it would be extremly useful visually to see when each day ends, so you can visually compare the data blocks made by the separation.

Some kind of soft vertical line in the backgroud

**Comment by RomRider** [comment]
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.

**Comment by lordraiden** [comment]
> 
> 
> Thanks for this feature request.
> 
> This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
> This card is probably going to stay in maintenance mode, so no new features will be added in the future.

https://github.com/RomRider/apexcharts-card#simple-graph

what the the function that allow to have vertical separators? I can't find it

**Comment by RomRider** [comment]
Please post your questions on the forum in the apexcharts thread.
This is the feature: https://apexcharts.com/docs/options/grid/
