### ISSUE TITLE
Custom date format

### ISSUE THREAD

**Issue by tgulholm** [kalkih/mini-graph-card#561]
It would be nice to be able to specify a custom date/time format (using the standard date-time formatting) for displaying the extrema and state values.
E.g. for a graph grouped by date and showing data for a month (or more) I would make more sense for me to see the month and not the the time. 
![billede](https://user-images.githubusercontent.com/8114366/107741212-058c1100-6d0d-11eb-8b4f-28c3ae9b2dc2.png)
And just because it is fairly easy (I think), why not make it possible to specify different formats for state and extrema values and just fall back to default if not specified.
Keep up the great work!

**Comment by zeratax** [comment]
still very much interested in this!

edit: i guess this is a duplicate of https://github.com/kalkih/mini-graph-card/issues/1102
