### ISSUE TITLE
Feature request: state_secondary

### ISSUE THREAD

**Issue by Fettkeewl** [kalkih/mini-graph-card#562]
If possible
Would be neat with a state_secondary card option :)

I'd say temp and humidity is the most common combination to show together
due to the way sensors are created.

![image](https://user-images.githubusercontent.com/25577040/107844008-32552c80-6dd0-11eb-997b-52c0918a26a0.png)

**Comment by gazpachoking** [comment]
I believe this is already possible.
![image](https://user-images.githubusercontent.com/187133/108407725-1b5c7300-71f2-11eb-821f-61f17cac4313.png)

**Comment by Fettkeewl** [comment]
Ah my bad, thanks for showing me how it's done :)
