### ISSUE TITLE
[Feature Request] Dynamic Extreme/State 

### ISSUE THREAD

**Issue by peter-dolkens** [kalkih/mini-graph-card#566]
Just playing around with concepts for more compact state/extrema displays, and I came up with this idea - feel free to shoot it down.

Effectively, the card would have 2 forms, one that displayed a Min + Current state, and one that displayed Max + Current state.

The logic would work as follows:

If `current state` is above `average state` then display `min state` + `current state`

![image](https://user-images.githubusercontent.com/469666/108244739-6e2d2080-7147-11eb-9978-ef26bf16a3a4.png)

If `current state` is below `average state` then display `current state` + `max state`

![image](https://user-images.githubusercontent.com/469666/108147774-6d54aa00-70c7-11eb-8f72-16712f10a437.png)

**Comment by peter-dolkens** [comment]
In case it wasn't clear in my original idea, the state I was referring to were the labels on the chart

**Comment by jlsjonas** [comment]
This feels like quite a niche feature.
You could accomplish most of what you want using
```
show:
  - labels: true
```
Let me know if that helps
