### ISSUE TITLE
[Feature request] Group by hour number

### ISSUE THREAD

**Issue by ChrisMD123** [kalkih/mini-graph-card#572]
| Day 1 | Day 2 | Day 3 |   | Min | Avg | Max
-- | -- | -- | -- | -- | -- | -- | --
0:00 | 65 | 72 | 73 |   | 65 | 70 | 73
1:00 | 64 | 71 | 70 |   | 64 | 68.33333 | 71
2:00 | 63 | 69 | 67 |   | 63 | 66.33333 | 69
3:00 | 60 | 69 | 65 |   | 60 | 64.66667 | 69
4:00 | 60 | 69 | 63 |   | 60 | 64 | 69
5:00 | 60 | 66 | 61 |   | 60 | 62.33333 | 66
6:00 | 59 | 65 | 61 |   | 59 | 61.66667 | 65
7:00 | 56 | 63 | 58 |   | 56 | 59 | 63
8:00 | 57 | 65 | 58 |   | 57 | 60 | 65
9:00 | 57 | 67 | 61 |   | 57 | 61.66667 | 67
10:00 | 59 | 67 | 64 |   | 59 | 63.33333 | 67
11:00 | 62 | 70 | 66 |   | 62 | 66 | 70
12:00 | 64 | 72 | 67 |   | 64 | 67.66667 | 72
13:00 | 67 | 72 | 69 |   | 67 | 69.33333 | 72
14:00 | 68 | 72 | 69 |   | 68 | 69.66667 | 72
15:00 | 68 | 72 | 69 |   | 68 | 69.66667 | 72
16:00 | 70 | 72 | 69 |   | 69 | 70.33333 | 72
17:00 | 70 | 73 | 70 |   | 70 | 71 | 73
18:00 | 71 | 75 | 70 |   | 70 | 72 | 75
19:00 | 69 | 73 | 68 |   | 68 | 70 | 73
20:00 | 68 | 73 | 67 |   | 67 | 69.33333 | 73
21:00 | 67 | 73 | 67 |   | 67 | 69 | 73
22:00 | 65 | 72 | 65 |   | 65 | 67.33333 | 72
23:00 | 62 | 72 | 65 |   | 62 | 66.33333 | 72

![image](https://user-images.githubusercontent.com/4922831/109372903-d9ba7080-7860-11eb-8c4f-562897e8a41b.png)

**Comment by ChrisMD123** [comment]
Looks like the text got cut off. Feature request is to be able to aggregate by hour number - i.e., all the hour 0s together; all the hour 1s, hour 2s, etc.

The use case is to be able to see time-of-day trends over time.

**Comment by ChrisMD123** [comment]
Bump

**Comment by jlsjonas** [comment]
How do you see this in practice? How would you configure it f.e.?

**Comment by ChrisMD123** [comment]
It would be functionally identical to the aggregation that occurs on, say, a seven-day basis, but instead of being the average, min, and max per day, it would reflect the average, min, and max in the 0:00 hour for the past seven days.
