### ISSUE TITLE
Support for horizontal bar chart

### ISSUE THREAD

**Issue by fullcavediver** [kalkih/mini-graph-card#574]
Hi kalkih,

is it possible to add support for horizontal bar charts like [history graph](https://www.home-assistant.io/images/lovelace/lovelace_history_graph.png) to your custom card? The original HA history-graph has few options to configure.

Thank you!

**Comment by ildar170975** [comment]
Closed in favour of https://github.com/kalkih/mini-graph-card/issues/473

**Comment by jlsjonas** [comment]
This is related to #693, will be looked at again after the config update
