### ISSUE TITLE
Can't configure Resources nor via GUI, nor in configuration.yaml.

### ISSUE THREAD

**Issue by Masterz69** [kalkih/mini-graph-card#575]
Have UI and YAML dashboards together.

Adding resources to configuration.yaml:
Logger: homeassistant.components.lovelace
Source: components/lovelace/init.py:110
Integration: Lovelace (documentation, issues)
First occurred: 16:56:12 (1 occurrences)
Last logged: 16:56:12

Lovelace is running in storage mode. Define resources via user interface

Trying to access Configuration -> Lovelace Dashboards -> Resources :
![image](https://user-images.githubusercontent.com/15225823/110211348-dea1a480-7e9e-11eb-8191-966dcf8c39ba.png)

Have some clues ?

**Comment by kalkih** [comment]
Hello,
Sorry, I don't think I can help you with this issue, I think you will have better luck getting help by posting ont he official HA forum, since this isn't really related to this specific card but HA in general.
