### ISSUE TITLE
Custom element doesn't exist: mini-graph-card. (on update?)

### ISSUE THREAD

**Issue by Rendeik** [kalkih/mini-graph-card#578]
Hi, with core-2021.3.2 and supervisor-2021.03.4 makes this error.
Custom element doesn't exist: mini-graph-card.

I saw it doesn't work with version 0.10.0 but using 0.9.3 it works.

Is there any way to fix it?
thanks

**Comment by jaddel** [comment]
same here, I installed it via hacs.

Is this supposed to be to point at /null  <---?
![image](https://user-images.githubusercontent.com/46263124/111317396-6ab48880-8664-11eb-9b40-5daba6841fbf.png)

**Comment by pLeXwithFleX** [comment]
The installation from HACS isnt working too for me. Could you get it to work?

![image](https://user-images.githubusercontent.com/34384097/112603444-4d767b80-8e15-11eb-89df-3d86963e8b31.png)

![image](https://user-images.githubusercontent.com/34384097/112603458-5404f300-8e15-11eb-9ae1-d2288341525d.png)

**Comment by wellsyke** [comment]
I have a similar error when trying to add a first mini-graph-card.
Adding "javascript_version: latest" to configuration.yaml doesn't help.

- running HA in a VM on Synology
- core-2021.4.3
- supervisor-2021.03.9
- Home Assistant OS 5.13

![image](https://user-images.githubusercontent.com/81808233/114304524-8d9f5480-9acb-11eb-983f-61ab5679a15d.png)

Adding the resource reference from readme.md to configuration.yaml and checking the configuration under server controls reports the following error: 
Component error: resources - Integration 'resources' not found.  

The installation instructions mention both configuration.yaml and ui-lovelace.yaml
Where should I find ui-lovelace.yaml?

**Comment by mecag** [comment]
Same problem here... Any solution?

**Comment by spikerguy** [comment]
Hello,
I see similar issue on latest HassOS for RPI3
![image](https://user-images.githubusercontent.com/48839029/117494696-5ebab800-af7d-11eb-84ca-41407c1ee51e.png)

Frontend add-on is installed
![image](https://user-images.githubusercontent.com/48839029/117494780-772ad280-af7d-11eb-9f3a-9fa8e02a52ec.png)

Resource is added by the installer itself.
![image](https://user-images.githubusercontent.com/48839029/117494819-87db4880-af7d-11eb-806a-f08c3b9c5043.png)

I checked the file path and added another resource like this 
![image](https://user-images.githubusercontent.com/48839029/117495225-0637ea80-af7e-11eb-90ef-272fa0fe228f.png)

Still the same error.
Did something change in the new update?

**Comment by OmgImAlexis** [comment]
> I have a similar error when trying to add a first mini-graph-card.
> Adding "javascript_version: latest" to configuration.yaml doesn't help.
> 
> * running HA in a VM on Synology
> * core-2021.4.3
> * supervisor-2021.03.9
> * Home Assistant OS 5.13
> 
> ![image](https://user-images.githubusercontent.com/81808233/114304524-8d9f5480-9acb-11eb-983f-61ab5679a15d.png)
> 
> I'm not configuring Lovelace with YAML so I've added the resource reference via Configuration -> Lovelace Dashboards -> Resources Tab

Same issue here, everything was working until last night when I was changing some sensors around in mqtt.

**Comment by jrbecart** [comment]
adding ?v=0.10.0 after bundle.js and running HA in incognito mode worked for me.

**Comment by ferdead** [comment]
I have same problem.. not open the graph "custom element doesnt exist"

**Comment by geidorei** [comment]
Same issue as well - Cannot read property 'length' of undefined / type: custom:mini-graph-card...

**Comment by gfrancesco** [comment]
Same issue here with HA core 2021.11.3, installed via HACS, none of the fixes above seems to work for me.

**Comment by Magnuspp** [comment]
Same for me HA core-2021.11.4, installed via HACS

**Comment by sidlauskaslukas** [comment]
Same issue

**Comment by pagdot** [comment]
This resource path worked for me:

```
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.11.0
```

**Comment by brain-d** [comment]
> This resource path worked for me:
> 
> ```
> /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.11.0
> ```
> 
> If others can confirm it to be working, I'll open a PR to update the documentation

Doesn't work for me.

**Comment by gfrancesco** [comment]
> This resource path worked for me:
> 
> ```
> /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.11.0
> ```
> 
> If others can confirm it to be working, I'll open a PR to update the documentation

Worked for me, before setting the resource I updated HACS and mini-graph-card, not sure what fixed it.

**Comment by jlsjonas** [comment]
Please try clearing your browser cache after updating (or try in incognito mode), there seems to be something off with caching (to be investigated)

**Comment by gfrancesco** [comment]
A bit of additional troubleshoot:
I installed for the first time HACS and mini-graph-card on another HA box and it worked without touching the resources path.
This is the path the was set by the installer:
`/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110`
