### ISSUE TITLE
[Feature request] Ability to set font size of legend

### ISSUE THREAD

**Issue by u8915055** [kalkih/mini-graph-card#579]
Had a request.  I really like the ability to set the font size of the title and state labels.  However, i find that when those are changed, the legend labels become too small to view.  Im assuming there is some sort of multiplier in there for the font size of the legend, but its making the text too small when the graphs are small.

I would like to request a configuration option for the legend text entries.

Thank you.

**Comment by u8915055** [comment]
just to follow up here.. i made the following change and it seems to work well.. not the same as having a configurable item, but gets the job done

In src/style.js

```
346   .graph__legend__item {
347     cursor: pointer;
348     display: flex;
349     min-width: 0;
350     margin: .4em;
351     font-size: 1.75em;  <-- added this
352     align-items: center
353   }
```

**Comment by RomRider** [comment]
You can do that using card-mod. No need to rebuild a specific card for that.

**Comment by ildar170975** [comment]
Using a card-mod: https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1585?u=ildar_gabdullin
See the "Changing font-size" chapter
