### ISSUE TITLE
Custom name replaced by entities name when hover

### ISSUE THREAD

**Issue by septeven** [kalkih/mini-graph-card#58]
Hi, 
When you set up a custom name for the card and then you hover a point, it will show the entities name instead. Hopefully, you see what I'm talking about.

**Comment by kalkih** [comment]
That's by design, to be able to tell which entity you hover over.
I guess it's a bit redundant for graphs containing a single entity through.

For now, you can avoid this by setting the same name in the [entity object](https://github.com/kalkih/mini-graph-card#entities-object).

**Comment by septeven** [comment]
Oh I see, well the name parameter in the entity object is doing the job for me ! Thanks ;)

**Comment by kalkih** [comment]
Not sure if I should change this behavior or not when the graph contains a single entity?
I'll have to think about it 🙂

**Comment by septeven** [comment]
Actually, I think using the entity object is enough for those who wants similar behavior...

**Comment by kalkih** [comment]
Okay, let's keep it as is for the time, thanks for your input.
