### ISSUE TITLE
[Feature request] Set a target / goal

### ISSUE THREAD

**Issue by bramboe** [kalkih/mini-graph-card#581]
I didn't find it so I guess this is a feature request: Would be great to set a horizontal line as a max. target. Like, as an example; If I want to see my power usage per day I might want to keep it under a certain amount? Visualising that would definitely put the output in perspective!

**Comment by ildar170975** [comment]
Same as https://github.com/kalkih/mini-graph-card/issues/570

**Comment by ildar170975** [comment]
Duplicate, closed.
