### ISSUE TITLE
feature request: value_factor should be a property of the entity

### ISSUE THREAD

**Issue by animalillo** [kalkih/mini-graph-card#586]
the value_factor property would be more useful as an enity property, this way you could, for example, show two sensor that have different kind of value data (for example, mg and µg) shown on a graph that makes more sense. 

Or maybe add an option to apply some kind of unit conversion math there?

**Comment by kalkih** [comment]
You should be able to do this by creating a [template sensor](https://www.home-assistant.io/integrations/template/) where you do the needed math operations.
