### ISSUE TITLE
color thresholds per entity

### ISSUE THREAD

**Issue by martijnz43** [kalkih/mini-graph-card#589]
First I would like to say that it is a very nice graph card! I'm sorry if it's not the right location for the post.

Does anybody know if it's possible to use the color_thresholds option per entity when using different entities in one graph?

**Comment by mattbruman** [comment]
I would like to second this question.

**Comment by RomRider** [comment]
Apexcharts-card has this feature if you want to give it a try. 
This card is in maintenance mode and won't get new features.

**Comment by smizles** [comment]
According to this 2019 comment, this should already be possible..? I'm testing now.

https://github.com/kalkih/mini-graph-card/issues/141#issuecomment-524989448

**Comment by jlsjonas** [comment]
Duplicate of #153
