### ISSUE TITLE
where does this char come from?

### ISSUE THREAD

**Issue by realjax** [kalkih/mini-graph-card#590]
I'm getting the chinese (?) char wehere I used to see the Celsius character..  Any idea why that is?
![Screenshot 2021-04-11 at 12 13 30](https://user-images.githubusercontent.com/883435/114300201-5e82e600-9abf-11eb-8b7c-4dc6c0b94739.png)

**Comment by kalkih** [comment]
Most likely the `unit_of_measurement` of your sensor, the card usethe unit of measurement from the sensors `unit_of_measurement` attribute unless a unit is specified in the card config.
