### ISSUE TITLE
Can you please ignore the entity option if it is present?

### ISSUE THREAD

**Issue by danielo515** [kalkih/mini-graph-card#592]
Hello,
This plugin is great, so thanks for it.
I'm trying u use auto-entities to build a grid of graphs. The problem I have is that auto-entities will inject the entity property, and this will fail. Can you please just ignore in instead of failing?
![image](https://user-images.githubusercontent.com/2270425/115156982-4dba0d80-a087-11eb-8091-94db88bb117e.png)

Regards

**Comment by kalkih** [comment]
Sure, we could remove the warning now I guess, the breaking change was made like two years ago now, so should be OK.

**Comment by danielo515** [comment]
Awesome!
I just discovered that providing an empty value on the "template" will result in:
- auto entities not injecting that property
- since it is empty mini-graph-card will not detect it

But I had that feeling because my developer background, others may not have it.
I understand that, when this breaking change was introduced, this was a way to reduce users confusion, but as you said, since that was very long ago it is not necessary anymore.

Thanks for your quick answer by the way
