### ISSUE TITLE
What is default data aggregation method?

### ISSUE THREAD

**Issue by cpohli** [kalkih/mini-graph-card#594]
Hi,

i'm trying to replicate the look of the mini-graph-card in the apex-card.
But the default data aggregation methods seem to be different, so i alway get different looking curves.

So my question is, what is the default (if nothing is specified)? Doesn't seem to be max.
avg also gives different curves. 
And is it grouped by some timeframe or will every entity value change be counted?

Thanks a lot!

**Comment by kalkih** [comment]
Hello, it's the average for the time interval of the data point.
We calculate the rolling average and the intervals which these are based on are calculated based on the current time, unless grouped by hour or date.
The numbers are updated based on value changes yes.

**Comment by cpohli** [comment]
Ah, thank you very much. That clears things up and i'm able to replicate this (almost). :-)
The smoothing of the curves seems to be a bit smoother here in the mini-graph-card though :-)
