### ISSUE TITLE
[Feature request] Start bars at zero instead of lower_bound

### ISSUE THREAD

**Issue by Brazen00** [kalkih/mini-graph-card#595]
It would be great if bars would start at zero and go downwards for negative values, instead of starting at lower_bound, like so:

![image](https://user-images.githubusercontent.com/4339219/116318457-24704e80-a7f8-11eb-9e6e-2d87de4264fe.png)

Even better if negative and positive values could be coloured differently

**Comment by Brazen00** [comment]
Still an issue

**Comment by ildar170975** [comment]
Duplicate of https://github.com/kalkih/mini-graph-card/issues/630
Closed.
