### ISSUE TITLE
Accuracy lets graph disappear

### ISSUE THREAD

**Issue by cicero200272** [kalkih/mini-graph-card#6]
Sometimes graphs disappear when the set accuracy does not fit to the available history data. No matter which accury level I choose, graphs keep disappearing and reappearing.

![screen_mini_graph](https://user-images.githubusercontent.com/15817602/46693644-b8fb0d00-cc0a-11e8-8d5d-16ac695bb1cf.png)

Sometimes setting the accuracy to a higher level brings back the graph, sometimes I must set it to a lower value. After some time, the graph disappears again and reappears some time later.

The underlying sensors update every 2 minutes (temperature derived from a Hue motion sensor).

**Comment by kalkih** [comment]
Hopefully fixed with v0.0.5, you have to also update `mini-graph-lib.js` for this fix.
Let me know if this issue still occur!

**Comment by kalkih** [comment]
Should be resolved, closing this.
