### ISSUE TITLE
Day starts at 4am?

### ISSUE THREAD

**Issue by mhspelt** [kalkih/mini-graph-card#603]
I was getting some weird readings on my chart so I set the aggregate function to _last_ to check if the underlying data was correct. Turns out I get the value from 4:00 this morning, instead of midnight:

```

type: 'custom:mini-graph-card'
entities:
  - entity: sensor.gross_energy_reading
name: Energy usage
group_by: date
hours_to_show: 164
aggregate_func: last
show:
  graph: bar
hour24: true
smoothing: false

```

As you see: the bar shows the last value of 11 May to be 6,082.64:
![image](https://user-images.githubusercontent.com/21200417/117931813-f1ea4980-b2ff-11eb-96b6-e61811204c51.png)

but looking at the sensor data, that seems to be the value at 12 May 4:00:
![image](https://user-images.githubusercontent.com/21200417/117931974-2231e800-b300-11eb-8df5-1226be0c3fdc.png)

The sensor increases monotonously so it cannot also be the value at an earlier time, that should be as in the following screenshot:
![image](https://user-images.githubusercontent.com/21200417/117932103-48578800-b300-11eb-9e95-6d41eba9310c.png)

I see this effect with delta, diff (see my PR), first and last. I am in CET / GMT+02:00 so it seems like a time zone offset applied twice, but I don't know where the problem is exactly or how to fix it.

**Comment by mamartins** [comment]
I'm seeing also an odd behaviour on my graphs group_by where the values do not match what's under the history
