### ISSUE TITLE
Show date when hovering over a data point

### ISSUE THREAD

**Issue by jarrah31** [kalkih/mini-graph-card#61]
Would it be possible to optionally show the date of a particular data point when hovering the mouse over the graph please? Perhaps the date could go on the same line as the time information? 

Maybe it could have an option to customise the date format (MM/DD, or DD/MM/YY, etc) and specify whether before or after the time?

This would be useful when displaying graphs with a timeframe longer than 24hrs.

Thanks.

**Comment by kalkih** [comment]
Yes, and should probably also be enabled and siplayed by default if the timeframe is longer than 24 hours.

**Comment by kalkih** [comment]
Now available in the latest release [v0.3.1](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.1).

There's no option for it though, it's instead displayed by default if the graph timeframe is longer than 24 hours.
