### ISSUE TITLE
[Feature Request] Custom card height without adjust graph

### ISSUE THREAD

**Issue by Perlnx** [kalkih/mini-graph-card#614]
Hello,
I've decrease height option from default to 20 because I have limited space in tablet dashboard.
But result is I got flat graph.

Before
![before](https://user-images.githubusercontent.com/13845123/120474703-b8729e80-c3d2-11eb-8754-e2686bc087f0.JPG)
After (with height: 20)
![after](https://user-images.githubusercontent.com/13845123/120474713-bad4f880-c3d2-11eb-8462-038334031c3f.JPG)

Is it able to decrease card height without adjust graph ?
It's ok if graph overlap with value number.

**Comment by itobey** [comment]
I am also interested in this. Setting the `height` property only scales the card larger even further, we would need the option to adjust the graph level within. Or even just an option to scale the entire card in the height.
