### ISSUE TITLE
Graphs not working starting with Home Assistant 2021.6

### ISSUE THREAD

**Issue by marcobe** [kalkih/mini-graph-card#616]
Not sure if I'm the only one, or maybe the first one reporting this, but my graphs stopped working after the Home Assistant 2021.6 update.

Anybody else having this issue?

**Comment by titobustillo** [comment]
Same issue here. Just upgraded and now system shows  "Custom element not found: mini-graph-card" error message

**Comment by RomRider** [comment]
Did you try to clear your cache?

**Comment by marcobe** [comment]
Tried on different browsers and platforms, and emptied the cache.

**Comment by marcobe** [comment]
Ok figured it out,  I had to add this one to my configuration. For some reason it got removed from my config or changed with this last update (not sure, but looks like it). 

---

The history integration will track everything that is going on within Home Assistant and allows the user to browse through it. It depends on the recorder integration for storing the data and uses the same database setting. If any entities are excluded from being recorded, no history will be available for these entities.

This integration is by default enabled, unless you’ve disabled or removed the default_config: line from your configuration. If that is the case, the following example shows you how to enable this integration manually:

# Basic configuration.yaml entry
history:
