### ISSUE TITLE
Show dimmer value on graph [question]

### ISSUE THREAD

**Issue by gryzli133** [kalkih/mini-graph-card#617]
Is there a way to show Light.Dimmer's value on graph? I'm using Dimmer Objects to show remaining time of my irrigation system in minutes (8 valves). Would be nice to see all 8 values at once on one graph. Did not found how to show percentage value on mini-graph. Thank you in advance!

**Comment by kalkih** [comment]
Hello, only entities from domains `sensor` & `binary_sensor` are currently supported.
You could however create a `template_sensor` entity from the dimmer value and then use that entity in the card.

Or wait for the next release where you should be able use entity attributes in the card config directly, see #564.

**Comment by jlsjonas** [comment]
Attribute support has been added, so you should be able to do this now :tada:
