### ISSUE TITLE
BUG: AVERAGE calculation is wrong. The average always shows just the half of the real figure due to wrong method. UPDATE: Details fully explained

### ISSUE THREAD

**Issue by typxxi** [kalkih/mini-graph-card#618]
Here is my chart 
![image](https://user-images.githubusercontent.com/20662430/122500996-22568f00-cff4-11eb-82a9-c47cd420e3de.png)

The minimum consumption over 7 days can not be calculated as the lowest consumption , but among each of the 7 days maximum.

Then the average can not be true in this case - at least if the maximum of 1,6 kWh is right

In this way these to figures do not make sense.

Finally: if the title is "**electricty usage daily**" and below the most current figure of the day then you should add at least the word "today"!

**Comment by typxxi** [comment]
UPDATE of a more detailed example

We have sunday so the last bar represents sunday or 3/4 of it while being still a bit smaller than the minimum of the week.

![image](https://user-images.githubusercontent.com/20662430/122682105-d6743780-d1f7-11eb-82b8-1ee45b2618dd.png)

Here are the data for each bar from sunday back just to give you an example to follow that something is wrong - in my opinion
kWh
1,120 sunday at 6 pm
1,374 saturday
1,695 friday
1,188 thursday
1,604 wednesday
1,348 tuesday
1,282 monday
9,611 
which would mean an average per day if divided by 7 of **1,373 and NOT 0,710**


How can the average be just 0,710 kWh if every day had value above 1 ? 
Here is a screenshot from the smallest consumption this week, the thursday bar that you can check that the figures are right, cause that bar is shown dark orange :
![image](https://user-images.githubusercontent.com/20662430/122682261-b8f39d80-d1f8-11eb-8359-d1492384c91d.png)

The only possibility to explain it somehow would be a total strange arithmetic to calculate an average for every single day first cause than it would do (0 kWh + 1,282 kWh (saturday) ) / 2 = 0,641 kWh ... 

that would simply devide the figures by 2 and lead to a figure close to 0,710 kWh which is shown right now.

But: we need the whole (sum of each days max of the last 7 days ) / 7 to get the real average consumption.

I hope someone will dig into that cause it was pretty time consuming to get behind all these specialities of this card like the always on dnamic scale which usually starts with the current day as that has the lowest figure of all.   

Is there any chance to get the sum and divide that by what is needed, in this case?

**Comment by manute84** [comment]
I have the same issue with all my graphic cards. Average calculation not working happening what its exposed in the post.

Example: I have a minimum consumption at home in the last month of 3,69 kWh/day and a maximum of 9.71 kWh/day, and the calculation show an average of 3,34 kWh/day with its absolutely incorrect. And Minimum of course it's incorrect too, showing 0 kWh/day.

<img width="316" alt="Captura de pantalla 2021-06-30 a las 16 39 19" src="https://user-images.githubusercontent.com/65078869/123980702-096db680-d9c2-11eb-9a97-778b227bd039.png">

**Comment by guevara777** [comment]
same problem here. The average is right if "group_by" isn't used...example:
![image](https://user-images.githubusercontent.com/29648553/150921191-ea2d5428-cf4b-48c0-b5d4-8c9ebe7dc1c0.png)

if data is "group_by" it doesn't show realistic values (here: "group_by: hour" and "aggregate_func: delta" ...example
![image](https://user-images.githubusercontent.com/29648553/150921013-adf6eb68-4f3f-495a-9595-1e2b113ca098.png)

**Comment by Murgeye** [comment]
Issue is still present.
