### ISSUE TITLE
On click - Open another entity

### ISSUE THREAD

**Issue by Hertizch** [kalkih/mini-graph-card#62]
Not sure if it's possible, but, I would love an option to specify another entity's 'more info' to open when clicking the card. I use these cards on my main dashboard but would like if I click the card, it opens the thermostat for that room.

**Comment by kalkih** [comment]
You can achieve this by using this custom [popup-card](https://github.com/thomasloven/lovelace-popup-card) card.

**Comment by Hertizch** [comment]
Beatiful! ;)
