### ISSUE TITLE
[Feature request] Make Dynamic Color Line option to have different colors for each line on same graph

### ISSUE THREAD

**Issue by Aephir** [kalkih/mini-graph-card#627]
I'd like to request that the [dynamic color line](https://github.com/kalkih/mini-graph-card#dynamic-line-color) option be made so you can have different colors/threshold combination for different lines/series on the same graph.

E.g. a single graph where series1 is red from 0-100, orange from 100-200 and yellow above 200, where series2 is blue from 0-25 and cyan above 25 (so also different number of threshold levels for each series).

**Comment by kalkih** [comment]
Duplicate of #589
