### ISSUE TITLE
After upgrading Home Assistant, history graph color changed

### ISSUE THREAD

**Issue by mkanet** [kalkih/mini-graph-card#632]
I just upgraded to **Home Assistant 2021.7.3**.  Now, all my history graph card color changed mysteriously.  

It used to use `accent-color` from my theme.  Now, it's a different random color.  How do I switch back to using `accent-color` without having to revert Home Assistant to an older version again; or at least change the color to the same color as `accent-color` without adversely affecting anything else in Home Assistant?

**Comment by octaviz** [comment]
It has also happened to me, I think that this repository has not been updated for more than 6 months, there are not many responses from the owners of the repository, let's see if we are lucky!

**Comment by kalkih** [comment]
Sorry, I've not been following the development of HA, do you know if the theme variable for the accent color has changed in Home Assistant and if so; to what?

**Comment by ildar170975** [comment]
> It used to use `accent-color` from my theme

Could you elaborate the meaning of "used" - provide a code for the card with used `accent-color`.
