### ISSUE TITLE
Aggregation functions (min max) return wrong values when grouped by date.

### ISSUE THREAD

**Issue by jacko85** [kalkih/mini-graph-card#642]
Min / Max for today (currently ~10:45am)
![image](https://user-images.githubusercontent.com/16775020/129287296-16212a8c-05dc-47e9-85ca-2ba3ecdb72e2.png)
![image](https://user-images.githubusercontent.com/16775020/129287315-aed2c2d4-a6be-4061-8eba-63cd5c71cf27.png)

Actual min so far since midnight ~10c
![image](https://user-images.githubusercontent.com/16775020/129287379-f29aeb73-dd31-42c9-bb72-6ec67cac09cb.png)

Actual max since midnight (now) ~15.5c
![image](https://user-images.githubusercontent.com/16775020/129287401-43db136c-afa3-476e-a1a9-303dea79564e.png)

Current code:

`type: custom:mini-graph-card
entities:
  - entity: sensor.bme280_outside_0
    name: Max
    icon: mdi:home-thermometer
    aggregate_func: max
    color: null
  - entity: sensor.bme280_outside_0
    name: Min
    icon: mdi:home-thermometer
    aggregate_func: min
  - entity: sensor.bme280_outside_0
    name: Avg
    color: green
    icon: mdi:home-thermometer
    aggregate_func: Avg
name: Outside daily temp (last week)
hours_to_show: 168
group_by: date
`

Any idea why the aggregation is quite off?

J

**Comment by kalkih** [comment]
Same issue as #648, closing in favor for that one, thanks.
