### ISSUE TITLE
Wondering how to show state with comma if the value is very large

### ISSUE THREAD

**Issue by ranrinc** [kalkih/mini-graph-card#643]
I want to show coronavirus infection on a graph which works great. But the value is large in most cases in millions. How can I show state correctly for example 1,000,000 

In my case its cut into 3 digits?

![Screen Shot 2021-08-15 at 8 12 16 PM](https://user-images.githubusercontent.com/15801696/129479809-602c8ea3-049c-47a7-b087-2b3061977e3a.png)

Maybe someone can help me out?

**Comment by RomRider** [comment]
That's available in the latest beta

**Comment by jjohnreese** [comment]
Any solution found for this issue?

**Comment by jlsjonas** [comment]
@jjohnreese are you experiencing the number being cut in pieces on the latest release?
Could you provide some screenshots & more details on what you expect to happen instead
Thnx!

**Comment by ranrinc** [comment]
somehow it still did not appear in lovelace
