### ISSUE TITLE
Installation issue when installing through HACS

### ISSUE THREAD

**Issue by orandasoft** [kalkih/mini-graph-card#645]
Installed mini-graph-card through HACS and would like to confirm the following

1) HACS created the graphical resource with URL 
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620100, but the .js file is stored in the conf/community folder and there is no config/hacsfiles folder.

2) I cannot find any reference to these resources in any yaml file I looked at. Is this as expected? I added a second graphical resource which points to the community directory as well.

3) When adding cards to a dashboard, this card is not available. Is there a different way of adding this card?

**Comment by UraniumDonut** [comment]
Bump, have the same issue

**Comment by sander76** [comment]
metoo

**Comment by UraniumDonut** [comment]
I have fixed the issue through chaotic reinstalling, reloading and rebooting. I do not know what exactly fixed the issue

**Comment by Midnitte** [comment]
It's been awhile since I've had messed with my HA and I've done a fresh install, installed this via HACs and am facing the same issue (also having the same issue with Auto Entities).
I tried loading `/config/www/community/mini-graph-card/mini-graph-card-bundle.js` as a JavaScript module, to no avail.

Has something changed with the way HACs works?

**Comment by sander76** [comment]
I have solved my issue following this suggestion: https://github.com/kalkih/mini-graph-card/issues/553#issuecomment-893509724

**Comment by Midnitte** [comment]
> I have solved my issue following this suggestion: [#553 (comment)](https://github.com/kalkih/mini-graph-card/issues/553#issuecomment-893509724)

Worked for me - very confusing that you have to use that file path, since it's not a file path you can view from the File Editor...

**Comment by matt70tx** [comment]
I tried that suggestion and its not working for me. I cant figure this out.

**Comment by Midnitte** [comment]
> I tried that suggestion and its not working for me. I cant figure this out.

The steps I took are as followed (note, I am using HAOS, not sure if that changes anything):
Install via HACS.
Go to your Dashboard.
Edit Dashboard.
Manage Resources.
Add/Edit resource to be a JavaScript module, with the above file path.
Restart.
![Screenshot_20210920-114609_Home Assistant](https://user-images.githubusercontent.com/49769850/134032429-b93d7e58-27e3-46a9-8d21-c80015491ee7.jpg)
![Screenshot_20210920-114627_Home Assistant](https://user-images.githubusercontent.com/49769850/134032452-9b16f155-d024-4143-908c-3ecff1696ff6.jpg)

**Comment by matt70tx** [comment]
I found my issue. It was the yaml code that was not formatted properly. After I did this, no issues.

`type: custom:mini-graph-card
entities:
  - entity: sensor.temperature
    aggregate_func: max
    name: Max
    color: null
  - entity: sensor.temperature
    aggregate_func: min
    name: Min
  - entity: sensor.temperature
    aggregate_func: avg
    name: Avg
    color: green
name: Temp Office daily (last week)
hours_to_show: 168
group_by: date
line_width: 2
`

**Comment by Midnitte** [comment]
I created a PR to add a mention to the readme about this since it's very confusing.
https://github.com/kalkih/mini-graph-card/pull/650

**Comment by kalkih** [comment]
@orandasoft Did any of the suggestions help? Still having issues?

**Comment by jlsjonas** [comment]
Going to assume this is resolved. Please open a new issue with details about your config & steps you took if you're still facing issues.

**Comment by orandasoft** [comment]
Apologies. I haven't been distracted and not played with the front-end for the a long time. Under 3) I noted that the card was not available when I wanted to add it while editing the dashboard. Secondly, HACS tells me that I am running v0.10.0 and that version v0.11.0 is available. I assume that the problem has indeed been resolved and will upgrade to the next version.

I did mention that HACS seemed to have added the wrong graphics resource and that I manually added an additional graphic resource. Can someone remind me whether the graphical resources are stored so that I can do a quick sanity check before pressing the upgrade button?

**Comment by jlsjonas** [comment]
> Can someone remind me whether the graphical resources are stored so that I can do a quick sanity check before pressing the upgrade button?

I'm not entirely sure what you mean by this? :grimacing: do you mean our bundle (from your edit)?

> I am confused on where the /hacsfiles/ folder went. I don't seem to find it looking through the folders using file editor ???

It's a confusing thing HACS does, `/hacsfiles` actually maps to `/config/www/community` in the resources list
