### ISSUE TITLE
Improvment for color_thresholds_trasition

### ISSUE THREAD

**Issue by AseKarlsson** [kalkih/mini-graph-card#651]
Hi,

Here comes a suggestion for improvement.

I like the color_thresholds_transition look when on smooth vs hard.
For me the smooth can be quite misleading sometimes (dealing with small temperature intervals).
Please see the differences in below picture smooth vs hard

My suggestion would be more options for color_thresholds_transition smooth:
wide could be as today and narrow would be somewhere between todays smooth and hard.

Thanks,
AseKarlsson

![SmoothVsHard](https://user-images.githubusercontent.com/80900477/134204771-9ce2d2c2-7170-485b-a38c-5facec2119e1.jpg)

**Comment by kalkih** [comment]
Thanks,
Similar request to https://github.com/kalkih/mini-graph-card/issues/118
