### ISSUE TITLE
Data is not accurate in 2 scenarios

### ISSUE THREAD

**Issue by mamartins** [kalkih/mini-graph-card#653]
I've found 2 problemas with this card.

1. 
I have a graph to group by date a sensor. 
The value presented on the top is correct, but the value for today, which should be the same as the top since the sensor is an aggregator, does not present the same value:
<img width="361" alt="Screenshot 2021-09-25 at 16 46 10" src="https://user-images.githubusercontent.com/856772/134777496-0a67970f-d099-42ba-adb3-0041307f39b2.png">

<img width="360" alt="Screenshot 2021-09-25 at 16 46 22" src="https://user-images.githubusercontent.com/856772/134777493-d1d19aad-c6f5-405c-92e7-10885523ecbb.png">

2.
I have a wind sensor that sends the wind speed every second to HA. When comparing on a date what the history and the Max/avg graph displayed I found out that the MAX wind speed for today was above what history said:
![769750640d257ea96a77148de389587ccf6d2f6b](https://user-images.githubusercontent.com/856772/134777535-cbb4b556-08b5-48af-a4ec-ac927d397de3.jpeg)
![982d3fb244cc98c39574a88d38a7c45ef9218b8e_2_948x1000](https://user-images.githubusercontent.com/856772/134777539-c43ca9c4-33aa-47a3-97a8-90e8519651bd.jpeg)
I went to check on the database, and I confirmed that the max number was 15.36km/h

**Comment by kalkih** [comment]
Hello,

For the first case try using the `aggregate_func` option and set it to `last`.

Second case, is that the same sensor displayed in the last two pictures? From  a quick glance, the plotted data doesn't seem to line up at all really.

**Comment by mamartins** [comment]
@kalkih I'll try to use those and will report back

Second case is the same sensor, yes

**Comment by mamartins** [comment]
@kalkih changing to last returned even worst results.
yesterday max wind speed: 36.29
reported with last: 7.72
reported with max: 24.35

**Comment by kalkih** [comment]
The suggestion for using `aggregate_func` was for your first problem, the `group by date` sensor.

Still having the issue with the second card? What does the card-config look like?
From the information provided i can't give a good answer. The data looks totally off comparing the two screenshots, do they display the same timeframe?
The graph line represents the moving average, hovering over a point on the graph line will display the moving average of that particular interval.

**Comment by eMeF1** [comment]
I have a similar issue displaying utility meter values. Any thoughts?

![image](https://user-images.githubusercontent.com/26500036/148722880-f6bc19ed-de9b-4ef0-8bb5-22c598a7e880.png)
![image](https://user-images.githubusercontent.com/26500036/148722964-54fb4a6a-b59a-44c4-b464-3dd69036c261.png)

Below is my utility meter settings
`
utility_meter:
  energy_heating_bedroom_dayly_kwh:
      name: Heating Bedroom Daily kWh
      source: sensor.thermostat_bedroom_status_energy
      cycle: daily
`
