### ISSUE TITLE
[Feature Request] background image

### ISSUE THREAD

**Issue by JamesMarcum** [kalkih/mini-graph-card#660]
Would love to be able to add a background image to the graph.  Obviously, being able to control overall height would then also be important.  Love the add-on so far, BTW!

**Comment by ildar170975** [comment]
> add a background image to the graph.

Easily done with card-mod:
```
type: custom:mini-graph-card
entities:
  - sensor.cleargrass_1_temperature
show:
  labels: true
style: |
  ha-card {
    background-image: url("/local/images/blue_low_2.jpg");
    background-size: 100% 100%;
  }
```
More styles - https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1585?u=ildar_gabdullin

**Comment by ildar170975** [comment]
> control overall height

Use `height` option to control a height of a graph area.
For overall height - use `card-mod`.

**Comment by kalkih** [comment]
great answers above, `card-mod` is the way to go.
