### ISSUE TITLE
set the height of the graph

### ISSUE THREAD

**Issue by marcodb82** [kalkih/mini-graph-card#664]
hy,
i try to set the height of the graph but i cant.
I insert 4 mini-graph-card in a browser_mod popup but the graphs not fill all available space.
How i can enlarge the graph until all available area?
thanks,

![Cattura](https://user-images.githubusercontent.com/74054791/140495804-a6353e33-a326-40f0-b00b-03cf51600dc5.JPG)

**Comment by kalkih** [comment]
The `height` card option is the closest you'll get.

Cards are meant to be isolated entities, they shouldn't be aware of surrounding cards or the context they are used in.
It's possible that there exists some form of custom wrapper-like card that resizes cards to available height, but I'm not aware of any.

You could also try using `card-mod` as mentioned above.
