### ISSUE TITLE
Error install with HACS "Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Uncl3dad** [kalkih/mini-graph-card#667]
Hi guys, looking for some help getting this working. Full disclosure I'm pretty(Very) new to HA and the complexities of it and the more complex integrations between all the elements at work. I'm also sure what I'm doing wrong is something pretty obvious, a step I've not done or something I've misinterpreted. 

hopefully by posting my method as detailed as i can with the errors i got some one can just tell me where i;ve cocked it all up. any and all help is appreciated.

Installation Via HACS on HA on RPi 4 - it's a pretty new installation 

1. Go to the hacs  interface, front end then add and explore repositories. 
2. Click mini-graph-card then "install this repository in hacs"
3. Ensure V0.10.0 is selected as version and hit Download
4. Pop up "you need to reload... ect" So hit reload
5. Navigate to Config, love lace dashboards, resources to ensure the module is in there.
![image](https://user-images.githubusercontent.com/94788668/143478283-234713ba-fdfd-475e-8402-e9430458aeed.png)
(Issue 1: From my reading i think this is my first issue, i think that perhaps i shouldn't have the "?hacstag=1512800620100" section and it should be deleted)
6. Restart my Pi 

7. Log back in 
8. Navigate to configuration, lovelace, resource. hit add resource 
![image](https://user-images.githubusercontent.com/94788668/143480064-e943d33a-62df-4282-8b40-771ea725e02b.png)
(As you can see here this is an example from the time i corrected the "?hacstag=1512800620100"

9. Navigate to over view, edit dashboard, add card and scroll down to mini graph card and click that.
10. An error appears 
![image](https://user-images.githubusercontent.com/94788668/143478963-f2ed9796-ff2a-4c8a-8031-d11665c18fb5.png)
(Issue 2: I get this error. Redoing the whole process and adding/removing the  "?hacstag=1512800620100" from Issue 1 I still get the same error.

Added some other screen shots or other parts of the install 
![image](https://user-images.githubusercontent.com/94788668/143482774-c453fd99-9beb-409f-a8a9-b85a60cca970.png)
 
![image](https://user-images.githubusercontent.com/94788668/143483023-40437a24-d618-4848-b23c-f0f6e5e4ba03.png)

![image](https://user-images.githubusercontent.com/94788668/143483076-9b4de269-ea10-4f55-97f9-fe504c8b41c8.png)

**Comment by kalkih** [comment]
Hello, please try adding an entity to the card configuration.

```
...
entities:
  - sensor.name_of_sensor
```

**Comment by Uncl3dad** [comment]
Oh dear, sorry for wasting your time. I guess i had an error , solved it and just assumed this was the same one....

It is, and has been, working.

HA hasn't been 'that easy'

Thank you!

**Comment by kalkih** [comment]
Great to hear!
Well, the error message could certainly be improved... it doesn't really say anything of help right now. 😉
