### ISSUE TITLE
Align x axis wtih multiple units of measurement

### ISSUE THREAD

**Issue by joejulian** [kalkih/mini-graph-card#669]
With this graph, the states of the HVAC and the temperature deltas don't align. Aligning the x axis would make the valleys match the idle time and the peaks match the heating time. Without the alignment, it's much harder to read.

Aligning the x-axis would make this, or any other mixed-unit graphs make sense.

![image](https://user-images.githubusercontent.com/952828/144871012-b7a2c978-c49c-4667-8170-03d73b2d0575.png)

**Comment by kalkih** [comment]
Hello, this is not the right place for this issue, the card in the image is not this custom card.

**Comment by joejulian** [comment]
D'oh! Sorry about that.
