### ISSUE TITLE
Bars and Lines

### ISSUE THREAD

**Issue by bucika-mali** [kalkih/mini-graph-card#670]
Hi. 
Can I mix bar and lines in same window? 
For example, I would like to see different daily energy as bar  and temperature as line.

**Comment by ildar170975** [comment]
Option `show::graph: bar` is global for all graphs

**Comment by bucika-mali** [comment]
Thanks.

**Comment by ThomasPietrzak** [comment]
Would be great to show a night/day curve on a bar chart. Would be possible from a syntax point of view by moving the graph parameter to entities.
