### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by xXDjMikeXx** [kalkih/mini-graph-card#671]
I just get this Error

I also tried some of the Examples….

![AC23CBEF-5FAD-4FC4-BAF3-D8BED913FB81](https://user-images.githubusercontent.com/20925297/146462576-5693001c-157b-4c37-9023-ef9819ad276d.png)

**Comment by kalkih** [comment]
You need to specify one or more entities.

**Comment by xXDjMikeXx** [comment]
I have done it, sorry wrong Screenshot haha
I also tried several examples

**Comment by jarekb76** [comment]
Me too doesnt work.  Home Assistant 2021.12.4

**Comment by retepkirasam** [comment]
![format-yaml](https://user-images.githubusercontent.com/96387545/147650140-05912f9b-acc4-4b01-9573-424be932c530.png)
I don't understand why, but it helped me reformat the sample code by deleting spaces.

**Comment by kalkih** [comment]
Please try the above and reopen if issue remains
