### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'length') type: custom:mini-graph-card

### ISSUE THREAD

**Issue by SrekerGER** [kalkih/mini-graph-card#672]
Hi,

after i installed this card via HACS, i reveived this error when i try to use the card.

```
Cannot read properties of undefined (reading 'length')
type: custom:mini-graph-card
```
Can anybody help?
thx

**Comment by kalkih** [comment]
Please try adding one or more entities to the card configuration.

```yaml
type: custom:mini-graph-card
entities:
  - sensor.example_name
´``

**Comment by SrekerGER** [comment]
Hi,Thanks a lot. Its working.StephanAm 20.12.21 um 22:58 schrieb Karl Kihlström
                
            
            
                
                    Von: "Karl Kihlström" ***@***.***>Datum: 20. Dezember 2021An: "kalkih/mini-graph-card" ***@***.***>Cc: "SrekerGER" ***@***.***>,"Author" ***@***.***>Betreff: Re: [kalkih/mini-graph-card] Error: Cannot read properties of undefined (reading 'length') type: custom:mini-graph-card (Issue #672)
                
                

Please try adding one or more entities to the card configuration.

type: custom:mini-graph-card

entities:

  - sensor.example_name

´``
