### ISSUE TITLE
Feature request : last bar color

### ISSUE THREAD

**Issue by silversmarty** [kalkih/mini-graph-card#684]
Hi,

thanks for this amazing plugin ! It's really impressive how it can enhance our lovelace dashboards !

I'm using it for Energy Barchart (meaning having a bar for every hour in the last 24h), but the last bar is always "not accurate" as the hour is not ended yet. Therefore I'd like to change its color, to reflect its "ongoing" status" (and the fact it can still go higher than its current level).

Would it be possible to add an option as `last_bar_color : #AB1234` ?

Thanks a lot

**Comment by ildar170975** [comment]
May be achieved by card-mod:
```
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    show:
      graph: bar
    card_mod:
      style: |
        rect.bar:last-of-type {
           fill: red;
        }
```
![изображение](https://user-images.githubusercontent.com/71872483/148538498-77ff59ee-2066-4f18-a8d4-657e6434f05a.png)

**Comment by silversmarty** [comment]
wonderfull ! It's exactly what I was looking for!
Thank you so much
