### ISSUE TITLE
Upcoming release 0.11.0 - 22 Jan 2022

### ISSUE THREAD

**Issue by jlsjonas** [kalkih/mini-graph-card#692]
We are preparing for release v0.11.0, currently released as [v0.11.0-dev.5](https://github.com/kalkih/mini-graph-card/releases/tag/v0.11.0-dev.5) (beta release).
If you notice any issues that don't occur on 0.10.0, please create an issue, referencing this one, and we'll try to resolve them before the release.

**Comment by Mick51** [comment]
Hello, would it be possible to fix the problems that I also mentioned in my post on the next version, because your Dev version has exactly the same problem as the stable version.
