### ISSUE TITLE
Problem with graph daily BUG

### ISSUE THREAD

**Issue by Mick51** [kalkih/mini-graph-card#694]
Hello, I have a problem with the graphics of the old one which do not correspond to my history, so I deduce that the problem comes from this mod. I you but the photos of the problem and my code right after. Thank you

https://ibb.co/QMnSm6h
https://ibb.co/FzG8wHv

Code used :
` type: custom:apexcharts-card
graph_span: 1d
apex_config:
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
header:
  show: true
  title: Consommation Journalière
  show_states: true
  colorize_states: true
series:
  - entity: sensor.energie_journaliere_kwh
    name: Consommation Aujourd'hui
    stroke_width: 2
    group_by:
      func: avg
      duration: 15min
  - entity: sensor.energie_journaliere_kwh
    name: Consommation Hier
    stroke_width: 2
    offset: '-1d'
    group_by:
      func: avg
      duration: 15min
 `

**Comment by ildar170975** [comment]
The provided code & screenshot is related to `apexcharts-card`.
Th issue is not supposed to be registered here.
