### ISSUE TITLE
Feature request: compact mode

### ISSUE THREAD

**Issue by Eckart0** [kalkih/mini-graph-card#699]
Hi,
ist there a feature to define the vertical position of icon / header / state? 
This could spare some room.
Examples: 
- show/name: false and icon and state on the same line
- state overlapping the graph in the foreground
Regards,
Eckart
(an tanks for this impressive card!!!)

**Comment by ildar170975** [comment]
> * state overlapping the graph in the foreground

Like here: https://github.com/kalkih/mini-graph-card/issues/176
