### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-graph-card#7]
Hi, i copied the 2 .js in the www folder, i put code in un-lovelace.js
but i get
https://xxxx.xxxx.xxx:8123/local/mini-graph-card.js?v=0.0.4:7:1 Uncaught SyntaxError: Unexpected token <
in the logfile

**Comment by kalkih** [comment]
Need more info, what browser are you using?
Can you check the developer console in your browser, and pasted the error messages from there?

**Comment by Kedryn** [comment]
I'm using chrome, latest version. But i have not yet put the card in my ui, only inserted the resource in ui-lovelace.yaml (sorry for my previous error in specifying the filename)

If i've understood what you are asking, this is my developer console

![image](https://user-images.githubusercontent.com/12759632/46772346-df4aa680-ccf7-11e8-938c-a54dada3d93e.png)

**Comment by HFsi** [comment]
Same problem for me

**Comment by kalkih** [comment]
Alright, can any of you please try the previous version [v0.0.4](https://github.com/kalkih/mini-graph-card/releases/tag/v0.0.4) and see if that version works for you?

**Comment by Kedryn** [comment]
I tried every single version, from 0.0.01 to 0.0.5, same error.
I get the error in my browser dev console, but also in the HASSIO logs when i try to view the first page

**Comment by kalkih** [comment]
Ok, my guess is that it has to do with the import of the lit-element dependency.
It's possible that it fails to load it properly, I'm not sure if pihole could be interfering with it, if it's an issue with SSL or if it's something else.

Home Assistant will come built with lit-element in the next release 0.80.0 which will eliminate the need for the external loading of it.

**Comment by kalkih** [comment]
Another person had this exact same issue over at the [Home Assistant forum](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/32?u=kalkih)
He had downloaded the files incorrectly and solved it by getting the correct files.

Please check the files again and make sure your local files match the raw versions of [mini-graph-card.js](https://raw.githubusercontent.com/kalkih/mini-graph-card/master/mini-graph-card.js) and [mini-graph-lib.js](https://raw.githubusercontent.com/kalkih/mini-graph-card/master/mini-graph-lib.js).

**Comment by Kedryn** [comment]
I tried every single version and downloaded them in zip filse, no way they were corrupted.

**Comment by kalkih** [comment]
If you are sure the files are looking fine (open them in any text editor and check), it's most likely a problem with loading the external lit-element dependency, possibly blocked by your ad/content blockers.

**Comment by HFsi** [comment]
I tought that, so I disabled Pi-hole, but the issue remains the same....
Wich domains do you use? So I can check them manualy, DNS and IP level

**Comment by kalkih** [comment]
import { LitElement, html, svg } from 'https://unpkg.com/@polymer/lit-element@^0.6.2/lit-element.js?module';

**Comment by HFsi** [comment]
It´s working!
The save as option copied a wrong content, Copy & Paste from the raw was the solution.
Thanks!

**Comment by kalkih** [comment]
> It´s working!
> The save as option copied a wrong content, Copy & Paste from the raw was the solution.
> Thanks!

That's great to hear!
