### ISSUE TITLE
Installed by HACS doesn't work v0.11.0

### ISSUE THREAD

**Issue by DomoSnk** [kalkih/mini-graph-card#712]
Hi, I have a problem on installed version of mini-graph-card v0.11.0

Installed by HACS

mini-graph-card-boundle.js here:
\\192.168.1.x\config\www\community\mini-graph-card

resource:
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=XXXXXXXXXXXX

If I try to add custom code like:

`- type: custom:mini-graph-card
  entities:
    - sensor.tempcamera_temperature`
     
it doesn't work, and give me erro like **No card type found**
Already tryed to empty browser cache, change resource path several times.
Any suggestion?

**Comment by jlsjonas** [comment]
You need to remove the array identifier (‘- ‘) when adding a card via Lovelace
If you add the card & open the code editor you should see the type already there, that should be a valid starting point.

We're working on aligning the configuration, which will also include an update to the readme to hopefully make things more easy to understand for new users.

**Comment by DomoSnk** [comment]
Ok I fix it thank you so much :)
