### ISSUE TITLE
Data 

### ISSUE THREAD

**Issue by nkznkz** [kalkih/mini-graph-card#715]
Hi,
In what table (SQLite) are the data displayed on the charts?
I could find update history but it has no relation I see.
I would like to update a few points:
![image](https://user-images.githubusercontent.com/55733396/152056315-f8ee6f19-a715-4e52-a31c-a91c27c38633.png)
Thanks

**Comment by jlsjonas** [comment]
https://www.home-assistant.io/integrations/history/

Do note that we (for performance reasons) also cache data in your browser's localstorage (‘cache: false‘ to disable)
