### ISSUE TITLE
No graph will display

### ISSUE THREAD

**Issue by syntaxalen** [kalkih/mini-graph-card#718]
I am a noob so please forgive me. I tried to google it and found others with the same problem but nothing works for me. The entity is pulling but the data itself is not( see photo). 

![Screenshot 2022-02-03 012110](https://user-images.githubusercontent.com/53226391/152291798-e25843f4-e688-4b9f-96d2-4caa0a8eabae.png)

**Comment by max5962** [comment]
Same here ( since Two days ) 
It seems something (an update ) is breaking something : 


`mini-graph-card-bundle.js:1 mini-graph-card:  DOMException: Transaction timed out due to inactivity.
xc @ mini-graph-card-bundle.js:1
`

 MINI-GRAPH-CARD  0.11.0

**Comment by ildar170975** [comment]
1. You have not provided a code for the card.
2. Check these sensors with a conventional history-graph.

**Comment by max5962** [comment]
hello @ildar170975  it was working well before. 

1. page "home" :  working
![image](https://user-images.githubusercontent.com/34659571/152325475-4252082b-b4ac-4d3d-ade6-ce80d9931c99.png)
2. switch to parameter page : not working 
![image](https://user-images.githubusercontent.com/34659571/152325550-e35c28ae-2a40-44c9-89ec-9ce68f8ab4f4.png)
3. refresh parameter page : working
![image](https://user-images.githubusercontent.com/34659571/152325603-9942dcc0-b132-460f-a05f-1e63446bd12a.png)
4. switch to home home page : non working 
![image](https://user-images.githubusercontent.com/34659571/152325666-65d8ac5e-8536-4237-bb23-bdff12410f8f.png)
5. refresh home page : working
![image](https://user-images.githubusercontent.com/34659571/152325698-a33e8768-19dd-4ce7-b525-28ebbc1f6919.png)

And no error in console :(

**Comment by ildar170975** [comment]
Why these pics were posted? Please check again my previous post.

**Comment by syntaxalen** [comment]
> * You have not provided a code for the card.
> * Check these sensors with a conventional history-graph.

Sorry! Here it is 

type: custom:mini-graph-card
entities:
  - sensor.downstairs_humidity
line_color: blue
line_width: 8
font_size: 75

**Comment by syntaxalen** [comment]
fixed it! Looks like I didn’t have default_config: in my yaml

**Comment by ildar170975** [comment]
That is why I asked about testing with history-graph

**Comment by pinkfloydFR** [comment]
Have the same problem, all was worked well before update 2022.2, now i have no graph.

Exemple : 

type: custom:mini-graph-card
entities:
  - entity: sensor.processor_use_percent
    name: CPU Usage
icon: mdi:memory
lower_bound: ~0
points_per_hour: 4
hours_to_show: 12
color_thresholds:
  - value: 0
    color: '#40bf40'
  - value: 10
    color: '#ffde00'
  - value: 50
    color: '#bf4040'



this is the default config you are talkin about ? ( configuration.yaml )
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
