### ISSUE TITLE
I cant create any graph.

### ISSUE THREAD

**Issue by FamKeGala** [kalkih/mini-graph-card#728]
I inatalled mini graph card 0.11 from HACS but in lovelace when I create a mini graph,
Code:
type: custom:mini-graph-card
entitie: sensor.broadlink_andres_humidity

I recive the messsge:

Please provide the "entities" option as a list. See https://github.com/kalkih/mini-graph-card/blob/master/README.md

What am i doing wrong?

**Comment by ildar170975** [comment]
> What am i doing wrong?

Not reading docs.
Please check this example:
https://github.com/kalkih/mini-graph-card/blob/master/README.md#single-entity-card
