### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by tiagonmas** [kalkih/mini-graph-card#733]
I followed the ReadMe  but I'm getting the error:
![image](https://user-images.githubusercontent.com/42462/154130471-a7d9ae85-6dff-4989-86fa-76c688cab447.png)

I've copied the latest js file to config/www
I've then tried to manually update configuration.yaml with the resource information but I get the error 
`Integration error: resources - Integration 'resources' not found.`

So I added it via the UI
![image](https://user-images.githubusercontent.com/42462/154130682-631a4675-15d6-4b9a-a5b7-c29845930fb1.png)

I restarted Home assitant, see no errors in logs, but still the UI cannot find that card type.

**Comment by ildar170975** [comment]
Wrong card name:
minigraphcard

**Comment by tiagonmas** [comment]
The issue happens with the original name. I copy pasted when I was trying to try different names to see if it would solve the issue

**Comment by ildar170975** [comment]
Seems you are not using HACS.
Did you add the card as a resource as it is [described here](https://github.com/kalkih/mini-graph-card#add-resource-reference)?

**Comment by tiagonmas** [comment]
I am not using HACS. 

As mentioned above I did try to add it as a resource as  [described here](https://github.com/kalkih/mini-graph-card#add-resource-reference) but when I do and try to restart I get the error:

![image](https://user-images.githubusercontent.com/42462/154160122-d1df45e4-24d1-4954-b96b-03fe8e5ad145.png)

Here is the Lovelace error when using the correct name.
![image](https://user-images.githubusercontent.com/42462/154159910-74c1b1ee-73fe-4408-a690-bacefc570be7.png)

**Comment by tiagonmas** [comment]
More info: Home Assistant 2021.11.5
Frontend version: 20211109.0 - latest
## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v7l
arch | armv7l
timezone | Europe/Lisbon

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 27.8 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), Mosquitto broker (6.0.1), Pi-hole (4.0.0), Duck DNS (1.14.0), TasmoAdmin (0.16.0), InfluxDB (4.3.0), Grafana (7.4.1), Terminal & SSH (9.3.0), eWeLink Smart Home (1.2.3), WireGuard (0.6.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 1
views | 8
mode | storage

</details>

**Comment by ildar170975** [comment]
You added "resources" in a wrong place.
Remove it from "configuration.yaml" and just add it via UI (https://github.com/kalkih/mini-graph-card#add-resource-reference).

**Comment by tiagonmas** [comment]
I did it also, as mentioned in the original post. It also does not work. I even added a screen grab of adding the resource via the UI
<img width="869" alt="image" src="https://user-images.githubusercontent.com/42462/154163983-5b09a5f6-97c8-402d-9169-29e1db06bb82.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/42462/154164028-c370008a-b748-47e7-b8bf-4d92da9fe4ee.png">

**Comment by ildar170975** [comment]
I noticed on your screenshot that the code starts with "-".
Not clear whether how this screenshot was taken.
If this is a code of a card then it should NOT start with "-".

**Comment by tiagonmas** [comment]
That was it! Thanks
I took it from [Example Usage](https://github.com/kalkih/mini-graph-card#example-usage) so probably that needs to be fixed !?

it worked like this
![image](https://user-images.githubusercontent.com/42462/154239728-db3d879f-058e-4981-9ac4-82a56fa27959.png)

**Comment by ildar170975** [comment]
> that needs to be fixed !?

Most people understand that a card always starts with a “type:”

**Comment by tiagonmas** [comment]
well, we can improve docs to work for everyone, not just "most people" :) I'll suggest the edit

**Comment by ildar170975** [comment]
> I'll suggest the edit

Great, this is the real effort!
