### ISSUE TITLE
Changeable state icons on mini-graph-card

### ISSUE THREAD

**Issue by LUBANG37** [kalkih/mini-graph-card#742]
**I want to set the icon to change according to the state. I can't do this. Can anyone help me?** 

Thats not work:

 - type: grid
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.dom_caqi
        name: POWIETRZE
        icon: |
          [[[
              if (entity.state < 25) return 'mdi:emoticon-happy';
              if (entity.state >= 25 && entity.state < 50) return 'mdi:emoticon-neutral';
              if (entity.state >= 50 && entity.state < 75) return 'mdi:emoticon-neutral';
              if (entity.state >= 75 && entity.state < 87.5) return 'mdi:emoticon-sad';
              if (entity.state >= 87.5 && entity.state < 100) return 'mdi:emoticon-sad';
              if (entity.state >= 100 && entity.state < 125) return 'mdi:emoticon-sad';
              if (entity.state >= 125 ) return 'mdi:emoticon-dead';
          ]]]   
        show:
          name_adaptive_color: false
          icon_adaptive_color: true
          graph: bar
          extrema: false
        line_color: '#b80000'
        line_width: 12
        font_size: 100
        font_size_header: 12
        align_state: center
        hours_to_show: 12
        points_per_hour: 1
        smoothing: true
        hour24: true
        #height: 150
        color_thresholds:
          - value: 0
            color: '#20c400'
          - value: 25
            color: '#c4bd00'
          - value: 50
            color: '#c48600'
          - value: 75
            color: '#c48600'
          - value: 87.5
            color: '#c40000'
          - value: 100
            color: '#c40065'
          - value: 125
            color: '#a000c4'
        style: |
          .header.flex .icon {
          --mdc-icon-size: 40px;
          }

![Przechwytywanie](https://user-images.githubusercontent.com/26896616/155536028-fda230fe-b183-41ea-99d7-0dec0f54b235.JPG)

**Comment by ildar170975** [comment]
Please use an appropriate formatting when posting a code.
