### ISSUE TITLE
Wrong alignment with multiple states

### ISSUE THREAD

**Issue by Kalfany** [kalkih/mini-graph-card#75]
The alignment of multiple states which have different length is not "right". It doesn't stand out as long as they are the same length

v0.3.1 @ HA 0.90.0

![alignment](https://user-images.githubusercontent.com/6972342/54780546-53c83080-4c1a-11e9-98b3-c1099ab7c29b.jpg)

          - type: custom:mini-graph-card
            hour24: true
            decimals: 1
            align_state: left
            points_per_hour: 2
            line_width: 3
            name: Drinnen
            show:
              fill: false
            entities:
              - entity: sensor.netatmo_wetterstation_temperature
                name: Wohnzimmer
              - entity: sensor.netatmo_kuche_temperature
                name: Küche
                show_state: true
                state_adaptive_color: true
              - entity: sensor.netatmo_schlafen_temperature
                name: Schlafzimmer
                show_state: true
                state_adaptive_color: true
              - entity: sensor.flur_temperatur
                name: Flur
                show_state: true
                state_adaptive_color: true
              - entity: sensor.bad_temperatur
                name: Bad
                show_state: true
                state_adaptive_color: true

**Comment by kalkih** [comment]
Okay, the secondary states are now aligned like this inside their container:

| align_state | secondary state alignment |
|------|----|
| left or unset | right |
| right | left |
| center | center |


![hyperion_8123_lovelace_4 (3)](https://user-images.githubusercontent.com/457678/54783151-ec61af00-4c20-11e9-8ba8-c3a99ca9113f.png)
![hyperion_8123_lovelace_4 (4)](https://user-images.githubusercontent.com/457678/54783154-ed92dc00-4c20-11e9-87d0-985a6381a8ff.png)
![hyperion_8123_lovelace_4 (5)](https://user-images.githubusercontent.com/457678/54783156-eec40900-4c20-11e9-9668-0799152091c7.png)

**Comment by kalkih** [comment]
This is now available in the latest release [v0.3.2](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.2)

**Comment by Kalfany** [comment]
> This is now available in the latest release [v0.3.2](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.2)

![Zwischenablage02](https://user-images.githubusercontent.com/6972342/54882224-046f4380-4e58-11e9-8b21-39b09cf3fa4e.jpg)

Perfect! Thanks!
