### ISSUE TITLE
Template sensor doesn't show

### ISSUE THREAD

**Issue by Calorian** [kalkih/mini-graph-card#753]
Apologies if this has already been flagged, I searched and couldn't see a report.

I am using a template sensor for averaging temperature as recommended here https://github.com/kalkih/mini-graph-card/issues/73#issuecomment-524072577 
This is working for other cards however it is not available for selection on this card. In the Lovelace GUI it is not listed, and manual addition in the yaml also does not make it show.

The sensor code matches the home-assistant documentation like so:
```
template:
  - sensor:
      - name: "Average temperature"
        unit_of_measurement: "°C"
        state: >
          {% set bedroom = states('sensor.bedroom_temp') | float %}
          {% set kitchen = states('sensor.kitchen_temp') | float %}

          {{ ((bedroom + kitchen) / 2) | round(1, default=0) }}
```

**Comment by ildar170975** [comment]
Duplicate of https://github.com/kalkih/mini-graph-card/issues/697

**Comment by ildar170975** [comment]
Templates not supported currently.

**Comment by ildar170975** [comment]
Template sensors may be used in mini-graph-card like other sensors.
Check if the sensor created properly.
Also, code snippets should be posted with formatting.

**Comment by Calorian** [comment]
> Aso, code snippets should be posted with formatting (``` surrounding your code).
Corrected, apologies the mobile display was being daft.

> Check if the sensor created properly.
The sensor appears in the entity list as sensor.average_temp as expected and can be used on a default graph or entity card correctly 

> P.S. Sorry a lot for wrong actions (marking as a duplicate, closing). Head was busy with other thoughts.
No worries, it's all good.

**Comment by jlsjonas** [comment]
Could you please share your card yaml (not just the sensor), and ensure your sensor shows as expected in the developer tools?

>  it is not available for selection on this card. In the Lovelace GUI it is not listed

Are you sure you're using mini-graph-card? We currently don't have a visual editor.

**Comment by Calorian** [comment]
A hundred apologies, noob here. I checked code over and over and missed it wasn't this card (too many graphs!). Can confirm this card works perfectly fine. I'll go raise the bug in the right place now. Apologies again.
