### ISSUE TITLE
v0.3.1 Uncaught SyntaxError

### ISSUE THREAD

**Issue by tinysnake** [kalkih/mini-graph-card#76]
Hi, I've got an error in my home-assistant log section

`local/mini-graph-card-bundle.js?v=0.3.1:1:50 Uncaught SyntaxError: Invalid or unexpected token`

I install it from wget, it was working well yesterday, but stop working today. lovelace shows `Custom Element doesn't exists`, other custom uis works fine, and v0.3.0 is ok.

my home-assistant version is 0.89.1

**Comment by kalkih** [comment]
Try deleting the file and download it again.

**Comment by tinysnake** [comment]
weird.. re-downloading 0.3.1 is not helping, but placing it to 0.3.0 and back to 0.3.1 works. maybe there's some caching going one

**Comment by kalkih** [comment]
Strange, but yeah as you said, probably a caching issue.
The bad/corrupt file might be cached, try manually clearing the cache if you have further issues.

**Comment by tinysnake** [comment]
ok, thanks!

**Comment by tinysnake** [comment]
I'm here again, 0.3.1 tends to go bad after a while, I fallback to 0.3.0 and everything is good again. maybe you can provide a uncompressed version to a void this kinda problem.

**Comment by kalkih** [comment]
Are you using custom updater or anything else that is making changes to the file?
I don't understand how it could possibly stop working unless something is making changes to the file.

**Comment by tinysnake** [comment]
nope, I just switch from local network IP address to public domain, and it just stop working.

**Comment by kalkih** [comment]
Okay, here's a non transpiled and minified, give it a shot and see if you still have issues.
https://gist.github.com/kalkih/490d4fc20a3c071ce14521a1d0ab2daf

**Comment by tinysnake** [comment]
the non minified version works, and 0.3.2 works ok too, I donno what happened back then, but I think you should close this issue for now.
