### ISSUE TITLE
feat: Threshold lines

### ISSUE THREAD

**Issue by idunnololz** [kalkih/mini-graph-card#767]
It would be useful to allow users to specify a threshold line that will be drawn in the graph. I can currently work around this issue by making a dummy sensor and use it's value as the threshold line, however this has the problem that it can change the y-axis range of the graph if the threshold value differs greatly from any data in shown.

**Comment by ildar170975** [comment]
@idunnololz
Is it same?
https://github.com/kalkih/mini-graph-card/issues/570
If same - let us know, then this issue will be closed as duplicate.

**Comment by idunnololz** [comment]
@ildar170975 Yep. You can close as duplicate.

**Comment by ildar170975** [comment]
Duplicates https://github.com/kalkih/mini-graph-card/issues/570
