### ISSUE TITLE
group_by 'day'

### ISSUE THREAD

**Issue by MickMake** [kalkih/mini-graph-card#769]
It'd be nice to be able to `group_by: day`. The specific use case I have in mind is that I want to be able to view my Solar panel stats as compared to previous days.
That is: showing a min/avg/max graph of the current day with each hour compared to the same hour from previous days.

Unless, I'm missing something... :-)

**Comment by pachi81** [comment]
What about `group_by: date`!? I´m using it for a graph of the daily rain the last 7 days...
