### ISSUE TITLE
Feature request: hours_to_show between A and B

### ISSUE THREAD

**Issue by aidbish** [kalkih/mini-graph-card#77]
Hi
Is it possible to implement the hours to show between certain time periods

i am trying to show my solar generation, but only need to show it for the time its generating (usually from 6am to 6 pm

**Comment by Tim-GitHub** [comment]
I'm looking for the exact same feature. Currently I have my solar panel power chart set to 12 hours, but it would be preferable if the chart started at a specific time and continued to chart data over time, then reset at the next start time.

**Comment by Brausmith** [comment]
Same here, for power consumption. I would like the option to start/stop at midnight.

**Comment by arretx** [comment]
Can't you construct a history_stats sensor with the exact measurement you're looking for?

**Comment by jarrah31** [comment]
Me too please! - https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1390?u=jarrah
