### ISSUE TITLE
Upper / lower limit in line chart to match the selected entity

### ISSUE THREAD

**Issue by MHeuvel** [kalkih/mini-graph-card#771]
Hi,

First of all: great work on this card!
My feature request would be to display the upper- and lower limit of the line chart to a selected entity when the chart contains multiple entities. See image for a better explanation of what I mean:
![BC396F53-2A38-4EF5-B046-8287E405FD15](https://user-images.githubusercontent.com/31540749/162559949-d7333a45-5c6e-4e77-8943-467fc1d5cbf3.jpeg)

Thanks again for all your hard work.

**Comment by ildar170975** [comment]
Check this: https://github.com/kalkih/mini-graph-card/issues/51.
If proposed ideas in that issue are OK for you - then you may close your issue as a duplicate issue.

**Comment by MHeuvel** [comment]
Did not exactly catch the content of the post, I will try it out. But I think it might work. I will close this issue and thanks for your help.
