### ISSUE TITLE
Add a visual editor

### ISSUE THREAD

**Issue by welcoMattic** [kalkih/mini-graph-card#773]
It would be very useful to add a visual editor for this very complete card, to ease non-dev user to leverage this card.

**Comment by welcoMattic** [comment]
Still active, as it hasn't been implemented yet.

**Comment by welcoMattic** [comment]
Still activé

**Comment by BoxedBrain** [comment]
Still an active issue.

**Comment by SamJongenelen** [comment]
@welcoMattic this is stil not featured right? I was searching for it and found this topic.
