### ISSUE TITLE
Does not follow profile configured "Number Format"

### ISSUE THREAD

**Issue by scaarup** [kalkih/mini-graph-card#774]
Hi.

Even though I have configured my Number Format as this:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/8055470/163722889-d605b773-9bd2-4f03-9551-224400bc82ea.png">

The card is rendering numbers with American/English style:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/8055470/163722860-bab479d3-3114-40db-9810-ae177a3c6a76.png">

**Comment by cataseven** [comment]
Should be fix

**Comment by cataseven** [comment]
https://github.com/kalkih/mini-graph-card/issues/1010#issuecomment-1937086129

**Comment by cataseven** [comment]
> Hi.
> 
> Even though I have configured my Number Format as this: <img alt="image" width="578" src="https://user-images.githubusercontent.com/8055470/163722889-d605b773-9bd2-4f03-9551-224400bc82ea.png">
> 
> The card is rendering numbers with American/English style: <img alt="image" width="505" src="https://user-images.githubusercontent.com/8055470/163722860-bab479d3-3114-40db-9810-ae177a3c6a76.png">

https://github.com/kalkih/mini-graph-card/issues/1010#issuecomment-1937086129

**Comment by adegruijl** [comment]
+1
