### ISSUE TITLE
Feature request: configure significant digits

### ISSUE THREAD

**Issue by MayeulC** [kalkih/mini-graph-card#779]
## Issue
See the screenshot below:
![image](https://user-images.githubusercontent.com/3952726/165484209-995ac6c2-7ab2-4060-8fe4-a48374d9bac9.png)
On the left, a default lovelace sensor (I have no idea what's up with the graph, ranges are the same).

I have 6 different electricity metering rates (EDF TEMPO):

* 0.1231 (low demand day, off-peak)
* 0.1498 (low demand day, peak hours)
* 0.1412 (medium demand day, off-peak)
* 0.1773 (medium demand day, peak hours)
* 0.1509 (high demand day, off-peak)
* 0.6274 (high demand day, peak hours)

I am not sure 2 digits are enough. In any case, there might be some other cases where they are absolutely significant.

## Suggested fix
Either add a setting to change the number of significant digits, or provide a formatspec-compatible ([python's](https://docs.python.org/3/library/string.html#format-specification-mini-language) or a subset) way of specifying it.

This would also help with #643.

Ideally, a format field should support a full `{{ template }}` syntax, but I think the formatting happens in javascript, so making it compatible with jinja templates would be a complex project. On the other hand, I am pretty sure javascript supports a similar formatspec.

That way, I could display € cents instead of decimal € (another approach would be to create a new sensor, but that's something I'd rather avoid).

**Comment by MayeulC** [comment]
I don't think this has been implemented yet.

**Comment by ildar170975** [comment]
> (I have no idea what's up with the graph, ranges are the same).

Probably you are missing:
- lower bound
- aggregate_func, smoothing, points_per_hour
?

**Comment by MayeulC** [comment]
> Any reasons of not using `decimals` option?

I... didn't find that option when I looked for it. Thanks for pointing it out, it works for my use-case, even though this is not exactly what I asked :)
(as in: 0.00010, 10  and 1.0 all have 2 significant digits; but the number of `decimal` places might be better)

I will also look at the options you provided for the default graph, thank you for your help.

**Comment by ildar170975** [comment]
> (as in: 0.00010, 10 and 1.0 all have 2 significant digits; but the number of `decimal` places might be better)

Probably I do not understand you.
According to your example
![image](https://user-images.githubusercontent.com/71872483/176536223-279e8ed5-0205-4b26-998f-fc1ca57ddcd6.png)
you needed to display MORE digits after comma.
This is exactly what `decimals` do:
![image](https://user-images.githubusercontent.com/71872483/176538517-110b4d84-42fb-4e9e-a5f4-927f6cd00ed2.png)
