### ISSUE TITLE
Daily bar chart

### ISSUE THREAD

**Issue by tinglis1** [kalkih/mini-graph-card#78]
Feature request:
It would be great to be able to make a daily bar chart.
I can currently set a 24hr bar chart but it would be great if the period could be locked to a set period e.g. midnight to midnight.

My use case for this would be to show energy usage for the last 7 days from a cumulative energy sensor. The current day would only show the usage from midnight.

**Comment by kalkih** [comment]
Yes indeed, that would be a great and useful feature.

**Comment by mrkrb** [comment]
I agree as well, this would be awesome! For example for creating charts of the min and max temperature along the week, or to display the power consumption of the last N months, so on so forth.

**Comment by NicoBijl** [comment]
Would be very useful indeed, for me personally to visualize my hours at work on a daily basis (based on device tracking)

**Comment by mynameisdaniel32** [comment]
Something that could fit well with this would be an option for a pie chart - who doesn't need more pie charts in their life?

**Comment by arnoldpistorius** [comment]
My use case would be to view the distance traveled with my car per day in a bar chart.

**Comment by kaosmagix** [comment]
+1 For displaying my daily utility totals (they reset at midnight)

**Comment by kaosmagix** [comment]
see also issue #77

**Comment by geniusve** [comment]
+1 For displaying my daily energy consumption.

**Comment by maxwroc** [comment]
I needed it too. Started working on the change today and it looks like I have a working code already. Once I test it and make it prod ready will send PR (probably over the weekend)

**Comment by maxwroc** [comment]
PR sent and waiting for review

**Comment by ACrazyConcept** [comment]
Just tried the new bar chart and I can't get it working correctly:
`      - type: custom:mini-graph-card
        entities:
          - entity: sensor.daily_electricity
        name: Energy consumption
        hours_to_show: 168
        aggregate_func: max
        group_by: date
        show:
          graph: bar
`

**Comment by maxwroc** [comment]
It looks like the change is not in your js. Please make sure that your browser doesn't use cached previous version. Do the following:
* in your ui-lovelace.yaml add version ("v") param int he url e.g. resources:
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js?**v=0.7.1**
* refresh lovelace UI by clicking on ".." up-right corner of your Home Assistant and then click "Refresh"
* force your browser to download fresh resources by using Ctrl+F5 combination

Please let me know if that helps.

**Comment by kalkih** [comment]
@maxwroc is correct, this hasn't been released yet, if you want to use it right now you would have to build the dev branch from source.

**Comment by ACrazyConcept** [comment]
> @maxwroc is correct, this hasn't been released yet, if you want to use it right now you would have to build the dev branch from source.

Oh ok then. I don't think I know how to do that though.
Tried your suggestion @maxwroc, but made no difference.

Guess I'll have to wait for release :)

**Comment by dale3h** [comment]
@ACrazyConcept I *might* have a temporary workaround until the feature is released. Try this and see if it works for the time being:

```yaml
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.daily_electricity
        name: Energy consumption
        hours_to_show: 168
        points_per_hour: 0.04166666667
        aggregate_func: max
        group_by: date
        show:
          graph: bar
```

This will set the graph to only display one bar per day. If you're curious, `0.041666` (repeating) is the result of `1` divided by `24`.

**Comment by maxwroc** [comment]
@dale3h this actually doesn’t work very well because of the following resons:
* single point is calculated based on the average value so what you will see is probably far from what you expect; for example if you had a big energy usage yesterday it will significantly affect the value from current day (since the very beginning)
* values are not grouped by day but by 24h buckets going backwards, starting from now; so the effect will be that all the bars from the previous days will be fluctuating when you will be watching them through the day

That is why I wouldn’t call it a workaround. BTW @rzolau was mentioning this option and its implications few comments above

**Comment by kalkih** [comment]
Hello everybody,
This feature is now available in the latest release thanks to @maxwroc!

See [Grouping by date](https://github.com/kalkih/mini-graph-card#grouping-by-date) for example usage.
