### ISSUE TITLE
Attribute of entity id not working

### ISSUE THREAD

**Issue by caohuongls** [kalkih/mini-graph-card#786]
Hi @kalkih, I want to add attribute of entity value instead of state entity. But when I add as description it's not working, It's just get state value of entity 

For example, I have light with zigbee connected, how can I make graph for linkquality  value of this light which I get from sensor.light_battery as example

![image](https://user-images.githubusercontent.com/17307638/166862356-d638a132-0333-4221-aa9f-1dff580f1aa0.png)

![image](https://user-images.githubusercontent.com/17307638/166894807-101310d1-fc58-4edc-90a4-4d75bd728aee.png)

`
type: custom:mini-graph-card
entities:
  - entity: sensor.light_battery
    attribute: linkquality
name: Light

`

**Comment by ildar170975** [comment]
Where is s screenshot of your mini-graph-card?

**Comment by caohuongls** [comment]
> Where is s screenshot of your mini-graph-card?

I update it.  It's just show value of state, not attribute linkquality

**Comment by ildar170975** [comment]
Could you post a screen from this table with YOUR entity:
![image](https://user-images.githubusercontent.com/71872483/166900395-1cd1c31b-233b-4070-9062-59b4b2e96d62.png)

**Comment by caohuongls** [comment]
Here it is

![image](https://user-images.githubusercontent.com/17307638/166902092-648d3d6d-a1a0-490d-9c65-8a6b7ed2f68a.png)

**Comment by ildar170975** [comment]
And the corrected & formatted code?

**Comment by caohuongls** [comment]
> And the corrected & formatted code?

![Screenshot_20220505-182838_Home Assistant.jpg](https://user-images.githubusercontent.com/17307638/166914362-d303e591-2354-47fa-baf8-49cb2c51ad64.jpg)

**Comment by caohuongls** [comment]
Here is full code of this card
I also try lowercase without successful. 
I think the linkquality is string  so that the card can't read it 

![Screenshot_20220505-183709_Home Assistant.jpg](https://user-images.githubusercontent.com/17307638/166915906-f27e6370-8833-425c-ba74-dc79693c29fe.jpg)

**Comment by ildar170975** [comment]
Same - you posted a clipped picture, where is the fully visible code?

**Comment by caohuongls** [comment]
You mean yaml code ?

**Comment by ildar170975** [comment]
> You mean yaml code ?

Surely yes. But now it seems that the problem is in your syntax.
Correct it. If it works - no need to post the code, just report & close))

**Comment by caohuongls** [comment]
Can you send me some code example for me to follow.  Thanks

**Comment by ildar170975** [comment]
> some code example

https://github.com/kalkih/mini-graph-card/issues/786#issuecomment-1118387172

**Comment by caohuongls** [comment]
Thanks alot,  i'll try that and find out why and then reply you soon.  Nice to talk with you
