### ISSUE TITLE
Show an aggregated state but keep lines disaggregated

### ISSUE THREAD

**Issue by alessioarena** [kalkih/mini-graph-card#793]
This card already offers great functionalities, but I was wondering if would be possible for multiple graphs to show an aggregated state (like mean) instead of the first entity when not interacting with the card.

For example, if having multiple sensors across the house, would be good to see the average temperature at a glance, and still have the more rich data per sensor plotted

**Comment by ildar170975** [comment]
You may add a state for any sensor without showing its graph. 
https://github.com/kalkih/mini-graph-card/issues/744
Create a template sensor for your needs and add it as it was described.

**Comment by alessioarena** [comment]
Thanks, would be good to have that hack listed in the documentation, as it may be a common issue

**Comment by jlsjonas** [comment]
@ildar170975 do you want to make it more clear in the readme that you can have a state displayed that isn't shown in the graph, with a tip that this could be used to show a calculated state?

**Comment by ildar170975** [comment]
@[jlsjonas](https://github.com/jlsjonas)
Done!
https://github.com/kalkih/mini-graph-card#showing-additional-info-on-the-card

**Comment by jlsjonas** [comment]
Thanks! Next time please update dev though, master should only receive dev _merges_ 😅

**Comment by ildar170975** [comment]
> Next time please update dev though

That was my FIRST edition on GitHub repo 😳
