### ISSUE TITLE
[Question/Enhancement] Using different scale-size, graph type , and aggregation for 2 entities

### ISSUE THREAD

**Issue by TheDarthFather** [kalkih/mini-graph-card#794]
Hello,
I have a challanging use case:
I would like to add 2 entities to 1 graph, however they have a big difference in value range.
One is between 40 and 250 and another between 0 and 5.
I can of course add them, but because the second one has values so small .. you actualy see a ... horizontal line .
Can we setup somehow a "scale max" for a particular entity so the second one values, while small, will look bigger ?

The same question for the graph type ... it will be great if the second one will be a bar ... or the other way around ?
And similar for the aggregatioin function ... different per entity.

If not possible, would this possible in the future ?

Thank you!

**Comment by TheDarthFather** [comment]
> You can use `y_axis: secondary` on one of your entities
> 
> > y_axis
> > string
> >  
> > If 'secondary', displays using the secondary y-axis on the right.
> 
> Moving several options from the global to the entity space is planned for the next update (ETA TBD).

Thank you!!

**Comment by TheDarthFather** [comment]
> y_axis: secondary
Works pretty Good! Thank you!
PS: I guess I will wait for the graph type! :D 
![image](https://user-images.githubusercontent.com/23462204/170751610-2a637de2-9be4-4ae0-b3e2-fa69d6c73392.png)

**Comment by jlsjonas** [comment]
No problem!

**Comment by TheDarthFather** [comment]
> > And similar for the aggregatioin function ... different per entity.
> 
> This seems to be already supported according to the docs (never tried by myself): ![изображение](https://user-images.githubusercontent.com/71872483/170752480-6fba32cc-6ee9-4340-bfd6-c78eabe63af4.png)

Indeed - I realised that just after, reading again the docs :)
