### ISSUE TITLE
Feature Request: Add state_padding option to assist in reducing empty space.

### ISSUE THREAD

**Issue by david-holbrook** [kalkih/mini-graph-card#801]
![state-padding](https://user-images.githubusercontent.com/86042175/174693507-cf5bb640-b0f0-4123-ad7c-162946c708fb.png)

It would be great if we could adjust the padding around the state value as shown at the top of the card. The mini-graph-card is brilliant for showing a lot of detail in a small card. If we had the option of tightening up some of the padding we could fit even more into the space. Alternatively, maybe separate options for font_size and extrema_font_size, as currently they both scale which prevents setting this too small and making the extrema values unreadable.

**Comment by ildar170975** [comment]
> Alternatively, maybe separate options for font_size and extrema_font_size,

https://github.com/kalkih/mini-graph-card/issues/752


> adjust the padding around the state value

Why only padding? Changing margin may be useful too:
![image](https://user-images.githubusercontent.com/71872483/174804495-6811119c-c0e2-4c97-852d-18a879e50cd1.png)

Actually, list of possible CSS improvements is unlimited - that is why sometimes it is better to use card-mod than adding more & more options to the card.
