### ISSUE TITLE
Card Background Color

### ISSUE THREAD

**Issue by WhistleMaster** [kalkih/mini-graph-card#81]
Amazing work, thank ! A request: Would it be possible to have all the card background of the color of the value, like the line ?

Something like that:
https://cdn-images-1.medium.com/max/1600/1*OA5W3jwAJ_nbtAvwBLbaOQ.png

**Comment by kalkih** [comment]
Hey, cool concept.
You can set the card background to whatever you like by using https://github.com/thomasloven/lovelace-card-modder.

**Comment by WhistleMaster** [comment]
Sure but it would be so much nicer to do it with your card 😅

**Comment by kalkih** [comment]
Okay sure, could potentially be added in the future.

**Comment by tomlut** [comment]
If you're going to do that can you add alpha transparency at the same time please?

**Comment by MatteGary** [comment]
I tried to replicate that beautiful concept with card-modder, the only thing I'm not able to overrule is the opacity of the fill of the graph... do you have any suggestion on this? otherwhise it could be a nice feature to be able to set the fill opacity (or directly the color) as setting

**Comment by WhistleMaster** [comment]
Any chance to see that feature in your amazing add-on :-) ?

**Comment by S474N** [comment]
+1, I would like to achieve a state like in Grafan

![Image](https://github.com/user-attachments/assets/3c366016-d31e-460a-8b9a-9c8db0566f57)

a:
