### ISSUE TITLE
Gauge Card Config : value_factor, decimals, unit (not working)

### ISSUE THREAD

**Issue by warlordattack** [kalkih/mini-graph-card#816]
Hello, i try to display donload/upload speed for my internet box.
I use docker Home Assistant core-2022.7.3 and Lovelace Mini Graph Card installed via HACS.

type: gauge
entity: sensor.freebox_download_speed
name: down
max: 125000
unit: ' '
value_factor: 0.015
decimals: 0

type: gauge
entity: sensor.freebox_upload_speed
name: up
max: 62500
unit: ' '
value_factor: 0.015
decimals: 0

The speed is displayed in kb/s, but i want display Mbps like speedtest.net
And i dont want decimals and unit.

So i use : 55550 (box kb/s)*0.015=833 (speed test Mbps)
value_factor: 0.015
but id doesn't work , i always see the kb/s value (55550) instead of Mbps (833) : after restarted HA

And i use decimals: 0
because i don't want decimals on screen, but decimals always display.

And i use unit: ' ' (one space caracter) to hide units,
how not display units at all ?  unit: '' don't work

Same problem for disk space value from HASS.Agent, it's displayed in mb and i want it in Gb.

Best regards :)

`        {
          "theme": "Backend-selected",
          "title": "fbx",
          "path": "freebox",
          "icon": "mdi:router-wireless",
          "badges": [],
          "cards": [
            {
              "type": "gauge",
              "entity": "sensor.freebox_download_speed",
              "name": "down",
              "max": 125000,
              "unit": " ",
              "value_factor": 0.001,
              "decimals": 0
            },
            {
              "hours_to_show": 1,
              "graph": "line",
              "type": "sensor",
              "entity": "sensor.freebox_download_speed",
              "detail": 1,
              "name": "down"
            },
            {
              "type": "gauge",
              "entity": "sensor.freebox_upload_speed",
              "name": "up",
              "max": 62500,
              "unit": " ",
              "value_factor": 0.001,
              "decimals": 0
            },
            {
              "hours_to_show": 1,
              "graph": "line",
              "type": "sensor",
              "entity": "sensor.freebox_upload_speed",
              "detail": 1,
              "name": "up"
            },`

![2022-07-17_210046](https://user-images.githubusercontent.com/3226486/179421062-1b3dfd36-9461-4379-838e-d102701ba701.jpg)
![2022-07-17_210550](https://user-images.githubusercontent.com/3226486/179421063-7bcad056-76a1-45d3-a4bd-2e7ba16da851.jpg)
![2022-07-17_210640](https://user-images.githubusercontent.com/3226486/179421064-194a2627-2ed5-4ebe-b303-c6264b930d3d.jpg)

**Comment by ildar170975** [comment]
This issue is not about mini-graph-card

**Comment by warlordattack** [comment]
Where can i report issue about value_factor, decimals, unit (not working) please ?
(i am not developper, i don't know where to go)

Best regards :)

**Comment by ildar170975** [comment]
Your code does not contain a code for mini-graph-card.
Many cards have options like "unit", "value_factor" etc.
You are using a standard "gauge" card.
Hence go to the homeassistant github and post an issue there.

**Comment by warlordattack** [comment]
.... You are using a standard "gauge" card ...

😒 i feel so bad now 

.... thank you, i am complete noob un home assistant, i didn't realize i used standard "gauge" 🤣
