### ISSUE TITLE
Dynamic Legend Colors

### ISSUE THREAD

**Issue by BlackCatPeanut** [kalkih/mini-graph-card#817]
I'm plotting the values for pollen for three preiods - today, tomorrow and today +2.

I'm using color_thresholds to colour the line but thought it would be a nice feature to make the legend colours dynamic as by using the color_thresholds negates the meaning of the legend colors.

Here is my current configuration for the graph:

`
type: custom:mini-graph-card
name: Pollen - Tree
hours_to_show: 72
animate: true
lower_bound: 0
upper_bound: 5
color_thresholds:
  - value: 0
    color: '#16a624'
  - value: 2
    color: '#ff7733'
  - value: 4
    color: '#cc4400'
entities:
  - entity: sensor.pollen_tree
    name: Today
    state_adaptive_color: true
  - entity: sensor.pollen_tree
    attribute: Tomorrow
    name: Tomorrow
    state_adaptive_color: true
  - entity: sensor.pollen_tree
    attribute: Today + 2
    name: Today + 2
    state_adaptive_color: true
`

This is the colored graph:

![image](https://user-images.githubusercontent.com/17835997/179492676-fcd34133-a06c-40ca-931a-8a87527f02d0.png)

And here is a focus on the Today +2 attribute where you can see the latest point colour is green:

![image](https://user-images.githubusercontent.com/17835997/179492775-4710b248-c3a1-41f6-8755-2709a94c2016.png)

I'm guessing this is a new feature request as the nature of a legend colour is to identify the line which it presents. However this is confused due to the Dynamic Line Color. Or it is a misunderstanding on my behalf.

**Comment by Epeedelorage** [comment]
Hello,
   I'm interrested to !
Thx for ur time

**Comment by michapr** [comment]
Yes, I think this is a good feature - to show the state using the defined colors. Maybe as option.
Thanks!
