### ISSUE TITLE
Feature Request: set min and max values manually

### ISSUE THREAD

**Issue by luixal** [kalkih/mini-graph-card#819]
Hi,

I'm using mini-graph-card to display the level of a PH- (or any liquid) tank. Everything is working as expected but I'm finding it quite hard to get visual feedback without paying attention to the numbers. Level is not going up and down (like temperature, for example) it goes up at some point and then it keeps going down slowly.

Thing is, when you just look over, you're not seeing important info, only the color thresholds you have set. It would be great to be able to set  min and max values manually. This way, I could set a min of 0 and a max of 100 so the graph shows all these values and a simple look at the card tells me how much PH- is left.

Does it make sense to you?

Thanks!

**Comment by ildar170975** [comment]
Use `lower_bound` option

**Comment by luixal** [comment]
That works great, thanks!
