### ISSUE TITLE
Cannot get sun.sun attribute to display

### ISSUE THREAD

**Issue by jchhenderson** [kalkih/mini-graph-card#821]
I am sure this is my error, but I cannot get it to work.

I am trying to display azimuth:
![Screenshot 2022-07-24 at 10 21 55](https://user-images.githubusercontent.com/34644672/180640668-7394ae53-c768-4bff-9eb6-27bb9181c53e.png)

![Screenshot 2022-07-24 at 10 22 08](https://user-images.githubusercontent.com/34644672/180640677-4089c8fe-496f-4468-a6cd-2152a4094db2.png)

It's getting the attribute as it is showing the correct angle, but I cannot get the line to show.  What basic error am I making?
![Screenshot 2022-07-24 at 10 22 41](https://user-images.githubusercontent.com/34644672/180640700-46ed28f9-37da-467d-89cf-9a6d393b76b2.png)

thanks!

**Comment by ildar170975** [comment]
Read release notes to HA. Sun’s attributes were excluded from Recorder

**Comment by jchhenderson** [comment]
I do read the release notes but obviously missed that.

Thanks.

**Comment by ildar170975** [comment]
https://www.home-assistant.io/blog/2022/04/06/release-20224/#breaking-changes

![image](https://user-images.githubusercontent.com/71872483/180655353-a579dd38-e7db-485b-a71f-92f58259d0e7.png)

**Comment by jchhenderson** [comment]
Thanks.  I now realise why I missed it; I wasn't using sun.sun then.
