### ISSUE TITLE
HA 2022.8.2 instructions don't seem to be working

### ISSUE THREAD

**Issue by Bart56** [kalkih/mini-graph-card#826]
I installed with HACS. js file is in config/www/community/mini-graph-card/

configuration.yaml file has:
`lovelace:
  resources:
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    type: js`

I've tried type: module and I've also tried url: /local/mini-graph-card-bundle.js, and others.

When I try to add a card using the gui, it does not show up as a choice, so I try to add it manual card and I get:
**`Custom element doesn't exist: mini-graph-card.**
type: custom:mini-graph-card
entities:
  - sensor.cpu_temp_f`
 
It's not clear from the instructions what else I should be doing but I did follow the 4 items listed if having errors.
I have restarted HA many times, but it seems as though the gui editor does not know about the custom card. HACS shows it as installed.
Else, if you prefer the graphical editor, use the menu to add the resource:
Instructions say:
Make sure, advanced mode is enabled in your user profile (click on your user name to get there) **[This is done]**
Navigate to Configuration -> Lovelace Dashboards -> Resources Tab. Hit orange (+) icon **>>>[This does not exist in 2022.8.2}**
Enter URL /local/mini-graph-card-bundle.js and select type "JavaScript Module".
(Use /hacsfiles/mini-graph-card/mini-graph-card-bundle.js and select "JavaScript Module" for HACS install) 

Note: I put the .js file in each of the directories 
config/www, 
config/www/community/, and 
config/www/community/mino-grapg-card/
I also put this in my config file:
`lovelace:
  resources:
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
`
Still, get the same error 
**Custom element doesn't exist: mini-graph-card**

Can this be clarified for the current HA version?

**Comment by Epeedelorage** [comment]
Hello,

Same for me
Core 2022.8.2 break my mini graphs
😭

Thx for ur help

**Comment by silverl** [comment]
Here to report the same.

Chrome Dev Tools is reporting '500 Internal Server Error\n\nServer got itself in trouble'

**Comment by Bart56** [comment]
UPDATE:

Sometime overnight last night, the mini-graph-card started working. I did not reboot. I was using that particular lovelace page yesterday and since I left the card on it showing the error, I went back to the page today and there was a graph.

Since it was a minimal configuration, I decided to edit it. It showed the 2 lines of yaml code:
type: custom:mini-graph-card
entities: sensor.house_temp

But it would no longer let me edit manually showing the note:
No visual editor available for type 'custom:mini-graph-card'.

So I can't say this is a bug, but simply inexplicable behavior.
Thanks.

**Comment by ildar170975** [comment]
> type: custom:mini-graph-card
> entities: sensor.house_temp

Wrong code.
Ref docs for a proper usage.

**Comment by Bart56** [comment]
type: custom:mini-graph-card
entities:
  - sensor.cpu_temp_f

**Comment by ildar170975** [comment]
@Bart56 
I edited your comments to format a code.
Please insert a code into triple "`" - otherwise in most cases it is impossible to analyse a code.

> But it would no longer let me edit manually showing the note:
> No visual editor available for type 'custom:mini-graph-card'.

What I see when I select a "mini-graph-card" from a list of cards:
![image](https://user-images.githubusercontent.com/71872483/185241533-4e658524-1703-4852-8e9c-a0f46264f9d8.png)

YES - the card does not have a possibility to edit itself via UI.
Currently it is editable via yaml only.
I myself do not consider this as a bug.
This is just a lack of functionality.

Do not afraid of using yaml.
Yes, there is a current trend "let's use only UI-manageable integrations & deprecate yaml-settings" - which is hated by many people. But anyway you still have to use yaml a lot. For example - to setup custom cards.

**Comment by Bart56** [comment]
Agreed. Thanks for the feedback.
The last change I made was to put multiple copies in several directories as
I mentioned above. But it still didn't work.
I wish I  knew why it started working overnight but I think you can close
this issue.

**Comment by ildar170975** [comment]
> but I think you can close

No, this is what YOU should do if you think that your issue is resolved.

**Comment by Bart56** [comment]
Oops - got it. Thanks!
