### ISSUE TITLE
Upgrade to the released lit-element package

### ISSUE THREAD

**Issue by justinfagnani** [kalkih/mini-graph-card#85]
The `@polymer/lit-element` npm package has been moved to `lit-element`. `@polymer/lit-element` is deprecated and not receiving any updates, so please upgrade to `lit-element@^2.0.0` as soon as possible.

Thanks!

**Comment by kalkih** [comment]
Is this a bot? I've already switched over a long time ago.
https://github.com/kalkih/mini-graph-card/blob/a2a8870f4150cf54dd211ddda6283739119a953e/package.json#L22
