### ISSUE TITLE
Mini graph card is displaying the most recent data point instead of the binned total

### ISSUE THREAD

**Issue by lennon101** [kalkih/mini-graph-card#853]
Just wondering if there is a way to display the current value of the binned column? Currently, I have a 0.2mm rain bucket that is being sampled and sent to Thingspeak every 5mins. I am then binning the data into 1hr bins. This is working great except for the value circled which is displaying the most recently posted data (in the last 5mins) instead of the value of the column, which in this case is 0.4mm of rain (see the second screenshot where I hover over the column)

![image](https://user-images.githubusercontent.com/1709944/197116695-7f58a031-4a24-4412-a69a-bdd24b820ea3.png)

![image](https://user-images.githubusercontent.com/1709944/197116704-277a7c59-52da-4635-bd1f-f76d83a8ac08.png)

**Comment by wonderiuy** [comment]
+1 for this

**Comment by ildar170975** [comment]
@lennon101 
1. No code is posted.
2. The initial question is unclear.

Is this issue still valid?
