### ISSUE TITLE
Attribute value not shown

### ISSUE THREAD

**Issue by gonzzovela** [kalkih/mini-graph-card#864]
Hi,

I'm trying to show an entity's atribute and the card does not extract any value (NaN)

type: custom:mini-graph-card
name: Temperatura
entities:
  - entity: climate.salon_soto
    atribute: current_temperature

The entity is a Netatmo thermostat:

These are the attributes shown in the developer tools:
hvac_modes:
  - auto
  - heat
  - 'off'
min_temp: 7
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - away
  - boost
  - Frost Guard
  - Schedule
friendly_name: Salón Soto
supported_features: 17
current_temperature: 17.4
temperature: 5
hvac_action: idle
preset_mode: Frost Guard
attribution: Data provided by Netatmo
selected_schedule: Mi programa

Furthermore, if I create an entity card and select the same attribute, it works without any problem:
type: entity
entity: climate.salon_soto
attribute: current_temperature

Thanks for your help

**Comment by ildar170975** [comment]
1. Please edit your post - use a formatting for a code. Place a code into triple "`".
2. Test the same card with an attribute from another entity (`sensor`, not `climate`).

**Comment by gonzzovela** [comment]
> 1. Please edit your post - use a formatting for a code. Place a code into triple "`".
> 2. Test the same card with an attribute from another entity (`sensor`, not `climate`).

thanks for the hint.

Using the entity sun, I was able to make it work and from there I was able to replicate it for the netatmo thermostat entity.

type: custom:mini-graph-card
entities:
  - entity: climate.mi_habitacion
    attribute: current_temperature
    
    all is working.
    
    Sorry if I mislead you.
