### ISSUE TITLE
Jitters with name: ' '

### ISSUE THREAD

**Issue by kloggy** [kalkih/mini-graph-card#87]
For a full description (and explanation, and indeed solution!!) see https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/505

Having ```name: ' '``` causes the graph card and all cards in the same column below it to jitter when hovering over a point on the graph.

The solution is 

```
show:
  name: false
```

But a coded solution to remove the possibility of it occurring might be to 

"add a min height to the name? unless it’s hidden or something"

**Comment by kalkih** [comment]
Thanks, fixed in the latest release.
