### ISSUE TITLE
[Question] color_thresholds paramter (Line color object)

### ISSUE THREAD

**Issue by yu-tendo** [kalkih/mini-graph-card#873]
Hello,

I am confused as I cannot map the behavior which I observe to the actual documentation. I hope someone can help me :) 

The documentation says that the color_thresholds parameter takes a list of Line color objects. The Line color object is initalized with "value" and "color". The parameter value is described as "The threshold for the color stop." If we now pass the following list to color_thresholds:

```
    color_thresholds:
      - value: 18
        color: "#CC3333"
      - value: 21
        color: "#6600FF"
```
(These are web safe hex codes).

I would now expect that everything below and including 18 is `#CC3333` (as 18 is the "color stop"). Then it should turn into `#6600FF` until 21. (Which color is used after 21?)

In practice, I observe a total different behaviour. As you can see on the attached image, the red color is visbile above 18 (the marked dot is 19,9). Please note that I set `color_thresholds_transition: hard`. It is unclear to me why this is happening (as the stop threshold for red is 18).

What I would like to have is: below value X, color a; bteween X and Y, color b, and above value Y, color c. How can I do this?

Thank you!

![example](https://user-images.githubusercontent.com/72860114/204042542-8981d0ce-6692-465a-8cda-0042d6255ccd.png)

**Comment by timo-sztyler** [comment]
Hello,

I had some time and looked at the source code. To my understanding the following part is responsible:

`

intColor(inState, i) {
    const { color_thresholds, line_color } = this.config;
    const state = Number(inState) || 0;

    let intColor;
    if (color_thresholds.length > 0) {
      if (this.config.show.graph === 'bar') {
        const { color } = color_thresholds.find(ele => ele.value < state)
          || color_thresholds.slice(-1)[0];
        intColor = color;
      } else {
        const index = color_thresholds.findIndex(ele => ele.value < state);
        const c1 = color_thresholds[index];
        const c2 = color_thresholds[index - 1];
        if (c2) {
          const factor = (c2.value - inState) / (c2.value - c1.value);
          intColor = interpolateColor(c2.color, c1.color, factor);
        } else {
          intColor = index
            ? color_thresholds[color_thresholds.length - 1].color
            : color_thresholds[0].color;
        }
      }
    }

    return this.config.entities[i].color || intColor || line_color[i] || line_color[0];
  }`

**Comment by timo-sztyler** [comment]
closed on accident

**Comment by ildar170975** [comment]
> The threshold for the color stop

I am not a native English speaker.
Cannot say what a "stop" is supposed to mean.
In fact - it works in an opposite way:
> I would now expect that everything below and including 18 is #CC3333 (as 18 is the "color stop"). Then it should turn into #6600FF until 21. (Which color is used after 21?)

i.e.
>= 18 -> #CC3333
>= 21 -> #6600FF

A small example:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/b8b57217-6ca4-423a-b3cf-6c310bd161ba)

**Comment by ildar170975** [comment]
Close the issue if resolved.

**Comment by yu-tendo** [comment]
Thank you very much for the detailed answer @ildar170975 

There is one aspect which is not covered by your answer (and also not by the documentation) -and this missing details lead to my confusion in the first place:
In your example, you write "Sensor's value starts from 0 (minimal value).", but what is the behaviour if there is (for whatever reason) a value smaller than 0? Which color is used? (Alternatively, looking at my original example, which color is applied for a value smaller than 18?)

**Comment by ildar170975** [comment]
>  a value smaller than 0

You may find out this by yourself)))
But anyway - suggest to always define the 1st value as a minimal possible (guess you know possible values for every sensor).

Any other questions?

**Comment by yu-tendo** [comment]
Not a satisfying answer but I don't complain. You at least confirmed my assumptions. Thank you!

I don't have another question but a request: Please change/adapt the description of this field in the ReadMe file. I think our discussion made at least clear that there are (non obvious) assumptions.

**Comment by ildar170975** [comment]
> description of this field in the ReadMe file

PR is already made.
