### ISSUE TITLE
display dates under x-axis, and scale y-axis

### ISSUE THREAD

**Issue by paqpaqpaq** [kalkih/mini-graph-card#874]
Is there a possibility to show the dates under the x-axis when the values are sorted by date?
In addition to that I would to know whether I can influence the scale on the y-axis.
When values are close to each other, it is hard to differentiate the changes based on the two small labels on the left (labels: true)

**Comment by madasus** [comment]
+1 for the ability to add values on the x-axis

**Comment by Nicwalle** [comment]
+1 for the x-axis as well

**Comment by Svarstad** [comment]
Is there any update on this? this would be a highly useful feature. Now I'm speaking for the x-axis part.

**Comment by ildar170975** [comment]
Dates for X,Y-axis are here: https://github.com/kalkih/mini-graph-card/issues/739
Gridlines here: https://github.com/kalkih/mini-graph-card/issues/837

Closing as a duplicate.
