### ISSUE TITLE
Placement of multiple show_state entities

### ISSUE THREAD

**Issue by studiostevus** [kalkih/mini-graph-card#896]
The location of mutiple entities which show_state is true seems arbitrary. I would like to display the state of 4 values on the left and right of the box. 
- Left: Solar consumption (W) and power (kwh) for solar set 1
- Right: Solar consumption (W) and power (kwh) for solar set 2

The below places the W of set 1 on the left, and the rest on the right.

`- type: custom:mini-graph-card

                entities:
                  - entity: sensor.current_pv_production_roof
                    name: Solar Roof
                    show_state: true
                  - entity: sensor.solar_production_roof_daily
                    name: Solar Roof
                    show_state: true
                    show_line: false
                    show_fill: false
                    show_legend: false
                  - entity: sensor.current_pv_production_garage
                    name: Solar Garage
                    show_state: true
                  - entity: sensor.solar_production_garage_daily
                    name: Solar Garage
                    show_state: true
                    show_line: false
                    show_fill: false
                    show_legend: false
                name: Solar Production
                hours_to_show: 24
                points_per_hour: 12
                font_size: 75
                line_width: 2`

**Comment by ildar170975** [comment]
Not arbitrary. 
It is by design: if more than 2 states are to be displayed, the 1st is displayed on the left, others - on the right. 

So, what is this issue about?

**Comment by ildar170975** [comment]
Closing as unanswered.
