### ISSUE TITLE
Fill to be between line and zero

### ISSUE THREAD

**Issue by layanto** [kalkih/mini-graph-card#899]
Is it possible to configure fill to be between line and zero? I want to mimic the graph below from Sungrow's iSolarCloud. Presently the fill appears to be between line and bottom of graph regardless of whether line value is positive or negative and regardless if bottom of graph is zero or negative.

![Screenshot_2022-12-29-12-52-41-413_com.isolarcloud.manager.jpg](https://user-images.githubusercontent.com/245078/209893232-53d8aa5c-f0d6-44f9-9781-44487b9cd529.jpg)

This is what it looks like presently in HA.
![Screenshot_2022-12-29-12-47-05-762_io.homeassistant.companion.android~2.jpg](https://user-images.githubusercontent.com/245078/209892973-e58a9888-ca73-4280-ab4b-78b073c827da.jpg)

**Comment by ildar170975** [comment]
Duplicates https://github.com/kalkih/mini-graph-card/issues/630
