### ISSUE TITLE
accuracy of 25 results in incorrect graph

### ISSUE THREAD

**Issue by bmesuere** [kalkih/mini-graph-card#9]
When setting the accuracy to 25, the last data point seems to be set to the max value of the graph. A lower value doesn't have this problem.
25:
![image](https://user-images.githubusercontent.com/481872/46856794-b9142c00-ce07-11e8-99a2-271935b8762f.png)

24:
![image](https://user-images.githubusercontent.com/481872/46856831-cf21ec80-ce07-11e8-915b-d4548e28a88e.png)

raw data:
![image](https://user-images.githubusercontent.com/481872/46856858-e19c2600-ce07-11e8-968b-eb846ab992f3.png)

**Comment by kalkih** [comment]
Fixed in [v0.0.6](https://github.com/kalkih/mini-graph-card/releases/tag/v0.0.6)
