### ISSUE TITLE
Feature Request: Gradual change of graph colour depending on value

### ISSUE THREAD

**Issue by DoctorOctagonapus** [kalkih/mini-graph-card#90]
How difficult would it be to have a "heat map" style graph that gradually changes colour depending on value rather than have the colour change at a particular threshold? For example define a lower limit as one colour, an upper limit as another, and the line fades between the two depending on what the value is.

For example a temperature sensor that fades gradually between blue and red/yellow the higher the temperature.

**Comment by kalkih** [comment]
Hey,
I think what you are asking for should now be possible in the latest update, thanks to https://github.com/kalkih/mini-graph-card/commit/d86c1eed40ec93fd71874ae0a63b8e156f096b8e
The color thresholds are now rendered vertically instead of horizontally and therefore the "fade/blend" between thresholds could be made much smoother.

**Comment by DoctorOctagonapus** [comment]
Hey, I see what you've done but it wasn't what I had in mind. My bad, I think I was a bit too vague.

Say I create a graph based on a sensor. I set two thresholds, one with a value of '0' and a colour of '#000000', and the other with a value of '100' and a colour of '#ff0000'. Is it possible to have some kind of gradient mode, where if the sensor returns a value of 50 the colour is rendered as '#770000', or with a value of 25 it renders '#330000', and so on?

**Comment by kalkih** [comment]
Still not entierly sure what you mean, do you want the graph to be rendered as a single color?

Not like this?
![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/57958336-d9591b80-78ff-11e9-8350-554da1d8f1b0.png)

If you want a single (dynamic) color, no that's not possible, but I would suggest looking at creating a template sensor where you based on some data calculate the desired color, then a [config-template-card](https://github.com/custom-cards/config-template-card) to dynamically set the color of the mini-graph-card config from the template sensor state.
