### ISSUE TITLE
Actual Value is shown instead of 0 on mouse hover over 0 value

### ISSUE THREAD

**Issue by TobiasSchwarz74** [kalkih/mini-graph-card#900]
When you hover over a 0 value in the bar graph, the value is not shown.
Instead, the actual value is still shown. 

View without mmouse hover:
![image](https://user-images.githubusercontent.com/66618167/210068969-28fc8db5-2ddf-41a4-9e8f-5b26e8cccaee.png)

View when hovering over 0 value:
![image](https://user-images.githubusercontent.com/66618167/210069034-7aae2abc-b0a2-4e02-a30f-41b9ec710f13.png)

**Comment by akloeckner** [comment]
Duplicate #805 ?

**Comment by TobiasSchwarz74** [comment]
yes, it's a duplicate to #805 - sorry, searched for it, but didn't find this one.

**Comment by ildar170975** [comment]
Closing as a duplicate
