### ISSUE TITLE
Graph / Bar shows incorrect Data (some value instead of zero)? 

### ISSUE THREAD

**Issue by marczai** [kalkih/mini-graph-card#902]
Good Morning,

i dont know why but somehow the graph get values (0,39) even there should be zero.

![image](https://user-images.githubusercontent.com/96234674/211258808-5979802d-1b75-4174-9cdd-cf0a2b6b383e.png)

Here in the real entity i see its zero:

![image](https://user-images.githubusercontent.com/96234674/211258620-254a7db1-1084-4e0c-8285-78a4438eba39.png)

I used this minimal config to test it:

`
type: custom:mini-graph-card
entities:
  - entity: sensor.gas_hourly
hours_to_show: 24
points_per_hour: 60
`

Thanks for your replies

**Comment by Tontze** [comment]
Do you mean selected point on the timeline ? Same goes with BARs, when power consumption has been zero, howering over zero consumption bar, it just shows recent consumption. If bar has consumption, it shows it correctly.

**Comment by ildar170975** [comment]
duplicate https://github.com/kalkih/mini-graph-card/issues/805
