### ISSUE TITLE
[Question] secondary Y-axis night time

### ISSUE THREAD

**Issue by Pimentoso** [kalkih/mini-graph-card#903]
Hello, this is probably not the right place to ask this, feel free to redirect me somewhere else

I find adding a night overlay on 24-hour charts really useful, like in this example:
https://github.com/kalkih/mini-graph-card#alternate-y-axis

Is there a way to configure the day/night axis to pull data from the sun entity?

**Comment by ildar170975** [comment]
> Is there a way to configure the day/night axis to pull data from the sun entity?

A graph is build based on a particular entity, not some template.
You have to create a template sensor for day/night and then use this sensor for the 2nd axis.

Please ask similar questions in the [Community](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1) and leave Github for reporting bugs & feature requests.
Let us know if you are satisfied with this answer, then the issue will be closed.
Any further discussions may be continued in the Community.

**Comment by michele-ferri-iubenda** [comment]
Thanks @ildar170975 I still have a long way to go with yaml sensor syntax. This example is good enough for my use! Feel free to close this. I will use the community thread next time.
