### ISSUE TITLE
Anyway to use show_graph toggle with button

### ISSUE THREAD

**Issue by humanBeer** [kalkih/mini-graph-card#905]
Im trying to Toggle graphs by clicking on an icon from a different crad. Is there any way to do this?

![image](https://user-images.githubusercontent.com/47748428/211875779-3acd126a-d140-4306-9051-90c86882e22e.png)

The icons are from mushroom template card
![image](https://user-images.githubusercontent.com/47748428/211876365-a2377f91-6b5d-4980-a9c4-495ff167d059.png)

**Comment by humanBeer** [comment]
maybe something like this:
```
                    show_graph: |
                      {{ states('input_boolean.test_graph_icon') }}
```
But i don't think that's supported?

**Comment by ildar170975** [comment]
Duplicate. 
https://github.com/kalkih/mini-graph-card/issues/697
