### ISSUE TITLE
Font Color Treshhold Feature Request

### ISSUE THREAD

**Issue by sgtpepperaut** [kalkih/mini-graph-card#910]
Just like in grafana it would be great if the font / value itself could also be displayed with color treshhold for a clear visual on dashboards (ie something is red needs attention)

https://i.imgur.com/0oe16pQ.jpg
something like:
https://i.imgur.com/eZhIJ8s.jpg

**Comment by ildar170975** [comment]
1. Place images INSIDE your post, not as links to other sites.
2. Elaborate what you want with details and examples. Otherwise your issue may be understood in a wrong way. If you are asking about using same colors for a "state" label and a graph's line - it is already supported, check docs.

**Comment by ildar170975** [comment]
No feedback from OP for a year.
Closing.
