### ISSUE TITLE
Feature Request: Hide header + icon

### ISSUE THREAD

**Issue by Nornode** [kalkih/mini-graph-card#921]
In order to save space on a camped dash, I would want to hide the header bar + icon.
And the first thing upper left /right corner can be the current state. Please see the screenshot.
![Screenshot 2023-02-15 at 15 08 18](https://user-images.githubusercontent.com/10966757/219036216-01c099b2-89a1-464a-b85d-fa321a8e5203.png)

**Comment by ildar170975** [comment]
Miracle!!!
![image](https://user-images.githubusercontent.com/71872483/219066665-e7d59981-0d7f-420f-9154-52c73c548a2e.png)

**Comment by Nornode** [comment]
Okay, I'm hiding here under a rock for a while... 😊
