### ISSUE TITLE
Zero is not zero, but last read in bar graph ? 

### ISSUE THREAD

**Issue by Tontze** [kalkih/mini-graph-card#925]
My bar graphs (electric consumption) has zero lines, or very small usage which propably is rounded to zero, but when hovering over, they show last consumption read, i believe... 

Below small green bars are zero, but now they show up as 104W ...

![image](https://user-images.githubusercontent.com/28216916/219934867-9fe97993-1066-41a7-bb28-6e71a08d76dd.png)

**Comment by ildar170975** [comment]
Duplicate https://github.com/kalkih/mini-graph-card/issues/805
