### ISSUE TITLE
Feature Request - add ability to capture future / forecasted data to graph (OpenWeathermap forecast data) 

### ISSUE THREAD

**Issue by DeFlanko** [kalkih/mini-graph-card#929]
With the hours_to_show being historical time, please find a way to add in hours_to_show_future for future data predictions. 

In my example, OpenWeatherMap uses future predications for ran precipitation forecasting, it would be nice to see that in a line graph on the upcoming 7 or 10 days

**Comment by ildar170975** [comment]
The card uses DB to get data. 
This is the only source. 
The card will not predict data. 

If some integration like OpenWeatherMap creates sensors containing data describing a “future” (like “a set of values for tomorrow”, “a set of values for a day after tomorrow”, …) - then you can create template sensors to keep these forecast data and build your graphs.

**Comment by ildar170975** [comment]
This mainly about accessing complex attributes.
Implemented in https://github.com/kalkih/mini-graph-card/pull/996.
Closing
