### ISSUE TITLE
[Feature Request] Hide label background option

### ISSUE THREAD

**Issue by brpeterso** [kalkih/mini-graph-card#934]
I love the simplicity of the mini-graph-card.  One thing that defies the simplistic/minimalistic look is the label background.  In some cases, it may be handy to have it, otherwise it can make the card look clunky.  Is there any way to add an option to hide the label backgrounds?  Example below shows how it could benefit if there wasn't a label background.  If there is a way to do this in CSS, please let me know.... I haven't been able to find one yet.  Thanks!

![image](https://user-images.githubusercontent.com/24624605/222923356-c0baf252-b3d7-4dcf-a268-b2a36698788e.png)

**Comment by Doug-Wyman** [comment]
I think the "show" options are what you need. https://github.com/kalkih/mini-graph-card#available-show-options

**Comment by brpeterso** [comment]
I want to show the labels, so labels: true is correct in this case.  I just want to remove the background to the label so you only see the number (in my example above, it's the dark "oval" around the number that I want to hide).

**Comment by ildar170975** [comment]
Probably the person asked about possibility to remove rounded areas under labels. 
It is possible by card-mod. 
A bit later I will post here a solution.

**Comment by brpeterso** [comment]
> Probably the person asked about possibility to remove rounded areas under labels. It is possible by card-mod. A bit later I will post here a solution.

Have you had a chance to look into this?  Thanks.  I looked in the card-mod and mini-graph-card ha forums to see if there were any updates.

**Comment by ildar170975** [comment]
@brpeterso 
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/2273?u=ildar_gabdullin

You may close the issue if you are satisfied with this workaround .
If you still need a corresponding option - then let us know.

**Comment by brpeterso** [comment]
@ildar170975 ,
This still leaves the rounded areas behind the label, but with transparency its actually still a huge improvement from what I had before.  Thanks.
![image](https://user-images.githubusercontent.com/24624605/223593310-8c426d3d-df02-4a4a-a7e6-f5bf3c2e05f2.png)

**Comment by ildar170975** [comment]
@brpeterso 
Add `box-shadow: none`:
![изображение](https://user-images.githubusercontent.com/71872483/223600939-971a164a-d319-4943-8558-98bb62045495.png)
