### ISSUE TITLE
Maxima showing the wrong value

### ISSUE THREAD

**Issue by fschwarz86** [kalkih/mini-graph-card#936]
Hi there,

unfortunately, the maxima feature doesn't seem to display the right value. I have stripped down the code to the very minimum:

```
entities:
  - entity: sensor.speedtest_ping
type: custom:mini-graph-card
```

As you can see from the screenshot, the maxima is already showing the wrong value (Max is 5ms, while current value is already 12ms):

![Screenshot 2023-03-07 11 15 36](https://user-images.githubusercontent.com/67014654/223393179-241e7b90-81b4-459f-957c-404e8800f0ec.png)

I'm using mini-graph-card v0.11.0 and HA 2023.3.1

Any idea what I'm doing wrong?

Thanks,
Florian

**Comment by ildar170975** [comment]
1. I doubt the you posted a valid card's picture since it shows "extrema" data - which is not supposed to be displayed by default (https://github.com/kalkih/mini-graph-card#available-show-options).

2. Do not use default values for important options.
Set:
`ponts_per_hour` same as a real update freq
`smoothing: false`
`aggregate_func: last`

**Comment by ildar170975** [comment]
You have not set hours_to_show and have not provided info about a real update freq.

**Comment by fschwarz86** [comment]
From reading the documentation, I was under the assumption that hours_to_show defaults to 24 if not set, but I've included it in the code. Output remains unchanged. Real update frequency is 1 per hour. Therefore, as per your recommendation, I've set points__per_hour to 2.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.speedtest_ping
show:
  extrema: true
points_per_hour: 2
smoothing: false
aggregate_func: last
hours_to_show: 24
```
![Screenshot 2023-03-07 17 20 03](https://user-images.githubusercontent.com/67014654/223483544-dd40aa82-1cd1-4949-92d4-f6c98557dfe8.png)

Here's the output from history graph:

![Screenshot 2023-03-07 17 21 23](https://user-images.githubusercontent.com/67014654/223483945-931a25ef-8085-4915-9749-3a04c2d65f19.png)

**Comment by ildar170975** [comment]
Your History view shows that is about 17:30 and your mini-graph says that extrema is 9:50PM - why? Are these graphs made at the same time ore be you posted a mini-graph from another day?

**Comment by ildar170975** [comment]
Hmmm, try clearing a browser cache...

**Comment by fschwarz86** [comment]
Tried that, doesn't help...

**Comment by ildar170975** [comment]
What HA do you use?
I am using 2023.3.0, just updated to 3.1

**Comment by markgllin** [comment]
experiencing the same issue with other entities, e.g. temperature, download/upload speed, and is not limited to maxima, but also minima, avg., and datapoints as well.

For instance, with temperature:
![image](https://user-images.githubusercontent.com/10660708/224569141-347e6ffb-8e24-4e7c-b975-455e5a5ac3e9.png)
temperature here reports a max of 99 Celsius (obviously incorrect). On hovering over one of the datapoints, the reported values are also incorrect. This can be seen by comparing it to the native history-graph in homeassistant, which shows the highest temp is only 8.9 Celsius:
![image](https://user-images.githubusercontent.com/10660708/224569257-4b7fd24d-4852-4baf-8dd4-b9f92aa31254.png)
![image](https://user-images.githubusercontent.com/10660708/224569399-537eaa80-2be4-46ca-beec-9a2c136597e5.png)
Card configuration:
```
type: custom:mini-graph-card
entities:
  - sensor.vancouver_temperature
show:
  extrema: true
  minima: true
```
Currently using Home Assistant 2023.3.3 w/ the latest frontend (Frontend 20230309.0 - latest) in a docker container.
Using v0.11.0 of the Lovelace Mini Graph Card.

**Comment by ildar170975** [comment]
@markgllin 
https://github.com/kalkih/mini-graph-card/issues/933#issuecomment-1464932117

**Comment by NiamoR42** [comment]
Hello, 
it looks like I have the same issue :
![image](https://user-images.githubusercontent.com/74781726/224842281-f568497c-bf04-462c-88df-68c6c6f11ccc.png)
![image](https://user-images.githubusercontent.com/74781726/224842349-f0ccf717-81a0-44cd-a6a3-57bfb0fc21e3.png)

the code is so simple, I don't understand what's wrong ?!
`type: custom:mini-graph-card
entities:
  - sensor.co2
`

**Comment by ildar170975** [comment]
@NiamoR42 read one post above

**Comment by NiamoR42** [comment]
> @NiamoR42 read one post above

Hello & thanks for your feedback : that looks better today, don't know why... I did not change anything...

**Comment by ildar170975** [comment]
@NiamoR42 
Your code which you [posted](https://github.com/kalkih/mini-graph-card/issues/936#issuecomment-1467031377) could be WRONG. It has default values which probably make your graph absolutely different from a real picture. Even looking at the History from more-info popup (which is also WRONG since this is not a real data but an approximate statistics) I see a difference between your `mini-graph` & History.
I recommended what you should do. Not it looks that I am begging you to improve your setup.

**Comment by ildar170975** [comment]
Is this issue still observed?

**Comment by ildar170975** [comment]
No feedback within 3.5 months, closing
