### ISSUE TITLE
Feature Request: Tap Action

### ISSUE THREAD

**Issue by jer78** [kalkih/mini-graph-card#94]
Is it possible to incorporate tap action into the card? I’d like the ability to run a script or navigate to a new view with the graph. Obviously this would overwrite the ability to click on the chart to view data but in some instances I’d like to just see a graph and build a whole new view with more info or a bigger version of the graph.

**Comment by kalkih** [comment]
Now available in the latest release with the new `tap_action` option, configureable through the [action object](https://github.com/kalkih/mini-graph-card#action-object-options).
