### ISSUE TITLE
Change color line graph with value

### ISSUE THREAD

**Issue by DonCastor** [kalkih/mini-graph-card#943]
Hello Community !

I'm trying to do a simple thing, but it seems that i'm taking it on the wrong side!

I have created cards where I display temperature and humidity of the room (on that no issue). The temperature icon, is colored with different values as you can see below :

![image](https://user-images.githubusercontent.com/60355611/227218399-39197c6f-88aa-43ff-a1ac-a5f3205bea05.png)
It's working fine and I have the right color with the right temperature.
But when I want to apply this scheme to my mini-graph-card, it's not working : I just want to have my graph-line with the same color as my icon...

For that, here is the code : 

![image](https://user-images.githubusercontent.com/60355611/227218862-452170f0-26b6-44aa-8ed0-884540159618.png)

This is driving me crazy, I'm sure it can work, but I don't understand why it is not.

If any of you has any idea ? I would appreciate !

**Comment by ildar170975** [comment]
Already supported by color_thresholds

**Comment by DonCastor** [comment]
Hi,

The color_treshold behaviour is not what I want.

I want the whole graph to be from the color I put in parameter, not the threshold.

Regards,

**Comment by DonCastor** [comment]
> Already supported by color_thresholds

Hi,

The color_treshold behaviour is not what I want.

I want the whole graph to be from the color I put in parameter, not the threshold.

Regards,

**Comment by ildar170975** [comment]
> For example, If my temperature is 19, I want the whole graph line in green.
> If my temperature is 22, I want the whole line to be in red.

I see.
Then I suggest you to add your comments here - https://github.com/kalkih/mini-graph-card/issues/697
That issue is about a possibility to use templates for options.
