### ISSUE TITLE
deleteed

### ISSUE THREAD

**Issue by ghost** [kalkih/mini-graph-card#948]
deleted

**Comment by ams3401** [comment]
https://github.com/kalkih/mini-graph-card/pull/202

Looks like the feature was already added but doesn't work as designed

**Comment by akloeckner** [comment]
Maybe, those lines should be more alike:

https://github.com/kalkih/mini-graph-card/blob/210fb4c2ccdc3fe4ec95e9f6d82eb4e220405a5a/src/main.js#L195

https://github.com/kalkih/mini-graph-card/blob/210fb4c2ccdc3fe4ec95e9f6d82eb4e220405a5a/src/main.js#L284

https://github.com/kalkih/mini-graph-card/blob/210fb4c2ccdc3fe4ec95e9f6d82eb4e220405a5a/src/main.js#L333

**Comment by jlsjonas** [comment]
@akloeckner good find! We'll indeed have to reference `config.tap_action.entity` for other popups too, is this something you would like to try picking up? (if config is available on those lines, it would be as simple as prepending `this.entity` with `config.tap_action.entity || `)

**Comment by akloeckner** [comment]
If we follow #937, we should be hesitant to add new options and interweave them with existing code.

I'll want to move on with the pending bug fixes first, before looking into this. But time is sparse currently. :-/

**Comment by ildar170975** [comment]
@ghost
Deleting your posts describing the issue has no sense.
Inappropriate behavior.
