### ISSUE TITLE
Problem with input_numbers when using pre-release v0.12.0

### ISSUE THREAD

**Issue by Ndrinta** [kalkih/mini-graph-card#962]
Hi guys, I've always used a helper to show the '0' line on a graph, but after upgrading to v0.12.0 the entire card just won't show anything.

```
  - entity: input_number.zero
    color: '#0C0C0C'
```

I if then remove the entity from the list it'll start showing the other entities again, and if I downgrade to v.11.0 everything works again.

Is it possible that you broke compatibility with this feature unintentionally?
Thanks

**Comment by ildar170975** [comment]
@Ndrinta 
Compare with https://github.com/kalkih/mini-graph-card/issues/960
Close the issue if it duplicates.

**Comment by ildar170975** [comment]
Must be solved in 12.dev-3

**Comment by Ndrinta** [comment]
Looks OK. Thanks
