### ISSUE TITLE
Forecasted weather data in a chart? 

### ISSUE THREAD

**Issue by quadcom** [kalkih/mini-graph-card#963]
Still wrapping my head around HA, I found your plugin from a YT vid.

I am pulling weather data from Openweather. The entity is 'sensor.openweathermap_forecast_temperature'. That entity has 7 days of data in it. I'd like to get the graph to show the forecasted 7 days.

I saw another post/request for array data. Could this be the same thing? 

Is there any way to graph this forecasted data?

**Comment by akloeckner** [comment]
Possible duplicate: #929 
Possibly related: #942 (I guess, that's the other post you saw.) 

Yes, I believe it is the same thing.

But no, I cannot think of a way to do this in mini-graph-card, because using historic data is hardcoded.
