### ISSUE TITLE
Double trouble

### ISSUE THREAD

**Issue by TMRE** [kalkih/mini-graph-card#966]
Once I have Mini Graph Installed on HACS. I go to add UI Loveland Minimalist within integrations and I get two tabs, neither work.

![image](https://github.com/kalkih/mini-graph-card/assets/78712812/048b6b21-5033-4087-a3fb-af21f5232b44)

**Comment by ildar170975** [comment]
Suggest you to ask this question in a corresponding thread in Community for Minimalist.
