### ISSUE TITLE
bar/chart value decimals missing

### ISSUE THREAD

**Issue by cryptooth** [kalkih/mini-graph-card#968]
Hi there,

I have some mqtt sensors (without measurements unit, completely custom sensor) 

Sensor value is ok but bar/chart values displayed as rounded or no decimals.

<img width="254" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/28625750/64d7e7c6-ce24-4213-aa5b-de82ded66e02">

any suggestion?

best,
belek

**Comment by cryptooth** [comment]
problem solved, after changing point to comma

**Comment by ildar170975** [comment]
Closing since the author said "solved"
