### ISSUE TITLE
CAnnot seem to get tap_action to work.

### ISSUE THREAD

**Issue by bert269** [kalkih/mini-graph-card#975]
I defined a graph with mini-card and it works fine. What I need to do is when click/tap upon, I need the entity to appear, to change the temperature. This is for a Google Nest thermostat.
The entitiy id to control the temo is called: climate.entryway
The sensor (for the graph display) is called: sensor.entryway_temperature

The graph displays fine, but when I click on the graph , nothing happens.
This is the code I use:
![image](https://github.com/kalkih/mini-graph-card/assets/18601216/2248107c-9d10-4239-9a7e-fcefd701895f)

I tried action: more-info with entity: climate.entryway - same result.
I also tried action: call-service with service (or service_data): climate.entryway - nothing is displayed either.

Thank you

**Comment by bert269** [comment]
Please close - no issue.

**Comment by ildar170975** [comment]
1. Please do not post images of a code, post a formatted code (wrapped in triple "`").
2. Refer to [Docs](https://github.com/kalkih/mini-graph-card#action-object-options), a syntax for your `tap_action` part is wrong, must be a dictionary instead of a list.
