### ISSUE TITLE
Safari / MacOS - graph not rendered

### ISSUE THREAD

**Issue by furstyferret-dev** [kalkih/mini-graph-card#985]
I've started seeing an error on Safari (Somona public beta) where the graph is not rendered but the state information is. 

<img width="554" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/56730846/b3368e52-99db-4a73-b535-05cad9e12642">

There are numerous Javascript warnings recorded:
[Warning] mini-graph-card:  – "value [20.6] not found in state_map" (mini-graph-card-bundle.js, line 1)

It then recovers unpredictably. 

- Home Assistant 2023.7.2. 
- No ad blocking
- Works OK on other browsers

**Comment by ildar170975** [comment]
No code provided.

**Comment by furstyferret-dev** [comment]
`type: custom:mini-graph-card
name: SOLAR GENERATION
icon: mdi:solar-power-variant-outline
show:
  icon: true
  name: true
  fill: fade
  graph: line
  legend: true
hours_to_show: 6
points_per_hour: 15
line_width: 3
lower_bound: ~0.1
min_bound_range: 1
entities:
  - entity: sensor.pv_power
    show_graph: false
    color: '#ff9933'
    show_legend: false
    show_state: true
  - entity: sensor.pv1_power
    name: East Array
    color: '#66ccff'
  - entity: sensor.pv2_power
    name: West Array
    color: '#bf80ff'

**Comment by ildar170975** [comment]
Use formatting when posting a code.  Place triple “’”.
Please always read the post after posting.

**Comment by ildar170975** [comment]
Also, you seem to be using grid. Try remove the grid, using graphs without placing them into grid.

**Comment by ildar170975** [comment]
> There are numerous Javascript warnings recorded:
> [Warning] mini-graph-card: – "value [20.6] not found in state_map" (mini-graph-card-bundle.js, line 1)

Some of you mini-graph-card has a `state_map` option specified (which has a card-wide effect), and some graph(s) on this card has values not covered by this map.

**Comment by ildar170975** [comment]
Do you still observe any problems?
No feedback so far.

**Comment by furstyferret-dev** [comment]
Occasionally. It’s unpredictable and happens on the most basic graph on
multiple browsers.

I think it may be related to how Home Assistant accesses resources so will
see if it improves on the 2023.8 builds.

**Comment by ildar170975** [comment]
Do you still have issues?

**Comment by furstyferret-dev** [comment]
No, it’s worked well for some time now, thank you.
