### ISSUE TITLE
mini Graphic card help

### ISSUE THREAD

**Issue by adamsfour** [kalkih/mini-graph-card#986]
I downloaded the mini Graphic card from HACS and I see an error message Please provide the "entities" option as a list. See https://github.com/kalkih/mini-graph-card/blob/master/README.md. The read me file doesn't explain how to get around this issues. Help Please

**Comment by ildar170975** [comment]
This card is supposed to be "coded" via yaml.
Add this code:
```
type: custom:mini-graph-card
entities:
 - zone.home
```

**Comment by ildar170975** [comment]
I will close this issue after some time. Or it is better if you close it yourself.
See you in the Community thread!
