### ISSUE TITLE
Intermittent "Entity not available" error until Device toggled on/off

### ISSUE THREAD

**Issue by ryanmaule** [kalkih/mini-graph-card#993]
I have a mini-graph for the temperature of a Sonoff TH10, and intermittently the graph will not load and the error "Entity not available" will display.  This can be fixed by toggling the switch on the device on/off, which makes the mini-graph appear.  This happens for both of my Sonoff TH10 devices.

Before:
<img width="406" alt="Screenshot 2023-08-03 at 11 14 41 AM" src="https://github.com/kalkih/mini-graph-card/assets/867927/282a95ee-d860-4063-a07a-1ba9bbf904f2">

After:
<img width="402" alt="Screenshot 2023-08-03 at 11 14 48 AM" src="https://github.com/kalkih/mini-graph-card/assets/867927/6557e899-c63b-45c8-bd72-930fdadf2fa7">

It's strange that it's intermittent, and often the mini-graphs will display perfectly without this toggle.

**Comment by ryanmaule** [comment]
Here is my mini-graph code:

  - type: custom:mini-graph-card
    entities:
      - sensor.10008d0711_t
    name: Crawl Space
    line_color: var(--accent-color)
    line_width: 8
    font_size: 75
    show:
      labels: false
      extrema: true
    aspect_ratio: 1/3
    animate: true

Here is my switch code:

      - entity: switch.10008d0711
        icon: hass:fire
        name: Heater

**Comment by ildar170975** [comment]
Here the same card for 2 sensors:
-- unavailable
-- not existing

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/22a54d11-8cf7-438b-b267-e912fb0cd95a)

Seems that your sensor is disappearing sometimes.
Test with a standard history-graph.

**Comment by ildar170975** [comment]
Explanations were provided.
No feedback for 6 months.
Closed.
